import { ArrowDefs, Box, Edge, Frame, Label, Legend, VIZ_COLORS } from "./primitives";
import { asChoice, type VizDefinition, type VizStep } from "./types";

/** A retried payment with and without an idempotency key. The double charge is the whole lesson. */

export type IdempotencyParams = { mode: "without" | "with" };
export type IdempotencyState = { attempt: number; ledger: string[]; keys: Record<string, string>; message: "request" | "processing" | "ack-lost" | "response" | null; clientSees: string | null };

const DEFAULTS: IdempotencyParams = { mode: "without" };

function frame(state: IdempotencyState, kind: VizStep<IdempotencyState>["kind"], title: string, explain: string, interview: string): VizStep<IdempotencyState> {
  return { title, explain, interview, kind, state: { ...state, ledger: [...state.ledger], keys: { ...state.keys } } };
}

export function idempotencySteps(params: IdempotencyParams): VizStep<IdempotencyState>[] {
  const steps: VizStep<IdempotencyState>[] = [];
  const withKey = params.mode === "with";
  const state: IdempotencyState = { attempt: 0, ledger: [], keys: {}, message: null, clientSees: null };
  steps.push(frame(state, "setup", withKey ? "Client generates key k1 before sending" : "Client sends a charge with no key", withKey ? "The client creates a unique idempotency key once and reuses it for every retry of this same operation." : "The request is 'charge $20'. Nothing identifies it as the same operation if it is sent twice.", "Start from the network fact: 'a client that times out cannot tell whether the request was processed; the only safe move is to retry, so the server must make retries harmless'. That is what idempotency means operationally."));
  state.attempt = 1;
  state.message = "request";
  steps.push(frame(state, "invariant", "Attempt 1: charge $20", "The request reaches the server.", withKey ? "Say what the server does first: 'look up the key; if it exists, return the stored response; if not, reserve it atomically before doing the work'. The reservation is what prevents two concurrent retries from both proceeding." : "Without a key the server has no way to know this is new. It just processes."));
  state.ledger.push("charge $20 (attempt 1)");
  if (withKey) state.keys.k1 = "charged $20";
  state.message = "processing";
  steps.push(frame(state, "decision", "Server charges the card", withKey ? "Ledger gets one entry. The response is stored under k1." : "Ledger gets one entry.", withKey ? "Store the key and the response together, ideally in the same transaction as the side effect: 'if the ledger write commits, the key commits; if it rolls back, so does the key'. Otherwise a crash between the two leaves a key with no charge or a charge with no key." : "So far so good. The problem is entirely in what happens next."));
  state.message = "ack-lost";
  steps.push(frame(state, "tradeoff", "The response is lost on the way back", "The server did the work; the client's socket times out. The client sees an error.", "This is the moment to name: 'the client cannot distinguish request lost from response lost'. Any design that assumes it can is wrong. The client will retry, and it should."));
  state.attempt = 2;
  state.message = "request";
  steps.push(frame(state, "decision", withKey ? "Attempt 2 with the same key k1" : "Attempt 2: charge $20 again", withKey ? "Same key, same payload. The server looks up k1 first." : "To the server this looks like a brand-new charge.", withKey ? "The key must be generated by the client, before the first attempt: 'a server-generated id is useless, because the client never received it'." : "Say what the alternatives were: 'a natural key like order id, or a client-generated request id; both work, but only if the server checks before acting'."));
  if (withKey) {
    state.message = "response";
    state.clientSees = "charged $20 (stored response)";
    steps.push(frame(state, "result", "Server returns the stored response; no second charge", `Ledger still has one entry. The client finally sees success.`, "Close with the details they ask: 'keys expire after 24 hours or so; mismatched payload under the same key is an error, not a replay; and for concurrent retries the key row is locked or inserted with a unique constraint so exactly one wins'."));
  } else {
    state.ledger.push("charge $20 (attempt 2)");
    state.message = "response";
    state.clientSees = "charged $20";
    steps.push(frame(state, "result", "Double charge", `Ledger has two entries for one intended payment. The client sees one success and never knows.`, "This is the failure to prevent. Say the fix and where it lives: 'an idempotency key checked at the API boundary, stored with the result; and downstream, consumers of the payment event de-duplicate by event id because the queue is at-least-once too'. Idempotency is needed at every retry point, not just one."));
  }
  return steps;
}

export function IdempotencyView({ state, params }: { state: IdempotencyState; params: IdempotencyParams }) {
  const width = 480;
  const height = 200;
  const withKey = params.mode === "with";
  return (
    <div>
      <Frame width={width} height={height} label="Client retrying a payment against the server">
        <ArrowDefs />
        <Edge from={[130, 70]} to={[250, 70]} tone={state.message === "request" ? "active" : "idle"} />
        <Edge from={[250, 100]} to={[130, 100]} tone={state.message === "response" ? "ok" : state.message === "ack-lost" ? "hot" : "idle"} dashed={state.message === "ack-lost"} />
        {state.message === "ack-lost" ? (
          <text x={190} y={118} textAnchor="middle" fontSize={10} fill={VIZ_COLORS.coral}>
            ✕ timeout
          </text>
        ) : null}
        <Box x={30} y={45} width={100} height={70} title="Client" tone={state.message === "request" ? "active" : "idle"}>
          <text x={80} y={82} textAnchor="middle" fontSize={10} fill={VIZ_COLORS.muted}>
            attempt {state.attempt}
          </text>
          <text x={80} y={98} textAnchor="middle" fontSize={9} fill={withKey ? VIZ_COLORS.teal : VIZ_COLORS.muted}>
            {withKey ? "key: k1" : "no key"}
          </text>
        </Box>
        <Box x={250} y={45} width={200} height={70} title="Server" tone={state.message === "processing" ? "active" : "idle"}>
          <text x={260} y={82} fontSize={10} fill={VIZ_COLORS.muted}>
            keys: {Object.keys(state.keys).length ? Object.entries(state.keys).map(([k, v]) => `${k} → ${v}`).join(", ") : withKey ? "none yet" : "n/a"}
          </text>
          <text x={260} y={100} fontSize={10} fill={state.ledger.length > 1 ? VIZ_COLORS.coral : VIZ_COLORS.ink}>
            ledger: {state.ledger.length} charge{state.ledger.length === 1 ? "" : "s"}
          </text>
        </Box>
        {state.ledger.map((entry, i) => (
          <text key={i} x={260} y={140 + i * 14} fontSize={10} fill={i > 0 ? VIZ_COLORS.coral : VIZ_COLORS.muted} fontFamily="ui-monospace, monospace">
            {entry}
          </text>
        ))}
        <Label x={30} y={height - 10} tone={state.ledger.length > 1 ? "coral" : "muted"}>
          {state.clientSees ? `client sees: ${state.clientSees}` : state.message === "ack-lost" ? "client sees: error" : ""}
        </Label>
      </Frame>
      <Legend items={[{ tone: "accent", label: "in flight" }, { tone: "coral", label: "lost / duplicate" }, { tone: "teal", label: "replayed response" }]} />
    </div>
  );
}

export const idempotencyViz: VizDefinition<IdempotencyParams, IdempotencyState> = {
  id: "idempotency",
  title: "Retries and idempotency keys",
  summary: "The response gets lost, the client retries. Watch the ledger with and without a key.",
  fields: [
    {
      key: "mode",
      label: "Request",
      kind: "select",
      options: [
        { value: "without", label: "Without an idempotency key" },
        { value: "with", label: "With an idempotency key" },
      ],
    },
  ],
  defaults: DEFAULTS,
  parse: (raw) => ({ mode: asChoice(raw.mode, ["without", "with"] as const, DEFAULTS.mode) }),
  steps: idempotencySteps,
  View: IdempotencyView,
};
