/** Active problem slugs, so a story never links to a page that does not exist. Regenerate when problems are added. */
export const KNOWN_PROBLEMS: Record<string, string> = {
  "anagram-bundles": "Anagram Bundles",
  "balanced-brackets": "Balanced Brackets",
  "cycle-in-a-chain": "Cycle in a Chain",
  "first-and-last-position": "First and Last Position",
  "lc-1": "Two Sum",
  "lc-100": "Same Tree",
  "lc-1004": "Max Consecutive Ones III",
  "lc-101": "Symmetric Tree",
  "lc-1011": "Capacity To Ship Packages Within D Days",
  "lc-102": "Binary Tree Level Order Traversal",
  "lc-103": "Binary Tree Zigzag Level Order Traversal",
  "lc-104": "Maximum Depth of Binary Tree",
  "lc-1046": "Last Stone Weight",
  "lc-105": "Construct Binary Tree from Preorder and Inorder Traversal",
  "lc-108": "Convert Sorted Array to Binary Search Tree",
  "lc-11": "Container With Most Water",
  "lc-110": "Balanced Binary Tree",
  "lc-112": "Path Sum",
  "lc-1143": "Longest Common Subsequence",
  "lc-116": "Populating Next Right Pointers in Each Node",
  "lc-121": "Best Time to Buy and Sell Stock",
  "lc-122": "Best Time to Buy and Sell Stock II",
  "lc-124": "Binary Tree Maximum Path Sum",
  "lc-125": "Valid Palindrome",
  "lc-127": "Word Ladder",
  "lc-128": "Longest Consecutive Sequence",
  "lc-130": "Surrounded Regions",
  "lc-131": "Palindrome Partitioning",
  "lc-133": "Clone Graph",
  "lc-134": "Gas Station",
  "lc-136": "Single Number",
  "lc-138": "Copy List with Random Pointer",
  "lc-139": "Word Break",
  "lc-141": "Linked List Cycle",
  "lc-143": "Reorder List",
  "lc-146": "LRU Cache",
  "lc-148": "Sort List",
  "lc-15": "3Sum",
  "lc-150": "Evaluate Reverse Polish Notation",
  "lc-151": "Reverse Words in a String",
  "lc-152": "Maximum Product Subarray",
  "lc-153": "Find Minimum in Rotated Sorted Array",
  "lc-155": "Min Stack",
  "lc-16": "3Sum Closest",
  "lc-160": "Intersection of Two Linked Lists",
  "lc-162": "Find Peak Element",
  "lc-167": "Two Sum II - Input Array Is Sorted",
  "lc-168": "Excel Sheet Column Title",
  "lc-169": "Majority Element",
  "lc-17": "Letter Combinations of a Phone Number",
  "lc-173": "Binary Search Tree Iterator",
  "lc-189": "Rotate Array",
  "lc-19": "Remove Nth Node From End of List",
  "lc-191": "Number of 1 Bits",
  "lc-198": "House Robber",
  "lc-199": "Binary Tree Right Side View",
  "lc-2": "Add Two Numbers",
  "lc-20": "Valid Parentheses",
  "lc-200": "Number of Islands",
  "lc-206": "Reverse Linked List",
  "lc-207": "Course Schedule",
  "lc-208": "Implement Trie (Prefix Tree)",
  "lc-209": "Minimum Size Subarray Sum",
  "lc-21": "Merge Two Sorted Lists",
  "lc-210": "Course Schedule II",
  "lc-211": "Design Add and Search Words Data Structure",
  "lc-212": "Word Search II",
  "lc-213": "House Robber II",
  "lc-215": "Kth Largest Element in an Array",
  "lc-217": "Contains Duplicate",
  "lc-22": "Generate Parentheses",
  "lc-221": "Maximal Square",
  "lc-226": "Invert Binary Tree",
  "lc-227": "Basic Calculator II",
  "lc-23": "Merge k Sorted Lists",
  "lc-230": "Kth Smallest Element in a BST",
  "lc-234": "Palindrome Linked List",
  "lc-235": "Lowest Common Ancestor of a Binary Search Tree",
  "lc-236": "Lowest Common Ancestor of a Binary Tree",
  "lc-238": "Product of Array Except Self",
  "lc-239": "Sliding Window Maximum",
  "lc-242": "Valid Anagram",
  "lc-25": "Reverse Nodes in k-Group",
  "lc-253": "Meeting Rooms II",
  "lc-26": "Remove Duplicates from Sorted Array",
  "lc-268": "Missing Number",
  "lc-269": "Alien Dictionary",
  "lc-273": "Integer to English Words",
  "lc-278": "First Bad Version",
  "lc-283": "Move Zeroes",
  "lc-286": "Walls and Gates",
  "lc-289": "Game of Life",
  "lc-295": "Find Median from Data Stream",
  "lc-297": "Serialize and Deserialize Binary Tree",
  "lc-3": "Longest Substring Without Repeating Characters",
  "lc-300": "Longest Increasing Subsequence",
  "lc-31": "Next Permutation",
  "lc-314": "Binary Tree Vertical Order Traversal",
  "lc-322": "Coin Change",
  "lc-323": "Number of Connected Components in an Undirected Graph",
  "lc-33": "Search in Rotated Sorted Array",
  "lc-338": "Counting Bits",
  "lc-34": "Find First and Last Position of Element in Sorted Array",
  "lc-340": "Longest Substring with At Most K Distinct Characters",
  "lc-347": "Top K Frequent Elements",
  "lc-348": "Design Tic-Tac-Toe",
  "lc-355": "Design Twitter",
  "lc-36": "Valid Sudoku",
  "lc-362": "Design Hit Counter",
  "lc-380": "Insert Delete GetRandom O(1)",
  "lc-39": "Combination Sum",
  "lc-394": "Decode String",
  "lc-4": "Median of Two Sorted Arrays",
  "lc-41": "First Missing Positive",
  "lc-416": "Partition Equal Subset Sum",
  "lc-417": "Pacific Atlantic Water Flow",
  "lc-42": "Trapping Rain Water",
  "lc-424": "Longest Repeating Character Replacement",
  "lc-43": "Multiply Strings",
  "lc-430": "Flatten a Multilevel Doubly Linked List",
  "lc-435": "Non-overlapping Intervals",
  "lc-438": "Find All Anagrams in a String",
  "lc-45": "Jump Game II",
  "lc-450": "Delete Node in a BST",
  "lc-46": "Permutations",
  "lc-48": "Rotate Image",
  "lc-49": "Group Anagrams",
  "lc-5": "Longest Palindromic Substring",
  "lc-50": "Pow(x, n)",
  "lc-51": "N-Queens",
  "lc-53": "Maximum Subarray",
  "lc-535": "Encode and Decode TinyURL",
  "lc-54": "Spiral Matrix",
  "lc-542": "01 Matrix",
  "lc-543": "Diameter of Binary Tree",
  "lc-545": "Boundary of Binary Tree",
  "lc-547": "Number of Provinces",
  "lc-55": "Jump Game",
  "lc-56": "Merge Intervals",
  "lc-560": "Subarray Sum Equals K",
  "lc-567": "Permutation in String",
  "lc-57": "Insert Interval",
  "lc-572": "Subtree of Another Tree",
  "lc-61": "Rotate List",
  "lc-62": "Unique Paths",
  "lc-621": "Task Scheduler",
  "lc-647": "Palindromic Substrings",
  "lc-680": "Valid Palindrome II",
  "lc-684": "Redundant Connection",
  "lc-69": "Sqrt(x)",
  "lc-7": "Reverse Integer",
  "lc-70": "Climbing Stairs",
  "lc-704": "Binary Search",
  "lc-706": "Design HashMap",
  "lc-71": "Simplify Path",
  "lc-72": "Edit Distance",
  "lc-721": "Accounts Merge",
  "lc-73": "Set Matrix Zeroes",
  "lc-739": "Daily Temperatures",
  "lc-74": "Search a 2D Matrix",
  "lc-743": "Network Delay Time",
  "lc-76": "Minimum Window Substring",
  "lc-763": "Partition Labels",
  "lc-78": "Subsets",
  "lc-787": "Cheapest Flights Within K Stops",
  "lc-79": "Word Search",
  "lc-8": "String to Integer (atoi)",
  "lc-84": "Largest Rectangle in Histogram",
  "lc-863": "All Nodes Distance K in Binary Tree",
  "lc-875": "Koko Eating Bananas",
  "lc-88": "Merge Sorted Array",
  "lc-895": "Maximum Frequency Stack",
  "lc-90": "Subsets II",
  "lc-904": "Fruit Into Baskets",
  "lc-91": "Decode Ways",
  "lc-94": "Binary Tree Inorder Traversal",
  "lc-973": "K Closest Points to Origin",
  "lc-98": "Validate Binary Search Tree",
  "lc-981": "Time Based Key-Value Store",
  "lc-994": "Rotting Oranges",
  "level-walk": "Level Walk",
  "longest-unique-window": "Longest Unique Window",
  "merged-median": "Merged Median",
  "minimum-tracker-stack": "Minimum Tracker Stack",
  "mirror-number": "Mirror Number",
  "missing-range-value": "Missing Range Value",
  "pair-target": "Pair Target",
  "shared-ancestor": "Shared Ancestor",
  "single-pass-profit": "Single Pass Profit",
  "valley-rain": "Valley Rain",
  "widest-water-basin": "Widest Water Basin",
};
