import type { ProblemDetail, ProblemSolution } from "@/lib/api";

/**
 * Trigger a browser download of text/data as a local file.
 */
export function downloadFile(filename: string, content: string, mimeType = "text/plain") {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate a complete, beautifully structured Markdown document for offline reading.
 */
export function generateSolutionMarkdown(problem: ProblemDetail, solution: ProblemSolution): string {
  const parts: string[] = [];

  parts.push(`# ${problem.title}\n`);
  parts.push(`**Difficulty:** ${problem.difficulty}`);
  parts.push(`**Time Complexity:** ${problem.time_complexity} · **Space Complexity:** ${problem.space_complexity}\n`);

  if (problem.description) {
    parts.push(`## Problem Description\n\n${problem.description.trim()}\n`);
  }

  if (problem.constraints) {
    parts.push(`## Constraints\n\n${problem.constraints.trim()}\n`);
  }

  parts.push(`## The Core Idea\n\n${solution.summary.trim()}\n`);
  if (solution.pattern) {
    parts.push(`**Pattern:** ${solution.pattern}`);
  }
  if (solution.trigger) {
    parts.push(`**When to spot it:** ${solution.trigger}\n`);
  }

  parts.push(`## Approaches\n`);
  for (const approach of solution.approaches) {
    const badge = approach.is_optimal ? " (Optimal)" : approach.is_alternative ? " (Alternative)" : "";
    parts.push(`### ${approach.position + 1}. ${approach.name}${badge}\n`);
    parts.push(`- **Time Complexity:** ${approach.time_complexity} (${approach.time_why})`);
    parts.push(`- **Space Complexity:** ${approach.space_complexity} (${approach.space_why})\n`);
    parts.push(`${approach.idea.trim()}\n`);

    if (approach.steps?.length) {
      parts.push(`**Steps:**`);
      approach.steps.forEach((step, idx) => {
        parts.push(`${idx + 1}. ${step}`);
      });
      parts.push("");
    }

    if (approach.code) {
      parts.push("```java");
      parts.push(approach.code.trim());
      parts.push("```\n");
    }
  }

  if (solution.walkthrough?.rows?.length) {
    parts.push(`## Example Walkthrough\n`);
    parts.push(`**Input:** \`${solution.walkthrough.input}\`\n`);
    if (solution.walkthrough.columns?.length) {
      parts.push(`| ${solution.walkthrough.columns.join(" | ")} |`);
      parts.push(`| ${solution.walkthrough.columns.map(() => "---").join(" | ")} |`);
      for (const row of solution.walkthrough.rows) {
        parts.push(`| ${row.join(" | ")} |`);
      }
      parts.push("");
    }
    if (solution.walkthrough.result) {
      parts.push(`**Result:** ${solution.walkthrough.result}\n`);
    }
  }

  if (solution.mistakes?.length) {
    parts.push(`## Common Mistakes\n`);
    for (const m of solution.mistakes) {
      parts.push(`### ${m.name}`);
      parts.push(`- ❌ **Wrong:** ${m.wrong}`);
      parts.push(`- ✅ **Right:** ${m.right}\n`);
    }
  }

  if (solution.edge_cases?.length) {
    parts.push(`## Edge Cases to Test\n`);
    for (const ec of solution.edge_cases) {
      parts.push(`- \`${ec.input}\` → \`${ec.expected}\`: ${ec.why}`);
    }
    parts.push("");
  }

  if (solution.interview_script?.length) {
    parts.push(`## How to Explain in an Interview\n`);
    solution.interview_script.forEach((line, idx) => {
      parts.push(`${idx + 1}. ${line}`);
    });
    parts.push("");
  }

  parts.push("---\n*Generated by Anvil for offline reading.*");

  return parts.join("\n");
}
