"""Knowledge checks: interview scoring, DNS, cache invalidation, sharding, CAP, service discovery, search, key-value store, ride sharing, API gateway."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "sd-interview-scoring": [
        {
            "key": "same-diagram-different-score",
            "kind": "choice",
            "prompt": "Two candidates draw the same replica. One says why it was chosen (reads dominate 100:1, a second of lag is fine) and names the anomaly it creates. The other says nothing. Which rubric dimensions does the first candidate show that the second does not?",
            "options": [
                "Technical breadth only",
                "Technical depth and trade-off reasoning",
                "Problem framing only",
                "Communication only",
            ],
            "answer": 1,
            "explanation": "The diagram is the artifact; the reasoning is the product. Breadth gets you to the bar, and depth plus trade-off reasoning are what lift you above it.",
            "section": "mental-model",
            "concept": "sd-interview-scoring.rubric-dimensions",
            "mistake": "sd-interview-scoring.diagram-is-the-score",
        },
        {
            "key": "senior-vs-mid",
            "kind": "short_answer",
            "prompt": "In your own words: what does the senior (L5) bar add on top of the mid-level bar of 'a working system'?",
            "options": [],
            "answer": None,
            "model_answer": "Numbers drive the architecture explicitly; at least one genuine deep dive; trade-offs volunteered as 'I chose X over Y because'; failure modes handled concretely (retries, idempotency, degradation); and the design evolves correctly when the interviewer applies pressure such as 10x traffic.",
            "explanation": "Mid is a working system with the standard components used correctly. Senior is a working system you can defend and scale.",
            "section": "how-it-works",
            "concept": "sd-interview-scoring.level-bars",
        },
        {
            "key": "staff-signal",
            "kind": "choice",
            "prompt": "A candidate asks 'Do we actually need strong consistency here? That constraint costs us a region', then says what they would build in month one and defer to v2. Which bar does this behaviour belong to?",
            "options": ["Mid-level", "Senior", "Staff", "It is off-topic and scores badly"],
            "answer": 2,
            "explanation": "Questioning the requirements themselves, operational reality, simplicity bias and knowing what to defer are the staff bar: judgement about the whole problem, including the parts nobody asked about.",
            "section": "how-it-works",
            "concept": "sd-interview-scoring.level-bars",
        },
        {
            "key": "highest-signal-sentence",
            "kind": "choice",
            "prompt": "According to the lesson, which sentence is the single highest-signal thing you can say in a design interview?",
            "options": [
                "We add a cache here to make reads faster",
                "The part I am least happy with is the cross-shard read; with more time I would denormalise an index",
                "We would use Kafka, Redis, Cassandra and Elasticsearch",
                "This is the standard architecture for this problem",
            ],
            "answer": 1,
            "explanation": "Volunteering the weakness is what senior engineers do in real design reviews. Being caught by it instead is a much weaker signal.",
            "section": "design-decisions",
            "concept": "sd-interview-scoring.volunteer-the-weakness",
            "mistake": "sd-interview-scoring.hide-the-weakness",
        },
        {
            "key": "kafka-at-40-writes",
            "kind": "spot_mistake",
            "prompt": "A candidate puts Kafka into a system that receives 40 writes per second, explaining that it shows they know modern tooling. What is wrong with this?",
            "options": [
                "Nothing, it demonstrates technical breadth",
                "Reaching for a complex tool at that scale signals inexperience, not expertise",
                "Kafka cannot handle such a low write rate",
                "They should have proposed two Kafka clusters for redundancy",
            ],
            "answer": 1,
            "explanation": "Simplicity versus sophistication: the complex tool signals inexperience more often than expertise, and every extra component is a question you have invited.",
            "section": "trade-offs",
            "concept": "sd-interview-scoring.simplicity-bias",
            "mistake": "sd-interview-scoring.impressive-over-clear",
        },
        {
            "key": "depth-or-coverage",
            "kind": "choice",
            "prompt": "Ten minutes remain. You could go deep on the sharding strategy or cover notifications and search at a high level. What does the lesson recommend?",
            "options": [
                "Always cover more of the system; breadth wins",
                "Ask the interviewer which is more useful, expecting them to pick depth",
                "Always go deep without asking",
                "Skip both and start the summary early",
            ],
            "answer": 1,
            "explanation": "Interviewers almost always pick depth, and asking the question scores well by itself because it hands you the rubric.",
            "section": "trade-offs",
            "concept": "sd-interview-scoring.depth-vs-coverage",
        },
        {
            "key": "handling-a-challenge",
            "kind": "choice",
            "prompt": "The interviewer challenges your queue choice. You still believe it is right. Which response matches the lesson?",
            "options": [
                "Change the design immediately so you do not look defensive",
                "Say 'I still think this is right, because...' and give the reasoning",
                "Repeat the original decision without engaging with the challenge",
                "Say you do not know and move on",
            ],
            "answer": 1,
            "explanation": "Both defensiveness (doubling down) and excessive agreement (changing the design at every raised eyebrow) are failure modes. Sometimes the right answer is to hold the position with reasons; when the challenge is good, fix the problem.",
            "section": "common-failure-modes",
            "concept": "sd-interview-scoring.handling-challenges",
            "mistake": "sd-interview-scoring.excessive-agreement",
        },
        {
            "key": "when-you-do-not-know",
            "kind": "choice",
            "prompt": "You are asked something you genuinely do not know. Which response scores highest according to the lesson?",
            "options": [
                "A confident, plausible guess",
                "'I do not know, but here is how I would reason about it'",
                "Redirect to a component you know well",
                "Stay quiet and wait for the next question",
            ],
            "answer": 1,
            "explanation": "Confident wrong answers are the worst outcome. Never saying 'I don't know' is listed as a common mistake; honest reasoning scores far higher than invention.",
            "section": "common-mistakes",
            "concept": "sd-interview-scoring.confidence-vs-honesty",
            "mistake": "sd-interview-scoring.never-says-i-dont-know",
        },
    ],
    "sd-dns": [
        {
            "key": "cannot-invalidate",
            "kind": "choice",
            "prompt": "You change an A record on your authoritative server. Why can users still reach the old address an hour later?",
            "options": [
                "The root servers must approve the change first",
                "Browser, OS and resolver caches keep the old answer until its TTL expires",
                "DNS changes only propagate once a day",
                "The TLD server re-signs the zone every hour",
            ],
            "answer": 1,
            "explanation": "DNS is a cache hierarchy you can write to but cannot invalidate. The TTL you set on the authoritative answer is the only lever, and everything upstream is someone else's cache.",
            "section": "mental-model",
            "concept": "sd-dns.cache-hierarchy",
            "mistake": "sd-dns.failover-is-instant",
        },
        {
            "key": "ttl-bound-failover",
            "kind": "choice",
            "prompt": "You use pure DNS failover with a 300-second TTL. The European region dies and the authoritative server stops returning its address. What happens to clients that resolved a minute ago?",
            "options": [
                "They move to the healthy region within seconds",
                "They keep hitting the dead region for up to five minutes, and misbehaving resolvers longer",
                "They receive NXDOMAIN until the TTL expires",
                "They automatically retry a second A record",
            ],
            "answer": 1,
            "explanation": "DNS failover is TTL-bound: cached answers stay valid until they expire, and some resolvers and clients ignore the TTL entirely.",
            "section": "how-it-works",
            "concept": "sd-dns.ttl-failover",
            "mistake": "sd-dns.failover-is-instant",
        },
        {
            "key": "resolver-not-user",
            "kind": "choice",
            "prompt": "Latency-based DNS steering sends a user in Germany to us-east. What is the most likely cause?",
            "options": [
                "The steering decision is based on the resolver's location, and the user's VPN or central resolver is far away",
                "The TTL on the record is too low",
                "Anycast is misconfigured on the European edge",
                "The zone has no A record for Europe",
            ],
            "answer": 0,
            "explanation": "The authoritative server sees the resolver, not the client. EDNS Client Subnet mitigates this by passing a truncated client subnet along with the query.",
            "section": "how-it-works",
            "concept": "sd-dns.resolver-location",
            "mistake": "sd-dns.geo-sees-the-user",
        },
        {
            "key": "seconds-not-minutes",
            "kind": "choice",
            "prompt": "You need regional failover in seconds, not minutes. Which mechanism does the lesson point to?",
            "options": [
                "A 5-second TTL on every record",
                "Anycast, usually via a CDN or global load balancer in front, so failover is a route withdrawal",
                "Several A records so clients pick another one",
                "Geolocation routing with health checks",
            ],
            "answer": 1,
            "explanation": "Anycast fails over in seconds via route withdrawal and has no client cache problem. DNS-based failover stays TTL-bound no matter how low you set the TTL, because some clients ignore it.",
            "section": "how-it-works",
            "concept": "sd-dns.anycast-vs-dns",
        },
        {
            "key": "thirty-second-ttl-everywhere",
            "kind": "spot_mistake",
            "prompt": "To get fast failover, a team sets a 30-second TTL on every record and relies on DNS alone for failover. What is wrong?",
            "options": [
                "Nothing, low TTLs are the standard practice",
                "A DNS provider outage now takes the site down in under a minute, and TTL-ignoring clients still lag",
                "30 seconds is far too long for any failover to work",
                "Resolvers refuse TTLs under 60 seconds",
            ],
            "answer": 1,
            "explanation": "A low TTL buys agility but costs query volume and a hard dependency on DNS availability. The standard pattern is a low TTL only where needed and never relying on DNS alone for fast failover.",
            "section": "trade-offs",
            "concept": "sd-dns.ttl-trade-off",
            "mistake": "sd-dns.dns-alone-for-failover",
        },
        {
            "key": "negative-caching",
            "kind": "choice",
            "prompt": "A typo makes api.example.com return NXDOMAIN. You fix the record within a minute, but some users keep failing for much longer. Why?",
            "options": [
                "Negative answers are cached too, so the NXDOMAIN lives until the negative TTL expires",
                "The fix needs a restart of the authoritative server",
                "NXDOMAIN answers are never cached, so the cause must be elsewhere",
                "Anycast routes must be re-announced after any zone change",
            ],
            "answer": 0,
            "explanation": "Negative caching means a mistake that returns NXDOMAIN is cached like any other answer, and the fix takes as long as the negative TTL to reach everyone.",
            "section": "common-failure-modes",
            "concept": "sd-dns.negative-caching",
        },
        {
            "key": "provider-outage",
            "kind": "choice",
            "prompt": "Your DNS provider has a full outage while all your servers are healthy. What actually happens, and what is the mitigation?",
            "options": [
                "Every user loses access immediately; mitigation is a lower TTL",
                "Users with cached entries keep working, new resolutions fail; mitigation is a second authoritative provider",
                "Only anycast users are affected; mitigation is more A records",
                "Nothing, because the servers themselves are healthy",
            ],
            "answer": 1,
            "explanation": "DNS is itself a dependency. Cached answers survive the outage, but new lookups fail, which is why serious setups run two independent providers on the same zone.",
            "section": "common-failure-modes",
            "concept": "sd-dns.dns-is-a-dependency",
            "mistake": "sd-dns.dns-never-fails",
        },
        {
            "key": "migration-ttl",
            "kind": "choice",
            "prompt": "Tomorrow you must move api.example.com to a new provider with a two-minute rollback. The record currently has a 24-hour TTL. What do you do today?",
            "options": [
                "Nothing; change the record tomorrow and wait",
                "Lower the TTL now so tomorrow's cutover and rollback drain quickly, then raise it back afterwards",
                "Raise the TTL to 48 hours so clients are stable during the move",
                "Delete the record tonight so caches are empty by morning",
            ],
            "answer": 1,
            "explanation": "Cut the TTL a day in advance and raise it back afterwards. Setting a 24-hour TTL and then needing to move traffic in five minutes is a listed mistake.",
            "section": "common-mistakes",
            "concept": "sd-dns.planned-migration",
            "mistake": "sd-dns.ttl-not-lowered-before-migration",
        },
    ],
    "sd-cache-invalidation": [
        {
            "key": "two-problems",
            "kind": "choice",
            "prompt": "Classify these two incidents using the lesson's two problems: (a) a changed display name shows stale for five minutes; (b) a key expires and 5,000 identical queries hit the database at once.",
            "options": [
                "Both are correctness problems",
                "(a) is correctness, (b) is load",
                "(a) is load, (b) is correctness",
                "Both are load problems",
            ],
            "answer": 1,
            "explanation": "Correctness means the cached value no longer matches the truth, solved by expiry or invalidation. Load means the cache stops absorbing traffic, solved by coalescing, jitter and limits.",
            "section": "mental-model",
            "concept": "sd-cache-invalidation.correctness-vs-load",
        },
        {
            "key": "write-order",
            "kind": "choice",
            "prompt": "On an update, which order of operations does the lesson recommend?",
            "options": [
                "Delete the cache key, then write the database",
                "Write the database, then delete the cache key",
                "Write the database, then write the new value into the cache",
                "Write the cache first so readers see it, then the database",
            ],
            "answer": 1,
            "explanation": "Invalidating first leaves a window where a concurrent read refills the cache from the not-yet-updated database. Updating instead of deleting has the v1/v2 interleaving that leaves a stale value forever. Keep a TTL backstop either way.",
            "section": "how-it-works",
            "concept": "sd-cache-invalidation.write-order",
            "mistake": "sd-cache-invalidation.invalidate-before-write",
        },
        {
            "key": "versioned-keys",
            "kind": "choice",
            "prompt": "A team wants to avoid the delete-versus-refill race entirely. Which approach does the lesson call an excellent answer?",
            "options": [
                "Versioned keys like product:123:v7; a write bumps the version and old entries age out",
                "A longer TTL so refills happen less often",
                "Updating the cache on every write instead of deleting",
                "Deleting the key twice, before and after the write",
            ],
            "answer": 0,
            "explanation": "With versioned keys, old entries are never read again and expire naturally: no deletion, no race, slightly more memory.",
            "section": "how-it-works",
            "concept": "sd-cache-invalidation.versioned-keys",
        },
        {
            "key": "fail-open-or-closed",
            "kind": "choice",
            "prompt": "The cache cluster becomes unavailable. What does the lesson recommend for reads, and for something like a rate limiter?",
            "options": [
                "Fail open for everything: treat every lookup as a miss",
                "Fail open for reads with a concurrency limit; fail closed where a miss is unsafe, such as a rate limiter",
                "Fail closed for everything until the cache returns",
                "Queue all requests until the cache is healthy again",
            ],
            "answer": 1,
            "explanation": "Fail open without a concurrency limit turns a cache outage into a database outage. A rate limiter that fails open stops limiting exactly when it is under attack.",
            "section": "design-decisions",
            "concept": "sd-cache-invalidation.fail-open-closed",
            "mistake": "sd-cache-invalidation.unbounded-fail-open",
        },
        {
            "key": "stale-while-revalidate",
            "kind": "choice",
            "prompt": "You enable stale-while-revalidate for profile lookups. What do you gain and what do you pay?",
            "options": [
                "Fresher data, paid for with more origin misses",
                "No user waits for a refill because the expired value is served while a background refresh runs; data is briefly stale",
                "No need for a TTL any more",
                "The hot key is spread across several nodes",
            ],
            "answer": 1,
            "explanation": "Stale-while-revalidate mostly breaks the short-TTL-versus-origin-load trade-off, at the cost of knowingly serving a stale value for a few seconds.",
            "section": "trade-offs",
            "concept": "sd-cache-invalidation.stampede-mitigations",
        },
        {
            "key": "synchronised-expiry",
            "kind": "choice",
            "prompt": "A deploy populates 100,000 keys with a fixed 600-second TTL. What happens ten minutes later, and what is the fix?",
            "options": [
                "Nothing unusual; keys expire as they are read",
                "They all expire in the same second and the database takes a burst; add random jitter such as 600 plus 0 to 60 seconds",
                "Redis evicts them early under memory pressure",
                "LFU refreshes them automatically before expiry",
            ],
            "answer": 1,
            "explanation": "Synchronised expiry comes from a fixed TTL applied across a class of keys. TTL jitter spreads the expiries so nothing expires under load all at once.",
            "section": "common-failure-modes",
            "concept": "sd-cache-invalidation.ttl-jitter",
            "mistake": "sd-cache-invalidation.fixed-ttl",
        },
        {
            "key": "scan-pollution",
            "kind": "short_answer",
            "prompt": "A nightly batch job reads a million cold rows through the cache. Next morning the hit rate has collapsed. What happened, and name one fix.",
            "options": [],
            "answer": None,
            "model_answer": "Scan pollution: the batch read evicted the entire hot set under LRU. Fixes: use LFU, which resists one-off scans, or route analytical and batch traffic away from the cache entirely. Watch the eviction rate as a first-class metric.",
            "explanation": "Rising evictions mean the working set no longer fits, and the hit rate is about to fall off a cliff.",
            "section": "common-failure-modes",
            "concept": "sd-cache-invalidation.eviction",
        },
        {
            "key": "shard-the-hot-key",
            "kind": "spot_mistake",
            "prompt": "One celebrity profile key gets 30% of reads and its Redis node sits at 100% CPU while the others idle. A teammate proposes adding ten more cache shards. What is wrong?",
            "options": [
                "Nothing, more shards spread the load",
                "One key hashes to one shard, so more shards do nothing; put a 1 to 5 second in-process cache in front",
                "It only works if the cluster uses consistent hashing",
                "The fix is to switch the eviction policy to FIFO",
            ],
            "answer": 1,
            "explanation": "A cache cluster balances keys, not traffic per key. A short-TTL local cache collapses thousands of requests per node into one; key splitting is the next option.",
            "section": "common-mistakes",
            "concept": "sd-cache-invalidation.hot-keys",
            "mistake": "sd-cache-invalidation.sharding-fixes-hot-keys",
        },
    ],
    "sharding": [
        {
            "key": "partitioning-is-not-sharding",
            "kind": "choice",
            "prompt": "A team uses Postgres declarative partitioning to split a large table into monthly pieces on one machine and calls it sharding. Is it?",
            "options": [
                "Yes, partitioning and sharding are the same thing",
                "No: it improves pruning, retention and index size on one machine but adds no capacity across machines",
                "Yes, as long as the partitions are hash-based",
                "No, because only vertical partitioning counts as sharding",
            ],
            "answer": 1,
            "explanation": "Sharding splits rows across independent machines so capacity grows with machine count. Partitioning within one database does not, and knowing the difference is a real signal.",
            "section": "mental-model",
            "concept": "sharding.partitioning-vs-sharding",
            "mistake": "sharding.partitioning-confused-with-sharding",
        },
        {
            "key": "key-absent-from-query",
            "kind": "choice",
            "prompt": "A marketplace shards orders by order_id. The most common read is 'all orders for merchant X'. Which shard-key criterion is violated, and what happens?",
            "options": [
                "Cardinality: order_id has too few distinct values",
                "Presence in queries: every merchant lookup becomes a scatter-gather across all shards",
                "Stability: order ids change after checkout",
                "Even distribution: order ids cluster on one shard",
            ],
            "answer": 1,
            "explanation": "If the dominant read does not include the shard key, it hits every shard and latency becomes the slowest shard's latency. This is the criterion candidates forget and the one that hurts most.",
            "section": "how-it-works",
            "concept": "sharding.shard-key-criteria",
            "mistake": "sharding.key-absent-from-query",
        },
        {
            "key": "hot-tenant-order",
            "kind": "choice",
            "prompt": "A SaaS product shards by tenant_id. The largest tenant is 20% of all load and sits on one shard. What is the lesson's escalating order of mitigations?",
            "options": [
                "Change the shard key immediately",
                "Cache in front, then salt the key, then give the tenant its own shard, then change the key",
                "Add more physical machines so the hash spreads it out",
                "Switch from hash to range partitioning",
            ],
            "answer": 1,
            "explanation": "Hot shards are a traffic problem, not a key-distribution problem. Start with the cheapest fix and escalate; splitting a heavy tenant onto its own shard is common in B2B SaaS.",
            "section": "how-it-works",
            "concept": "sharding.hot-shards",
            "mistake": "sharding.hashing-spreads-traffic",
        },
        {
            "key": "shard-migration",
            "kind": "short_answer",
            "prompt": "You need to move one logical shard to a new machine without downtime. Describe the migration steps.",
            "options": [],
            "answer": None,
            "model_answer": "Copy the data to the new shard while the old one still serves, replicate the delta continuously, verify, then cut over reads and writes for that logical shard atomically, keeping the old copy until you are confident. It is a dual-write and backfill problem.",
            "explanation": "Being able to describe resharding as dual-write and backfill is a senior-level answer; 'rehash everything' invites a follow-up you will not enjoy.",
            "section": "how-it-works",
            "concept": "sharding.resharding",
        },
        {
            "key": "logical-shards",
            "kind": "choice",
            "prompt": "You are sharding for the first time onto four machines. How many shards should you create, according to the lesson?",
            "options": [
                "Exactly four, one per machine",
                "Many logical shards such as 256 or 1,024, mapped onto the four machines",
                "One per table",
                "As few as possible to keep operations simple",
            ],
            "answer": 1,
            "explanation": "Growing then becomes a mapping change: reassign some logical shards and move only their data. Hashing modulo the machine count means adding a machine remaps nearly every key.",
            "section": "design-decisions",
            "concept": "sharding.virtual-shards",
            "mistake": "sharding.mod-n-no-indirection",
        },
        {
            "key": "bigger-machine",
            "kind": "choice",
            "prompt": "A team weighs sharding against buying a much larger single instance. Which statement matches the lesson's judgement?",
            "options": [
                "Always shard; vertical scaling is a dead end",
                "Sharding often costs more engineering than several years of a larger instance, and saying so is good judgement",
                "A bigger machine never helps with write throughput",
                "Sharding is cheaper to operate than one large instance",
            ],
            "answer": 1,
            "explanation": "Modern single instances are very large. Sharding costs joins, transactions and unplanned queries, and multiplies every operational task by N.",
            "section": "trade-offs",
            "concept": "sharding.shard-vs-scale-up",
        },
        {
            "key": "time-range-hotspot",
            "kind": "choice",
            "prompt": "An events table is range-partitioned by created_at across shards. What goes wrong under write load, and what is the fix?",
            "options": [
                "Range scans become slow; add an index",
                "Every new write lands on the newest partition, so one shard takes all the write load; add a hash component",
                "Resharding moves every row; use consistent hashing",
                "Ids collide across shards; switch to UUIDs",
            ],
            "answer": 1,
            "explanation": "Sequential ids and timestamps as the partition key send every new write to the same place. Combine time with a hash, or hash or reverse the high-order bits.",
            "section": "common-failure-modes",
            "concept": "sharding.sequential-key-hotspot",
            "mistake": "sharding.range-by-time",
        },
        {
            "key": "sharding-at-800-writes",
            "kind": "spot_mistake",
            "prompt": "A system does 800 writes per second on one primary with no replicas and no cache. The candidate opens with 'we shard by user_id'. What is wrong?",
            "options": [
                "user_id has too little cardinality to shard on",
                "Sharding is premature: vertical scaling, replicas, caching and archiving have not been tried at that load",
                "They should shard by country instead",
                "Nothing, sharding early avoids a painful migration later",
            ],
            "answer": 1,
            "explanation": "The strong sequence is vertical scale, then read replicas, then caching, then sharding only when writes or data volume genuinely exceed one node. Sharding first is a listed mistake.",
            "section": "common-mistakes",
            "concept": "sharding.shard-last",
            "mistake": "sharding.too-early",
        },
    ],
    "cap-theorem": [
        {
            "key": "minority-side-cp",
            "kind": "choice",
            "prompt": "During a partition, what does the minority side of a CP system do with a request?",
            "options": [
                "Serves possibly stale data and reconciles later",
                "Refuses the request rather than serve possibly stale data",
                "Elects its own leader and keeps accepting writes",
                "Forwards it to the majority side over the broken link",
            ],
            "answer": 1,
            "explanation": "Partition is not a choice; C and A are. CP refuses on the minority side, AP serves from both sides and reconciles later.",
            "section": "mental-model",
            "concept": "cap-theorem.cp-vs-ap",
        },
        {
            "key": "w1-r1",
            "kind": "choice",
            "prompt": "A store runs N=3 with W=1 and R=1 for speed, and the team expects reads to always return the latest write. What is true?",
            "options": [
                "W + R = 2, which is not greater than N, so reads and writes need not overlap and a read can be stale",
                "Reads are strong because there are three replicas",
                "Reads are strong as long as read repair is enabled",
                "Writes fail whenever any replica is down",
            ],
            "answer": 0,
            "explanation": "Overlap needs W + R > N. N=3, W=2, R=2 is the common balance: a majority both ways, tolerating one failure. W=1 R=1 with an expectation of consistency is a listed misconfiguration.",
            "section": "how-it-works",
            "concept": "cap-theorem.quorums",
            "mistake": "cap-theorem.quorum-misconfiguration",
        },
        {
            "key": "pacelc",
            "kind": "short_answer",
            "prompt": "What does PACELC add to CAP, and why does the lesson call it the more useful framing?",
            "options": [],
            "answer": None,
            "model_answer": "If there is a Partition, choose Availability or Consistency; Else, choose Latency or Consistency. The else branch governs the system almost all the time: even with a healthy network, stronger consistency costs round trips, such as 100 ms or more on every cross-region quorum write.",
            "explanation": "CAP only describes behaviour during a partition. PACELC captures the everyday cost of consistency, which applies far more often.",
            "section": "how-it-works",
            "concept": "cap-theorem.pacelc",
        },
        {
            "key": "consensus-is-cp",
            "kind": "choice",
            "prompt": "You need leader election and distributed locks. Which tool does that, and what happens to a minority partition?",
            "options": [
                "Consensus (Raft or Paxos, as in etcd or ZooKeeper); the minority cannot make progress",
                "A sloppy quorum; the minority keeps accepting writes",
                "Last-write-wins replication; the minority reconciles later",
                "Gossip; both sides make progress independently",
            ],
            "answer": 0,
            "explanation": "Consensus systems are CP by construction because progress requires a majority. That is why coordination services are kept small and hold only the metadata that must be consistent.",
            "section": "how-it-works",
            "concept": "cap-theorem.consensus",
        },
        {
            "key": "smallest-consistent-part",
            "kind": "choice",
            "prompt": "A shopping site needs to never oversell the last unit but wants to stay available. Where does the lesson say to put strong consistency?",
            "options": [
                "Make the whole system CP so nothing is ever stale",
                "Concentrate it in the smallest component, such as the inventory decrement, and let browsing stay available",
                "Make everything AP and fix overselling with a nightly job",
                "Use CA for checkout and AP for the rest",
            ],
            "answer": 1,
            "explanation": "Systems that need consistency everywhere are slow everywhere. Put the consistent part in a coordination service, a single-shard transaction or a conditional write, and keep the rest available.",
            "section": "design-decisions",
            "concept": "cap-theorem.per-operation",
        },
        {
            "key": "ap-obligation",
            "kind": "choice",
            "prompt": "You choose AP for shopping carts so both sides of a partition keep accepting writes. What does that choice oblige you to build?",
            "options": [
                "A consensus service for cart writes",
                "A reconciliation strategy for conflicting writes, such as last-write-wins, a merge rule or asking the user",
                "Synchronous replication between the two sides",
                "Nothing; AP systems converge on their own",
            ],
            "answer": 1,
            "explanation": "AP always answers but may answer with stale or conflicting data. Choosing AP and never building reconciliation lets divergence accumulate permanently.",
            "section": "trade-offs",
            "concept": "cap-theorem.reconciliation",
            "mistake": "cap-theorem.ap-without-reconciliation",
        },
        {
            "key": "what-counts-as-partition",
            "kind": "choice",
            "prompt": "A candidate says partitions are rare because the datacentre has redundant links. Which of these does the lesson count as a partition?",
            "options": [
                "Only a physical cable cut between regions",
                "A long GC pause, an overloaded node, a misconfigured firewall or a cloud network blip",
                "Only a failure of the consensus service",
                "A disk failure on one replica",
            ],
            "answer": 1,
            "explanation": "Partitions are routine. Anything that makes nodes unable to exchange messages in time behaves like one, which is why assuming they are rare is a failure mode.",
            "section": "common-failure-modes",
            "concept": "cap-theorem.partitions-are-routine",
            "mistake": "cap-theorem.partitions-are-rare",
        },
        {
            "key": "whole-system-ap",
            "kind": "spot_mistake",
            "prompt": "A candidate says: 'Our payment system is AP.' What is wrong with that statement?",
            "options": [
                "Nothing, it is a valid classification",
                "The choice is per operation: the ledger should be CP while the transaction history view can be AP",
                "A payment system must be CA",
                "AP is impossible with three replicas",
            ],
            "answer": 1,
            "explanation": "Labelling a whole system AP or CP is a listed mistake. A single product mixes both, and saying which operation sits where, and why, is the accurate answer.",
            "section": "common-mistakes",
            "concept": "cap-theorem.per-operation",
            "mistake": "cap-theorem.whole-system-label",
        },
    ],
    "sd-service-discovery": [
        {
            "key": "readiness-gates-discovery",
            "kind": "choice",
            "prompt": "A new instance starts and spends 20 seconds warming caches and opening pools. Which of the three moving parts should decide when callers can see it?",
            "options": [
                "Registration alone: it is discoverable as soon as it announces itself",
                "Health, specifically readiness: it is removed or hidden until it can actually serve",
                "Liveness: it is discoverable as long as the process is running",
                "The DNS TTL: it appears when the previous answer expires",
            ],
            "answer": 1,
            "explanation": "Register, discover, health check. Readiness, not liveness, controls discoverability; instances registering before they are ready cause early traffic to fail.",
            "section": "mental-model",
            "concept": "sd-service-discovery.readiness",
            "mistake": "sd-service-discovery.register-before-ready",
        },
        {
            "key": "registry-down",
            "kind": "short_answer",
            "prompt": "The service registry is unavailable for ten minutes and the autoscaler adds 50 instances meanwhile. What should callers do, and what stops working?",
            "options": [],
            "answer": None,
            "model_answer": "Keep serving from the last-known-good instance list. Instances that die are found by connection failures and ejected locally. The 50 new instances are not discoverable until the registry recovers, so only changes stall; nothing user-facing breaks.",
            "explanation": "Refusing to serve because discovery failed makes the registry a hard dependency of everything, which a control plane should never be.",
            "section": "how-it-works",
            "concept": "sd-service-discovery.last-known-good",
            "mistake": "sd-service-discovery.registry-hard-dependency",
        },
        {
            "key": "client-side-balancing",
            "kind": "choice",
            "prompt": "A gRPC service wants least-request balancing because request cost varies a lot. Which discovery pattern gives it that, and what is the cost?",
            "options": [
                "Server-side load balancer; the cost is an extra hop",
                "Client-side discovery, where the caller holds the instance list and balances; the cost is logic in every client",
                "DNS with a high TTL; the cost is staleness",
                "Third-party registration; the cost is a slower registry",
            ],
            "answer": 1,
            "explanation": "Client-side discovery avoids the hop and allows better algorithms than a round-robin proxy, at the price of duplicating discovery logic per language.",
            "section": "how-it-works",
            "concept": "sd-service-discovery.patterns",
        },
        {
            "key": "crashed-self-registered",
            "kind": "choice",
            "prompt": "An instance that self-registers and heartbeats crashes hard. What do callers experience?",
            "options": [
                "It disappears from discovery instantly",
                "It lingers in the registry until its lease expires, so callers may hit it and get connection errors",
                "The platform removes it immediately because it observed the crash",
                "Nothing, because self-registration excludes it from the list",
            ],
            "answer": 1,
            "explanation": "Self-registration is simple, but a crashed instance stays until its lease expires. Third-party registration by the platform, based on observed state, is cleaner.",
            "section": "how-it-works",
            "concept": "sd-service-discovery.registration-styles",
        },
        {
            "key": "aggressive-health-checks",
            "kind": "choice",
            "prompt": "You configure health checks to remove an instance after a single failed probe. What is the trade-off you have accepted?",
            "options": [
                "Slower removal of instances that are really broken",
                "Flapping: healthy instances are removed during a brief blip",
                "The registry becomes overloaded with probes",
                "There is no downside; faster is always better",
            ],
            "answer": 1,
            "explanation": "Aggressive health checking trades fast removal of bad instances against removing healthy ones during a momentary glitch.",
            "section": "trade-offs",
            "concept": "sd-service-discovery.health-check-sensitivity",
        },
        {
            "key": "deploy-error-burst",
            "kind": "choice",
            "prompt": "Every deploy produces a burst of connection errors as old instances exit. Which missing step is the most likely cause?",
            "options": [
                "Registering the new instances earlier",
                "Draining: fail readiness, deregister, let in-flight requests finish, then exit",
                "Raising the DNS TTL so the list changes less often",
                "Running more replicas so the errors are diluted",
            ],
            "answer": 1,
            "explanation": "With no deregistration on shutdown, traffic keeps going to a dying instance for the lease duration. Deregistration on shutdown is what makes deploys clean.",
            "section": "common-failure-modes",
            "concept": "sd-service-discovery.draining",
            "mistake": "sd-service-discovery.no-deregistration",
        },
        {
            "key": "global-config-push",
            "kind": "spot_mistake",
            "prompt": "A team pushes a new rate-limit setting to all 200 instances at once through the config store, saying 'it is just config, not code'. What is wrong?",
            "options": [
                "Config should be hardcoded so it goes through code review",
                "Config changes need staging, canarying, observability and rollback like code; a bad push has a global blast radius",
                "The config store should be read on every request instead",
                "Nothing; configuration is lower risk than a deploy",
            ],
            "answer": 1,
            "explanation": "A bad config push has taken down more large systems than a bad deploy, because config often bypasses the review and canary process code goes through.",
            "section": "common-mistakes",
            "concept": "sd-service-discovery.config-discipline",
            "mistake": "sd-service-discovery.config-without-staging",
        },
    ],
    "sd-search-inverted-index": [
        {
            "key": "cost-is-posting-lists",
            "kind": "choice",
            "prompt": "A corpus grows from 10 million to 100 million documents. What happens to the cost of searching for the rare word 'zirconium' with LIKE '%zirconium%' versus with an inverted index?",
            "options": [
                "Both get about 10 times slower",
                "LIKE reads every row so it gets 10 times slower; the index query costs the size of one short posting list",
                "Both stay the same because the database caches results",
                "LIKE stays the same; the index gets slower because the dictionary grew",
            ],
            "answer": 1,
            "explanation": "A B-tree cannot serve a match in the middle of a string, so the database scans every row. An inverted index query costs the size of the posting lists it touches, not the size of the corpus.",
            "section": "mental-model",
            "concept": "sd-search-inverted-index.cost-model",
            "mistake": "sd-search-inverted-index.like-scales",
        },
        {
            "key": "and-intersection",
            "kind": "choice",
            "prompt": "Posting lists: park -> [1, 3], run -> [1, 2], beach -> [2, 3]. What does the query 'park AND run' return, and how is it computed?",
            "options": [
                "[1, 2, 3], by merging the two lists",
                "[1], by walking both sorted lists with two pointers and keeping the ids in both",
                "[3], by taking the last id in the park list",
                "[2, 3], by subtracting run from beach",
            ],
            "answer": 1,
            "explanation": "AND is an intersection of sorted posting lists. OR is a merge, and phrases need positions on top.",
            "section": "how-it-works",
            "concept": "sd-search-inverted-index.query-execution",
        },
        {
            "key": "bm25-plain-words",
            "kind": "short_answer",
            "prompt": "Document A is very long and mentions 'battery' 50 times. Document B is short and mentions it 5 times. In plain words, what does BM25 do that raw term frequency does not?",
            "options": [],
            "answer": None,
            "model_answer": "Repeats count with diminishing returns (the fiftieth mention is worth much less than the second), long documents are penalised so they are not favoured for having more words, and rare terms count more than common ones (IDF). So B may well outrank A.",
            "explanation": "TF-IDF multiplies term frequency by inverse document frequency; BM25 saturates TF and corrects for document length. Boosting adds product rules on top.",
            "section": "how-it-works",
            "concept": "sd-search-inverted-index.ranking",
        },
        {
            "key": "positions-or-not",
            "kind": "choice",
            "prompt": "You are indexing two things: application logs and product titles. For which should you store term positions?",
            "options": [
                "Both, positions are always needed",
                "Logs, because phrase queries need positions; product titles usually do not, and positions roughly double the index",
                "Neither, positions are only for keyword fields",
                "Product titles only, because they are short",
            ],
            "answer": 1,
            "explanation": "Positions make phrase queries possible and the index bigger. Log search needs them; a product title search often does not.",
            "section": "design-decisions",
            "concept": "sd-search-inverted-index.positions",
        },
        {
            "key": "stop-words-the-who",
            "kind": "choice",
            "prompt": "Your analyser drops stop words. A user searches for the band 'The Who' and gets nothing useful. What trade-off is biting you?",
            "options": [
                "Stemming versus precision",
                "Stop words versus phrases: dropping 'the' saves space but breaks a search made of common words",
                "Refresh interval versus cost",
                "Positions versus size",
            ],
            "answer": 1,
            "explanation": "Stop words match every document and mean little, so dropping them is a good default that breaks exactly this kind of query.",
            "section": "trade-offs",
            "concept": "sd-search-inverted-index.analysis-trade-offs",
        },
        {
            "key": "analyser-mismatch",
            "kind": "spot_mistake",
            "prompt": "Documents are indexed with an English stemmer. The query path only lowercases. Searching 'running' finds nothing even though many documents contain 'run'. What is wrong?",
            "options": [
                "The corpus does not contain the documents",
                "The analyser differs at index time and query time, so the query term 'running' never matches the indexed term 'run'",
                "The stop-word list removed 'running'",
                "The index has no positions",
            ],
            "answer": 1,
            "explanation": "The same analyser must run on documents and on queries. If documents are stemmed and queries are not, nothing matches and nobody knows why.",
            "section": "common-failure-modes",
            "concept": "sd-search-inverted-index.analyser-consistency",
            "mistake": "sd-search-inverted-index.analyser-mismatch",
        },
        {
            "key": "deep-pagination",
            "kind": "choice",
            "prompt": "An index has 20 shards and pages hold 10 results. Page 1 makes the coordinator merge 200 results. Roughly how many does page 100 merge, and what is the fix?",
            "options": [
                "Still 200; each shard returns its top 10",
                "About 20,000, because each shard must return 1,000; cap the depth or use a cursor (search-after)",
                "About 2,000; add more replicas",
                "About 1,000; add more shards",
            ],
            "answer": 1,
            "explanation": "Scatter-gather is cheap for the top k but deep pagination multiplies the work on every shard and the coordinator.",
            "section": "common-failure-modes",
            "concept": "sd-search-inverted-index.deep-pagination",
            "mistake": "sd-search-inverted-index.unbounded-pagination",
        },
        {
            "key": "sellers-own-edit",
            "kind": "choice",
            "prompt": "A seller edits a price and immediately reloads their product page, which reads from the search index. The old price shows. What is the right fix?",
            "options": [
                "Set the refresh interval to zero so writes are visible instantly",
                "Serve the seller's own record from the database after a write; the index is a derived, eventually consistent copy",
                "Reindex the whole catalogue after every edit",
                "Add more replicas so the index catches up faster",
            ],
            "answer": 1,
            "explanation": "The database is the source of truth and the index lags about a second. Treating the index as the source of truth, or promising immediate visibility, are listed mistakes.",
            "section": "common-mistakes",
            "concept": "sd-search-inverted-index.derived-copy",
            "mistake": "sd-search-inverted-index.index-as-source-of-truth",
        },
    ],
    "sd-key-value-store": [
        {
            "key": "writes-per-second",
            "kind": "choice",
            "prompt": "The store handles 40,000 operations per second at peak with three reads for every write. How many writes per second is that, and what does the lesson conclude about the write path?",
            "options": [
                "10,000 per second; the write path must be sequential and cheap",
                "13,333 per second; writes must go to a B-tree",
                "30,000 per second; writes must be batched hourly",
                "40,000 per second; reads can be ignored",
            ],
            "answer": 0,
            "explanation": "One write per four operations gives 10,000 writes per second. Random writes into a big sorted structure on disk would not keep up, which is why the design appends to a log.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-key-value-store.scale",
        },
        {
            "key": "single-node-write-path",
            "kind": "choice",
            "prompt": "On one node, in what order does a write proceed before the client is told 'done'?",
            "options": [
                "Update the memtable, then append to the commit log, then acknowledge",
                "Append to the commit log on disk, then update the memtable, then acknowledge",
                "Write a new SSTable to disk, then acknowledge",
                "Acknowledge, then append to the commit log in the background",
            ],
            "answer": 1,
            "explanation": "The sequential commit-log append makes the write durable before the acknowledgement. Acknowledging before the log is written means a crash loses the write.",
            "section": "step-4-one-machine-first",
            "concept": "sd-key-value-store.log-structured-write",
            "mistake": "sd-key-value-store.ack-before-log",
        },
        {
            "key": "quorum-overlap",
            "kind": "choice",
            "prompt": "With N = 3, W = 2 and R = 2, why is a read guaranteed to see the latest acknowledged value?",
            "options": [
                "Because the coordinator is the master and holds every value",
                "Because W + R > N, so the replicas a read asks overlap the replicas that confirmed the write on at least one node",
                "Because hinted handoff replays every write before a read",
                "Because timestamps always pick the newest version",
            ],
            "answer": 1,
            "explanation": "That is the quorum rule. W = 1 and R = 1 is faster and accepts that a read can be briefly stale.",
            "section": "step-5-many-machines",
            "concept": "sd-key-value-store.quorum",
        },
        {
            "key": "dead-replica-then-heal",
            "kind": "short_answer",
            "prompt": "A replica is down when a write arrives with W = 2. Later it comes back holding stale data. What keeps the write working now, and what fixes the stale replica later?",
            "options": [],
            "answer": None,
            "model_answer": "Now: the other two replicas confirm, so the write succeeds, and the coordinator stores a hint that is replayed when the node returns (hinted handoff). Later: a read that sees two versions returns the newer one and writes it to the stale replica (read repair), and a background anti-entropy process compares ranges with Merkle trees and fixes anything read repair missed.",
            "explanation": "Hinted handoff keeps writes working when a replica is down; read repair and anti-entropy fix stale copies afterwards.",
            "section": "how-it-works",
            "concept": "sd-key-value-store.healing",
            "mistake": "sd-key-value-store.no-hinted-handoff",
        },
        {
            "key": "reads-slow-after-month",
            "kind": "choice",
            "prompt": "Reads got slow after a month in production. Which cause does the lesson point to first?",
            "options": [
                "Too many SSTables per node because compaction fell behind, so each read checks many files",
                "The ring became unbalanced because a node left",
                "Hints piled up on the coordinator",
                "Vector clocks grew too large to compare",
            ],
            "answer": 0,
            "explanation": "Check the file count per node, give compaction more room, and make sure the Bloom filters are sized for the key count.",
            "section": "evolution-under-pressure",
            "concept": "sd-key-value-store.compaction",
        },
        {
            "key": "replicas-one-rack",
            "kind": "choice",
            "prompt": "All three replicas of a key are placed on machines in the same rack. What is the risk, and what does the lesson recommend?",
            "options": [
                "Reads become slower; add a fourth replica",
                "One switch failure loses the key entirely; place replicas in different racks or zones",
                "Hinted handoff stops working; move hints to another rack",
                "Nothing, because the commit log is on disk",
            ],
            "answer": 1,
            "explanation": "No single failure should take all copies. For a second region, replicate asynchronously with a small loss window, or run a cross-region quorum and pay about 100 ms per write.",
            "section": "failure-modes",
            "concept": "sd-key-value-store.replica-placement",
            "mistake": "sd-key-value-store.all-replicas-one-rack",
        },
        {
            "key": "lww-vs-vector-clocks",
            "kind": "choice",
            "prompt": "Two clients update the same key at the same moment on opposite sides of a partition. What happens with timestamp-based last-writer-wins, and what is the alternative?",
            "options": [
                "Both writes are kept automatically; no alternative is needed",
                "One real write is silently lost; vector clocks keep both so the reader or application can merge them",
                "The store refuses both writes; the alternative is consensus",
                "The coordinator merges the values by concatenation",
            ],
            "answer": 1,
            "explanation": "Last writer wins is simple and lossy; vector clocks are correct and harder for callers. Say which you chose and why, and do not pretend the conflict cannot happen.",
            "section": "trade-offs",
            "concept": "sd-key-value-store.versioning",
            "mistake": "sd-key-value-store.conflict-cannot-happen",
        },
        {
            "key": "delete-without-tombstone",
            "kind": "spot_mistake",
            "prompt": "A design handles delete(k) by removing k from the memtable and returning 204. What is wrong?",
            "options": [
                "Nothing, the memtable is the newest data",
                "Older immutable SSTables still hold k, so it reappears on the next read; a delete must be written as a tombstone",
                "Deletes must be sent to every node in the ring",
                "The memtable cannot delete entries because it is sorted",
            ],
            "answer": 1,
            "explanation": "You cannot remove a line from an immutable file, so deletes are written as tombstones and dropped later during compaction. Dropping tombstones too early lets a deleted key come back from an old replica.",
            "section": "common-mistakes",
            "concept": "sd-key-value-store.tombstones",
            "mistake": "sd-key-value-store.delete-without-tombstone",
        },
    ],
    "sd-ride-sharing": [
        {
            "key": "location-write-rate",
            "kind": "choice",
            "prompt": "One million drivers are online, each sending a location ping every 4 seconds. How many location writes per second is that, and where should they go?",
            "options": [
                "250,000 per second, into the primary trip database",
                "250,000 per second, into an in-memory geo-indexed store with a TTL",
                "4 million per second, into a message queue for later processing",
                "250 per second, into a relational table partitioned by month",
            ],
            "answer": 1,
            "explanation": "Data that is worthless after 30 seconds must not go to a durable database. It belongs in memory, keyed geospatially, with any durable trail written asynchronously.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-ride-sharing.ephemeral-locations",
            "mistake": "sd-ride-sharing.locations-in-database",
        },
        {
            "key": "async-ride-request",
            "kind": "choice",
            "prompt": "POST /v1/rides returns 202 with status 'matching' instead of holding the request open until a driver is found. Why?",
            "options": [
                "HTTP cannot keep a request open for more than a second",
                "Matching takes seconds and involves offers and declines, so an async response plus a subscription is the right shape",
                "REST requires 202 for any create",
                "Riders prefer polling to push updates",
            ],
            "answer": 1,
            "explanation": "Holding an HTTP request open while offers are made and declined is the wrong shape, and saying so shows you have thought about how long the matching protocol runs.",
            "section": "step-3-api-design",
            "concept": "sd-ride-sharing.async-matching",
        },
        {
            "key": "location-ttl",
            "kind": "choice",
            "prompt": "Entries in the driver_locations store expire after 30 seconds of silence. What does that expiry handle?",
            "options": [
                "It saves database disk space",
                "Driver disconnections, with no explicit cleanup step",
                "It is required by Redis geospatial commands",
                "It prevents riders from seeing a driver's history",
            ],
            "answer": 1,
            "explanation": "A driver whose app disconnects simply stops refreshing and drops out of the index. The same property lets the whole index rebuild itself within seconds after a node loss.",
            "section": "step-4-data-model",
            "concept": "sd-ride-sharing.ephemeral-locations",
        },
        {
            "key": "check-then-set",
            "kind": "spot_mistake",
            "prompt": "Driver accept path: SELECT driver_state; if current_trip_id is null, UPDATE it to this trip; commit. What is wrong?",
            "options": [
                "It should use a Redis lock with a TTL around the two statements",
                "Two accepts can both see null; use one conditional UPDATE WHERE current_trip_id IS NULL and check rows affected",
                "The check belongs in the location service, not the trip database",
                "Nothing; the transaction makes it safe",
            ],
            "answer": 1,
            "explanation": "Double-booking is prevented by a single-row conditional update in the same transaction that moves the trip to matched. Zero rows updated means another trip claimed the driver first.",
            "section": "how-it-works",
            "concept": "sd-ride-sharing.conditional-update",
            "mistake": "sd-ride-sharing.check-then-set",
        },
        {
            "key": "concert-surge",
            "kind": "choice",
            "prompt": "A concert ends: 10,000 ride requests in one square kilometre within five minutes, and many riders try to claim the same few drivers. What is the strong answer?",
            "options": [
                "Add more Redis shards for the location index",
                "Batch matching: run an assignment over a batch of requests and drivers every second or two, plus queueing and surge",
                "Take a distributed lock on the whole cell during matching",
                "Switch to strictly sequential offers to reduce contention",
            ],
            "answer": 1,
            "explanation": "Greedy per-request matching under surge produces contention and poor assignments. Batch assignment turns a contention problem into an optimisation problem solved once per interval.",
            "section": "evolution-under-pressure",
            "concept": "sd-ride-sharing.batch-matching",
            "mistake": "sd-ride-sharing.greedy-matching",
        },
        {
            "key": "trip-across-services",
            "kind": "choice",
            "prompt": "A design splits the trip state machine across three services: one owns matching, one owns the ride, one owns completion. What does that cost?",
            "options": [
                "Better isolation with no downside",
                "It needs a saga for something that fits in one service and one transaction",
                "Faster transitions because each service is smaller",
                "It is required so payment can be idempotent",
            ],
            "answer": 1,
            "explanation": "Transitions are conditional updates on the current state, validated and appended to trip_events, all in one database. Spreading that across services is a self-inflicted wound.",
            "section": "failure-modes",
            "concept": "sd-ride-sharing.trip-state-machine",
            "mistake": "sd-ride-sharing.state-machine-spread-out",
        },
        {
            "key": "cell-size",
            "kind": "choice",
            "prompt": "You choose one fixed geospatial cell size for the whole country. What goes wrong at each extreme, and what addresses both?",
            "options": [
                "Large cells miss drivers; small cells find too many; fix with a global scan",
                "Large cells scan too many drivers; small cells need many neighbour queries; a hierarchical system (S2, H3) fits both",
                "Large cells break the TTL; small cells break geohash; fix with Redis",
                "There is no trade-off; smaller is always better",
            ],
            "answer": 1,
            "explanation": "Dense city centres and sparse rural areas want different resolutions, which is the argument for a hierarchical cell system. Remember to query neighbouring cells for points near a boundary.",
            "section": "trade-offs",
            "concept": "sd-ride-sharing.geospatial-index",
        },
        {
            "key": "redis-lock-for-assignment",
            "kind": "choice",
            "prompt": "The interviewer proposes a Redis lock with a TTL to prevent double-booking instead of a database constraint. What is the failure you should explain?",
            "options": [
                "Redis is too slow for 230 matches per second",
                "A process holding the lock can pause past the TTL; another claims the driver, the first resumes, and both proceed",
                "Redis cannot hold more than one lock per key",
                "There is no failure; a lock and a constraint are equivalent",
            ],
            "answer": 1,
            "explanation": "The single-row conditional update is a real, transactional mutual exclusion. Reaching for a distributed lock where a database constraint is available is a listed mistake.",
            "section": "common-mistakes",
            "concept": "sd-ride-sharing.conditional-update",
            "mistake": "sd-ride-sharing.distributed-lock",
        },
    ],
    "sd-api-gateway-design": [
        {
            "key": "config-fits-in-memory",
            "kind": "choice",
            "prompt": "5,000 routes with their policies come to a few megabytes. What does that fact enable in the design?",
            "options": [
                "Store the config in a database and query it on each request",
                "Push the whole configuration to every gateway node and hold it in memory; never look it up per request",
                "Shard the configuration across nodes so each holds a slice",
                "Serve the configuration from a CDN edge on demand",
            ],
            "answer": 1,
            "explanation": "Small config read constantly belongs in memory on every node. At 500,000 requests per second, any per-request lookup happens 500,000 times per second.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-api-gateway-design.config-in-memory",
            "mistake": "sd-api-gateway-design.config-lookup-per-request",
        },
        {
            "key": "control-plane-down",
            "kind": "choice",
            "prompt": "The control plane is unavailable for an hour. What happens to traffic through the gateway?",
            "options": [
                "All requests fail because routes cannot be resolved",
                "Traffic continues on the last-known-good configuration; only configuration changes are blocked",
                "Requests slow down while nodes retry the config store",
                "Authentication fails but routing continues",
            ],
            "answer": 1,
            "explanation": "The data plane holds the current config in memory and can run indefinitely without the control plane. A gateway that needs a live config lookup has made the config store a single point of failure for the whole platform.",
            "section": "step-3-the-two-planes",
            "concept": "sd-api-gateway-design.two-planes",
            "mistake": "sd-api-gateway-design.planes-not-separated",
        },
        {
            "key": "cheap-rejections-first",
            "kind": "choice",
            "prompt": "In the request chain, where do route matching and body-size validation belong relative to authentication, and why?",
            "options": [
                "After authentication, so unauthenticated clients learn nothing about routes",
                "Before authentication: cheap rejections before expensive work keeps the gateway cheap under attack",
                "After rate limiting, so limits count every request",
                "The order does not matter for a stateless gateway",
            ],
            "answer": 1,
            "explanation": "Rejecting an oversized body before parsing it and an unknown route before authenticating is the ordering principle of the chain.",
            "section": "step-5-the-request-path",
            "concept": "sd-api-gateway-design.chain-order",
        },
        {
            "key": "rate-limit-at-scale",
            "kind": "choice",
            "prompt": "At 500,000 requests per second, how does the lesson enforce per-consumer rate limits without a Redis round trip per request?",
            "options": [
                "Each node keeps its own independent counter with the full limit",
                "Each node holds a share of each consumer's limit and reconciles with a central store every few hundred milliseconds",
                "Requests are sampled and only one in ten is counted",
                "Rate limiting is moved to the backend services",
            ],
            "answer": 1,
            "explanation": "Local budgets make enforcement approximate within a sync interval, which is the right trade for a rate limiter. A Redis call per request would add a millisecond and a dependency.",
            "section": "how-it-works",
            "concept": "sd-api-gateway-design.local-rate-limits",
        },
        {
            "key": "bad-config-recovery",
            "kind": "short_answer",
            "prompt": "A route change breaks every request to a service. How do you recover in under a minute, and what should have stopped it reaching all nodes?",
            "options": [],
            "answer": None,
            "model_answer": "Roll back by republishing the previous immutable config version number, which takes seconds and needs no deploy. It should have been caught by validation at submission and a staged rollout (one node, then 10%, then all) with automated error-rate checks between stages.",
            "explanation": "Configuration is a deployable artefact: immutable versions, validation, staged rollout and instant rollback. Treating config as less risky than code is a listed mistake.",
            "section": "evolution-under-pressure",
            "concept": "sd-api-gateway-design.config-as-artifact",
            "mistake": "sd-api-gateway-design.unstaged-config",
        },
        {
            "key": "trust-header-not-stripped",
            "kind": "spot_mistake",
            "prompt": "After authentication the gateway adds an X-Tenant-Id header for backends, and forwards all inbound client headers unchanged. What is wrong?",
            "options": [
                "Tenant identity should be carried in a cookie instead",
                "The gateway does not strip a client-supplied X-Tenant-Id, so any client can claim to be any tenant",
                "Headers added by the gateway make responses too large",
                "Nothing; backends verify the header again",
            ],
            "answer": 1,
            "explanation": "The gateway must strip any inbound header it uses internally to convey trusted identity. Forgetting this is a real, recurring vulnerability.",
            "section": "failure-modes",
            "concept": "sd-api-gateway-design.trust-headers",
            "mistake": "sd-api-gateway-design.trust-headers-not-stripped",
        },
        {
            "key": "local-jwt-cost",
            "kind": "choice",
            "prompt": "Tokens are verified locally against cached public keys, so the identity service is not in the request path. What does that cost, and how is it mitigated?",
            "options": [
                "Higher latency per request; mitigated with a bigger CPU budget",
                "A token stays valid until it expires; mitigated with short lifetimes and a small pushed revocation list",
                "Keys must be fetched per request; mitigated with Redis",
                "Nothing; local verification has no downside",
            ],
            "answer": 1,
            "explanation": "Local verification means an identity service outage leaves existing sessions working and only blocks new logins. The price is slower revocation.",
            "section": "trade-offs",
            "concept": "sd-api-gateway-design.local-verification",
        },
        {
            "key": "aggregation-in-gateway",
            "kind": "choice",
            "prompt": "A team wants to add response aggregation for the mobile app into the shared gateway. What risk does the lesson warn about?",
            "options": [
                "Only a small latency increase, which is acceptable",
                "Business logic creeps into the gateway and it becomes a monolith every team must coordinate through",
                "Nothing; aggregation is what a gateway is for",
                "The control plane would need more storage",
            ],
            "answer": 1,
            "explanation": "Putting business logic or response aggregation in the general gateway is a listed mistake, and every added capability is milliseconds on every request forever.",
            "section": "common-mistakes",
            "concept": "sd-api-gateway-design.scope-creep",
            "mistake": "sd-api-gateway-design.business-logic-in-gateway",
        },
    ],
}
