"""Knowledge checks: system design template, back-of-the-envelope estimation, distributed transactions,
monolith vs microservices, cost optimization, rate limiter design, notification system, ticket booking."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "system-design-template": [
        {
            "key": "twenty-five-minutes-no-box",
            "kind": "choice",
            "prompt": "You are 25 minutes into a 45-minute interview and have not drawn a single box yet. Judged against the template's time split, what has gone wrong?",
            "options": [
                "Nothing, the deep dive belongs in the second half anyway",
                "ASK and SIZE ran far too long; SHAPE should have started around minute 10 to 13",
                "You skipped SELL, which should come first",
                "You should have opened with the failure table",
            ],
            "answer": 1,
            "explanation": "ASK takes 5 to 8 minutes and SIZE 3 to 5, so drawing starts near minute 10. The lesson is blunt: twenty-five minutes in with no box means you have already lost, because there is no time left for STRESS.",
            "section": "mental-model",
            "concept": "system-design-template.time-split",
            "mistake": "system-design-template.over-clarifying",
        },
        {
            "key": "shape-order",
            "kind": "choice",
            "prompt": "In the SHAPE step, which order does the template use, and why?",
            "options": [
                "Boxes, then APIs, then data model, because the diagram anchors the conversation",
                "APIs, then data model, then boxes, because the contract and the data model decide if the design is possible",
                "Data model, then boxes, then APIs, because storage is the hard part",
                "Any order, as long as every box is labelled",
            ],
            "answer": 1,
            "explanation": "APIs define the system boundary, the data model usually determines whether the design can work at all, and the boxes are the easy part once those two exist.",
            "section": "how-it-works",
            "concept": "system-design-template.shape-order",
            "mistake": "system-design-template.boxes-first",
        },
        {
            "key": "nfr-justifies-component",
            "kind": "choice",
            "prompt": "Your non-functional list says: p99 start-of-playback under 2 s for viewers worldwide, and view counts may lag by 60 s. Which components do these two lines justify?",
            "options": [
                "A CDN for playback, and an asynchronous counter pipeline for view counts",
                "A CDN for both, since both are read paths",
                "A sharded database for playback, and a cache for view counts",
                "Neither; non-functional requirements describe quality, not components",
            ],
            "answer": 0,
            "explanation": "The non-functional list is what buys architecture. 'Fast globally' buys a CDN; 'counts can lag' buys an async counter pipeline. Skip the list and every later component is a guess.",
            "section": "how-it-works",
            "concept": "system-design-template.requirements-justify-boxes",
        },
        {
            "key": "interviewer-interrupts",
            "kind": "choice",
            "prompt": "Halfway through sketching the architecture, the interviewer says 'let's talk about the database'. What does the lesson recommend?",
            "options": [
                "Ask to finish the architecture first so the template stays in order",
                "Go there now, then return afterwards: 'Good, that covers storage. Can I come back to the read path?'",
                "Explain that storage belongs in the STRESS step and continue",
                "Jump straight to SELL to recover the lost time",
            ],
            "answer": 1,
            "explanation": "The template bends to the interviewer's agenda. When they keep pushing on one area, that is the rubric telling you where the points are, so you go there and come back later.",
            "section": "trade-offs",
            "concept": "system-design-template.follow-the-interviewer",
            "mistake": "system-design-template.rigid-order",
        },
        {
            "key": "unknown-technology",
            "kind": "choice",
            "prompt": "The interviewer suggests Cassandra for a table and you have never used it in production. Which response matches the lesson's recovery line?",
            "options": [
                "Say you have used it, to keep momentum, and move on quickly",
                "Say you have not used it in production, state what you know it is good for, and refocus on the access pattern",
                "Ask to switch to a database you know well instead",
                "Stay quiet and keep drawing until the topic passes",
            ],
            "answer": 1,
            "explanation": "Never bluff. The recovery is honest and useful: name what you do know (a wide-column store with tunable consistency), say where it fits, and bring the discussion back to the access pattern that actually matters.",
            "section": "common-failure-modes",
            "concept": "system-design-template.recovery-lines",
            "mistake": "system-design-template.bluffing",
        },
        {
            "key": "weak-opening",
            "kind": "spot_mistake",
            "prompt": "A candidate opens with: 'Okay, so we'll have a load balancer, some app servers, Redis, a database, and Kafka for events.' What is wrong with this opening?",
            "options": [
                "The components are wrong for most systems",
                "Nothing; naming the stack early shows confidence",
                "Every component is chosen before a requirement or a number justifies it",
                "Kafka should have been named before Redis",
            ],
            "answer": 2,
            "explanation": "The strong opening asks who the users are, what the write volume is, and where the hard parts will be, and only then chooses storage. The difference is deciding what matters before deciding what to use.",
            "section": "what-a-strong-candidate-says",
            "concept": "system-design-template.justify-before-select",
            "mistake": "system-design-template.jumping-to-components",
        },
        {
            "key": "closing-summary",
            "kind": "short_answer",
            "prompt": "In your own words: what belongs in the final thirty-second summary, and why is ending on 'and I think that's it' a mistake?",
            "options": [],
            "answer": None,
            "model_answer": "Recap the architecture in one sentence, name two or three key decisions with what they cost, and volunteer the weakest point or what you would revisit with more time. Trailing off skips SELL entirely; volunteering a weakness reads as senior, being caught by one does not.",
            "explanation": "The summary is the SELL step. It shows you can defend a decision rather than recite one, and closing on your own terms is how you avoid being caught by the weakness you already know about.",
            "section": "common-mistakes",
            "concept": "system-design-template.sell",
            "mistake": "system-design-template.no-summary",
        },
    ],
    "back-of-the-envelope-estimation": [
        {
            "key": "qps-from-daily",
            "kind": "choice",
            "prompt": "A service receives 2 billion requests per day. Using the lesson's anchors, roughly what average and peak QPS should you plan for?",
            "options": ["2K average, 6K peak", "20K average, 60K peak", "20K average, 40K peak", "200K average, 600K peak"],
            "answer": 1,
            "explanation": "Average QPS is requests per day divided by 100,000 seconds: 2B / 100K = 20K. Peak is about 3x average, so 60K. Drop two zeros from millions per day to get QPS.",
            "section": "the-most-important-formula-qps",
            "concept": "back-of-the-envelope-estimation.qps-formula",
        },
        {
            "key": "storage-with-replication",
            "kind": "choice",
            "prompt": "A photo app stores 50 million photos per day at about 2 MB each. Roughly how much raw storage does one day add once replication is included?",
            "options": ["About 30 TB", "About 100 TB", "About 300 TB", "About 1 PB"],
            "answer": 2,
            "explanation": "50M x 2 MB = 100 TB per day, and the lesson says to always multiply by about 3 for replication, giving roughly 300 TB. Add 20 to 30% overhead on top if you want a safer number.",
            "section": "storage-estimation",
            "concept": "back-of-the-envelope-estimation.storage-formula",
            "mistake": "back-of-the-envelope-estimation.forgot-replication",
        },
        {
            "key": "cross-region-latency",
            "kind": "choice",
            "prompt": "An API server in the US reads a value from a database in the EU on every request. Which latency bucket does that hop fall into, and what does it justify?",
            "options": [
                "About 0.5 ms, like a same-datacenter hop; nothing to fix",
                "About 100 ms or more; a replica or a cache near the caller",
                "About 100 microseconds; a faster SSD",
                "About 10 ms, like a disk seek; a faster disk",
            ],
            "answer": 1,
            "explanation": "Cross-region RTT is 80 to 150 ms, roughly 200 to 300x a same-datacenter round trip. Gaps that large are exactly why you cache and place replicas in other regions.",
            "section": "latency-numbers-every-engineer-must-know",
            "concept": "back-of-the-envelope-estimation.latency-hierarchy",
        },
        {
            "key": "concurrent-users",
            "kind": "choice",
            "prompt": "A consumer product has 50M MAU and sessions average 30 minutes. Using the lesson's default ratios, roughly how many concurrent users should you expect?",
            "options": ["About 5M", "About 1M", "About 100K to 200K", "About 10K"],
            "answer": 2,
            "explanation": "DAU is about 10 to 20% of MAU, so 5M to 10M. A 30-minute session means about 2% of DAU are online at once (30 / 1,440), giving 100K to 200K concurrent. Say the assumptions out loud.",
            "section": "users-estimation",
            "concept": "back-of-the-envelope-estimation.users-funnel",
        },
        {
            "key": "bandwidth-suggests-cdn",
            "kind": "choice",
            "prompt": "An endpoint serves 10K QPS with about 100 KB per response. What is the egress bandwidth, and what does the number immediately suggest?",
            "options": [
                "About 1 MB/s; a single server is fine",
                "About 100 MB/s; a bigger network card",
                "About 1 GB/s, roughly 8 Gbps; a CDN, object storage or streaming",
                "About 10 GB/s; shard the database",
            ],
            "answer": 2,
            "explanation": "Bandwidth = QPS x data per request = 10K x 100 KB = 1 GB/s. Since 1 Gbps is about 125 MB/s, that is around 8 Gbps, well past the 'few Gbps' point where the lesson says you need a CDN, multiple NICs or sharding.",
            "section": "bandwidth-estimation",
            "concept": "back-of-the-envelope-estimation.bandwidth-formula",
        },
        {
            "key": "cache-pareto",
            "kind": "choice",
            "prompt": "You have 100M user profiles at 10 KB each. Using the lesson's Pareto heuristic, about how big should the cache be to serve most of the traffic?",
            "options": [
                "About 1 TB, so every profile fits",
                "About 200 GB, plus 20 to 50% headroom for overhead and growth",
                "About 20 GB",
                "About 10 MB",
            ],
            "answer": 1,
            "explanation": "The top 20% of data often serves 80% of traffic: 20M profiles x 10 KB = 200 GB. The lesson's own example sizes a 100 GB working set at 120 to 150 GB in practice, so add headroom.",
            "section": "cache-estimation",
            "concept": "back-of-the-envelope-estimation.cache-sizing",
            "mistake": "back-of-the-envelope-estimation.cache-everything",
        },
        {
            "key": "four-nines-downtime",
            "kind": "spot_mistake",
            "prompt": "A candidate says: 'We promise 99.99% availability, which allows about 8 hours of downtime a year, so a weekly maintenance window is fine.' What is wrong?",
            "options": [
                "Four nines allows only about 52 minutes a year, so weekly windows do not fit",
                "Four nines allows about 5 minutes a year, so no maintenance is possible",
                "Nothing; 8 hours a year is correct for four nines",
                "Availability is measured per month, so the yearly figure is meaningless",
            ],
            "answer": 0,
            "explanation": "8.76 hours is three nines (99.9%). Four nines is about 52.6 minutes a year and five nines about 5.26 minutes. Each extra nine cuts the budget tenfold.",
            "section": "availability-the-9s",
            "concept": "back-of-the-envelope-estimation.availability-nines",
            "mistake": "back-of-the-envelope-estimation.nines-off-by-one",
        },
        {
            "key": "universal-sequence",
            "kind": "short_answer",
            "prompt": "Walk through the universal estimation sequence for a product with 100M users, 10% daily active, and 10 actions per user per day, ending at peak QPS. Say what you would state first.",
            "options": [],
            "answer": None,
            "model_answer": "State the assumptions first. 100M users, 10% DAU gives 10M daily active; 10 actions each gives 100M requests per day; divide by 100K seconds for about 1K average QPS; peak is 3x, so about 3K QPS. Then storage and bandwidth follow from item size, retention and payload.",
            "explanation": "Users, active users, actions per user, requests per day, QPS, peak QPS, then storage and bandwidth. Order-of-magnitude accuracy with visible assumptions is what the interviewer is scoring, not the exact number.",
            "section": "universal-estimation-sequence",
            "concept": "back-of-the-envelope-estimation.sequence",
        },
    ],
    "sd-distributed-transactions": [
        {
            "key": "avoid-first",
            "kind": "choice",
            "prompt": "Two services need atomic updates together on almost every order. Which option does the lesson call the best answer when it is available?",
            "options": [
                "Two-phase commit between the two databases",
                "Redraw the boundary so the data lives in one database and the operation is a local transaction",
                "An orchestrated saga with compensations",
                "Retry both writes until they agree",
            ],
            "answer": 1,
            "explanation": "Avoiding the distributed transaction is the most underrated answer in the topic. Boundaries drawn along transactional boundaries are good boundaries, and constant cross-service atomic updates mean the boundary is wrong.",
            "section": "mental-model",
            "concept": "sd-distributed-transactions.avoid-it",
            "mistake": "sd-distributed-transactions.2pc-by-default",
        },
        {
            "key": "coordinator-dies",
            "kind": "choice",
            "prompt": "In two-phase commit, every participant has prepared and then the coordinator crashes before sending its decision. What happens to the participants?",
            "options": [
                "They commit on their own after a timeout",
                "They abort automatically and release their locks",
                "They hold their locks with no authority to decide until a recovery protocol or a human intervenes",
                "They retry the prepare phase with a new coordinator",
            ],
            "answer": 2,
            "explanation": "This is the blocking problem. Prepared participants have promised they can commit but cannot decide alone, so they hold locks indefinitely. It is the main reason 2PC is avoided across services.",
            "section": "how-it-works",
            "concept": "sd-distributed-transactions.2pc-blocking",
        },
        {
            "key": "step-ordering",
            "kind": "choice",
            "prompt": "A trip saga has: a hotel hold (free to release), a car hold (free to release), a flight booking (cancellation fee), and a payment capture. In what order should the steps run?",
            "options": [
                "Flight first, because seats are the scarcest resource",
                "Payment first, so no work is wasted if the card fails",
                "Hotel and car holds, then the flight, then payment: the least reversible steps go last",
                "Any order; compensation undoes whatever fails",
            ],
            "answer": 2,
            "explanation": "Order the saga so the irreversible or costly step is last and everything before it is reversible. A failure at the flight step then releases two free holds and nobody is charged.",
            "section": "how-it-works",
            "concept": "sd-distributed-transactions.irreversible-last",
            "mistake": "sd-distributed-transactions.irreversible-first",
        },
        {
            "key": "retry-double-booking",
            "kind": "choice",
            "prompt": "A saga step's 'book hotel' response is lost and the orchestrator retries it. What stops a second room being booked?",
            "options": [
                "An idempotency key per operation, stored with its result and checked before the effect",
                "The saga's overall deadline",
                "The transactional outbox",
                "A shorter timeout on the hotel call",
            ],
            "answer": 0,
            "explanation": "Retries are guaranteed, so every step and every compensation must be idempotent. The key lets a retry return the original outcome instead of repeating the effect. The outbox solves a different problem: the local write and the next-step message cannot diverge.",
            "section": "how-it-works",
            "concept": "sd-distributed-transactions.idempotency",
            "mistake": "sd-distributed-transactions.non-idempotent-steps",
        },
        {
            "key": "in-memory-orchestrator",
            "kind": "spot_mistake",
            "prompt": "A saga orchestrator keeps each saga's progress in memory for speed and writes to the database only when the saga completes. What is wrong?",
            "options": [
                "If the orchestrator crashes, in-flight sagas cannot be resumed or compensated",
                "Memory is too slow for saga state",
                "Sagas must be choreographed, so there should be no orchestrator",
                "Nothing; completion is the only state worth persisting",
            ],
            "answer": 0,
            "explanation": "Saga state lives durably in a database keyed by saga id and is updated after each step, so a crashed orchestrator resumes from it. As the lesson puts it, an orchestrator with in-memory state is not an orchestrator.",
            "section": "design-decisions",
            "concept": "sd-distributed-transactions.durable-saga-state",
            "mistake": "sd-distributed-transactions.orchestrator-state-in-memory",
        },
        {
            "key": "choreography-or-orchestration",
            "kind": "choice",
            "prompt": "A fulfilment workflow has eight steps across six services. Choreography or orchestration, and why?",
            "options": [
                "Choreography, because it avoids a central component",
                "Orchestration; choreography is unreadable beyond a few steps and a coordinator makes it visible and testable",
                "Two-phase commit, because eight steps is too many for a saga",
                "Neither; split it into eight independent sagas",
            ],
            "answer": 1,
            "explanation": "Choreography is simple for three steps and unreadable at eight. Orchestration trades decoupling for a central state holder that is debuggable, and the lesson says it wins beyond three steps.",
            "section": "trade-offs",
            "concept": "sd-distributed-transactions.orchestration",
        },
        {
            "key": "allocated-forever",
            "kind": "choice",
            "prompt": "An inventory service marks items 'allocated' when checkout starts. Abandoned checkouts leave items allocated forever and stock slowly disappears. Which fix addresses the cause?",
            "options": [
                "Reservations with an expiry, so abandoned attempts release themselves",
                "Switch to two-phase commit so allocation is atomic",
                "Buy more inventory to cover the leak",
                "Run a manual clean-up every night",
            ],
            "answer": 0,
            "explanation": "Reservations with a short expiry are the semantic lock that makes sagas safe. The expiry is what makes the system self-healing; a reservation with no expiry is a listed failure mode.",
            "section": "common-failure-modes",
            "concept": "sd-distributed-transactions.reservations-expire",
            "mistake": "sd-distributed-transactions.reservation-without-expiry",
        },
        {
            "key": "compensation-fails",
            "kind": "short_answer",
            "prompt": "A compensating action fails permanently, for example the refund API keeps rejecting the call. What should the system do, and which design mistake makes this case a disaster?",
            "options": [],
            "answer": None,
            "model_answer": "Retry with backoff, then move the saga to an exception queue where a human resolves it, with the state recorded so it is attributable. The mistake is designing only the happy path and treating compensation as a rollback that cannot fail, which leaves money or inventory silently inconsistent.",
            "explanation": "Compensations are new business actions with their own effects, and they can fail. Every mature system has an exception queue and a human; pretending otherwise is the tell the lesson warns about.",
            "section": "common-mistakes",
            "concept": "sd-distributed-transactions.compensation-failure",
            "mistake": "sd-distributed-transactions.compensation-as-detail",
        },
    ],
    "sd-monolith-vs-microservices": [
        {
            "key": "split-for-speed",
            "kind": "choice",
            "prompt": "A six-person team wants to split their app into microservices 'so it runs faster'. According to the lesson, does splitting help performance?",
            "options": [
                "Yes, because each service scales independently",
                "No; network calls are slower than function calls. Splitting buys independent deploys and ownership, not speed",
                "Yes, as long as the services use gRPC",
                "Only if a service mesh is added",
            ],
            "answer": 1,
            "explanation": "Microservices are a deployment and ownership boundary. For scaling the whole application you run more copies of the monolith; for code organisation you use modules.",
            "section": "mental-model",
            "concept": "sd-monolith-vs-microservices.what-splitting-buys",
            "mistake": "sd-monolith-vs-microservices.split-for-performance",
        },
        {
            "key": "boundary-rule",
            "kind": "choice",
            "prompt": "Which of these splits follows the lesson's rule for where service boundaries go?",
            "options": [
                "An API layer service, a business logic service, and a database access service",
                "Orders, payments, and catalogue",
                "One service per database table",
                "A read service and a write service",
            ],
            "answer": 1,
            "explanation": "Split along business capabilities, not technical layers. Splitting by layer means every feature change touches every service, and a service per table produces dozens of tiny services one team cannot maintain.",
            "section": "how-it-works",
            "concept": "sd-monolith-vs-microservices.business-capabilities",
            "mistake": "sd-monolith-vs-microservices.split-by-layer",
        },
        {
            "key": "keep-together",
            "kind": "choice",
            "prompt": "Catalogue and orders change together on almost every feature. A colleague proposes splitting them into two services. What does the lesson's boundary test say?",
            "options": [
                "Split them; they are different entities",
                "Keep them together; a boundary that nearly every change crosses turns each feature into a two-service release",
                "Split them for fault isolation",
                "Split them only if they share a database",
            ],
            "answer": 1,
            "explanation": "A good boundary means most changes touch exactly one service. In the lesson's example the company keeps catalogue and orders in the monolith for exactly this reason, and knowing what not to split is the senior part of the answer.",
            "section": "how-it-works",
            "concept": "sd-monolith-vs-microservices.boundary-test",
        },
        {
            "key": "migration-approach",
            "kind": "choice",
            "prompt": "You are asked to migrate a large monolith to services. Which approach does the lesson say every successful large migration follows?",
            "options": [
                "Freeze features and rewrite the system as services over six months",
                "Put a gateway in front, route one endpoint to a new service, mirror traffic to compare, move its data, then repeat",
                "Split the database into per-service schemas first, then the code",
                "Extract every module at once so the cut-over is clean",
            ],
            "answer": 1,
            "explanation": "This is the strangler pattern. Each step is reversible, and the big-bang rewrite is the recognised failure mode.",
            "section": "how-it-works",
            "concept": "sd-monolith-vs-microservices.strangler",
            "mistake": "sd-monolith-vs-microservices.big-bang-rewrite",
        },
        {
            "key": "sync-chains",
            "kind": "choice",
            "prompt": "Service A calls B, which calls C, all synchronously, for every user request. What does the lesson recommend?",
            "options": [
                "Add a shared library so the three services agree on the data model",
                "Prefer asynchronous events where the caller does not need the result, and keep synchronous chains short",
                "Merge the three calls into one larger synchronous call",
                "Add retries at each hop so failures are hidden",
            ],
            "answer": 1,
            "explanation": "Synchronous chains multiply latency and divide availability. Keep synchronous calls for genuine request-response needs, and use events when the caller does not need the answer.",
            "section": "design-decisions",
            "concept": "sd-monolith-vs-microservices.sync-vs-async",
            "mistake": "sd-monolith-vs-microservices.availability-maths-ignored",
        },
        {
            "key": "fifteen-services-one-team",
            "kind": "choice",
            "prompt": "A single team of eight engineers runs fifteen services. Which cost from the lesson are they most likely paying?",
            "options": [
                "Operational multiplication: fifteen partially maintained pipelines, dashboards, alert sets and on-call surfaces",
                "Lower request throughput",
                "Vendor lock-in to one cloud",
                "Tighter coupling between modules",
            ],
            "answer": 0,
            "explanation": "Every service is a deploy pipeline, monitoring, alerts, on-call and backups. The lesson names this exact situation as the real-world failure mode of premature splitting.",
            "section": "trade-offs",
            "concept": "sd-monolith-vs-microservices.operational-multiplication",
        },
        {
            "key": "shared-database",
            "kind": "spot_mistake",
            "prompt": "Five services, each with its own repo and deploy pipeline, all read and write the same Postgres database directly. What is wrong?",
            "options": [
                "Nothing; separate pipelines already give independent deploys",
                "It is a distributed monolith: coupled through the schema, not deployable independently, each can corrupt the others",
                "Postgres cannot serve five services at once",
                "They should share a domain-model library instead of a database",
            ],
            "answer": 1,
            "explanation": "Each service must own its data and no other service touches that store. A shared database keeps all the costs of services and removes the entire benefit. Cross-service reads become APIs or read models; cross-service writes become sagas.",
            "section": "common-failure-modes",
            "concept": "sd-monolith-vs-microservices.data-ownership",
            "mistake": "sd-monolith-vs-microservices.shared-database",
        },
        {
            "key": "new-product-microservices",
            "kind": "choice",
            "prompt": "A small team starting a brand-new product proposes microservices from day one, because the boundaries will be needed eventually. Which mistake is this?",
            "options": [
                "Splitting before knowing the boundaries; wrong boundaries cost far more to fix in a distributed system",
                "Choosing the wrong language for the services",
                "Starting with a monolith instead of a modular monolith",
                "Not adding a service mesh from the start",
            ],
            "answer": 0,
            "explanation": "For a new product with a small team the lesson says modular monolith, almost always. Get the boundaries right first where mistakes are cheap, and extraction later becomes mechanical.",
            "section": "common-mistakes",
            "concept": "sd-monolith-vs-microservices.start-monolith",
            "mistake": "sd-monolith-vs-microservices.split-before-boundaries",
        },
    ],
    "sd-cost-optimization": [
        {
            "key": "surprise-categories",
            "kind": "choice",
            "prompt": "Which two cost categories does the lesson say consistently surprise teams because they grow with traffic and are rarely budgeted?",
            "options": [
                "Compute and storage",
                "Data transfer (cross-AZ and cross-region) and observability",
                "Managed services and licences",
                "CDN and DNS",
            ],
            "answer": 1,
            "explanation": "Compute is where people assume the money goes. Transfer between zones and regions, and log volume, are the line items discovered late.",
            "section": "mental-model",
            "concept": "sd-cost-optimization.where-money-goes",
            "mistake": "sd-cost-optimization.assume-compute-dominates",
        },
        {
            "key": "cross-az-mesh",
            "kind": "choice",
            "prompt": "A chatty service mesh spreads requests randomly across three availability zones. What is the cost problem, and what is the fix?",
            "options": [
                "Cross-AZ traffic is charged per byte; use zone-aware routing with spillover",
                "Latency is too high; add a CDN in front",
                "There is no problem; traffic inside a region is free",
                "Compute is wasted; right-size the fleet",
            ],
            "answer": 0,
            "explanation": "Most clouds charge for cross-AZ traffic, so random spreading generates a large bill for nothing. Zone-aware routing keeps calls local and spills over only when a zone lacks capacity.",
            "section": "how-it-works",
            "concept": "sd-cost-optimization.cross-az-transfer",
            "mistake": "sd-cost-optimization.ignore-cross-zone-charges",
        },
        {
            "key": "most-effective-lever",
            "kind": "choice",
            "prompt": "Which single lever does the lesson call the most effective, because it reduces compute, database load and egress at the same time?",
            "options": [
                "Reserved or committed-use pricing",
                "Caching and CDN offload",
                "Sampling logs and reducing metric cardinality",
                "Moving batch jobs to spot capacity",
            ],
            "answer": 1,
            "explanation": "The cheapest request never reaches your origin. Raising a CDN offload ratio from 85% to 97% can cut origin infrastructure by about half, because the work is removed rather than made cheaper.",
            "section": "how-it-works",
            "concept": "sd-cost-optimization.cache-offload",
        },
        {
            "key": "cost-per-unit",
            "kind": "short_answer",
            "prompt": "In your own words: why does the lesson say to track cost per request or per tenant, rather than just the monthly bill? Give two things it lets you see.",
            "options": [],
            "answer": None,
            "model_answer": "Cost per unit turns cost into an engineering signal instead of a monthly surprise: you can see a deploy make it worse and stop cost growing faster than usage. Attributing cost per tenant also shows which customers are unprofitable, which is a business insight infrastructure can provide.",
            "explanation": "A total bill hides both the regression and the customer. Per-request and per-tenant ratios are what let you alert on cost growing faster than usage and act on unprofitable accounts.",
            "section": "how-it-works",
            "concept": "sd-cost-optimization.cost-per-unit",
            "mistake": "sd-cost-optimization.per-tenant-cost-unmeasured",
        },
        {
            "key": "reliability-target",
            "kind": "choice",
            "prompt": "An internal reporting tool is designed for four nines of availability, but an hour of downtime costs the business very little. What does the lesson say about that target?",
            "options": [
                "It is over-investment; matching the target to the business impact is judgement, not carelessness",
                "Four nines is the minimum any production system should promise",
                "The downtime cost is irrelevant to the availability target",
                "Add a second region to reach five nines instead",
            ],
            "answer": 0,
            "explanation": "Each additional nine costs real money. If the impact of downtime is small, paying for four nines is waste, and saying so out loud is a sign of seniority.",
            "section": "design-decisions",
            "concept": "sd-cost-optimization.cost-of-nines",
        },
        {
            "key": "spot-tradeoff",
            "kind": "choice",
            "prompt": "You move video transcoding to spot capacity for a 60 to 90% discount. What must the workload tolerate, and which design properties make that possible?",
            "options": [
                "Termination at any time; checkpointing per segment, statelessness and idempotency",
                "Higher latency; a larger cache in front",
                "Data loss; a higher replication factor",
                "Nothing; spot capacity behaves exactly like on-demand",
            ],
            "answer": 0,
            "explanation": "Spot is cheap because it can be interrupted. Interruptible work such as batch, transcoding and CI fits, and the lesson's example checkpoints transcoding per segment so a restart loses little.",
            "section": "trade-offs",
            "concept": "sd-cost-optimization.spot-capacity",
        },
        {
            "key": "storage-grows-forever",
            "kind": "choice",
            "prompt": "A system's storage bill grows every month even though user activity is flat. Which cause from the lesson is most likely?",
            "options": [
                "No lifecycle or retention policy, so data nobody reads stays in hot storage forever",
                "The replication factor is too low",
                "Compression is too aggressive",
                "Cross-region egress is being billed as storage",
            ],
            "answer": 0,
            "explanation": "Most systems store data nobody has read in years. Tiering hot to infrequent to archive on an access schedule, and simply deleting, are often the biggest single savings available.",
            "section": "common-failure-modes",
            "concept": "sd-cost-optimization.lifecycle-policies",
            "mistake": "sd-cost-optimization.no-lifecycle",
        },
        {
            "key": "reserved-without-measuring",
            "kind": "spot_mistake",
            "prompt": "A team's bill is growing faster than traffic. They conclude compute must be the cause and buy three-year reserved instances for the whole fleet. What did they get wrong?",
            "options": [
                "They never measured where the money goes; transfer, storage and logs often dominate, and the commitment locks in a guess",
                "Nothing; reserved capacity is always the cheapest option",
                "They should have switched cloud providers first",
                "They should have added more replicas before committing",
            ],
            "answer": 0,
            "explanation": "Assuming compute dominates is a listed mistake. Measure first, and use commitments only for the steady baseline; a fleet running at 10% utilisation is cheaper to right-size than to reserve.",
            "section": "common-mistakes",
            "concept": "sd-cost-optimization.measure-first",
            "mistake": "sd-cost-optimization.assume-compute-dominates",
        },
    ],
    "sd-rate-limiter-design": [
        {
            "key": "real-bottleneck",
            "kind": "choice",
            "prompt": "50,000 limiter decisions per second, 200,000 API keys at about 100 bytes of state each, and a Redis round trip of about 0.3 ms. What is the real bottleneck in this design?",
            "options": [
                "Memory: 200,000 keys will not fit in one Redis node",
                "The round trip on the hot path and the availability of the store, not capacity",
                "CPU on the gateway nodes",
                "Disk throughput for persisting the counters",
            ],
            "answer": 1,
            "explanation": "State is about 20 MB, which is nothing. 50,000 operations per second is comfortable for one Redis node but leaves no headroom, so the design must worry about the latency of the hot-path call and what happens when the store is unreachable.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-rate-limiter-design.scale-conclusions",
        },
        {
            "key": "get-then-set",
            "kind": "choice",
            "prompt": "A gateway implements the token bucket by reading (tokens, last_refill) from Redis with GET, computing the refill in the application, then writing back with SET. What breaks at 50,000 requests per second?",
            "options": [
                "Two concurrent requests read the same count and both proceed; the read-compute-write must be one atomic Lua script",
                "Redis rejects the SET because the key already exists",
                "The refill drifts because SET has no timestamp",
                "Nothing; Redis is single-threaded so this is safe",
            ],
            "answer": 0,
            "explanation": "Redis serialises individual commands, not the gap between GET and SET in your application. That race is exercised constantly at this rate, which is why the check and decrement run inside one Lua script.",
            "section": "step-4-choosing-the-algorithm",
            "concept": "sd-rate-limiter-design.atomicity",
            "mistake": "sd-rate-limiter-design.non-atomic-increment",
        },
        {
            "key": "limiter-placement",
            "kind": "choice",
            "prompt": "Where in the gateway's request path should the limiter run?",
            "options": [
                "After authentication against the user database, so the key is verified",
                "After body parsing, so cost-weighted limits can inspect the request",
                "Before database authentication, body parsing and any upstream call",
                "In the upstream service, closest to the resource being protected",
            ],
            "answer": 2,
            "explanation": "A limiter that runs after the expensive work has already spent the resource it exists to protect. The gateway verifies a signed token locally, evaluates the Lua script, and proxies or returns 429.",
            "section": "step-5-first-architecture",
            "concept": "sd-rate-limiter-design.placement",
            "mistake": "sd-rate-limiter-design.limiter-after-work",
        },
        {
            "key": "global-limit-sync",
            "kind": "spot_mistake",
            "prompt": "A design enforces one global limit per API key by having gateways in all three regions call a single Redis in the US on every request. What is wrong?",
            "options": [
                "It adds 80 to 150 ms to the hot path; use per-region budgets that a central service reallocates from reported usage",
                "Nothing; a single store is the only way to be exact",
                "Redis cannot be reached across regions at all",
                "The limiter should fail open for the remote regions",
            ],
            "answer": 0,
            "explanation": "Nobody coordinates cross-region synchronously on the hot path. Per-region budgets with dynamic reallocation are the practical answer, and the honest statement is that global limits are approximate, bounded by the number of regions.",
            "section": "how-it-works",
            "concept": "sd-rate-limiter-design.multi-region",
            "mistake": "sd-rate-limiter-design.synchronous-global-limit",
        },
        {
            "key": "ten-thousand-accounts",
            "kind": "choice",
            "prompt": "A free-tier user creates 10,000 accounts and stays under the limit on each. The limiter is working perfectly. What does the lesson conclude?",
            "options": [
                "A key the attacker can mint is not an abuse defence; limit account creation and add a dimension like IP range or ASN",
                "Lower the per-key limit for the free tier until the abuse stops",
                "Switch the limiter to fail closed during the attack",
                "Remove the free tier",
            ],
            "answer": 0,
            "explanation": "The attacker controls the dimension you count. Defences are limits on account creation itself, a second limit on something not cheaply minted, and detecting correlated behaviour across accounts.",
            "section": "evolution-under-pressure",
            "concept": "sd-rate-limiter-design.mintable-identifiers",
        },
        {
            "key": "clock-skew",
            "kind": "choice",
            "prompt": "Refill calculations disagree across gateways: some clients get more tokens than others for the same limit. Which cause and fix does the lesson give?",
            "options": [
                "Clock skew between gateway hosts; use the Redis server's clock inside the script instead of each gateway's",
                "Hash collisions on the key; use a longer key",
                "Different Lua versions; pin the script",
                "Network jitter; add retries",
            ],
            "answer": 0,
            "explanation": "Each gateway computing elapsed time from its own clock makes refill inconsistent. Taking the time from Redis inside the script gives every gateway the same clock.",
            "section": "failure-modes",
            "concept": "sd-rate-limiter-design.clock-skew",
        },
        {
            "key": "ten-x-traffic",
            "kind": "choice",
            "prompt": "Traffic grows to 500,000 requests per second and a single Redis cannot take one round trip per request with headroom. Which trade does the lesson recommend?",
            "options": [
                "Local budgets per gateway synced every few hundred milliseconds, giving up exactness within a sync interval",
                "A much larger Redis instance so exact counting continues",
                "Fail open above a traffic threshold",
                "Switch to a sliding window log to reduce load",
            ],
            "answer": 0,
            "explanation": "Central counting versus local budgets is exactness versus a round trip per request. At high scale you give up exactness, which is fine for a rate limiter and should be stated as a deliberate trade.",
            "section": "trade-offs",
            "concept": "sd-rate-limiter-design.local-budgets",
        },
        {
            "key": "redis-unavailable",
            "kind": "short_answer",
            "prompt": "Redis becomes unreachable from the gateways. Explain why both fail-open and fail-closed are wrong, and what the limiter should do instead.",
            "options": [],
            "answer": None,
            "model_answer": "Fail open removes protection exactly when an attack may be causing the outage; fail closed takes the whole API down because the limiter cannot decide. Instead fall back to a conservative in-memory limit per gateway, the global limit divided by the node count, and raise an alert, because degraded limiting is a security-relevant state.",
            "explanation": "Having no answer for the limiter's own failure is a listed mistake. The fallback keeps a bound on total throughput while losing only global accuracy, and the alert makes the degraded state visible.",
            "section": "common-mistakes",
            "concept": "sd-rate-limiter-design.store-failure",
            "mistake": "sd-rate-limiter-design.silent-fail-open",
        },
    ],
    "sd-notification-system": [
        {
            "key": "transactional-vs-marketing",
            "kind": "choice",
            "prompt": "Why does the lesson call the transactional-versus-marketing distinction critical to clarify up front?",
            "options": [
                "Transactional messages must be delivered and bypass most throttling; marketing must respect preferences and unsubscribes",
                "Marketing uses email and transactional uses push",
                "Only marketing needs an idempotency key",
                "Transactional messages are stored and marketing messages are not",
            ],
            "answer": 0,
            "explanation": "A password reset and a promotion need opposite policies. If the rule is not explicit, someone eventually suppresses a security code at 2am.",
            "section": "step-1-clarify-the-requirements",
            "concept": "sd-notification-system.priority-classes",
        },
        {
            "key": "burst-defines-architecture",
            "kind": "choice",
            "prompt": "500M notifications per day is about 5,000 per second average, but a campaign or incident can produce 10M in a few minutes. Which conclusion does the lesson draw?",
            "options": [
                "The burst ratio defines the architecture: a queue absorbs 100,000 per second and workers drain at provider-limited rates",
                "Average QPS defines the architecture; bursts are rare enough to ignore",
                "Delivery-record storage is the binding constraint",
                "Workers must be scaled to send 100,000 per second to providers",
            ],
            "answer": 0,
            "explanation": "Provider rate limits, not your capacity, are usually the binding constraint, so the queue between the API and the workers is the core of the design.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-notification-system.burst-ratio",
        },
        {
            "key": "intent-not-content",
            "kind": "choice",
            "prompt": "Twelve producing services call the notification API. What should each request contain, and why?",
            "options": [
                "The rendered subject and body, so the notification service stays simple",
                "A stable event_key, user, template id and params, so templates and localisation change in one place and retries are safe",
                "Only the user id and channel; the service looks up what to say",
                "A pre-rendered message per channel",
            ],
            "answer": 1,
            "explanation": "Producers send intent, not content, so a template change does not redeploy twelve services. The event_key is mandatory because it is the only defence against a producer retrying.",
            "section": "step-3-api-design",
            "concept": "sd-notification-system.api-contract",
            "mistake": "sd-notification-system.rendered-content",
        },
        {
            "key": "three-dedup-layers",
            "kind": "short_answer",
            "prompt": "Name the three places a duplicate notification can appear, and the guard for each.",
            "options": [],
            "answer": None,
            "model_answer": "Producer retries: a unique constraint on event_key. Queue redelivery: the worker checks the delivery row's state before calling the provider and writes the provider message id with the state change transactionally. Provider retries: a client-supplied idempotency key the provider accepts.",
            "explanation": "A system missing any one of the three will send duplicates, and duplicates are the failure users notice most.",
            "section": "how-it-works",
            "concept": "sd-notification-system.idempotency-layers",
        },
        {
            "key": "two-hundred-events-new-keys",
            "kind": "choice",
            "prompt": "A bug makes one service emit the same order-shipped event 200 times, generating a fresh event_key each time. What limits what the user receives?",
            "options": [
                "The event_key unique constraint absorbs all of them",
                "A content-based hash per user and template within a time window, with the per-user rate limit as the backstop",
                "The provider's idempotency key",
                "The circuit breaker on the provider",
            ],
            "answer": 1,
            "explanation": "With new keys, event_key dedup fails. The secondary content hash catches most of it, and the per-user cap turns a producer bug into five notifications instead of two hundred. That is why the limiter is blast-radius control.",
            "section": "evolution-under-pressure",
            "concept": "sd-notification-system.blast-radius",
            "mistake": "sd-notification-system.no-per-user-limit",
        },
        {
            "key": "quiet-hours-password-reset",
            "kind": "choice",
            "prompt": "A user has quiet hours from 22:00 to 07:00 in their timezone. They request a password reset at 02:00. What should the router do?",
            "options": [
                "Send it now; quiet hours must be explicitly exempted for transactional messages",
                "Hold it until 07:00 to respect the preference",
                "Add it to the morning digest",
                "Suppress it and record the reason",
            ],
            "answer": 0,
            "explanation": "Quiet hours applied to transactional messages is a listed failure mode. Store the timezone, evaluate at send time, and make the exemption an explicit rule.",
            "section": "failure-modes",
            "concept": "sd-notification-system.quiet-hours",
            "mistake": "sd-notification-system.quiet-hours-on-transactional",
        },
        {
            "key": "dedup-window",
            "kind": "choice",
            "prompt": "To be safe, a team widens content-based deduplication to 24 hours per user and template. What does the lesson say this trades away?",
            "options": [
                "Legitimately distinct events get suppressed, such as two different orders shipping on the same day",
                "More duplicates get through",
                "Rendering becomes slower",
                "Provider costs rise",
            ],
            "answer": 0,
            "explanation": "Aggressive deduplication versus missed notifications: too broad a window suppresses real, separate events. The window must be sized to the event, not set as wide as possible.",
            "section": "trade-offs",
            "concept": "sd-notification-system.dedup-window",
        },
        {
            "key": "single-queue-priority-field",
            "kind": "spot_mistake",
            "prompt": "A design uses one queue for push, email and SMS, with a priority field on each message so transactional items come first. The SMS provider slows to a crawl. What is wrong?",
            "options": [
                "Head-of-line blocking: push and email wait behind stuck SMS; a priority field cannot help, a consumer reads in order",
                "Nothing; the priority field keeps transactional messages moving",
                "SMS should not be in the system at all",
                "The queue needs more partitions",
            ],
            "answer": 0,
            "explanation": "Each channel needs its own queue and workers, and campaign traffic needs a separate low-priority queue. Priority must be separated by queue, not by a field inside one queue.",
            "section": "common-mistakes",
            "concept": "sd-notification-system.per-channel-queues",
            "mistake": "sd-notification-system.single-queue",
        },
    ],
    "sd-ticket-booking": [
        {
            "key": "oversell-answer",
            "kind": "choice",
            "prompt": "The interviewer confirms this is reserved seating for concerts, and no seat may ever be sold twice. What does that answer settle about the design?",
            "options": [
                "Inventory needs strong consistency and an exact purchase path; eventual consistency plus reconciliation will not do",
                "The system can be eventually consistent as long as a nightly job resolves conflicts",
                "Overselling by a small margin with compensation is fine, as airlines do",
                "The seats table must be written in every region for availability",
            ],
            "answer": 0,
            "explanation": "Whether overselling is allowed determines the consistency model. A customer told they have seat 14B and later told they do not is worse than a slow page, so this is the clearest CP case in the curriculum.",
            "section": "step-1-clarify-the-requirements",
            "concept": "sd-ticket-booking.consistency-choice",
        },
        {
            "key": "contention-not-throughput",
            "kind": "choice",
            "prompt": "500,000 buyers want 60,000 seats, producing about 200,000 requests per second, mostly seat-map refreshes. Which conclusion does the lesson draw?",
            "options": [
                "Most traffic is browsing by people who will not buy; cache the approximate browse path, keep buying exact",
                "Shard the seats table across ten nodes so writes scale",
                "Add read replicas to serve the hold requests",
                "Provision the database for 200,000 writes per second",
            ],
            "answer": 0,
            "explanation": "88% of users will fail, so most work serves people who buy nothing. Separating the approximate browse path from the exact purchase path is the central move, and no amount of sharding helps when everyone wants the same front-row seats.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-ticket-booking.two-paths",
            "mistake": "sd-ticket-booking.throughput-not-contention",
        },
        {
            "key": "conditional-update",
            "kind": "choice",
            "prompt": "How does the data model guarantee that a seat is never sold twice?",
            "options": [
                "A conditional UPDATE on the seat row with WHERE status = 'available'; zero rows affected means someone else got it",
                "A distributed lock per seat in a coordination service, taken before writing",
                "Read the seat's status, then write 'held' if it was available",
                "A single global queue that serialises every purchase",
            ],
            "answer": 0,
            "explanation": "The database row is the lock, and it is transactional. This is stronger and simpler than a separate lock service, and check-then-act oversells under concurrency.",
            "section": "step-4-data-model",
            "concept": "sd-ticket-booking.conditional-update",
            "mistake": "sd-ticket-booking.distributed-lock",
        },
        {
            "key": "waiting-room",
            "kind": "choice",
            "prompt": "What does the virtual waiting room change about the load the booking service sees at the on-sale moment?",
            "options": [
                "It sees a steady, metered admission rate derived from measured capacity; the waiting page is static on the CDN",
                "It removes the need for holds, because users arrive one at a time",
                "It doubles booking-service capacity by caching hold responses",
                "It queues database writes so they can be replayed later",
            ],
            "answer": 0,
            "explanation": "Users get a queue token at the edge and are admitted at a controlled rate, perhaps 1,000 per second. The 1,000x spike becomes a sized load, contention drops, and the experience is fairer than errors.",
            "section": "how-it-works",
            "concept": "sd-ticket-booking.admission-control",
            "mistake": "sd-ticket-booking.no-admission-control",
        },
        {
            "key": "payment-after-expiry",
            "kind": "short_answer",
            "prompt": "Payment takes 30 seconds and succeeds just after the 10-minute hold expired, so checkout's conditional update fails. What should the system do, and how do you prevent this case?",
            "options": [],
            "answer": None,
            "model_answer": "Never silently keep the money. Try to re-acquire the seats; if they are still available, complete the booking; if not, refund immediately and tell the user clearly. Prevent it by extending the hold when checkout begins so it cannot expire during payment. It is a saga whose compensation is the refund.",
            "explanation": "Ignoring the payment-after-expiry race is a listed mistake. Re-acquire or refund, and extend the hold at checkout so the window is bounded by the payment's own timeout.",
            "section": "evolution-under-pressure",
            "concept": "sd-ticket-booking.payment-expiry-race",
            "mistake": "sd-ticket-booking.keep-money-no-seat",
        },
        {
            "key": "reaper-race",
            "kind": "spot_mistake",
            "prompt": "The reaper runs UPDATE seats SET status='available' WHERE status='held' AND hold_expires_at <= now(). Checkout runs UPDATE seats SET status='sold' WHERE hold_id=? AND status='held'. What is wrong?",
            "options": [
                "Checkout does not require hold_expires_at > now(), so an expired hold can still be sold just before the reaper runs",
                "The reaper should run inside checkout's transaction",
                "Nothing; the database serialises the two updates",
                "The reaper needs a distributed lock before releasing",
            ],
            "answer": 0,
            "explanation": "Both updates must be conditional on the same row and on expiry from opposite sides. Then the database serialises them and exactly one wins, so a sold seat is never released and an expired hold is never purchased.",
            "section": "failure-modes",
            "concept": "sd-ticket-booking.reaper-race",
            "mistake": "sd-ticket-booking.checkout-ignores-expiry",
        },
        {
            "key": "hold-duration",
            "kind": "choice",
            "prompt": "Product asks to raise the hold from 10 minutes to 30 minutes so slow payers are not punished. What is the trade-off the lesson names?",
            "options": [
                "Longer holds remove inventory from sale for longer, which matters enormously when demand exceeds supply",
                "Longer holds increase database contention on the seat rows",
                "Longer holds make the seat map inconsistent",
                "There is no downside; holds are free",
            ],
            "answer": 0,
            "explanation": "Hold duration is kindness to slow payers against seats sitting unsold while others wait. With 500,000 buyers for 60,000 seats, every minute a held seat is off the market is felt.",
            "section": "trade-offs",
            "concept": "sd-ticket-booking.hold-duration",
        },
        {
            "key": "live-seat-map",
            "kind": "choice",
            "prompt": "A design serves GET /seatmap with a live query against the seats table during the on-sale. What is wrong, and what should it do instead?",
            "options": [
                "200,000 requests per second saturate the database that must serve holds; cache the map at the edge with a few-second TTL",
                "Nothing; a live map is required so the hold never fails",
                "The query should use a read replica with synchronous replication",
                "The map should be generated once per event and never refreshed",
            ],
            "answer": 0,
            "explanation": "The map is explicitly approximate with a generated_at timestamp, and a failed hold shows 'someone just took that seat'. For the hottest events, offering only best-available removes the browsing contention entirely.",
            "section": "common-mistakes",
            "concept": "sd-ticket-booking.seat-map-freshness",
            "mistake": "sd-ticket-booking.live-seat-map",
        },
    ],
}
