"""Knowledge checks: stateless services, API design, indexes, Kafka vs queues, coordination, scalability, probabilistic structures, YouTube, web crawler, collaborative editor."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "sd-stateless-services": [
        {
            "key": "memory-rule",
            "kind": "choice",
            "prompt": "A service keeps each user's shopping cart in the process memory of the node that served them. By the lesson's rule, what is the only kind of data that may live in an app node's memory?",
            "options": [
                "A pure cache: losing it costs latency, never correctness",
                "Anything that fits, as long as the node has a replica",
                "Small session data, since it is cheap to rebuild",
                "Data that is also written to the node's local disk",
            ],
            "answer": 0,
            "explanation": "State does not disappear, it moves to a component built to hold it. Anything left in process memory must be a pure cache, so a node dying or being replaced never loses a cart.",
            "section": "mental-model",
            "concept": "sd-stateless-services.state-moves",
            "mistake": "sd-stateless-services.state-in-process",
        },
        {
            "key": "scaling-order",
            "kind": "choice",
            "prompt": "Your app and its single database are near capacity. In what order does the lesson say to scale, and why?",
            "options": [
                "Vertically first, then the stateless tier horizontally, then partition the data tier",
                "Partition the data tier first, because it is the real bottleneck",
                "Scale out first; vertical scaling is a sign of poor design",
                "Add read replicas, then shard, then move to bigger machines",
            ],
            "answer": 0,
            "explanation": "Vertical scaling is free engineering time, scaling a stateless tier out is nearly free, and partitioning the data tier is the only genuinely hard move, so it comes last.",
            "section": "how-it-works",
            "concept": "sd-stateless-services.scaling-order",
            "mistake": "sd-stateless-services.shard-first",
        },
        {
            "key": "jwt-revocation",
            "kind": "choice",
            "prompt": "You replace sticky sessions with self-contained signed JWTs that need no server lookup. What new problem must you now answer?",
            "options": [
                "Revocation: a token stays valid until it expires",
                "Validation: only the node that issued the token can check it",
                "Availability: Redis is now on the auth path",
                "Claims: a token cannot carry roles or identity",
            ],
            "answer": 0,
            "explanation": "A self-contained token is fast and dependency-free, but it is valid until expiry. Mitigate with short lifetimes plus refresh tokens, or a small revocation list checked on sensitive operations.",
            "section": "how-it-works",
            "concept": "sd-stateless-services.tokens-vs-store",
            "mistake": "sd-stateless-services.jwt-no-revocation",
        },
        {
            "key": "websocket-tier",
            "kind": "choice",
            "prompt": "You add WebSockets for live order tracking. How does the lesson keep the rest of the system horizontally scalable?",
            "options": [
                "Thin gateway holds sockets only; a registry maps user_id to gateway; deliver via pub/sub",
                "Pin each user to one app node with sticky sessions for every endpoint",
                "Store each socket's state in the database so any node can resume it",
                "Run one large gateway node so all sockets live in one place",
            ],
            "answer": 0,
            "explanation": "Long-lived connections are the one legitimately stateful tier. Keep it thin: sockets in the gateway, a Redis registry of user to gateway, messages published to the owning gateway's channel, business logic in stateless services behind it.",
            "section": "how-it-works",
            "concept": "sd-stateless-services.connection-gateway",
        },
        {
            "key": "local-cache-bound",
            "kind": "choice",
            "prompt": "You add an in-process cache in front of Redis to remove a network hop for the hottest keys. What bound does the lesson put on it?",
            "options": [
                "A TTL of seconds, and never hold anything correctness depends on",
                "The same TTL as Redis so both stay in sync",
                "No TTL, but invalidate every node on each write",
                "Only values under 1 KB, to keep memory small",
            ],
            "answer": 0,
            "explanation": "A local cache introduces per-node staleness: different users get different answers depending on which node they hit. Bound it with a short TTL and keep correctness-critical data out of it.",
            "section": "design-decisions",
            "concept": "sd-stateless-services.local-cache",
            "mistake": "sd-stateless-services.long-local-ttl",
        },
        {
            "key": "in-memory-rate-limit",
            "kind": "choice",
            "prompt": "A service enforces 100 requests per minute per user with an in-memory counter. It runs on 8 nodes behind a round-robin load balancer. What limit does a user actually get?",
            "options": [
                "About 800 per minute, because each node counts on its own",
                "Exactly 100, because round-robin spreads requests evenly",
                "About 12 per minute, because each node sees a fraction",
                "100 per minute, but only while all 8 nodes stay up",
            ],
            "answer": 0,
            "explanation": "Each node enforces its own limit, so the effective limit is N times what you intended. Counters are state and belong in a shared store, not in process memory.",
            "section": "common-failure-modes",
            "concept": "sd-stateless-services.shared-counters",
            "mistake": "sd-stateless-services.per-node-counter",
        },
        {
            "key": "single-redis",
            "kind": "spot_mistake",
            "prompt": "A design says: 'The app tier is stateless. Sessions live in Redis, so deploys are safe. Redis runs as a single instance to keep things simple.' What is wrong?",
            "options": [
                "Redis is now a critical dependency on the auth path and needs replication and failover",
                "Sessions should be in Postgres, because Redis cannot hold them",
                "A stateless app tier is not allowed to talk to Redis",
                "Sticky sessions would be simpler and just as safe",
            ],
            "answer": 0,
            "explanation": "Moving state out creates a new dependency with its own availability story. A single Redis restart logs everyone out at once and the login stampede can take down the auth service.",
            "section": "common-mistakes",
            "concept": "sd-stateless-services.session-store-dependency",
            "mistake": "sd-stateless-services.forgot-store-availability",
        },
        {
            "key": "acceptable-stickiness",
            "kind": "short_answer",
            "prompt": "In your own words: when is sticky or in-process state an acceptable exception to statelessness, and how do you limit the damage?",
            "options": [],
            "answer": None,
            "model_answer": "Acceptable for a specific need: an in-progress multipart upload, a WebSocket, a server-side rendering cache, or a server holding a large model that is expensive to rebuild. Scope the stickiness to that endpoint rather than the whole service, keep the stateful tier thin, and make sure losing the node costs a reconnect or latency, not data.",
            "explanation": "Statelessness costs some recompute per request. That cost is usually far smaller than the operational cost of stickiness, but not always, so name the exception and confine it.",
            "section": "trade-offs",
            "concept": "sd-stateless-services.stateful-exceptions",
        },
    ],
    "api-design": [
        {
            "key": "skipped-question",
            "kind": "choice",
            "prompt": "GET /users/{id}/orders returns every order the user has ever placed. It has worked fine for two years. Which of the lesson's four per-endpoint questions did its designer skip?",
            "options": [
                "What is the worst-case response size?",
                "Who calls this, and how often?",
                "Is it safe to retry?",
                "What does it return when the work is slow?",
            ],
            "answer": 0,
            "explanation": "The worst-case size question is the one candidates skip and the one that kills systems. The endpoint is fine until someone has 400,000 orders, then it times out and takes the database with it.",
            "section": "mental-model",
            "concept": "api-design.four-questions",
            "mistake": "api-design.unbounded-list",
        },
        {
            "key": "idempotency-retry",
            "kind": "choice",
            "prompt": "A client's POST /v1/links times out, so it retries with the same Idempotency-Key header. What should the server do?",
            "options": [
                "Return the stored original response without creating a second link",
                "Create a second link, since POST is not idempotent",
                "Return 409 Conflict so the client can GET the first link",
                "Reject with 400 because the key was already used",
            ],
            "answer": 0,
            "explanation": "The server stores the key with the result for about 24 hours. A repeat with the same key returns the original response. This is how payment APIs work and is the expected answer to 'what if the client retries?'.",
            "section": "how-it-works",
            "concept": "api-design.idempotency-key",
            "mistake": "api-design.retry-duplicates",
        },
        {
            "key": "cursor-vs-offset",
            "kind": "choice",
            "prompt": "A feed table has 10 million rows. A client requests page 5,000 with LIMIT 20 OFFSET 100000. Why is the lesson's cursor approach cheaper?",
            "options": [
                "Offset makes the database walk and discard 100,000 rows; a cursor seeks directly at constant cost",
                "Cursors are cached by the client, so the server does no work",
                "Offset pagination cannot use an index at all",
                "Cursors let the client jump straight to any page number",
            ],
            "answer": 0,
            "explanation": "Offset cost grows linearly with depth and shifts when data changes. Keyset queries like WHERE id < ? LIMIT 20 use the index directly, so page 5,000 costs the same as page 1. Cursors give up page jumps in return.",
            "section": "how-it-works",
            "concept": "api-design.pagination",
            "mistake": "api-design.offset-on-large-table",
        },
        {
            "key": "long-running",
            "kind": "choice",
            "prompt": "A video upload kicks off processing that takes several minutes. What should POST /v1/videos return?",
            "options": [
                "202 Accepted with a job_id and status_url; the client polls or gets a webhook",
                "200 OK once processing finishes, so the client knows it worked",
                "201 Created with the fully processed video representation",
                "503 until the processing queue has capacity",
            ],
            "answer": 0,
            "explanation": "Anything longer than a second or two should not hold the request open. Returning 202 with a job id is the API-level signature of an async pipeline and makes the queue on the diagram necessary rather than decorative.",
            "section": "how-it-works",
            "concept": "api-design.async-operations",
            "mistake": "api-design.sync-long-work",
        },
        {
            "key": "batch-partial-failure",
            "kind": "choice",
            "prompt": "You add POST /v1/items/batch that accepts 100 items. Item 37 fails validation. What should the response look like?",
            "options": [
                "Per-item status for all 100 items",
                "422 for the whole batch, so the client retries everything",
                "200 OK, silently skipping item 37",
                "202 Accepted, with the valid items processed later",
            ],
            "answer": 0,
            "explanation": "A bulk endpoint turns 100 round trips into one, but it needs partial-failure semantics. Return per-item status rather than failing the whole batch.",
            "section": "design-decisions",
            "concept": "api-design.bulk-endpoints",
        },
        {
            "key": "200-with-error",
            "kind": "choice",
            "prompt": "An API returns 200 OK with the JSON body {error: 'rate limited'} when a client exceeds its quota. What goes wrong?",
            "options": [
                "Clients branch on status codes, so they treat it as success or retry blindly",
                "Nothing; the body tells the client exactly what happened",
                "The client's HTTP library will throw on the JSON body",
                "200 is fine, but the body should be HTML so humans can read it",
            ],
            "answer": 0,
            "explanation": "Clients build retry logic off status codes. Lying about them produces retry storms. Use 429 with Retry-After, and a structured body with a stable code, a message and a request_id.",
            "section": "common-mistakes",
            "concept": "api-design.honest-status-codes",
            "mistake": "api-design.200-for-errors",
        },
        {
            "key": "breaking-change",
            "kind": "spot_mistake",
            "prompt": "A team removes a deprecated response field and changes a default from false to true. They ship both under /v1 as a 'non-breaking cleanup'. What is wrong?",
            "options": [
                "Removing a field and changing a default are breaking changes; clients you do not control never upgrade",
                "Nothing, because the field was marked deprecated first",
                "It should have used header versioning instead of a path",
                "Only the removal is breaking; changing a default is safe",
            ],
            "answer": 0,
            "explanation": "Adding an optional field is safe. Removing a field, changing a type, or changing a default is not. Breaking changes need a new version and a deprecation window.",
            "section": "common-failure-modes",
            "concept": "api-design.evolution",
            "mistake": "api-design.breaking-as-nonbreaking",
        },
        {
            "key": "style-choice",
            "kind": "choice",
            "prompt": "A mobile app needs data from six services to render one screen, and your backend also has heavy internal service-to-service traffic. Which default does the lesson suggest?",
            "options": [
                "REST at the edge with a BFF or gateway aggregating for mobile; gRPC between internal services",
                "GraphQL everywhere, so every client picks its own fields",
                "gRPC at the edge for speed; REST internally for simplicity",
                "Let the mobile client call all six services directly",
            ],
            "answer": 0,
            "explanation": "REST at the edge is cacheable and simple; gRPC internally gives speed and typed contracts. Chunkier wins on mobile because round trips are expensive, so a BFF or gateway owns the aggregation. GraphQL is for many heterogeneous clients and brings query cost control problems.",
            "section": "trade-offs",
            "concept": "api-design.rest-grpc-graphql",
            "mistake": "api-design.chatty-mobile",
        },
    ],
    "sd-indexes": [
        {
            "key": "sorted-copy",
            "kind": "choice",
            "prompt": "An index is a sorted copy of a column with a pointer back to the row. Given a plain B-tree index on email, which query can it serve?",
            "options": [
                "WHERE email = ? or WHERE email LIKE 'ann%'",
                "WHERE email LIKE '%@example.com'",
                "WHERE lower(email) = ?",
                "WHERE email contains a given substring",
            ],
            "answer": 0,
            "explanation": "Sorted means it serves equality, range, prefix and ordering. It cannot serve 'contains', a leading wildcard, or a function of the column unless you indexed that expression.",
            "section": "mental-model",
            "concept": "sd-indexes.sorted-copy",
            "mistake": "sd-indexes.index-serves-anything",
        },
        {
            "key": "composite-order",
            "kind": "choice",
            "prompt": "Query: all orders for tenant 42 with status 'open', newest first. Which single index serves both the filter and the sort?",
            "options": [
                "(tenant_id, status, created_at)",
                "(created_at, tenant_id, status)",
                "(tenant_id, created_at, status)",
                "Three separate single-column indexes",
            ],
            "answer": 0,
            "explanation": "Equality columns first, then the range or sort column. With created_at in the middle the database can filter with the index but must sort the whole matching set in memory.",
            "section": "how-it-works",
            "concept": "sd-indexes.composite-order",
            "mistake": "sd-indexes.sort-column-first",
        },
        {
            "key": "leftmost-prefix",
            "kind": "choice",
            "prompt": "You have a composite index on (a, b, c). A hot query filters on column b alone. What happens?",
            "options": [
                "The index is not used efficiently; it is sorted by a first, so b alone has no prefix",
                "The index is used, because b is one of its columns",
                "The index is used only if c is also in the WHERE clause",
                "The index is used but the results must be re-sorted",
            ],
            "answer": 0,
            "explanation": "This is the leftmost-prefix rule. A composite on (a, b, c) serves a, then a and b, then a, b and c. Filtering on b alone needs its own index.",
            "section": "how-it-works",
            "concept": "sd-indexes.leftmost-prefix",
        },
        {
            "key": "low-selectivity",
            "kind": "choice",
            "prompt": "A table has a boolean archived column and 95% of rows are false. Queries fetch WHERE archived = true. What is the best index?",
            "options": [
                "A partial index covering only the rows WHERE archived = true",
                "A plain B-tree index on archived",
                "A hash index on archived",
                "No index; the planner will always choose a scan",
            ],
            "answer": 0,
            "explanation": "An index only helps if it eliminates most rows. On a low-selectivity column the planner ignores it, because a scan beats millions of random row fetches. A partial index on the rare value is small and fast.",
            "section": "how-it-works",
            "concept": "sd-indexes.selectivity",
            "mistake": "sd-indexes.index-low-selectivity",
        },
        {
            "key": "hot-table-build",
            "kind": "choice",
            "prompt": "You need to add an index to a 500 GB table that serves live traffic. How do you do it?",
            "options": [
                "Build it concurrently, or build on a replica and promote",
                "Run CREATE INDEX during business hours; it only reads the table",
                "Drop the other indexes first so the build is faster",
                "Shard the table first, then index each shard",
            ],
            "answer": 0,
            "explanation": "A blocking index build on a large busy table is an outage. Plan schema migrations as carefully as deploys: concurrent builds or a replica-first rollout.",
            "section": "design-decisions",
            "concept": "sd-indexes.safe-migration",
            "mistake": "sd-indexes.blocking-build",
        },
        {
            "key": "twelve-indexes",
            "kind": "spot_mistake",
            "prompt": "Design: 'The orders table is write-heavy. To make every dashboard filter fast we add one index per column, twelve in total.' What is wrong?",
            "options": [
                "Every insert now updates twelve indexes; write throughput and storage suffer, and narrow indexes combine poorly",
                "Nothing; more indexes never hurt, only help reads",
                "Twelve is fine, but they should all be hash indexes",
                "The indexes must be unique for the planner to use them",
            ],
            "answer": 0,
            "explanation": "Each index adds write amplification and 10 to 30% of the table in storage. Prefer a small number of well-chosen composites for the common query shapes. Unused indexes are pure cost.",
            "section": "common-failure-modes",
            "concept": "sd-indexes.index-cost",
            "mistake": "sd-indexes.index-everything",
        },
        {
            "key": "slow-query-first-step",
            "kind": "choice",
            "prompt": "A query on a 200 million row table takes seconds. The candidate proposes sharding. What does the lesson say to do first?",
            "options": [
                "Look at the plan: is there a usable, selective index, and is the sort done by the index?",
                "Add a cache in front of the query",
                "Move to a larger database instance",
                "Shard by the sort column",
            ],
            "answer": 0,
            "explanation": "Most database performance problems are one missing or unusable index. Sharding or caching when the fix is one composite index is the most common mistake in this area.",
            "section": "common-mistakes",
            "concept": "sd-indexes.check-plan-first",
            "mistake": "sd-indexes.shard-instead-of-index",
        },
        {
            "key": "index-vs-materialised",
            "kind": "choice",
            "prompt": "A read joins three tables under tight latency and is still slow after indexing. What alternative does the lesson offer, and what does it cost?",
            "options": [
                "A materialised view or denormalised column: a precomputed answer, at the cost of staleness and refresh",
                "A covering index across all three tables at once",
                "A hash index on each join key",
                "OFFSET pagination to cut the result size",
            ],
            "answer": 0,
            "explanation": "An index speeds a query; a materialised view removes it. You trade staleness and a refresh job for a precomputed answer.",
            "section": "trade-offs",
            "concept": "sd-indexes.index-vs-materialised-view",
        },
    ],
    "sd-kafka-vs-queue": [
        {
            "key": "offset-bookmark",
            "kind": "choice",
            "prompt": "A queue is a to-do list; a log is a ledger. In a log, what single piece of consumer state decides what a consumer sees, and what does changing it give you?",
            "options": [
                "Its offset per partition; rewinding it replays history",
                "Its ack list; clearing it redelivers unacked messages",
                "Its visibility timeout; extending it holds messages longer",
                "Its group id; changing it deletes consumed messages",
            ],
            "answer": 0,
            "explanation": "Because the log retains messages, the consumer's bookmark is the only thing that determines what it reads. Rewind the offset and you replay. That single property makes a log a different tool from a queue.",
            "section": "mental-model",
            "concept": "sd-kafka-vs-queue.offset-replay",
        },
        {
            "key": "partition-cap",
            "kind": "choice",
            "prompt": "A topic has 16 partitions. The search-indexer consumer group runs 24 consumers. How many do useful work?",
            "options": [
                "16; parallelism is capped by partition count",
                "24; each consumer takes a slice of every partition",
                "8; consumers pair up on partitions",
                "It depends on the replication factor",
            ],
            "answer": 0,
            "explanation": "Each partition is read by one consumer in a group, so 16 partitions means at most 16 useful consumers. The extra 8 sit idle.",
            "section": "how-it-works",
            "concept": "sd-kafka-vs-queue.partition-parallelism",
            "mistake": "sd-kafka-vs-queue.consumers-unbounded",
        },
        {
            "key": "buggy-consumer",
            "kind": "choice",
            "prompt": "The search indexer mis-processed two days of events. With a log, how do you recover, and why is the same recovery impossible with a queue?",
            "options": [
                "Fix the code, reset the group's offset two days back, reprocess; a queue deleted the messages on consumption",
                "Ask producers to republish two days of events; a queue cannot accept republished messages",
                "Restart the broker so it redelivers; a queue cannot restart safely",
                "Point the consumer at a new topic; a queue has only one",
            ],
            "answer": 0,
            "explanation": "Retention plus offsets make replay a routine operation that needs no coordination with other groups. With a queue the only recovery is a bespoke backfill from the database. Confirm the consumer is idempotent first.",
            "section": "how-it-works",
            "concept": "sd-kafka-vs-queue.offset-replay",
        },
        {
            "key": "compaction",
            "kind": "choice",
            "prompt": "You want a topic that can rebuild a cache of every user's current profile from nothing, without storing every historical change forever. Which retention setting?",
            "options": [
                "Log compaction: keep only the latest message per key",
                "Seven-day time retention",
                "Size retention of 500 GB per partition",
                "Zero retention, so the topic behaves like a queue",
            ],
            "answer": 0,
            "explanation": "Compaction turns the topic into a snapshot of current state that can be replayed to rebuild a cache or materialised view. Mentioning it is a real depth signal.",
            "section": "how-it-works",
            "concept": "sd-kafka-vs-queue.compaction",
        },
        {
            "key": "outbox-instead",
            "kind": "choice",
            "prompt": "A small team emits 50 events per second to a single consumer and needs ordering and the ability to replay. What does the lesson suggest?",
            "options": [
                "An outbox table in the existing database, polled by a worker",
                "Self-hosted Kafka with 16 partitions",
                "A managed queue, since replay is rarely used",
                "Redis Streams, because Redis is fast",
            ],
            "answer": 0,
            "explanation": "At modest volume an outbox table gives ordering, retention and replay with no new system, and it is transactional and already backed up. Reaching for Kafka at 50 events per second is over-engineering.",
            "section": "design-decisions",
            "concept": "sd-kafka-vs-queue.outbox",
            "mistake": "sd-kafka-vs-queue.kafka-for-low-volume",
        },
        {
            "key": "add-partitions",
            "kind": "choice",
            "prompt": "Your topic is keyed by user_id and you double the partition count to allow more consumers. What breaks?",
            "options": [
                "Key-to-partition mapping changes, so per-user ordering breaks across the change",
                "Nothing; partitions can be added and removed freely",
                "Retention is halved because it is split across more partitions",
                "Consumer groups lose their offsets and restart from the beginning",
            ],
            "answer": 0,
            "explanation": "Partition count is easy to increase and hard to decrease, and increasing it changes which partition a key maps to. Size partition count for target parallelism plus headroom up front.",
            "section": "common-failure-modes",
            "concept": "sd-kafka-vs-queue.partition-count",
        },
        {
            "key": "exactly-once-claim",
            "kind": "spot_mistake",
            "prompt": "Design: 'We use Kafka transactions, so each event is written exactly once to Postgres. Consumers commit the offset before processing each batch to avoid duplicates.' What is wrong?",
            "options": [
                "Exactly-once covers Kafka-to-Kafka only, not Postgres; committing before processing loses messages on crash",
                "Nothing; this is the standard exactly-once setup",
                "Only the offset order is wrong; transactions do cover Postgres",
                "Transactions should be replaced by a higher replication factor",
            ],
            "answer": 0,
            "explanation": "Delivery is at-least-once by default. Transactional produce plus offset commit gives exactly-once within Kafka and does not cover an external write. Commit the offset after processing, and make the consumer idempotent.",
            "section": "common-mistakes",
            "concept": "sd-kafka-vs-queue.delivery-semantics",
            "mistake": "sd-kafka-vs-queue.exactly-once-external",
        },
        {
            "key": "hot-partition",
            "kind": "short_answer",
            "prompt": "A topic is partitioned by customer_id and one customer produces 15% of all events. Explain what goes wrong and what trade-off you are managing.",
            "options": [],
            "answer": None,
            "model_answer": "All of that customer's events land on one partition, so it becomes a hot partition, like a hot shard: the whole pipeline is limited to one consumer's throughput for that key. The trade-off is ordering versus parallelism. Per-partition ordering is the compromise, and a skewed key breaks it. Check the key distribution before choosing, and pick a finer key (such as order_id) if ordering is only needed at that grain.",
            "explanation": "The partition key should be the entity whose ordering matters, but if one key is a large fraction of volume you have a hot partition. Naming the skew risk when you name the key is what the interviewer wants.",
            "section": "trade-offs",
            "concept": "sd-kafka-vs-queue.partition-key-skew",
            "mistake": "sd-kafka-vs-queue.ignore-skew",
        },
    ],
    "sd-coordination": [
        {
            "key": "majority-partition",
            "kind": "choice",
            "prompt": "A 5-node etcd cluster splits into a 3-node side and a 2-node side. What happens?",
            "options": [
                "The 3-node side can elect a leader and commit; the 2-node side makes no progress and cannot diverge",
                "Both sides elect a leader and reconcile when the split heals",
                "Neither side proceeds until all 5 nodes are reachable",
                "The 2-node side keeps serving because it still has the old leader",
            ],
            "answer": 0,
            "explanation": "Consensus needs a majority. A minority partition cannot elect anyone or commit entries, which is exactly the property that prevents split brain. A coordination service is CP.",
            "section": "mental-model",
            "concept": "sd-coordination.majority",
            "mistake": "sd-coordination.both-sides-lead",
        },
        {
            "key": "gc-pause-lock",
            "kind": "choice",
            "prompt": "Client A takes a Redis lock with a 30 s TTL, then pauses 40 s for garbage collection. Client B takes the lock. A resumes and writes. Why does no Redis setting fix this?",
            "options": [
                "A cannot know time passed; only a fencing token that the resource checks can reject A's stale write",
                "A longer TTL would have prevented it",
                "Redis replication would have stopped B from acquiring the lock",
                "A should delete the key before it resumes",
            ],
            "answer": 0,
            "explanation": "Both clients are in the critical section. The lock service issues an increasing token with each grant, every write carries it, and the resource rejects any token lower than the highest it has seen. A's write with token 33 loses to the 34 already seen.",
            "section": "how-it-works",
            "concept": "sd-coordination.fencing-tokens",
            "mistake": "sd-coordination.ttl-lock-is-safe",
        },
        {
            "key": "resource-cannot-fence",
            "kind": "choice",
            "prompt": "The resource you want to protect is a third-party API that ignores any extra token you send. Can you build a correct distributed lock around it?",
            "options": [
                "No; fencing needs the resource to reject old tokens, so design to not need a lock: idempotency or partitioning",
                "Yes, by using etcd instead of Redis for the lock",
                "Yes, if the lease is renewed at a third of the TTL",
                "Yes, as long as all clocks are synchronised",
            ],
            "answer": 0,
            "explanation": "Fencing requires the protected resource to participate. If the downstream cannot check a token, you cannot have a correct distributed lock, so remove the need for one.",
            "section": "how-it-works",
            "concept": "sd-coordination.fencing-tokens",
        },
        {
            "key": "billing-progression",
            "kind": "choice",
            "prompt": "Twelve instances, one hourly billing job. Which progression does the lesson say an interviewer hopes to hear?",
            "options": [
                "Lock, then make it idempotent with a unique constraint on (customer, period), then partition customers across instances",
                "Cron on every instance, and dedupe invoices afterwards",
                "A Redis SET NX lock with a generous TTL, and stop there",
                "Run the job only on the instance with the lowest IP address",
            ],
            "answer": 0,
            "explanation": "With the unique constraint, a second run's inserts conflict and are skipped, so correctness no longer depends on the lock. Partitioning by hash(customer_id) removes mutual exclusion entirely and makes the work parallel.",
            "section": "how-it-works",
            "concept": "sd-coordination.avoid-coordination",
            "mistake": "sd-coordination.lock-as-first-answer",
        },
        {
            "key": "lease-length",
            "kind": "choice",
            "prompt": "Leases are 10 s and renewed every 3 s. The leader pauses for 15 s. What happens, and what does a longer lease trade?",
            "options": [
                "The lease expires and another node takes over; a longer lease avoids spurious expiry but slows failover",
                "Nothing; renewal keeps running during a pause",
                "The cluster halts until the paused leader returns",
                "A longer lease would make failover faster",
            ],
            "answer": 0,
            "explanation": "Short leases mean fast failover and more risk of spurious expiry under pauses; long leases mean the opposite. Typical values are 10 to 30 s with renewal at a third of that.",
            "section": "design-decisions",
            "concept": "sd-coordination.lease-length",
        },
        {
            "key": "zk-per-request",
            "kind": "choice",
            "prompt": "A team stores per-request session data in ZooKeeper and reads it on every API call. What does the lesson predict?",
            "options": [
                "Coordination service overload, a well-known way to take down a cluster",
                "It works fine, because ZooKeeper is strongly consistent",
                "Sessions become eventually consistent",
                "Split brain in the application tier",
            ],
            "answer": 0,
            "explanation": "A coordination service holds small, critical metadata: leader identity, membership, configuration, shard assignment. Putting high-volume data or per-request calls into it is a classic outage.",
            "section": "common-failure-modes",
            "concept": "sd-coordination.what-belongs",
            "mistake": "sd-coordination.per-request-dependency",
        },
        {
            "key": "set-nx-guarantee",
            "kind": "spot_mistake",
            "prompt": "Design: 'A scheduled job must run once across 20 workers. We use SET NX with a 30-second TTL in Redis. Since Redis is the single source of truth for the lock, mutual exclusion is guaranteed.' What is wrong?",
            "options": [
                "A pause longer than the TTL lets two holders in; without fencing tokens the lock is not a correctness guarantee",
                "Redis cannot attach a TTL to a key",
                "The TTL should be 30 minutes to be safe",
                "SET NX is fine, but the job also needs a Postgres lock",
            ],
            "answer": 0,
            "explanation": "The naive lock fails exactly when a GC or hypervisor pause exceeds the TTL, producing rare duplicates that get dismissed as a mystery. Either the resource checks a fencing token, or the job is idempotent.",
            "section": "common-mistakes",
            "concept": "sd-coordination.fencing-tokens",
            "mistake": "sd-coordination.ttl-lock-is-safe",
        },
        {
            "key": "coordinator-down",
            "kind": "short_answer",
            "prompt": "The coordination service is unavailable for two minutes. What two choices does a system have for its exclusive work, and which would you pick for a nightly report job?",
            "options": [],
            "answer": None,
            "model_answer": "Either stop the exclusive work (safe but unavailable) or continue on the last lease or last-known configuration (available but risks split brain). For a nightly report, stop: a delayed report is fine and duplicate work is worse. The rest of the system should keep serving on last-known configuration rather than halting, because a CP coordination service being down must degrade the system, not stop it.",
            "explanation": "Consensus is CP: correctness over availability. Decide the degradation explicitly for each piece of exclusive work rather than discovering it during an incident.",
            "section": "trade-offs",
            "concept": "sd-coordination.degrade-without-coordinator",
        },
    ],
    "scalability": [
        {
            "key": "skipped-step",
            "kind": "choice",
            "prompt": "Reads dominate and the database sits at 90% CPU on repeated simple queries. The candidate proposes sharding. Which step was skipped, and why does that matter?",
            "options": [
                "Caching: it can remove about 95% of reads for a fraction of the effort, and sharding is hard to reverse",
                "Multi-region: it should always come before sharding",
                "Nothing: write capacity is the real limit here",
                "Vertical scaling only: after that, sharding is correct",
            ],
            "answer": 0,
            "explanation": "The order exists because each step is cheaper than the next. Never skip a step without saying why. Going straight to sharding when a cache would remove most of the load is the most common over-engineering error.",
            "section": "mental-model",
            "concept": "scalability.ordered-steps",
            "mistake": "scalability.premature-sharding",
        },
        {
            "key": "idle-but-slow",
            "kind": "choice",
            "prompt": "Every resource sits at 20% utilisation, yet p99 latency is high and rising. What is the likely cause, and does adding capacity help?",
            "options": [
                "A serialisation point (lock, single coordinator, sync dependency); adding capacity does nothing",
                "App CPU is the limit; add nodes",
                "The cache is undersized; add memory",
                "Network egress is saturated; add a CDN",
            ],
            "answer": 0,
            "explanation": "If nothing is busy and everything is slow, you are waiting on something. The first question when scaling stops working is: what is still serialised?",
            "section": "how-it-works",
            "concept": "scalability.serialisation-point",
            "mistake": "scalability.capacity-for-waiting",
        },
        {
            "key": "exact-count",
            "kind": "choice",
            "prompt": "A product page shows an exact view count computed by COUNT(*) on every request, now the slowest query in the system. Which pattern from the lesson fits best?",
            "options": [
                "Precompute or approximate: a denormalised counter updated on write, or an approximate '2.4M views'",
                "Shard the events table by view id",
                "Serve the count from a second region",
                "Add app nodes so the count runs in parallel",
            ],
            "answer": 0,
            "explanation": "Turning a read-time computation into a write-time one, or accepting an approximate figure when exactness is not a product requirement, often beats scaling the thing that computes.",
            "section": "how-it-works",
            "concept": "scalability.precompute-approximate",
        },
        {
            "key": "headroom",
            "kind": "choice",
            "prompt": "How much headroom does the lesson say to design for?",
            "options": [
                "Structure for about 10x current traffic, provision capacity for about 2x peak",
                "Structure for 1,000x, provision for 10x",
                "Provision exactly for current peak and rely on autoscaling",
                "Structure for 2x, provision for 10x",
            ],
            "answer": 0,
            "explanation": "Designing for 1,000x means building something you cannot ship, and interviewers penalise it. Structure for roughly 10x, pay for roughly 2x peak.",
            "section": "design-decisions",
            "concept": "scalability.headroom",
            "mistake": "scalability.overbuilt",
        },
        {
            "key": "sudden-spike",
            "kind": "choice",
            "prompt": "A 100x traffic spike arrives within one minute, with no warning. What is the lesson's answer?",
            "options": [
                "No autoscaler is that fast: queue, shed and degrade, and say which requests you drop first",
                "Autoscaling handles it if the trigger threshold is low enough",
                "Pre-scale, since spikes can always be predicted",
                "Add a read replica while the spike lasts",
            ],
            "answer": 0,
            "explanation": "Autoscaling lags by minutes. For scheduled events, pre-scale. For sudden ones you need queues and load shedding, because capacity you do not have is capacity you must decline to use.",
            "section": "design-decisions",
            "concept": "scalability.spikes",
            "mistake": "scalability.autoscaler-handles-spikes",
        },
        {
            "key": "wrong-layer",
            "kind": "choice",
            "prompt": "Latency is high, so you add app nodes. The database was actually the limit. What happens?",
            "options": [
                "More app nodes exhaust database connections faster, and things get worse",
                "Latency improves because requests spread across more nodes",
                "The database gets less load thanks to connection pooling",
                "Nothing changes; the new nodes sit idle",
            ],
            "answer": 0,
            "explanation": "Scaling the wrong layer because nobody measured is a classic failure. Scaling the app tier into the database just piles more connections onto the real bottleneck.",
            "section": "common-failure-modes",
            "concept": "scalability.measure-first",
            "mistake": "scalability.scale-wrong-layer",
        },
        {
            "key": "everything-at-once",
            "kind": "spot_mistake",
            "prompt": "Plan for 10x: 'We will add a cache, three read replicas, shard by user_id, and go active-active in two regions, all in the same quarter, so we are ready.' What is wrong?",
            "options": [
                "Everything at once with nothing measured; each step should follow a measured bottleneck, expensive moves last",
                "The cache should come after sharding",
                "Read replicas are unnecessary once you shard",
                "The regions should be active-passive, otherwise the plan is fine",
            ],
            "answer": 0,
            "explanation": "Applying every technique at once is guessing, and every added component adds failure modes. Sharding and multi-region are the hard-to-reverse moves and are delayed until a number forces them.",
            "section": "common-mistakes",
            "concept": "scalability.ordered-steps",
            "mistake": "scalability.everything-at-once",
        },
        {
            "key": "what-each-step-costs",
            "kind": "short_answer",
            "prompt": "For caching, sharding and going asynchronous, name what each one takes away from you.",
            "options": [],
            "answer": None,
            "model_answer": "Caching (like replication) adds staleness: reads can be behind the write. Sharding removes cross-shard transactions and joins, and is hard to reverse. Going async removes immediate confirmation: the caller gets a job id, not a result. Every step also adds components to run, monitor and fail.",
            "explanation": "Nothing is free. Naming the cost of each move as you propose it is what separates a scaling plan from a list of buzzwords.",
            "section": "trade-offs",
            "concept": "scalability.step-costs",
        },
    ],
    "sd-probabilistic-structures": [
        {
            "key": "probably-yes",
            "kind": "choice",
            "prompt": "A Bloom filter says an item is present. What exactly do you know, and what must you do next?",
            "options": [
                "It is probably present; you must still check the real store",
                "It is definitely present; no further check is needed",
                "It is definitely absent; other items set those bits",
                "Nothing; a Bloom filter only gives reliable negative answers",
            ],
            "answer": 0,
            "explanation": "All k bits being 1 means probably yes, because other items may have set those bits. Any bit being 0 means definitely no. The yes answer is only a hint to go and look.",
            "section": "mental-model",
            "concept": "sd-probabilistic-structures.bloom-direction",
            "mistake": "sd-probabilistic-structures.bloom-yes-is-certain",
        },
        {
            "key": "bloom-sizing",
            "kind": "choice",
            "prompt": "Size a Bloom filter for 50 million items at about 1% false positives. How much memory, and what happens if the item count doubles without resizing?",
            "options": [
                "About 500 million bits, roughly 60 MB; at 100 million items the false-positive rate gets much worse",
                "About 50 MB; the rate stays at 1% because it is fixed at creation",
                "About 12 KB; the size does not depend on item count",
                "About 6 GB; doubling the items halves the rate",
            ],
            "answer": 0,
            "explanation": "Rule of thumb: about 10 bits per item and 7 hashes gives about 1%. Bits per item is the knob, so a filter sized for today gets much worse as items grow, and resizing means rebuilding from source data.",
            "section": "how-it-works",
            "concept": "sd-probabilistic-structures.bloom-sizing",
            "mistake": "sd-probabilistic-structures.no-growth-room",
        },
        {
            "key": "no-deletes",
            "kind": "choice",
            "prompt": "Why can you not delete from a plain Bloom filter, and what do you use when deletes are needed?",
            "options": [
                "Clearing a bit may clear one another item needs, causing a false negative; use a counting Bloom filter",
                "Deletes work but are slow; use a hash set instead",
                "The item is never stored, so nothing can be removed; use HyperLogLog",
                "A delete resets all k hash functions; use a Count-Min Sketch",
            ],
            "answer": 0,
            "explanation": "The one guarantee is no false negatives, and a cleared bit breaks it. A counting Bloom filter keeps a small counter per slot, at about four times the memory.",
            "section": "how-it-works",
            "concept": "sd-probabilistic-structures.bloom-deletes",
            "mistake": "sd-probabilistic-structures.delete-from-bloom",
        },
        {
            "key": "hll-intuition",
            "kind": "choice",
            "prompt": "In HyperLogLog, the longest run of leading zeros seen in a bucket is 10. Roughly what does that suggest, and how do you merge two HyperLogLogs?",
            "options": [
                "About 1,000 distinct items; merge by taking the larger value per bucket",
                "About 10 distinct items; merge by adding the buckets",
                "About 1 MB of data; merge by re-hashing everything",
                "About 10,000 items; merging needs the raw data",
            ],
            "answer": 0,
            "explanation": "About one hash in a thousand starts with ten zeros, so seeing ten suggests about a thousand distinct items. Many buckets are averaged to reduce noise, and merging is a max per bucket, which is why one per server per hour can be merged into a daily fleet total.",
            "section": "how-it-works",
            "concept": "sd-probabilistic-structures.hyperloglog",
        },
        {
            "key": "cms-minimum",
            "kind": "choice",
            "prompt": "In a Count-Min Sketch, why is the count read as the minimum across rows, and in which direction is it wrong?",
            "options": [
                "Collisions only add, so the least-inflated row is closest to truth; it over-counts and never under-counts",
                "The minimum cancels collisions exactly, so heavy hitters are exact",
                "The minimum is a tie-breaker, and it under-counts rare items",
                "The minimum saves memory; it is wrong in both directions by about 1%",
            ],
            "answer": 0,
            "explanation": "Nothing ever subtracts, so every row is too high or exact. A rare item can look popular, a popular item can never look rare. That is the right direction for top-k, where candidates can be verified with exact counts.",
            "section": "how-it-works",
            "concept": "sd-probabilistic-structures.count-min-sketch",
        },
        {
            "key": "billing-from-sketch",
            "kind": "choice",
            "prompt": "The product team wants to bill link owners per click using the Count-Min Sketch behind the trending list. What do you say, and what do you build instead?",
            "options": [
                "No: an over-count charges for clicks that never happened; write every click to an append-only log and count exactly",
                "Yes, once the sketch error is tuned down to 0.1%",
                "Yes, but use HyperLogLog since it is only 1% off",
                "No; use a Bloom filter to dedupe the clicks first",
            ],
            "answer": 0,
            "explanation": "Money needs the exact answer. The sketch drives the chart; anything billed comes from the exact event log. Saying this before the interviewer asks is even better.",
            "section": "when-you-need-the-exact-answer",
            "concept": "sd-probabilistic-structures.exact-for-money",
            "mistake": "sd-probabilistic-structures.sketch-for-billing",
        },
        {
            "key": "bloom-idempotency",
            "kind": "spot_mistake",
            "prompt": "Design: 'To make payment processing idempotent, we keep a Bloom filter of processed payment ids. If the filter says the id is present, we skip the payment.' What is wrong?",
            "options": [
                "A false positive silently drops a real payment; a correctness gate needs an exact store",
                "Bloom filters cannot hold string ids",
                "The filter should be a Count-Min Sketch instead",
                "Nothing; false positives are only about 1%",
            ],
            "answer": 0,
            "explanation": "Ask what happens when the structure is wrong. Here the wrong direction is a lost payment, not a wasted lookup, so the approximate structure does not fit.",
            "section": "common-mistakes",
            "concept": "sd-probabilistic-structures.error-direction",
            "mistake": "sd-probabilistic-structures.bloom-as-correctness-gate",
        },
        {
            "key": "cheap-wrong-direction",
            "kind": "choice",
            "prompt": "The lesson's rule: make sure the structure's wrong direction is the cheap one. Which use is a good fit for a Bloom filter?",
            "options": [
                "A crawler's 'have we seen this URL' check, where a false positive skips one page",
                "Checking whether a refund was already issued",
                "Computing an account balance",
                "Deciding whether a user has paid for premium",
            ],
            "answer": 0,
            "explanation": "Skipping one page by mistake is a tolerable loss. The other three are money or correctness gates, where a wrong answer costs a customer or a payment.",
            "section": "trade-offs",
            "concept": "sd-probabilistic-structures.error-direction",
        },
    ],
    "sd-video-streaming": [
        {
            "key": "egress-arithmetic",
            "kind": "choice",
            "prompt": "5 billion views per day, average watch 6 minutes at 2 Mbps, about 90 MB per view. What is the egress, and what does that number decide?",
            "options": [
                "About 450 PB per day, roughly 40 Tbps; the CDN is the architecture, not an optimisation",
                "About 450 TB per day; a few origin servers can serve it",
                "About 4.5 PB per day; read replicas absorb it",
                "About 45 PB per day; the database is the bottleneck",
            ],
            "answer": 0,
            "explanation": "5B x 90 MB is about 450 PB a day. Nobody serves 40 Tbps from an origin. The number is the argument for CDN-and-segments, so say it early.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-video-streaming.egress",
            "mistake": "sd-video-streaming.ignore-egress",
        },
        {
            "key": "bytes-and-events",
            "kind": "choice",
            "prompt": "In the data model, where do the video bytes and the per-view events live?",
            "options": [
                "Bytes only in object storage; watch events in an append-only log; the database never holds a video byte",
                "Bytes as blobs in the videos table; watch events as rows updated per view",
                "Bytes on the app servers' local disks; events in Redis",
                "Bytes only in the CDN; events in the renditions table",
            ],
            "answer": 0,
            "explanation": "Object storage holds originals, segments, manifests and thumbnails. watch_events is a stream, not a table, and view_counts is updated in aggregate, never per view.",
            "section": "step-4-data-model",
            "concept": "sd-video-streaming.data-model",
        },
        {
            "key": "bytes-off-app-tier",
            "kind": "choice",
            "prompt": "What is the critical property of the first architecture regarding video bytes on upload and playback?",
            "options": [
                "They never pass through the app tier: pre-signed multipart to object storage; CDN serves segments",
                "They stream through the API so it can validate them",
                "Upload goes through the API; playback bypasses it",
                "Playback goes through the API; upload bypasses it",
            ],
            "answer": 0,
            "explanation": "Two flows: client to object storage via pre-signed part URLs, then queue and transcoders; client to CDN for manifest and segments. Your API serves JSON and URLs only.",
            "section": "step-5-first-architecture",
            "concept": "sd-video-streaming.bytes-off-app-tier",
            "mistake": "sd-video-streaming.bytes-through-api",
        },
        {
            "key": "no-streaming-server",
            "kind": "choice",
            "prompt": "During adaptive-bitrate playback, what does the server do for each viewer?",
            "options": [
                "Nothing per viewer; the player picks a bitrate per segment and fetches immutable segments from the CDN",
                "Transcodes to the viewer's bandwidth in real time",
                "Pushes segments over a persistent socket at the chosen bitrate",
                "Chooses the bitrate per viewer and proxies segments from origin",
            ],
            "answer": 0,
            "explanation": "The manifest lists renditions; the player measures throughput and switches at segment boundaries. Segments are ordinary HTTP objects, so there is no streaming server. This is the insight candidates most often miss.",
            "section": "how-it-works",
            "concept": "sd-video-streaming.adaptive-bitrate",
            "mistake": "sd-video-streaming.streaming-server",
        },
        {
            "key": "viral-video",
            "kind": "choice",
            "prompt": "A video goes viral: 2 million concurrent viewers. What actually needs attention?",
            "options": [
                "Not the segments; the metadata, view-count and comment paths, which are per-viewer",
                "The origin, which must now serve 2 million streams",
                "The transcoding queue, which must re-encode for the load",
                "Object storage, which serves each viewer directly",
            ],
            "answer": 0,
            "explanation": "Every viewer requests the same immutable segments, so one request per segment reaches the origin globally. Origin load for a viral video is about the same as for an unpopular one. The per-viewer paths need caching and the counter treatment.",
            "section": "evolution-under-pressure",
            "concept": "sd-video-streaming.cdn-segments",
        },
        {
            "key": "serial-transcode",
            "kind": "spot_mistake",
            "prompt": "Design: 'A worker transcodes each uploaded file as one job. If the job fails, the whole video is re-queued from the start. Every video keeps all five renditions forever.' What is wrong?",
            "options": [
                "Whole-file jobs cannot use spot capacity, one bad chunk fails the video, and no lifecycle policy means unbounded storage",
                "Nothing; whole-file jobs are simpler and full retries are safe",
                "Only the retry is wrong; keeping all renditions is required for playback",
                "Videos should be transcoded on the client before upload",
            ],
            "answer": 0,
            "explanation": "Split by chunk and rendition into hundreds of small idempotent jobs keyed by (video_id, chunk_index, rendition), retried individually. Tier storage by popularity, since most uploads are almost never watched.",
            "section": "failure-modes",
            "concept": "sd-video-streaming.chunked-transcoding",
            "mistake": "sd-video-streaming.serial-transcode",
        },
        {
            "key": "view-counter",
            "kind": "choice",
            "prompt": "150,000 view events per second. A candidate writes UPDATE videos SET views = views + 1 per view. What is wrong, and what is the pipeline instead?",
            "options": [
                "A hot row per popular video; batch events to a log, aggregate in windows, flush to a cached counter",
                "Nothing at this scale, as long as video_id is indexed",
                "Use a NoSQL store so each per-view update is faster",
                "Count views only from CDN access logs",
            ],
            "answer": 0,
            "explanation": "One write per view is impossible and a popular video becomes a single hot row. Stream, window, flush to Redis, and show a count seconds stale. Keep a separate slow, fraud-filtered pipeline for the authoritative count that money depends on.",
            "section": "common-mistakes",
            "concept": "sd-video-streaming.view-counting",
            "mistake": "sd-video-streaming.write-per-view",
        },
        {
            "key": "on-demand-transcode",
            "kind": "choice",
            "prompt": "For long-tail videos that may never be watched, the lesson offers transcoding on demand. What do you gain and what do you pay?",
            "options": [
                "Large compute and storage savings on the long tail; the first viewer waits for a slow first play",
                "Faster first play; more storage",
                "Better adaptation on poor networks; more renditions",
                "No trade-off; on-demand is strictly better",
            ],
            "answer": 0,
            "explanation": "Transcode on upload gives predictable playback. On demand saves a lot for the many uploads with almost no views, at the cost of a slow first view.",
            "section": "trade-offs",
            "concept": "sd-video-streaming.transcode-timing",
        },
    ],
    "sd-web-crawler": [
        {
            "key": "politeness-limit",
            "kind": "choice",
            "prompt": "Target: 1 billion pages a month, about 400 pages per second at 100 KB each, so 40 MB/s. Politeness allows one request per second per host. What is the real limit?",
            "options": [
                "Politeness: you need at least 400 distinct hosts in flight at all times, realistically thousands",
                "Bandwidth: 40 MB/s needs a dedicated network",
                "Storage: 100 TB of raw HTML a month cannot be stored",
                "Parsing: 400 pages per second is too many to parse",
            ],
            "answer": 0,
            "explanation": "Raw bandwidth is easy. The limiting factor is a policy, not a resource: total throughput comes from breadth across hosts, and hosts are not uniformly available.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-web-crawler.politeness-bound",
        },
        {
            "key": "queues-per-host",
            "kind": "choice",
            "prompt": "Why does the lesson shape the frontier as one queue per host, each with a next_allowed_fetch_time, instead of one global queue?",
            "options": [
                "Politeness becomes a property of the data structure, not a rule workers must remember to follow",
                "Per-host queues use less memory than one global queue",
                "It lets each worker be assigned a fixed host forever",
                "A global queue cannot be partitioned later",
            ],
            "answer": 0,
            "explanation": "This is the single most important structural decision. With a global queue plus a rate-limit check, a popular host's URLs cluster and many workers contend on it at once.",
            "section": "step-4-data-model",
            "concept": "sd-web-crawler.structural-politeness",
            "mistake": "sd-web-crawler.global-queue",
        },
        {
            "key": "stateful-component",
            "kind": "choice",
            "prompt": "In the architecture, which component is stateless and simply scaled out, and which is the stateful one to deep-dive?",
            "options": [
                "Fetchers are stateless; the frontier is the stateful, interesting component",
                "The frontier is stateless; the parser holds the crawl state",
                "Fetchers hold the crawl state; storage is stateless",
                "All components are stateless because the database holds everything",
            ],
            "answer": 0,
            "explanation": "The fetcher pool is a stateless worker tier. The frontier holds priority and per-host timing, and its design decides both politeness and the shard key.",
            "section": "step-5-architecture",
            "concept": "sd-web-crawler.frontier-is-stateful",
        },
        {
            "key": "back-queue-guarantee",
            "kind": "choice",
            "prompt": "Mercator frontier: a worker takes a back queue whose next-allowed time has passed, fetches one URL, and sets a new time. Why can 1,000 workers never exceed a host's rate limit?",
            "options": [
                "A host maps to exactly one back queue, and a back queue is served by one worker at a time",
                "Workers share a global rate-limit counter in Redis",
                "Each worker sleeps for crawl_delay between any two fetches",
                "Front queues cap how many URLs per host enter the system",
            ],
            "answer": 0,
            "explanation": "Front queues handle priority; back queues handle politeness, one per host. Because of that mapping it is structurally impossible to exceed the rate for a host, no matter how many workers exist.",
            "section": "how-it-works",
            "concept": "sd-web-crawler.structural-politeness",
        },
        {
            "key": "bloom-direction",
            "kind": "choice",
            "prompt": "A Bloom filter answers 'have we seen this URL'. A false positive occurs. What happens, and why is that acceptable for a crawler?",
            "options": [
                "A new URL is occasionally skipped; the filter never causes a re-fetch, and a skipped page is a tolerable loss",
                "The page is fetched twice; harmless because fetching is idempotent",
                "The URL falls through to the exact store; slower but correct",
                "The filter is rebuilt from the database; costly but rare",
            ],
            "answer": 0,
            "explanation": "A Bloom filter never gives a false negative, so it never causes duplicate fetches. Its only error is skipping something, and for 10 billion URLs at about 12 GB that asymmetry is the whole reason it fits.",
            "section": "trade-offs",
            "concept": "sd-web-crawler.bloom-dedup",
            "mistake": "sd-web-crawler.bloom-wrong-direction",
        },
        {
            "key": "frontier-shard-key",
            "kind": "choice",
            "prompt": "Scaling to 4,000 pages per second, you must partition the frontier. What is the shard key, and why?",
            "options": [
                "Hash of host, so all URLs for a host live on one shard and the politeness guarantee survives",
                "Hash of the full URL, for the most even spread",
                "Priority level, so high-priority URLs get their own shard",
                "Round-robin, so every shard gets equal load",
            ],
            "answer": 0,
            "explanation": "The politeness constraint decides the shard key. Each frontier shard then owns its own partition of the Bloom filter as well.",
            "section": "evolution-under-pressure",
            "concept": "sd-web-crawler.shard-by-host",
        },
        {
            "key": "naive-crawler",
            "kind": "spot_mistake",
            "prompt": "Design: 'One global FIFO queue. Each fetcher pops a URL, checks a per-host rate limit in Redis, and retries later if limited. Seen-URL dedup is a hash set in each fetcher's memory.' What is wrong?",
            "options": [
                "Popular hosts cluster in the queue so workers contend on one host; per-process dedup is lost on restart and not shared",
                "Redis is too slow to check a rate limit per fetch",
                "The queue should be LIFO so new pages are fetched first",
                "Nothing, as long as the rate limit is honoured",
            ],
            "answer": 0,
            "explanation": "Both are named failure modes: a single global frontier violates politeness in practice, and in-memory dedup on one node is neither durable nor shared across workers.",
            "section": "failure-modes",
            "concept": "sd-web-crawler.structural-politeness",
            "mistake": "sd-web-crawler.global-queue",
        },
        {
            "key": "recrawl-schedule",
            "kind": "choice",
            "prompt": "A crawler recrawls every page weekly. A news homepage changes hourly; an archive page has been unchanged for five crawls. What does the lesson suggest?",
            "options": [
                "Estimate change frequency per URL: back off on unchanged pages, crawl changing ones more, weighted by importance",
                "Recrawl everything daily so the news stays fresh",
                "Recrawl only pages with high link-graph importance",
                "Never recrawl; spend the budget on new URLs only",
            ],
            "answer": 0,
            "explanation": "Uniform intervals waste most of the budget on unchanged pages. Back off exponentially when the content hash stays the same, crawl more often when it changes, and combine with importance.",
            "section": "common-mistakes",
            "concept": "sd-web-crawler.recrawl-estimation",
            "mistake": "sd-web-crawler.uniform-recrawl",
        },
    ],
    "sd-collaborative-editor": [
        {
            "key": "scale-shape",
            "kind": "choice",
            "prompt": "500,000 documents open at peak with about two editors each, and 1 million operations per second across the service. What does that shape imply for the design?",
            "options": [
                "Many small problems: one server per document is plenty, log growth forces snapshots, about 1M sockets need a layer",
                "One big problem: a single ordering server for every document",
                "Per-document load is heavy, so each document needs consensus across servers",
                "Sockets are negligible; only the database write rate matters",
            ],
            "answer": 0,
            "explanation": "Per document the load is a few dozen operations per second. Across the service it spreads over many servers. The log grows forever, so a new joiner must not replay a year of edits, and a million WebSockets is its own layer.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-collaborative-editor.many-small-problems",
        },
        {
            "key": "load-version",
            "kind": "choice",
            "prompt": "How do you load version N of a document from the data model?",
            "options": [
                "Take the newest snapshot at or below N and apply the operations up to N",
                "Replay every operation from version 1",
                "Read the documents row, which holds the current text",
                "Read presence, which holds each editor's latest copy",
            ],
            "answer": 0,
            "explanation": "A document is a snapshot plus the ordered log of operations after it. The log is the truth; the snapshot is a shortcut. History and undo come from the same log.",
            "section": "step-4-data-model",
            "concept": "sd-collaborative-editor.snapshot-plus-log",
        },
        {
            "key": "sticky-by-doc",
            "kind": "choice",
            "prompt": "The gateway routes each session to a doc server. Sticky by what, and why?",
            "options": [
                "By doc id, so one server assigns every version for a document and distributed ordering problems disappear",
                "By user id, so one user's edits across documents stay ordered",
                "Randomly, so load spreads evenly",
                "By region, so latency is lowest",
            ],
            "answer": 0,
            "explanation": "Every session for one document goes to the same server, which holds the text in memory and is the only thing that assigns versions. Sessions on random servers mean nobody can assign a single order.",
            "section": "step-5-first-architecture",
            "concept": "sd-collaborative-editor.one-ordering-server",
            "mistake": "sd-collaborative-editor.random-servers",
        },
        {
            "key": "ot-example",
            "kind": "choice",
            "prompt": "Text is 'cat' at version 5. Alice inserts 's' at 3; Bob inserts 'a ' at 0. The server takes Alice's op first (v6), then Bob's (v7). What does Bob's client do with Alice's op?",
            "options": [
                "Shift it from position 3 to 5, because his own insert added two characters before it; result 'a cats'",
                "Apply it at position 3 as sent; result 'a csat'",
                "Reject it because it is based on an older version",
                "Replace his text with a fresh copy from the server",
            ],
            "answer": 0,
            "explanation": "Operational Transformation shifts an insert right by the length of any concurrent insert that landed before its position. Both screens end at 'a cats'.",
            "section": "how-it-works",
            "concept": "sd-collaborative-editor.operational-transformation",
            "mistake": "sd-collaborative-editor.apply-without-transform",
        },
        {
            "key": "crdt-vs-ot",
            "kind": "choice",
            "prompt": "When would you choose a CRDT over Operational Transformation, and what does it cost?",
            "options": [
                "When peers sync directly or offline periods are long; the cost is per-character ids and tombstones",
                "When you want the smallest possible document in memory",
                "When one server already orders every operation",
                "When all editors are in one region",
            ],
            "answer": 0,
            "explanation": "A CRDT gives every character a permanent id, so operations mean the same thing in any order with no central server. The document can be many times bigger than the text. With a server anyway, OT keeps it compact.",
            "section": "trade-offs",
            "concept": "sd-collaborative-editor.ot-vs-crdt",
        },
        {
            "key": "server-crash",
            "kind": "choice",
            "prompt": "The doc server crashes while five people are typing. What is lost, and how does the system recover?",
            "options": [
                "Nothing acked is lost; a new owner rebuilds from snapshot plus log; clients resend unacked ops, op_id stops duplicates",
                "The operations since the last snapshot are lost",
                "Everything since the document was opened is lost",
                "Nothing is lost only if the server mirrored its memory to a standby",
            ],
            "answer": 0,
            "explanation": "Every acknowledged operation is already in the log. The gateway picks a new owner, which rebuilds the text in well under a second. The server is a cache of the log, so it can die.",
            "section": "evolution-under-pressure",
            "concept": "sd-collaborative-editor.server-is-a-cache",
        },
        {
            "key": "ack-and-presence",
            "kind": "spot_mistake",
            "prompt": "Design: 'The doc server acknowledges each operation immediately and appends it to the log in the background. Cursor positions are saved to the operations table.' What is wrong?",
            "options": [
                "Acking before the append can lose an edit the user saw as saved; stored cursors become most of the write load",
                "Cursors belong in the snapshots table instead",
                "Acking early is fine, because the client keeps a copy",
                "Nothing; background writes are standard practice",
            ],
            "answer": 0,
            "explanation": "The server must append to the log and only then acknowledge. Presence goes through a per-document pub/sub channel and is never written to disk.",
            "section": "failure-modes",
            "concept": "sd-collaborative-editor.ack-after-append",
            "mistake": "sd-collaborative-editor.presence-in-db",
        },
        {
            "key": "undo",
            "kind": "choice",
            "prompt": "A user hits undo after other people have typed. Why can the server not simply pop the last operation, and what happens instead?",
            "options": [
                "The last op may be someone else's; undo is a new op, the inverse transformed against everything since",
                "The log is immutable, so undo is not supported",
                "Popping works as long as the user's op was the most recent",
                "The snapshot must be rewritten before anything can be undone",
            ],
            "answer": 0,
            "explanation": "Each client keeps an undo stack of its own operations. To undo, it builds the inverse, transforms it against later edits, and sends it as a new operation. The log only grows.",
            "section": "common-mistakes",
            "concept": "sd-collaborative-editor.undo-is-an-op",
            "mistake": "sd-collaborative-editor.undo-as-rewind",
        },
    ],
}
