"""Knowledge checks: capacity estimation, proxies and gateways, SQL vs NoSQL, consistency, disaster recovery, URL shortener, chat system, payment system, message queue."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "capacity-estimation": [
        {
            "key": "number-worth-computing",
            "kind": "choice",
            "prompt": "You are sizing a text-only JSON API. You already have peak QPS, storage per year and the read:write ratio. Should you also compute bandwidth?",
            "options": [
                "No: for a text-only API it does not change any decision, so skip it",
                "Yes: the four numbers are always required",
                "Yes: bandwidth decides whether to shard",
                "No: bandwidth only matters for write-heavy systems",
            ],
            "answer": 0,
            "explanation": "A number is only worth computing if it maps to a decision. Bandwidth decides CDN, object storage and egress, none of which a text-only API needs; the lesson lists it as a wasted two minutes.",
            "section": "mental-model",
            "concept": "capacity-estimation.numbers-map-to-decisions",
            "mistake": "capacity-estimation.number-nobody-needed",
        },
        {
            "key": "peak-qps-arithmetic",
            "kind": "choice",
            "prompt": "A normal consumer product has 50M daily active users, each making 20 requests a day. Using the lesson's anchors, roughly what is the peak QPS?",
            "options": ["About 30,000", "About 10,000", "About 100,000", "About 3,000"],
            "answer": 0,
            "explanation": "50M x 20 = 1B requests a day. Divide by 100,000 seconds for about 10,000 average QPS, then multiply by 3 for a normal diurnal peak: about 30,000.",
            "section": "how-it-works",
            "concept": "capacity-estimation.qps-sequence",
            "mistake": "capacity-estimation.quoting-average-as-peak",
        },
        {
            "key": "one-machine-comparison",
            "kind": "choice",
            "prompt": "Your estimate says 400,000 peak QPS of simple indexed reads. Using the per-node ranges in the lesson, what does that tell you?",
            "options": [
                "Roughly fifty databases' worth of work, so partitioning, caching, or both",
                "One well-tuned relational node handles it",
                "About five databases with read replicas",
                "Nothing until you know the payload size",
            ],
            "answer": 0,
            "explanation": "One relational node serves 5,000 to 20,000 simple reads a second. 400,000 is about fifty of them, which forces caching or partitioning. The estimate is only useful because you know what one machine does.",
            "section": "how-it-works",
            "concept": "capacity-estimation.machine-capacity",
            "mistake": "capacity-estimation.no-per-node-anchor",
        },
        {
            "key": "spike-multiplier",
            "kind": "choice",
            "prompt": "You estimate 600 average QPS for a ticketing site with scheduled on-sales. What peak multiplier does the lesson suggest, and what does it change?",
            "options": [
                "10 to 100x, and the design shifts from provision-for-peak to queue and shed",
                "3x, so provision for about 1,800 QPS",
                "2x, and autoscaling covers the rest",
                "None: on-sales are rare enough to ignore",
            ],
            "answer": 0,
            "explanation": "Normal consumer products peak at 2 to 3x average. Anything with a scheduled event peaks at 10 to 100x, and a spike shape means you queue and shed rather than provision for the peak.",
            "section": "design-decisions",
            "concept": "capacity-estimation.peak-multiplier",
            "mistake": "capacity-estimation.average-for-spiky-product",
        },
        {
            "key": "storage-multipliers",
            "kind": "choice",
            "prompt": "You compute 1 TB of raw row data per year. With the lesson's replication factor and index overhead, roughly how much disk should you plan for?",
            "options": ["About 4 to 6 TB", "About 1 TB", "About 2 TB", "About 30 TB"],
            "answer": 0,
            "explanation": "Replication is x3, so 3 TB, and indexes add 30 to 100% on top. Forgetting both understates by 3 to 5x, which is the difference between one node and a cluster.",
            "section": "trade-offs",
            "concept": "capacity-estimation.storage-overheads",
            "mistake": "capacity-estimation.forgot-replication-and-indexes",
        },
        {
            "key": "silent-precise-answer",
            "kind": "spot_mistake",
            "prompt": "A candidate thinks silently for a minute, then says: 'About 43,891 QPS, so we need six app servers.' What is wrong?",
            "options": [
                "Nobody heard the reasoning and the precision is fake; narrate and round to an order of magnitude",
                "Six app servers is too few for that QPS",
                "They quoted peak when they should have quoted average",
                "Nothing; precise numbers show rigour",
            ],
            "answer": 0,
            "explanation": "Silent maths cannot be scored, and five significant figures from rounded assumptions is false precision. Being within 3x, said out loud with the assumption named, is a complete success.",
            "section": "common-failure-modes",
            "concept": "capacity-estimation.narrate-and-round",
            "mistake": "capacity-estimation.silent-calculation",
        },
        {
            "key": "state-the-decision",
            "kind": "short_answer",
            "prompt": "Your estimate comes out at about 6,000 peak read QPS for a feed. Say what this tells you about the architecture, the way the lesson wants it said.",
            "options": [],
            "answer": None,
            "model_answer": "6,000 peak QPS is more than one relational database should serve on its own, and feed reads repeat, so I will cache the read path (Redis plus replicas). The sentence should contain the number and the decision it forces, not just the arithmetic.",
            "explanation": "The most common mistake is doing arithmetic instead of drawing a conclusion from it. Every number must be followed by the decision it forces.",
            "section": "common-mistakes",
            "concept": "capacity-estimation.numbers-map-to-decisions",
            "mistake": "capacity-estimation.arithmetic-without-conclusion",
        },
    ],
    "sd-proxies-and-gateways": [
        {
            "key": "which-layer",
            "kind": "choice",
            "prompt": "Service A calls service B inside the cluster. You want mTLS, retries and timeouts on that hop without changing either service's code. Which layer does that?",
            "options": [
                "A service mesh, because this is east-west traffic",
                "The API gateway, because it owns cross-cutting concerns",
                "A reverse proxy in front of service B",
                "A forward proxy in front of service A",
            ],
            "answer": 0,
            "explanation": "Gateways and reverse proxies handle north-south traffic from clients. Service-to-service (east-west) policy such as mTLS, retries and circuit breaking is the job of a mesh sidecar.",
            "section": "mental-model",
            "concept": "proxies-and-gateways.three-layers",
            "mistake": "proxies-and-gateways.gateway-confused-with-mesh",
        },
        {
            "key": "authz-split",
            "kind": "choice",
            "prompt": "Two checks: (a) is this API key allowed to call /v2/orders at all, and (b) may this user edit this particular order. Where does each belong?",
            "options": [
                "(a) at the gateway, (b) in the service",
                "Both at the gateway, so services stay simple",
                "Both in the service, so policy stays with the data",
                "(a) in the service, (b) at the gateway",
            ],
            "answer": 0,
            "explanation": "Coarse authorisation (may this client call this route) is identical across services and belongs at the gateway. Resource-level authorisation needs to know what an order is, and only the service knows that.",
            "section": "how-it-works",
            "concept": "proxies-and-gateways.authz-split",
            "mistake": "proxies-and-gateways.authz-in-wrong-place",
        },
        {
            "key": "mesh-threshold",
            "kind": "short_answer",
            "prompt": "A team of five engineers runs four services and proposes a service mesh. Give the lesson's honest position: when is a mesh worth it, and what does it cost?",
            "options": [],
            "answer": None,
            "model_answer": "Not yet. A mesh pays off at dozens of services and several teams. It costs an extra hop of latency each way, memory per pod for the sidecar, and a substantial operational learning curve. Below that threshold it is more machinery than problem.",
            "explanation": "Saying 'not yet, and here is the threshold' is the strong answer. A mesh is justified by service count and team count, not by fashion.",
            "section": "how-it-works",
            "concept": "proxies-and-gateways.mesh-threshold",
        },
        {
            "key": "local-jwt-tradeoff",
            "kind": "choice",
            "prompt": "The gateway verifies signed JWTs locally instead of calling the identity service. What do you give up, and what is the common compromise?",
            "options": [
                "Revocation is delayed until expiry; use short-lived tokens plus a cached revocation list",
                "Latency; add remote introspection on every request to fix it",
                "Nothing; local verification is strictly better",
                "Signature security; switch to opaque tokens",
            ],
            "answer": 0,
            "explanation": "Local verification is fast and removes a dependency, but a revoked token stays valid until it expires. Short-lived tokens with a cached revocation list keep the speed and bound the damage.",
            "section": "design-decisions",
            "concept": "proxies-and-gateways.token-validation",
        },
        {
            "key": "p99-creep",
            "kind": "choice",
            "prompt": "Gateway p99 latency has doubled over a year with no traffic change. Which cause does the lesson point at first?",
            "options": [
                "Plugins that each add a few ms, especially ones calling external systems synchronously",
                "TLS termination becoming more expensive",
                "Too many upstream services in the routing table",
                "The load balancer in front of the gateway",
            ],
            "answer": 0,
            "explanation": "Every plugin adds milliseconds to every request, and synchronous external calls in the chain are the usual culprit. The lesson budgets 1 to 5 ms for the gateway itself.",
            "section": "trade-offs",
            "concept": "proxies-and-gateways.latency-budget",
            "mistake": "proxies-and-gateways.plugin-latency-creep",
        },
        {
            "key": "trusted-header",
            "kind": "spot_mistake",
            "prompt": "The gateway resolves the API key to a tenant and forwards tenant_id as an internal header. It passes the client's own headers through untouched. What is wrong?",
            "options": [
                "A client can send its own tenant_id header and act as another tenant; the gateway must strip it",
                "tenant_id should be in the request body, not a header",
                "Nothing, because services re-validate the API key anyway",
                "The header should be encrypted before forwarding",
            ],
            "answer": 0,
            "explanation": "Services trust the header the gateway sets. If the gateway does not strip a client-supplied copy first, anyone can claim any tenant. The lesson calls this a classic real vulnerability.",
            "section": "common-failure-modes",
            "concept": "proxies-and-gateways.strip-trust-headers",
            "mistake": "proxies-and-gateways.trusting-client-headers",
        },
        {
            "key": "timeout-misalignment",
            "kind": "choice",
            "prompt": "The gateway times out after 30 seconds; the service behind it times out after 60. A slow request hits the 30 second mark. What happens?",
            "options": [
                "The client gets an error while the service keeps doing work nobody is waiting for",
                "The client waits the full 60 seconds",
                "The gateway retries the request on another instance",
                "Nothing; the longer timeout wins",
            ],
            "answer": 0,
            "explanation": "The gateway gives up first, but the service has no idea and keeps burning capacity for another 30 seconds. Timeouts must shrink as you go deeper into the stack.",
            "section": "common-failure-modes",
            "concept": "proxies-and-gateways.timeout-alignment",
            "mistake": "proxies-and-gateways.timeout-misalignment",
        },
        {
            "key": "identity-outage",
            "kind": "choice",
            "prompt": "The identity service goes down for five minutes. Which gateway design keeps most requests working?",
            "options": [
                "Local token verification with cached auth data, so requests do not depend on the identity service",
                "Retrying the identity call three times with backoff",
                "Failing open and skipping authentication until it returns",
                "Routing all traffic to the legacy monolith",
            ],
            "answer": 0,
            "explanation": "If the gateway calls the identity service on every request, that service's availability is the ceiling for the whole system. Auth dependencies must be cached or verified locally.",
            "section": "common-mistakes",
            "concept": "proxies-and-gateways.auth-dependency",
            "mistake": "proxies-and-gateways.sync-identity-call",
        },
    ],
    "sql-vs-nosql": [
        {
            "key": "real-trigger",
            "kind": "choice",
            "prompt": "Which fact is the real trigger for leaving a single relational primary for a distributed store, according to the lesson?",
            "options": [
                "Write volume exceeds one primary even after tuning",
                "Anticipated growth over the next two years",
                "The schema has a few optional fields per row",
                "The team is more comfortable with JSON",
            ],
            "answer": 0,
            "explanation": "Growth you expect is not a trigger; write volume that a tuned primary cannot absorb is. Optional fields are covered by relational JSON columns.",
            "section": "mental-model",
            "concept": "sql-vs-nosql.four-questions",
            "mistake": "sql-vs-nosql.anticipated-growth-as-trigger",
        },
        {
            "key": "new-access-pattern",
            "kind": "choice",
            "prompt": "Your Cassandra or DynamoDB design is live. Product now needs to query by a second attribute. What does that require?",
            "options": [
                "A second table or index maintained at write time, plus a backfill of existing rows",
                "A join at read time across the two attributes",
                "A schema migration that briefly locks the table",
                "Nothing; secondary attributes are indexed automatically",
            ],
            "answer": 0,
            "explanation": "NoSQL modelling is a table per access pattern. A new query shape means a new table or index written on every write, and a backfill for the rows already there.",
            "section": "how-it-works",
            "concept": "sql-vs-nosql.table-per-access-pattern",
            "mistake": "sql-vs-nosql.joins-at-read-time",
        },
        {
            "key": "two-myths",
            "kind": "spot_mistake",
            "prompt": "A candidate says: 'NoSQL has no transactions, and SQL does not scale.' What is wrong with this?",
            "options": [
                "Both are out of date: relational scales reads by replicas and writes by sharding; DynamoDB and MongoDB have transactions",
                "Only the first half is wrong; relational really cannot scale",
                "Only the second half is wrong; no NoSQL store has transactions",
                "Nothing; both are accurate summaries",
            ],
            "answer": 0,
            "explanation": "Relational databases scale reads very well and writes to a high ceiling, then by sharding. DynamoDB, MongoDB and Cassandra all offer transactions, more constrained and expensive than single-node relational ones.",
            "section": "how-it-works",
            "concept": "sql-vs-nosql.honest-comparison",
            "mistake": "sql-vs-nosql.folklore",
        },
        {
            "key": "reasoning-script",
            "kind": "choice",
            "prompt": "Orders and payments must change atomically at 500 orders a second. A separate append-only event stream does 50,000 writes a second, always read by (entity_id, time range). What does the lesson's script choose?",
            "options": [
                "Postgres for orders and payments, Cassandra for the event stream",
                "Cassandra for everything, to avoid running two stores",
                "Postgres for everything, sharded from day one",
                "MongoDB for orders, Postgres for the event stream",
            ],
            "answer": 0,
            "explanation": "Multi-row atomicity and constraints at modest volume point to relational. An append-only stream at 50,000 writes a second with a single key-plus-range pattern is a wide-column workload where you give up nothing you needed.",
            "section": "design-decisions",
            "concept": "sql-vs-nosql.reasoning-script",
        },
        {
            "key": "migration-asymmetry",
            "kind": "choice",
            "prompt": "Which asymmetry does the lesson state about changing your mind later?",
            "options": [
                "NoSQL to relational usually also reveals invariants that application code has been violating for years",
                "Relational to NoSQL is impossible without downtime",
                "Both directions are the same data migration",
                "NoSQL to relational is easier because the schema is looser",
            ],
            "answer": 0,
            "explanation": "Relational to NoSQL is a data migration. NoSQL to relational is a data migration plus the discovery that constraints the database would have enforced were quietly broken in application code.",
            "section": "trade-offs",
            "concept": "sql-vs-nosql.cost-of-wrong-choice",
        },
        {
            "key": "unbounded-partition",
            "kind": "choice",
            "prompt": "A wide-column table stores sensor readings with partition key device_id only. Devices report every 5 seconds for years. Which failure is this?",
            "options": [
                "An unbounded partition: the key has no time or hash component, so one partition grows forever",
                "A hot key caused by one very chatty device",
                "Modelling NoSQL relationally with client-side joins",
                "Using the search index as the source of truth",
            ],
            "answer": 0,
            "explanation": "A partition keyed only by device grows without limit. Adding a time bucket or hash to the key bounds each partition.",
            "section": "common-failure-modes",
            "concept": "sql-vs-nosql.partition-design",
            "mistake": "sql-vs-nosql.unbounded-partition",
        },
        {
            "key": "change-your-mind",
            "kind": "short_answer",
            "prompt": "You chose Postgres for orders. The interviewer asks: 'What would make you change your mind?' Give the answer the lesson wants.",
            "options": [],
            "answer": None,
            "model_answer": "A number. For example: if orders exceeded roughly 20,000 sustained writes a second, or a single merchant's data outgrew one node, I would move to sharded or distributed SQL rather than a different data model, because the transactional requirements do not go away with scale.",
            "explanation": "Having no trigger ready is listed as a common mistake. The trigger is a concrete threshold, and the move keeps the guarantees the workload needs.",
            "section": "common-mistakes",
            "concept": "sql-vs-nosql.trigger",
            "mistake": "sql-vs-nosql.no-trigger",
        },
    ],
    "consistency": [
        {
            "key": "practical-floor",
            "kind": "choice",
            "prompt": "A social app serves profile edits with plain eventual consistency, and users complain their changes 'do not save'. What is the cheapest model that fixes this?",
            "options": [
                "Read-your-writes: the user sees their own writes, others may lag",
                "Linearizable: every read sees the latest write globally",
                "Sequential: all nodes see operations in the same order",
                "Monotonic reads: time never goes backwards",
            ],
            "answer": 0,
            "explanation": "Eventual consistency with no session guarantee feels broken. Read-your-writes is cheap (session routing or version tracking) and buys most of the perceived correctness.",
            "section": "mental-model",
            "concept": "consistency.spectrum",
            "mistake": "consistency.eventual-with-no-session-guarantee",
        },
        {
            "key": "lost-update",
            "kind": "choice",
            "prompt": "Two requests each read a balance of 100, add 50, and write back. The final balance is 150. What is the anomaly and what fixes it?",
            "options": [
                "Lost update; fix with an optimistic version check or an atomic increment, not a stronger read model",
                "Stale read; fix by reading from the primary",
                "Write skew; fix only with serializable isolation",
                "Phantom read; fix with repeatable read",
            ],
            "answer": 0,
            "explanation": "Two read-modify-writes raced and one silently overwrote the other. Reading from the primary does not help; you need a version check (WHERE version = ?) or UPDATE ... SET n = n + 50.",
            "section": "how-it-works",
            "concept": "consistency.concurrency-control",
            "mistake": "consistency.stronger-reads-fix-lost-update",
        },
        {
            "key": "ryw-best-mechanism",
            "kind": "choice",
            "prompt": "The lesson names three ways to get read-your-writes without sending all reads to the primary. Which does it call the most precise and the best answer?",
            "options": [
                "Store the log position of the user's last write in the session; serve only from a replica at or beyond it",
                "Route that user to the primary for a short window after a write",
                "Send every read for logged-in users to the primary",
                "Poll the replica until it returns the new value",
            ],
            "answer": 0,
            "explanation": "Routing to the primary for a window works but is slightly wasteful. Tracking the write position is exact: any replica that has caught up can serve the read, else fall back to the primary.",
            "section": "how-it-works",
            "concept": "consistency.read-your-writes",
        },
        {
            "key": "isolation-vs-consistency",
            "kind": "short_answer",
            "prompt": "Explain the difference between consistency and isolation, name the usual default isolation level, and say one anomaly that default still allows.",
            "options": [],
            "answer": None,
            "model_answer": "Consistency is about replicas: what a read returns relative to recent writes. Isolation is about concurrent transactions on one database. Most databases default to read committed, which still allows non-repeatable reads, phantoms and write skew.",
            "explanation": "The two axes are frequently confused. Knowing your default level, and that it permits anomalies most code assumes are impossible, is a strong depth signal.",
            "section": "how-it-works",
            "concept": "consistency.isolation-levels",
            "mistake": "consistency.assumes-default-is-serializable",
        },
        {
            "key": "oversell-prevention",
            "kind": "choice",
            "prompt": "One item is left in stock and two checkouts arrive at once. Which approach does the lesson recommend to prevent overselling?",
            "options": [
                "A conditional update (WHERE quantity >= ?) or a reservation row with a unique constraint",
                "Read the quantity from the primary, then write if it is positive",
                "Linearizable reads on the inventory table",
                "A short-TTL cache so both requests see the same value",
            ],
            "answer": 0,
            "explanation": "Invariants are never enforced by a read, however strong. A check-then-act lets both requests pass the check; the conditional write makes the database decide atomically.",
            "section": "design-decisions",
            "concept": "consistency.invariants-in-writes",
            "mistake": "consistency.check-then-act",
        },
        {
            "key": "strong-costs",
            "kind": "choice",
            "prompt": "You make an operation strongly consistent across two regions. What does that cost, according to the lesson?",
            "options": [
                "Extra round trips of latency on every operation, and availability under a partition",
                "Storage, because every region must hold a full copy",
                "Nothing noticeable if the network is fast",
                "Only availability; latency is unaffected",
            ],
            "answer": 0,
            "explanation": "Quorum or consensus writes add round trips, a hundred milliseconds or more across regions, and cannot proceed when the regions cannot talk. That is why you pick the weakest model the operation tolerates.",
            "section": "trade-offs",
            "concept": "consistency.strong-costs",
        },
        {
            "key": "write-skew",
            "kind": "choice",
            "prompt": "Under snapshot isolation, two on-call engineers each check 'at least one other person is on call' and both go off call. Nobody is on call. Why did the database allow it?",
            "options": [
                "Write skew: each transaction read a valid snapshot and wrote a different row; snapshot isolation does not prevent it",
                "Lost update: the second write overwrote the first",
                "Dirty read: each saw the other's uncommitted change",
                "It was misconfigured; snapshot isolation prevents this",
            ],
            "answer": 0,
            "explanation": "Neither transaction violated the invariant alone, and they touched different rows, so snapshot isolation had nothing to conflict. Only serializable isolation, or a lock or constraint, prevents write skew.",
            "section": "common-failure-modes",
            "concept": "consistency.isolation-levels",
            "mistake": "consistency.snapshot-prevents-write-skew",
        },
        {
            "key": "lww-claim",
            "kind": "spot_mistake",
            "prompt": "A multi-region design says: 'Both regions accept writes and we resolve conflicts with last-write-wins by timestamp, so conflicts are handled.' What is wrong?",
            "options": [
                "LWW silently discards one write and trusts clocks you cannot trust; say what is lost, or use CRDTs or an app-level merge",
                "LWW cannot be used across regions",
                "Timestamps must be converted to UTC first",
                "Nothing; LWW is the standard resolution rule",
            ],
            "answer": 0,
            "explanation": "Last-write-wins is fine only if you acknowledge that data is silently dropped and that clock skew can discard the write that was actually later. CRDTs or keeping both versions are the alternatives.",
            "section": "common-mistakes",
            "concept": "consistency.convergence",
            "mistake": "consistency.lww-without-acknowledging-loss",
        },
    ],
    "sd-disaster-recovery": [
        {
            "key": "delete-without-where",
            "kind": "choice",
            "prompt": "An engineer runs DELETE without a WHERE clause on the primary. Replicas apply it within 200 ms. Which protection actually helps?",
            "options": [
                "Point-in-time restore from a base backup plus archived logs",
                "Multi-AZ synchronous replication",
                "A cross-region read replica",
                "Adding a third replica for redundancy",
            ],
            "answer": 0,
            "explanation": "Replication copies the destructive statement faithfully to every replica. Only backups, and specifically point-in-time recovery, let you go back to the second before it ran.",
            "section": "mental-model",
            "concept": "disaster-recovery.replication-is-not-backup",
            "mistake": "disaster-recovery.replication-as-backup",
        },
        {
            "key": "rpo-by-backup-type",
            "kind": "choice",
            "prompt": "Setup A: a nightly full backup only. Setup B: nightly backup plus continuous write-ahead log archiving. What RPO does each give?",
            "options": [
                "A: up to 24 hours. B: seconds",
                "Both up to 24 hours; logs only speed up restore",
                "A: seconds. B: up to 24 hours",
                "Both seconds, because the nightly backup is the base",
            ],
            "answer": 0,
            "explanation": "With only a nightly backup you can lose up to a day. Continuous log archiving lets you replay to any second and stop just before the damaging statement.",
            "section": "how-it-works",
            "concept": "disaster-recovery.point-in-time-recovery",
        },
        {
            "key": "same-account-backups",
            "kind": "choice",
            "prompt": "Backups are stored in a different region but the same cloud account as production, deletable by the production role. Which threat is not covered?",
            "options": [
                "A compromised credential that deletes production and then the backups",
                "A region outage",
                "A disk failure on the primary",
                "A bad migration that drops a column",
            ],
            "answer": 0,
            "explanation": "Account separation matters more than region separation. Ransomware or a stolen credential with delete permission takes the backups with it unless they sit in an isolated account with write-once retention.",
            "section": "how-it-works",
            "concept": "disaster-recovery.isolated-immutable-backups",
            "mistake": "disaster-recovery.backups-deletable-by-prod",
        },
        {
            "key": "six-hour-corruption",
            "kind": "short_answer",
            "prompt": "A deploy at 09:00 wrote bad data to 2% of rows. You discover it at 15:00. Describe the recovery for the database without losing the six hours of good writes.",
            "options": [],
            "answer": None,
            "model_answer": "Do not roll the live database back. Restore a copy to just before 09:00 in a parallel environment, identify the affected rows by the bug's signature, and repair only those in the live database. An append-only event log or audit trail makes the reconstruction much easier.",
            "explanation": "Restoring everything to 08:59 would discard six hours of legitimate writes, usually a worse outcome than the bug. Surgical repair from a parallel restore is the technique.",
            "section": "how-it-works",
            "concept": "disaster-recovery.selective-repair",
            "mistake": "disaster-recovery.full-rollback",
        },
        {
            "key": "rebuildable-data",
            "kind": "choice",
            "prompt": "Your system has a 2 TB search index derived from the transactional database. What backup treatment does the lesson give it?",
            "options": [
                "No backup: it is rebuildable, so it needs a tested rebuild procedure with a known duration",
                "RPO zero, the same as orders",
                "A nightly backup with 30-day retention",
                "Continuous log archiving for second-level RPO",
            ],
            "answer": 0,
            "explanation": "Marking data as rebuildable is a genuine simplification. Derived data needs a documented, tested rebuild and an honest estimate of how long it takes, not a backup.",
            "section": "design-decisions",
            "concept": "disaster-recovery.rpo-rto-per-dataset",
        },
        {
            "key": "erasure-and-backups",
            "kind": "choice",
            "prompt": "A user exercises their right to erasure. What does the lesson say makes this awkward with backups?",
            "options": [
                "Deletion requests must reach backups too, and long retention conflicts with data-minimisation duties",
                "Backups cannot be encrypted per user",
                "Immutable backups can only be edited by administrators",
                "Nothing; backups are exempt from erasure requests",
            ],
            "answer": 0,
            "explanation": "Long retention aids recovery but the deleted data is still sitting in every backup. Propagating deletion to backups is a real and often-missed requirement.",
            "section": "trade-offs",
            "concept": "disaster-recovery.retention-vs-privacy",
            "mistake": "disaster-recovery.deletion-not-in-backups",
        },
        {
            "key": "backups-never-restored",
            "kind": "spot_mistake",
            "prompt": "'Our backups have completed successfully every night for two years, so we are covered.' What is wrong with this claim?",
            "options": [
                "Completion is meaningless; an untested restore may be the wrong database, missing a table, or unreadable",
                "Nightly is too infrequent to count as covered",
                "Two years of retention is too long to be useful",
                "Nothing; successful completion is the metric that matters",
            ],
            "answer": 0,
            "explanation": "An untested backup is a belief, not a control. The metrics that matter are measured restore time and scheduled verified restores into an isolated environment.",
            "section": "common-failure-modes",
            "concept": "disaster-recovery.restore-is-the-product",
            "mistake": "disaster-recovery.never-tested-restore",
        },
        {
            "key": "partial-backup",
            "kind": "choice",
            "prompt": "The database is backed up nightly. User uploads in object storage are not. After a restore to yesterday, what is the state of the system?",
            "options": [
                "Metadata and files no longer match: rows point at files that differ from what they describe",
                "Fine, because object storage is durable on its own",
                "Fine, because the database restore recreates the files",
                "Only new uploads since yesterday are missing",
            ],
            "answer": 0,
            "explanation": "Backing up one half of a system is a partial backup. Restored metadata references files as they were yesterday, while object storage kept moving, so the two disagree.",
            "section": "common-mistakes",
            "concept": "disaster-recovery.partial-backups",
            "mistake": "disaster-recovery.db-but-not-object-storage",
        },
    ],
    "sd-url-shortener": [
        {
            "key": "estimate-conclusions",
            "kind": "choice",
            "prompt": "100M new links a month, a 100:1 read ratio, and about 500 bytes a row. Which conclusion does the lesson draw from the estimate?",
            "options": [
                "600 GB a year fits one database, 12,000 peak reads is a caching problem, and writes are trivial",
                "Shard from day one, because 3 TB over five years is too much for one node",
                "The write path is the bottleneck at 120 writes a second",
                "Both reads and writes need a distributed store",
            ],
            "answer": 0,
            "explanation": "40 writes a second is nothing. 12,000 peak reads of a single indexed lookup, with the same links requested repeatedly, is exactly what a cache is for. Saying you will not shard is a positive signal.",
            "section": "step-2-estimate-the-scale",
            "concept": "url-shortener.estimate",
            "mistake": "url-shortener.over-engineering",
        },
        {
            "key": "clicks-in-links-table",
            "kind": "choice",
            "prompt": "A candidate adds a clicks column to the links table and increments it on every redirect. What goes wrong at 12,000 redirects a second?",
            "options": [
                "Every read becomes a write and the popular row is a contention point; counts belong in a separate path",
                "The integer column overflows",
                "The primary key index becomes slower",
                "Nothing; it is a single indexed update",
            ],
            "answer": 0,
            "explanation": "The redirect path must never write to the database synchronously. Counts go to a Redis counter flushed periodically, or to events aggregated asynchronously.",
            "section": "step-4-data-model",
            "concept": "url-shortener.click-counting",
            "mistake": "url-shortener.synchronous-click-write",
        },
        {
            "key": "cache-on-write",
            "kind": "choice",
            "prompt": "The v1 design uses cache-aside on code to long_url. Why does the lesson also populate the cache when a link is created, not only on a read miss?",
            "options": [
                "A freshly created link is very likely to be clicked immediately",
                "To keep Redis and Postgres strongly consistent",
                "Because cache-aside cannot fill the cache on a miss",
                "To skip the unique-constraint check on insert",
            ],
            "answer": 0,
            "explanation": "New links are shared right away, so pre-warming on write avoids a guaranteed miss. With a steep power law of popularity, the hit rate stays well above 95%.",
            "section": "step-5-first-architecture",
            "concept": "url-shortener.read-path-cache",
        },
        {
            "key": "ranged-allocation",
            "kind": "choice",
            "prompt": "Each app node takes a block of 10,000 ids from a central allocator. A node crashes holding 6,000 unused ids. What happens, and what else must be done to the ids?",
            "options": [
                "The gap is harmless; scramble the sequential ids with a bijective transform so codes cannot be guessed",
                "The allocator must reclaim the 6,000 ids before handing out more",
                "Other nodes will produce duplicates in that range",
                "Nothing else; sequential codes are fine for a public product",
            ],
            "answer": 0,
            "explanation": "Gaps cost nothing in a 62^7 key space. Ranged allocation gives one coordination hop per 10,000 writes with no collisions, but the ids are sequential and enumerable unless scrambled.",
            "section": "how-it-works",
            "concept": "url-shortener.key-generation",
            "mistake": "url-shortener.guessable-codes",
        },
        {
            "key": "redis-down",
            "kind": "short_answer",
            "prompt": "At 120,000 reads a second, Redis goes down. What happens to the read path, and what keeps the system up?",
            "options": [],
            "answer": None,
            "model_answer": "Reads fall through to Postgres, which cannot serve that rate. The client treats a Redis timeout as a miss rather than an error; a concurrency limiter caps in-flight database queries so Postgres degrades instead of collapsing, with excess requests getting a fast 503 and Retry-After; the CDN keeps serving popular links; and recovery is a cold cache, so requests stay limited while it warms.",
            "explanation": "Never mentioning what happens when the cache is unavailable is a listed mistake. The answer is graceful degradation, not a bigger database.",
            "section": "evolution-under-pressure",
            "concept": "url-shortener.cache-outage",
            "mistake": "url-shortener.no-cache-outage-plan",
        },
        {
            "key": "viral-link",
            "kind": "choice",
            "prompt": "One link gets 50,000 requests a second. A candidate proposes moving to Redis Cluster. What does the lesson say?",
            "options": [
                "It does not help, one key lives on one node; use the CDN first, then a short in-process cache per app node",
                "It helps, because the key is spread across all cluster nodes",
                "Shard Postgres by code so the read load is spread",
                "Add read replicas for that link",
            ],
            "answer": 0,
            "explanation": "A hot key hashes to a single slot on a single node no matter how big the cluster is. Every request is identical and cacheable, so the edge absorbs nearly all of it and a 5 second local cache collapses the rest.",
            "section": "failure-modes",
            "concept": "url-shortener.hot-key",
            "mistake": "url-shortener.scale-redis-for-hot-key",
        },
        {
            "key": "301-proposal",
            "kind": "spot_mistake",
            "prompt": "A design says: 'We return 301 so browsers cache the redirect permanently and almost no traffic reaches us.' What is wrong?",
            "options": [
                "You can never change, disable or count clicks on that link for clients that cached it",
                "301 is not cacheable by browsers",
                "301 responses are slower than 302",
                "Nothing; the offload makes it the right choice",
            ],
            "answer": 0,
            "explanation": "The offload is real, and the cost is giving up control: analytics, revocation of a phishing link, and changing the target all break. The lesson chooses 302 with a short Cache-Control.",
            "section": "trade-offs",
            "concept": "url-shortener.301-vs-302",
            "mistake": "url-shortener.301-without-acknowledging-loss",
        },
        {
            "key": "overbuilt-design",
            "kind": "spot_mistake",
            "prompt": "For 100M links a month, a candidate proposes Cassandra sharded on code, Kafka for click events, and a single global counter for ids. What is the main problem?",
            "options": [
                "600 GB a year fits one database; the design is over-engineered and the global counter is a per-write bottleneck",
                "Cassandra cannot store URLs",
                "Kafka cannot handle 40 events a second",
                "Sharding on code makes owner lookups impossible",
            ],
            "answer": 0,
            "explanation": "The data fits comfortably on one machine and the traffic is in the read path. Reaching for distributed components here, and using an unbatched global counter, are both listed mistakes.",
            "section": "common-mistakes",
            "concept": "url-shortener.over-engineering",
            "mistake": "url-shortener.over-engineering",
        },
    ],
    "sd-chat-system": [
        {
            "key": "connection-arithmetic",
            "kind": "choice",
            "prompt": "100M concurrent WebSockets at about 50 KB of memory each, and 250,000 connections per gateway node. What does the estimate force you to say?",
            "options": [
                "About 400 gateway nodes and 5 TB of RAM just to hold sockets; connections are their own capacity line",
                "About 40 nodes; connections are cheap compared with messages",
                "Nothing; the load balancer holds the sockets",
                "A relational store is needed for 1M messages a second",
            ],
            "answer": 0,
            "explanation": "100M divided by 250,000 is 400 nodes, and 100M x 50 KB is 5 TB. Holding sockets is a capacity line item independent of message throughput.",
            "section": "step-2-estimate-the-scale",
            "concept": "chat-system.connection-cost",
        },
        {
            "key": "catch-up-after-drop",
            "kind": "choice",
            "prompt": "A phone loses its socket for a minute and reconnects. How does it get the messages it missed, according to the lesson's API?",
            "options": [
                "It pulls everything after its last acknowledged seq over HTTP; the socket is only a delivery optimisation",
                "The gateway replays its per-socket buffer over the new connection",
                "The server resends the last 100 messages on the new socket",
                "It relies on push notifications to fill the gap",
            ],
            "answer": 0,
            "explanation": "The HTTP catch-up endpoint is the correctness mechanism. Nothing depends on the socket having stayed up, which is what makes the stateful gateway tier safe.",
            "section": "step-3-api-design",
            "concept": "chat-system.socket-vs-catch-up",
            "mistake": "chat-system.socket-as-truth",
        },
        {
            "key": "unread-pointer",
            "kind": "choice",
            "prompt": "100B messages a day. Compare storing a row per unread message per recipient with storing a last_read_seq pointer per member.",
            "options": [
                "The pointer makes unread count a subtraction; rows would mean about 100 billion writes a day",
                "Rows are more accurate, so the write cost is worth paying",
                "The pointer only works for one-to-one chats",
                "Both cost about the same; the pointer is just simpler code",
            ],
            "answer": 0,
            "explanation": "The lesson calls this the single most important data-modelling decision in the problem. Unread is last_message_seq minus last_read_seq, one small row per member per conversation.",
            "section": "step-4-data-model",
            "concept": "chat-system.read-pointer",
            "mistake": "chat-system.row-per-unread",
        },
        {
            "key": "ordering",
            "kind": "short_answer",
            "prompt": "How does the design order messages within a conversation without synchronised clocks, and why does it not try to order messages across conversations?",
            "options": [],
            "answer": None,
            "model_answer": "The server assigns a per-conversation sequence number at persistence, with a single ordering point per conversation: either all writes for a conversation go to one shard with an atomic counter, or one service instance holds a lease for it. That makes ordering a partitioned problem. Across conversations no order is defined and none is needed, so building a global order would only add a bottleneck.",
            "explanation": "Per-conversation seq gives a total order every participant agrees on. Attempting global ordering is a listed failure mode.",
            "section": "how-it-works",
            "concept": "chat-system.sequence-numbers",
            "mistake": "chat-system.global-ordering",
        },
        {
            "key": "gateway-dies",
            "kind": "choice",
            "prompt": "A gateway holding 250,000 connections dies. What is the real risk, and what is the mitigation?",
            "options": [
                "A reconnect storm knocks over the next gateway; jittered backoff and edge connection-rate limits, no messages lost",
                "250,000 in-flight messages are lost; replay them from the gateway's log",
                "The registry must be rebuilt from scratch before anyone can chat",
                "Recipients receive every message twice",
            ],
            "answer": 0,
            "explanation": "Messages were persisted before the socket ever mattered, so nothing is lost. The danger is the thundering herd of simultaneous reconnects, handled by jitter, a connection-rate limiter and staggered restarts.",
            "section": "evolution-under-pressure",
            "concept": "chat-system.reconnect-storm",
            "mistake": "chat-system.no-reconnect-design",
        },
        {
            "key": "read-receipts-quadratic",
            "kind": "choice",
            "prompt": "A 500-member group shows per-member read state. Each member reads a message. Roughly how much receipt traffic does one message generate, and what do real products do?",
            "options": [
                "About 500 x 500 notifications, quadratic; products stop showing per-member read state above a threshold",
                "500 notifications, linear; nothing needs to change",
                "One notification per message; receipts are aggregated by the gateway",
                "None; read state is only stored, never delivered",
            ],
            "answer": 0,
            "explanation": "500 readers each generate a receipt that would notify 500 members. That is a product decision forced by data volume, and pointing it out is a good sign.",
            "section": "failure-modes",
            "concept": "chat-system.group-fan-out",
            "mistake": "chat-system.per-member-receipts-at-scale",
        },
        {
            "key": "home-region",
            "kind": "choice",
            "prompt": "Two users in different regions share a conversation. The lesson gives it one home region. What does that cost, and why not accept writes in both regions?",
            "options": [
                "Sends pay a cross-region round trip; writes in both regions would reintroduce the ordering conflicts seq exists to avoid",
                "Storage doubles; writes in both regions are cheaper",
                "Nothing; gateways forward locally so latency is unaffected",
                "Writes in both regions are fine if last-write-wins is used",
            ],
            "answer": 0,
            "explanation": "The sequence-number design depends on a single ordering point per conversation. A home region keeps that at the price of asymmetric latency for one participant.",
            "section": "trade-offs",
            "concept": "chat-system.sequence-numbers",
        },
        {
            "key": "gateway-as-truth",
            "kind": "spot_mistake",
            "prompt": "Design: 'The gateway acks the sender as soon as it receives the message, then forwards it for storage. If the recipient is offline, the gateway keeps the message in memory until they reconnect.' What is wrong?",
            "options": [
                "It acks before durability and treats the gateway as truth; persist, then ack, then deliver, and catch up by seq",
                "Gateway memory is too small; use disk instead",
                "Push notifications should replace sockets entirely",
                "Nothing; holding messages in the gateway is standard",
            ],
            "answer": 0,
            "explanation": "A crash after the ack loses an accepted message, the one failure this product cannot have. Offline recipients get a push notification and pull by sequence number on reconnect; gateways hold sockets and nothing else.",
            "section": "common-mistakes",
            "concept": "chat-system.persist-ack-deliver",
            "mistake": "chat-system.ack-before-persist",
        },
    ],
    "sd-payment-system": [
        {
            "key": "throughput-not-the-problem",
            "kind": "choice",
            "prompt": "10M payments a day, about 500 a second at peak, with roughly 100M ledger rows a day. Which conclusion does the lesson draw?",
            "options": [
                "Throughput is not the problem; one relational database is right, and the difficulty is correctness",
                "Shard by merchant_id from day one to be safe",
                "Use a wide-column store because 100M rows a day is too many for SQL",
                "Webhooks are rare enough to process synchronously",
            ],
            "answer": 0,
            "explanation": "500 a second is low by internet standards. Transactions and constraints are exactly what money needs, the append-only ledger partitions by time, and duplicate webhooks are the normal condition.",
            "section": "step-2-estimate-the-scale",
            "concept": "payment-system.correctness-over-throughput",
            "mistake": "payment-system.optimising-throughput",
        },
        {
            "key": "ledger-no-hot-row",
            "kind": "choice",
            "prompt": "A popular merchant receives thousands of payments a minute. Why does the lesson's ledger design have no hot-row contention on that merchant's balance?",
            "options": [
                "Balances are derived by summing appended entries, with periodic snapshots, so nothing updates a balance row",
                "Balances are kept in Redis and written back later",
                "Each merchant gets its own table",
                "Balance updates are batched once a minute",
            ],
            "answer": 0,
            "explanation": "Every movement is an append of entries that sum to zero. There is no mutable balance to lock, drift or corrupt, and any balance at any moment can be reconstructed.",
            "section": "step-4-data-model",
            "concept": "payment-system.double-entry-ledger",
            "mistake": "payment-system.balance-column",
        },
        {
            "key": "timeout-with-idempotency",
            "kind": "choice",
            "prompt": "The provider call times out. The provider supports idempotency keys and you passed your payment_id. What do you do?",
            "options": [
                "Retry with the same provider idempotency key, so the provider returns the original result instead of charging again",
                "Retry immediately; a timeout means nothing was charged",
                "Mark the payment failed and tell the customer",
                "Retry through a second provider",
            ],
            "answer": 0,
            "explanation": "A timeout is an unknown outcome. Retrying with the same key is safe. Without keys, query the provider by reference first; if neither is possible, mark it unknown and resolve in reconciliation.",
            "section": "how-it-works",
            "concept": "payment-system.ambiguous-timeout",
            "mistake": "payment-system.blind-retry",
        },
        {
            "key": "lost-webhook",
            "kind": "short_answer",
            "prompt": "A provider webhook for a captured payment is never delivered. Which part of the architecture makes the ledger correct anyway, and why is it drawn as a first-class component?",
            "options": [],
            "answer": None,
            "model_answer": "The reconciliation service. It takes the provider's daily settlement files, compares them against our ledger and payment records, and sends discrepancies to an exceptions queue. A payment in the provider file but missing from our ledger is a lost webhook, so we ingest it. It is first-class because webhooks are only an optimisation; reconciliation is the guarantee.",
            "explanation": "No payment system runs without reconciliation, because no design removes ambiguity from a network. Drawing it before being asked shows you understand the domain.",
            "section": "step-5-architecture",
            "concept": "payment-system.reconciliation",
            "mistake": "payment-system.trusting-webhooks",
        },
        {
            "key": "double-click",
            "kind": "choice",
            "prompt": "A customer double-clicks pay: two requests with the same idempotency key arrive milliseconds apart. Why must the key be enforced by a unique constraint rather than a read-then-write check?",
            "options": [
                "Both requests can pass the read before either writes; the constraint makes one insert win and the other gets 409",
                "A read is slower than an insert",
                "Constraints are easier to audit",
                "A read-then-write check cannot return 409",
            ],
            "answer": 0,
            "explanation": "With a check-then-act both requests see no existing key and both charge. The unique constraint lets the database decide atomically; the loser sees in_progress, gets 409, and retries for the real result.",
            "section": "evolution-under-pressure",
            "concept": "payment-system.idempotency-key",
            "mistake": "payment-system.read-then-write-idempotency",
        },
        {
            "key": "failover-while-unknown",
            "kind": "choice",
            "prompt": "Provider A times out on a charge. Provider B is healthy and cheaper. Should the router retry the payment on B?",
            "options": [
                "No: only after A's attempt is definitively known to have failed; retrying while unknown is how double charges happen",
                "Yes, immediately, because availability matters most",
                "Yes, if the amount is below a threshold",
                "Yes, but only through the same adapter",
            ],
            "answer": 0,
            "explanation": "The customer may already have been charged by A. Multi-provider retry is safe only for definite failures, a rule that makes sense once the unknown state is taken seriously.",
            "section": "failure-modes",
            "concept": "payment-system.ambiguous-timeout",
            "mistake": "payment-system.retry-other-provider-while-unknown",
        },
        {
            "key": "sync-vs-async-auth",
            "kind": "choice",
            "prompt": "Should authorisation be synchronous or asynchronous? What do most systems do, according to the lesson?",
            "options": [
                "Synchronous, with an asynchronous resolution path for the ambiguous cases",
                "Fully asynchronous; the customer polls for a result later",
                "Fully synchronous; retry until the provider answers",
                "Asynchronous by default, synchronous for large amounts",
            ],
            "answer": 0,
            "explanation": "Customers want an immediate answer, so the main path is synchronous. Timeouts enter unknown and a background resolver queries the provider's status API with backoff.",
            "section": "trade-offs",
            "concept": "payment-system.unknown-state",
        },
        {
            "key": "edit-ledger-entry",
            "kind": "spot_mistake",
            "prompt": "A merchant was charged a 30.00 fee instead of 3.00. Support proposes editing the ledger entry to 3.00. What is wrong?",
            "options": [
                "Ledger entries are never edited; write a compensating reversal entry so history stays complete",
                "The fee should be recomputed by the provider instead",
                "Edits are acceptable if they are logged",
                "Nothing, as long as the transaction still sums to zero",
            ],
            "answer": 0,
            "explanation": "Corrections are reversals, never edits, so any balance at any past moment is still explainable and a dispute months later is answerable. Editing financial records is a listed mistake.",
            "section": "common-mistakes",
            "concept": "payment-system.double-entry-ledger",
            "mistake": "payment-system.editing-financial-records",
        },
    ],
    "sd-message-queue": [
        {
            "key": "disk-is-the-constraint",
            "kind": "choice",
            "prompt": "1M messages a second at 1 KB each, three copies, seven days of retention. Which conclusion does the lesson draw?",
            "options": [
                "About 1.8 PB on disk; writes must be sequential and topics must be partitioned across brokers",
                "CPU is the bottleneck; add cores to one big broker",
                "It fits on one broker with a large disk",
                "Retention must be cut to one day to be feasible",
            ],
            "answer": 0,
            "explanation": "1 GB a second for seven days is about 600 TB, 1.8 PB with three copies. That does not fit on one machine, and random writes would cut disk speed by ten times.",
            "section": "step-2-estimate-the-scale",
            "concept": "message-queue.scale",
        },
        {
            "key": "segment-deletion",
            "kind": "choice",
            "prompt": "How does the broker delete messages that pass the seven-day retention, and why is it cheap?",
            "options": [
                "It deletes whole segment files past the age; deleting one message from the middle of a log would be expensive",
                "It marks each message deleted and compacts the partition nightly",
                "Consumers delete messages after reading them",
                "It rewrites the partition without the old messages",
            ],
            "answer": 0,
            "explanation": "A partition is a folder of segment files, rolled at 1 GB. Old segments are dropped whole. Messages are not deleted when read, so a new consumer group can start from the beginning.",
            "section": "step-4-data-model",
            "concept": "message-queue.log-structure",
        },
        {
            "key": "acks-all-vs-acks-1",
            "kind": "choice",
            "prompt": "You need acks under 10 ms and no acknowledged message lost when a broker dies. The leader acks a write and crashes a millisecond later. Which setting keeps that write, and what does it cost?",
            "options": [
                "acks=all with min in-sync of 2: one extra round trip per write, but at least one follower already had the bytes",
                "acks=1: faster, and followers catch up before any crash matters",
                "acks=1 with a replication factor of 5",
                "acks=all with min in-sync of 1, which is equally safe and faster",
            ],
            "answer": 0,
            "explanation": "With acks=all the leader answers only after every in-sync follower has the bytes, and min in-sync of 2 refuses a write that would live on one copy. acks=1 is faster and can lose the tail on a leader crash.",
            "section": "trade-offs",
            "concept": "message-queue.replication",
            "mistake": "message-queue.acks-1-tail-loss",
        },
        {
            "key": "duplicate-source",
            "kind": "choice",
            "prompt": "A consumer reads offsets 100 to 199, writes the results to its database, then crashes before committing offset 200. What happens next, and what is the fix?",
            "options": [
                "The next member starts at 100 and processes them again; make the work idempotent, e.g. key DB writes on the message id",
                "The broker skips to 200 because the messages were already read",
                "Messages 100 to 199 are lost",
                "The batch goes to the dead-letter topic after a rebalance",
            ],
            "answer": 0,
            "explanation": "Progress is the committed offset in the broker, not the consumer's memory. Reprocessing after a crash is at-least-once, the contract not a bug, and the consumer must be idempotent.",
            "section": "how-it-works",
            "concept": "message-queue.at-least-once",
            "mistake": "message-queue.consumer-memory-as-truth",
        },
        {
            "key": "order-across-keys",
            "kind": "short_answer",
            "prompt": "Why does the queue keep order only inside one partition, and how would you keep two keys in order together?",
            "options": [],
            "answer": None,
            "model_answer": "A keyed message goes to hash(key) mod partitions, offsets only go up inside one partition, and one consumer in a group owns that partition at a time, so order holds per key. Across partitions there is no order. To order two keys together, give them the same key, such as the customer id instead of the order id. True global order needs a single partition and gives up horizontal scale.",
            "explanation": "Push back first: per-key order is usually what is needed. Global order and horizontal scale do not go together.",
            "section": "evolution-under-pressure",
            "concept": "message-queue.ordering",
            "mistake": "message-queue.global-order",
        },
        {
            "key": "poison-message",
            "kind": "choice",
            "prompt": "One message makes the consumer throw on every attempt. It restarts, reads the same message, throws again. Lag never moves. What do you do?",
            "options": [
                "After a retry limit, write it to a dead-letter topic with the error, commit the offset, and move on",
                "Give the consumer more memory",
                "Add more members to the consumer group",
                "Restart the leader broker for that partition",
            ],
            "answer": 0,
            "explanation": "A poison message blocks its whole partition for hours if there is no dead-letter path. More members do not help, because that partition still belongs to one member at a time.",
            "section": "failure-modes",
            "concept": "message-queue.poison-message",
            "mistake": "message-queue.no-dead-letter",
        },
        {
            "key": "slow-consumer-pull",
            "kind": "choice",
            "prompt": "The consume call is a pull: GET .../messages?offset=&max=. One consumer group becomes ten times slower than the producers. What happens inside the broker?",
            "options": [
                "Nothing; that group's lag grows on its partitions, and lag is the number to watch",
                "The broker buffers per consumer and runs out of memory",
                "The broker starts dropping that group's messages",
                "Producers are blocked immediately",
            ],
            "answer": 0,
            "explanation": "Consumers pull at their own pace, so a slow consumer falls behind instead of overloading the broker. Fix it by adding members up to the partition count or splitting heavy work onto another queue.",
            "section": "step-3-api",
            "concept": "message-queue.pull-and-lag",
            "mistake": "message-queue.lag-not-monitored",
        },
        {
            "key": "exactly-once-claim",
            "kind": "spot_mistake",
            "prompt": "'We turned on exactly-once, so the consumer's database writes and emails will never be duplicated.' What is wrong?",
            "options": [
                "Exactly-once only holds inside the queue; the database write and the email still need to be idempotent",
                "Exactly-once is not possible in any queue",
                "It only covers the producer side, not consumers",
                "Nothing; that is what the setting guarantees",
            ],
            "answer": 0,
            "explanation": "An idempotent producer plus a transaction makes writing output messages and committing the input offset atomic. It does not reach into your database or an email service, and saying that limit out loud is expected.",
            "section": "common-mistakes",
            "concept": "message-queue.exactly-once-scope",
            "mistake": "message-queue.exactly-once-beyond-queue",
        },
    ],
}
