"""Knowledge checks: When to Scale (concrete thresholds and the decision sequence)."""

from __future__ import annotations

L = "sd-when-to-scale"

CHECKS: dict[str, list[dict]] = {
    L: [
        {
            "key": "first-question-writes",
            "kind": "choice",
            "prompt": "You have 2,000 writes/s and 60,000 reads/s. Following the decision sequence, what is the first thing you check and what does it say?",
            "options": [
                "Reads first: 60,000/s means read replicas immediately",
                "Writes first: 2,000/s is inside one primary's comfort zone, so the write path stays as it is",
                "Cache size first: 60,000/s needs a Redis cluster",
                "Connections first: 60,000 reads means 60,000 connections",
            ],
            "answer": 1,
            "explanation": "The sequence asks about writes before anything else, because only sharding or a different store fixes a write ceiling. 2,000/s is under the 3,000–5,000 trigger, so writes are fine and you move on to reads.",
            "section": "mental-model",
            "concept": f"{L}.sequence-order",
        },
        {
            "key": "cache-or-replicas",
            "kind": "choice",
            "prompt": "Reads are 40,000/s and the same few thousand items are read again and again. Cache or read replicas, and why?",
            "options": [
                "Replicas, because they serve any query without invalidation",
                "A cache, because a hit rate above 75% is realistic and it absorbs 80–95% of reads",
                "Both at once, because 40,000 is far above one node",
                "Neither, because 40,000 reads/s is inside one node's comfort zone",
            ],
            "answer": 1,
            "explanation": "Repeating reads mean a high hit rate, which is the cacheability test in the sequence. A cache absorbs most reads and shields the database from bursts; replicas only spread the same load.",
            "section": "mental-model",
            "concept": f"{L}.cacheable",
            "mistake": f"{L}.replicas-for-cacheable-reads",
        },
        {
            "key": "relational-write-ceiling",
            "kind": "choice",
            "prompt": "A design sends 20,000 writes/s to one PostgreSQL primary and adds five read replicas. What is wrong?",
            "options": [
                "Nothing: replicas absorb the writes too",
                "The primary still takes every write, and 20,000/s is far past its 1,000–3,000/s comfort zone",
                "Five replicas is too few for 20,000 writes",
                "PostgreSQL needs PgBouncer before replicas",
            ],
            "answer": 1,
            "explanation": "Replicas scale reads only; every write still lands on the single primary. At 20,000/s the write path must shard, move to a wide-column store, or buffer through a log.",
            "section": "how-it-works",
            "concept": f"{L}.replicas-do-not-scale-writes",
            "mistake": f"{L}.replicas-for-writes",
        },
        {
            "key": "hot-key",
            "kind": "choice",
            "prompt": "One celebrity profile key is read 50,000 times per second and the Redis node holding it is saturated. What fixes it?",
            "options": [
                "Add more Redis shards so the key is spread out",
                "An in-process cache on the app servers with a short TTL, because one key always lands on one core",
                "Move the key to PostgreSQL, which handles 50,000 reads/s",
                "Increase the Redis node's memory",
            ],
            "answer": 1,
            "explanation": "Sharding routes each key to exactly one node, so a hot key stays on one core no matter how many shards exist. Only caching it inside each app server removes the traffic.",
            "section": "how-it-works",
            "concept": f"{L}.hot-key",
            "mistake": f"{L}.shard-the-hot-key",
        },
        {
            "key": "kafka-lag-idle-cpu",
            "kind": "choice",
            "prompt": "A Kafka topic has 6 partitions and 20 consumers. Lag keeps growing while consumer CPU sits at 10%. What is the limit?",
            "options": [
                "Broker disk throughput",
                "Partition count: only 6 consumers can work, the other 14 are idle",
                "Consumer memory",
                "Message size above 1 MB",
            ],
            "answer": 1,
            "explanation": "Partitions equal maximum consumer parallelism. With 6 partitions, 14 of the 20 consumers receive nothing, so lag grows while CPU stays low. Add partitions first.",
            "section": "design-decisions",
            "concept": f"{L}.partitions-cap-parallelism",
        },
        {
            "key": "big-payloads",
            "kind": "choice",
            "prompt": "An events pipeline puts 3 MB video thumbnails into Kafka messages. What does the lesson say to do?",
            "options": [
                "Raise the broker's message size limit to 10 MB",
                "Use RabbitMQ instead, which handles large messages",
                "Store the payload in object storage and send only a pointer in the message (claim check)",
                "Compress the message and keep it in Kafka",
            ],
            "answer": 2,
            "explanation": "Messages above about 1 MB degrade the broker. The claim-check pattern keeps the log fast: the blob goes to object storage and the message carries its key.",
            "section": "design-decisions",
            "concept": f"{L}.claim-check",
        },
        {
            "key": "connections-rule",
            "kind": "choice",
            "prompt": "An autoscaled fleet of 300 servers opens 8 connections each to one PostgreSQL primary. What breaks and what is the fix?",
            "options": [
                "Nothing; 2,400 connections is normal for PostgreSQL",
                "Memory and context switching at 2,400 backends; add PgBouncer or ProxySQL to pool them into 50–100 real connections",
                "Disk, because each connection writes its own log; add faster disks",
                "The replicas lag; add more replicas",
            ],
            "answer": 1,
            "explanation": "Each connection costs 5–10 MB and a process, and past about 1,000 the database spends its time switching between them. A pooler turns thousands of client connections into a small bounded set.",
            "section": "design-decisions",
            "concept": f"{L}.connection-pooling",
        },
        {
            "key": "premature-cache",
            "kind": "spot_mistake",
            "prompt": "A candidate draws Redis in front of a database serving 400 reads/s and 30 writes/s, saying 'reads are heavier than writes'. What is wrong?",
            "options": [
                "Redis cannot handle 400 reads/s",
                "The read rate never threatened one node, so the cache adds invalidation risk for no gain",
                "The cache should be Memcached, not Redis",
                "Writes should be cached instead",
            ],
            "answer": 1,
            "explanation": "One relational node is comfortable to about 5,000 reads/s. Under that, the sequence stops at 'one node is comfortable'; adding a cache anyway is the mistake interviewers notice most.",
            "section": "why-it-matters",
            "concept": f"{L}.no-cache-under-threshold",
            "mistake": f"{L}.premature-cache",
        },
        {
            "key": "ten-x-question",
            "kind": "choice",
            "prompt": "The interviewer asks 'what breaks first if traffic grows 10x?' for a system at 1,200 writes/s and 4,000 reads/s behind one primary. What is the strongest answer?",
            "options": [
                "'We would add more servers everywhere'",
                "'The primary: 12,000 writes/s is past its 3,000–5,000 comfort, so the write path shards first; reads at 40,000 get a cache'",
                "'The load balancer, because it sees all the traffic'",
                "'Nothing, cloud databases scale automatically'",
            ],
            "answer": 1,
            "explanation": "The answer names the component nearest its trigger, the number that crosses it, and the move. Writes hit the wall before reads, so sharding comes before the cache.",
            "section": "interviewer-follow-ups",
            "concept": f"{L}.what-breaks-first",
        },
        {
            "key": "queue-to-log",
            "kind": "choice",
            "prompt": "A RabbitMQ setup must fan out 80,000 msg/s to three separate consumer groups that each want to replay the last hour. Which threshold is crossed and what is the move?",
            "options": [
                "None; RabbitMQ handles 80,000 msg/s per queue",
                "Fan-out above 50,000 msg/s plus a need for replay and several consumer groups: move to a log such as Kafka",
                "Message size; switch to SQS FIFO",
                "Queue depth; add more RabbitMQ memory",
            ],
            "answer": 1,
            "explanation": "Queues ack and forget, so they cannot replay, and their per-queue throughput tops out around 10,000–40,000 msg/s. Replay, many consumer groups, and high fan-out are exactly what a log is for.",
            "section": "how-it-works",
            "concept": f"{L}.queue-vs-log",
        },
        {
            "key": "blobs-in-db",
            "kind": "choice",
            "prompt": "A photo service stores 2 MB images as rows in PostgreSQL and the database is at 3 TB with nightly backups running into the morning. Which two triggers are crossed?",
            "options": [
                "Reads above 5,000/s and writes above 3,000/s",
                "Blobs above 500 KB–1 MB in the database, and data above 2 TB on one node",
                "Connections above 1,000 and a hot key",
                "Search latency above 200 ms and heap above 31 GB",
            ],
            "answer": 1,
            "explanation": "Large blobs belong in object storage with only the URL in the database, and past about 2 TB a single node's backups and vacuum slow down. Both triggers point at moving the images out.",
            "section": "how-it-works",
            "concept": f"{L}.blobs-and-size",
        },
        {
            "key": "ticket-burst",
            "kind": "choice",
            "prompt": "A ticketing site does 800 writes/s normally but 40,000 writes/s for two minutes when a sale opens. What is the single next move?",
            "options": [
                "Shard the database 15 ways to cover the peak",
                "Buffer the burst through a log and drain it into the primary at the rate it can take",
                "Add read replicas for the sale window",
                "Raise the connection limit to 40,000",
            ],
            "answer": 1,
            "explanation": "A short burst far above the primary's comfort is what a log is for: producers write at 40,000/s, consumers drain at a few thousand, and the shape of the traffic never reaches the database. Sharding for a two-minute peak is the expensive answer.",
            "section": "mini-design-exercise",
            "concept": f"{L}.buffer-bursts",
        },
        {
            "key": "trigger-and-move",
            "kind": "choice",
            "prompt": "Per the interview tip, which sentence is the one to say?",
            "options": [
                "'We might need to scale the database at some point'",
                "'That is 20,000 writes/s, past one primary's comfort of about 3,000, so the write path shards by user id'",
                "'PostgreSQL handles 3,000 writes per second'",
                "'We should use Cassandra because it scales'",
            ],
            "answer": 1,
            "explanation": "Number, threshold, move, in one breath. The first option has no number, the third has no move, and the last has neither.",
            "section": "interview-tip",
            "concept": f"{L}.one-sentence",
        },
        {
            "key": "tradeoff-cache-replicas",
            "kind": "choice",
            "prompt": "Reads outgrow one node but every query is different and must be fresh. Which side of the cache-versus-replicas trade-off wins, and what must you watch?",
            "options": [
                "Cache, and watch the hit rate",
                "Replicas, and watch replication lag against the freshness SLA",
                "Cache, and watch memory",
                "Replicas, and watch the partition count",
            ],
            "answer": 1,
            "explanation": "Unrepeating, must-be-fresh reads make the hit rate low, so a cache buys little. Replicas serve any query, and their cost is lag, which the lesson says to check against the SLA and route around when it matters.",
            "section": "trade-offs",
            "concept": f"{L}.cache-vs-replicas",
        },
        {
            "key": "cache-outage",
            "kind": "choice",
            "prompt": "Your cache absorbs 90% of 50,000 reads/s. A common failure mode the lesson names: what happens when the cache goes down, and what protects you?",
            "options": [
                "Nothing changes; the replicas take over",
                "The database suddenly receives all 50,000 reads/s; it must survive the miss storm or be shielded by request collapsing",
                "Writes fail because the cache is write-through",
                "The load balancer removes the database",
            ],
            "answer": 1,
            "explanation": "The database only ever saw 5,000 reads/s while the cache was healthy. A cache outage sends it the full load, so plan the database for that moment or collapse duplicate misses.",
            "section": "common-mistakes",
            "concept": f"{L}.cache-outage",
        },
    ]
}
