"""Pilot questions: caching, rate limiting, consistent hashing, replication."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "caching": [
        {
            "key": "hit-ratio-arithmetic",
            "kind": "choice",
            "prompt": "Your API receives 10,000 requests per second and the cache hit ratio is 95%. Roughly how many requests per second still reach the database?",
            "options": ["500", "5,000", "9,500", "It depends on the TTL"],
            "answer": 0,
            "explanation": "Origin load is requests × (1 − hit ratio): 10,000 × 0.05 = 500. Saying this arithmetic out loud is what turns 'add a cache' into a justified decision.",
            "section": "mental-model",
            "concept": "caching.hit-ratio-arithmetic",
        },
        {
            "key": "write-path",
            "kind": "choice",
            "prompt": "You use cache-aside. A row is updated in the database. What should the write path do with the cached copy?",
            "options": [
                "Delete the cached entry",
                "Write the new value into the cache",
                "Extend its TTL so it expires sooner",
                "Nothing, the TTL takes care of it",
            ],
            "answer": 0,
            "explanation": "Delete on write. Writing the new value into the cache races with a concurrent miss-fill and can leave a stale value cached indefinitely; a delete makes the next read fetch fresh data.",
            "section": "common-mistakes",
            "concept": "caching.write-policy",
            "mistake": "caching.update-cache-on-write",
        },
        {
            "key": "db-sizing",
            "kind": "spot_mistake",
            "prompt": "A design puts Redis in front of the database and sizes the database for the traffic that reaches it at a 95% hit rate. What is wrong?",
            "options": [
                "Nothing, that is the point of the cache",
                "A cache outage becomes a total outage, because the database cannot take the full load",
                "Redis should be replaced by Memcached",
                "The hit rate should be 99% before sizing anything",
            ],
            "answer": 1,
            "explanation": "Size the database to survive a cache outage. Otherwise the cache is a single point of failure in disguise: the day it is cold or down, twenty times the load lands on a database built for one twentieth of it.",
            "section": "common-mistakes",
            "concept": "caching.db-sized-for-outage",
            "mistake": "caching.db-sized-for-cached-load",
        },
        {
            "key": "worst-candidate",
            "kind": "choice",
            "prompt": "Which of these is the worst candidate for caching?",
            "options": [
                "A product record read a million times a day",
                "A rendered feed that costs 200 ms to build",
                "A per-user permission check that must reflect a revocation immediately",
                "The target URL of a short link",
            ],
            "answer": 2,
            "explanation": "A cached authorisation decision that outlives a permission revocation is a security bug, not a performance win. The other three are hot, expensive or immutable, which is exactly what caches are for.",
            "section": "trade-offs",
            "concept": "caching.when-not-to-cache",
            "mistake": "caching.stale-authorisation",
        },
        {
            "key": "stampede",
            "kind": "short_answer",
            "prompt": "A hot key expires, thousands of concurrent requests all miss at once, and they hit the database together. What is this failure called, and name one fix.",
            "options": [],
            "answer": None,
            "model_answer": "A cache stampede (thundering herd). Fixes: request coalescing so only one request rebuilds the value while the others wait, a short lock on the key, or refreshing the value before it expires with jittered TTLs.",
            "explanation": "The failure is the stampede; every fix works by making sure only one request pays for the rebuild.",
            "section": "common-failure-modes",
            "concept": "caching.stampede",
        },
        {
            "key": "write-behind-counter",
            "kind": "choice",
            "prompt": "A video's view counter is incremented far more often than it is read, and losing a few seconds of increments is acceptable. Which pattern fits, and why must it never be used for an account balance?",
            "options": [
                "Write-through; it is too slow for money",
                "Write-behind; acknowledged writes can be lost if the cache dies before the flush",
                "Refresh-ahead; it guesses wrong about what is hot",
                "Cache-aside; the first read after a write always misses",
            ],
            "answer": 1,
            "explanation": "Write-behind acknowledges from the cache and flushes to the database later, so it absorbs write spikes at the cost of real data loss risk. That is fine for counters and metrics and never for money.",
            "section": "how-it-works",
            "concept": "caching.write-policy",
            "mistake": "caching.write-behind-for-money",
        },
        {
            "key": "negative-caching",
            "kind": "choice",
            "prompt": "A flood of requests arrives for product ids that do not exist. Every one misses the cache and reaches the database. Which design decision fixes this?",
            "options": [
                "Raise the TTL on the keys that do exist",
                "Cache 'not found' for a short TTL, or reject impossible keys with a Bloom filter",
                "Switch from Redis to Memcached for lower latency",
                "Move to write-through so every key is always warm",
            ],
            "answer": 1,
            "explanation": "This is cache penetration, and it is how penetration attacks work. Negative caching or a Bloom filter stops non-existent keys from passing straight through to the database on every request.",
            "section": "design-decisions",
            "concept": "caching.penetration",
            "mistake": "caching.no-negative-caching",
        },
        {
            "key": "why-redis",
            "kind": "choice",
            "prompt": "The interviewer asks 'why Redis rather than Memcached?'. Which answer does the lesson call the honest one?",
            "options": [
                "Because Redis is faster",
                "Its data structures and atomic operations solve adjacent problems too, so one component replaces three",
                "Because Memcached cannot store strings larger than a page",
                "Because Redis uses less memory per key",
            ],
            "answer": 1,
            "explanation": "Memcached is simpler, multi-threaded and purely a cache. Redis is chosen for sorted sets, atomic counters, persistence and replication, and one operational component is better than three. 'Because it is fast' is the answer to avoid.",
            "section": "design-decisions",
            "concept": "caching.redis-vs-memcached",
            "mistake": "caching.redis-because-fast",
        },
    ],
    "rate-limiting": [
        {
            "key": "fixed-window-boundary",
            "kind": "choice",
            "prompt": "The limit is 100 requests per minute. A client sends 100 requests at 11:59:59 and 100 more at 12:00:00. Which algorithm lets both bursts through?",
            "options": ["Fixed window", "Token bucket", "Sliding window log", "Leaky bucket"],
            "answer": 0,
            "explanation": "A fixed window resets at the boundary, so 200 requests pass in one second without ever breaking the stated per-minute limit. Sliding windows and token buckets do not have this flaw.",
            "section": "how-it-works",
            "concept": "rate-limiting.algorithm-choice",
            "mistake": "rate-limiting.fixed-window-boundary",
        },
        {
            "key": "per-node-counters",
            "kind": "spot_mistake",
            "prompt": "Ten gateway nodes each keep an in-memory counter enforcing 100 requests per minute per API key. What actually happens?",
            "options": [
                "The limit is enforced correctly",
                "A client can make about 1,000 requests per minute",
                "Requests are rejected too early",
                "Only one node does any limiting",
            ],
            "answer": 1,
            "explanation": "Per-node counters multiply the limit by the node count. The count must be shared (Redis with an atomic script) or each node must be given a budget of the global limit.",
            "section": "common-failure-modes",
            "concept": "rate-limiting.distributed-counting",
            "mistake": "rate-limiting.per-node-counters",
        },
        {
            "key": "reject-response",
            "kind": "choice",
            "prompt": "A request is over the limit. What should the API return?",
            "options": [
                "Drop the connection silently",
                "200 with an empty body",
                "429 with Retry-After and limit headers",
                "500",
            ],
            "answer": 2,
            "explanation": "429 with Retry-After tells a well-behaved client when to come back. Silent drops and errors cause tight retry loops that make the overload worse.",
            "section": "common-mistakes",
            "concept": "rate-limiting.reject-response",
            "mistake": "rate-limiting.no-retry-after",
        },
        {
            "key": "store-failure",
            "kind": "choice",
            "prompt": "The Redis that holds the counters goes down. Which behaviour does the lesson recommend?",
            "options": [
                "Fail open: allow everything",
                "Fail closed: reject everything",
                "Fall back to conservative local per-node limits",
                "Queue every request until Redis is back",
            ],
            "answer": 2,
            "explanation": "Fail open removes protection exactly when it is needed; fail closed turns a cache outage into an API outage. A conservative local limit on each node keeps some protection and some availability.",
            "section": "trade-offs",
            "concept": "rate-limiting.limiter-failure",
            "mistake": "rate-limiting.silent-fail-open",
        },
        {
            "key": "token-bucket-burst",
            "kind": "choice",
            "prompt": "A token bucket has capacity 20 and refills at 100 tokens per minute. After a long idle period, how many requests can a client send at once?",
            "options": ["100", "20", "120", "1"],
            "answer": 1,
            "explanation": "The bucket holds at most its capacity, so the burst is 20. The refill rate then decides how quickly tokens come back; the two parameters map directly onto '100 per minute with a burst of 20'.",
            "section": "how-it-works",
            "concept": "rate-limiting.token-bucket",
        },
        {
            "key": "anonymous-key",
            "kind": "choice",
            "prompt": "You must rate limit unauthenticated traffic. Which key does the lesson say to use, and what is its pitfall?",
            "options": [
                "IP, with generous limits: corporate and carrier NAT put thousands of users behind one address",
                "User id, after forcing every visitor to sign up",
                "A random cookie set on the first request",
                "Tenant id resolved from the request path",
            ],
            "answer": 0,
            "explanation": "The key is the first of the three decisions in the mental model. For anonymous traffic IP is the only option, and it is blunt, so combine it with other signals and keep the limits generous.",
            "section": "mental-model",
            "concept": "rate-limiting.key-choice",
            "mistake": "rate-limiting.strict-ip-limits-behind-nat",
        },
        {
            "key": "limiter-after-expensive-work",
            "kind": "spot_mistake",
            "prompt": "The limiter runs inside the application after the token has been validated against the database and the user's plan loaded. What is wrong?",
            "options": [
                "It has already spent what it protects; enforce at the edge after the cheapest identity check, a local token verify",
                "Nothing; you need the plan before you know the limit",
                "It should run after the response so it can count bytes",
                "The database lookup only needs a cache, then it is fine",
            ],
            "answer": 0,
            "explanation": "A limiter behind authentication and database lookups protects nothing. Enforce at the edge, and if the limit depends on identity, verify a signed token locally rather than doing a database lookup.",
            "section": "how-it-works",
            "concept": "rate-limiting.where-to-enforce",
            "mistake": "rate-limiting.limiter-behind-expensive-work",
        },
        {
            "key": "per-endpoint-limits",
            "kind": "choice",
            "prompt": "One global limit of 1,000 requests a minute applies to every endpoint, including password reset and report export. What does the lesson recommend instead?",
            "options": [
                "Per-endpoint, cost-weighted limits, for example a cost-unit system where expensive endpoints deduct more tokens",
                "A stricter global limit, such as 100 a minute",
                "Rate limiting only for authenticated users",
                "Moving the limit into each service so it can decide locally",
            ],
            "answer": 0,
            "explanation": "One global limit is a blunt instrument. A read endpoint at 1,000 a minute, a search at 100 and a password reset at 5 an hour are different things, so weight limits by endpoint cost.",
            "section": "design-decisions",
            "concept": "rate-limiting.per-endpoint-limits",
            "mistake": "rate-limiting.one-limit-for-everything",
        },
    ],
    "sd-consistent-hashing": [
        {
            "key": "modulo-vs-ring",
            "kind": "choice",
            "prompt": "A cache tier grows from 10 nodes to 11. About what fraction of keys move under modulo hashing, and under consistent hashing?",
            "options": [
                "Both about 1 in 11",
                "Modulo: nearly all of them. Consistent: about 1 in 11",
                "Modulo: about 1 in 11. Consistent: nearly all of them",
                "Both nearly all of them",
            ],
            "answer": 1,
            "explanation": "Changing N in hash(key) mod N changes the result for almost every key. On the ring a new node only takes the arc between it and its predecessor, about 1/N of the keys.",
            "section": "mental-model",
            "concept": "consistent-hashing.minimal-movement",
        },
        {
            "key": "virtual-nodes",
            "kind": "choice",
            "prompt": "Why are virtual nodes needed in practice?",
            "options": [
                "They make lookups faster",
                "They even out load and spread a failed node's keys across many successors",
                "They remove the need for replication",
                "They prevent cache misses during membership changes",
            ],
            "answer": 1,
            "explanation": "With a few nodes the arcs are wildly uneven, and a failed node dumps its whole load on one successor. Hashing each node onto the ring hundreds of times fixes both.",
            "section": "how-it-works",
            "concept": "consistent-hashing.virtual-nodes",
            "mistake": "consistent-hashing.no-virtual-nodes",
        },
        {
            "key": "hot-key",
            "kind": "spot_mistake",
            "prompt": "A candidate says: 'One celebrity's profile gets 30% of all reads, so I will use consistent hashing to spread that load.' What is wrong?",
            "options": [
                "Nothing, that is exactly what it is for",
                "A single key always maps to one node, so consistent hashing does nothing for a hot key",
                "Consistent hashing only works for writes",
                "The ring would need more than 2^32 positions",
            ],
            "answer": 1,
            "explanation": "Consistent hashing balances many keys across nodes; one key is still one key on one node. A hot key needs a local cache in front of the tier or key splitting.",
            "section": "trade-offs",
            "concept": "consistent-hashing.hot-key",
            "mistake": "consistent-hashing.hot-key-fix",
        },
        {
            "key": "membership-view",
            "kind": "choice",
            "prompt": "During a membership change, two clients disagree about which node owns a key and write to different nodes. What is the underlying cause?",
            "options": [
                "Hash collisions",
                "The clients hold inconsistent views of ring membership",
                "Too many virtual nodes",
                "The clients use different hash functions",
            ],
            "answer": 1,
            "explanation": "Every client must agree on who is on the ring. That agreement comes from a coordination service or gossip, and it is the part of the design candidates most often forget to mention.",
            "section": "common-failure-modes",
            "concept": "consistent-hashing.membership",
            "mistake": "consistent-hashing.membership-ignored",
        },
        {
            "key": "replicas-on-ring",
            "kind": "short_answer",
            "prompt": "In a Dynamo-style store, how are the replicas for a key chosen on the ring?",
            "options": [],
            "answer": None,
            "model_answer": "Walk clockwise from the key's position and take the first R distinct physical nodes. That preference list needs no separate placement system and any client can compute it.",
            "explanation": "Replication falls out of the ring for free, which is why the design is so common in key-value stores.",
            "section": "how-it-works",
            "concept": "consistent-hashing.replication",
        },
        {
            "key": "no-misses-claim",
            "kind": "spot_mistake",
            "prompt": "A candidate says: 'With consistent hashing, adding a cache node causes no misses, because keys do not move.' What is wrong?",
            "options": [
                "About 1/(N+1) of keys still move and miss at once, so you still need request coalescing and a concurrency limit",
                "Nothing, that is the point of consistent hashing",
                "Keys move only if virtual nodes are used",
                "Misses happen only on node removal, never on addition",
            ],
            "answer": 0,
            "explanation": "Consistent hashing reduces movement to about 1/N of keys; it does not eliminate it. Even 10% of keys missing simultaneously is a large, sudden load increase on the origin, which is why the miss storm still needs handling.",
            "section": "common-mistakes",
            "concept": "consistent-hashing.minimal-movement",
            "mistake": "consistent-hashing.eliminates-misses",
        },
        {
            "key": "heterogeneous-nodes",
            "kind": "choice",
            "prompt": "One cache machine has twice the memory of the others. How do you give it twice the share of keys on the ring?",
            "options": [
                "Give it twice as many virtual nodes",
                "Hash its name twice per lookup",
                "Place it first on the ring",
                "Use modulo hashing for that node only",
            ],
            "answer": 0,
            "explanation": "Each physical node is hashed onto the ring many times, so weighting is just a count: a machine with twice the capacity gets twice as many virtual nodes and owns about twice as much of the ring.",
            "section": "how-it-works",
            "concept": "consistent-hashing.virtual-nodes",
        },
        {
            "key": "ring-vs-slot-map",
            "kind": "choice",
            "prompt": "You operate your own sharded store and want to move one hot partition onto a bigger machine deliberately. Does the lesson recommend a literal ring or a fixed slot map, and why?",
            "options": [
                "A fixed slot map: placement is explicit and auditable, and rebalancing is deliberate",
                "A literal ring: placement is automatic and needs no operator",
                "Neither; use modulo hashing",
                "A ring with many more virtual nodes",
            ],
            "answer": 0,
            "explanation": "A ring places automatically; a slot map (as in Redis Cluster's 16,384 slots) keeps the same indirection between hash and machine while letting you choose where a hot partition lives. Operationally the slot map is usually preferable.",
            "section": "trade-offs",
            "concept": "consistent-hashing.slot-map",
        },
    ],
    "replication": [
        {
            "key": "what-it-gives",
            "kind": "choice",
            "prompt": "Which of these does replication give you?",
            "options": [
                "More write throughput",
                "A backup you can restore after a bad DELETE",
                "Read scaling and survival of a node loss",
                "Strong consistency across regions",
            ],
            "answer": 2,
            "explanation": "Replicas take reads and stand in when the primary dies. Every write still goes through the primary, and a destructive statement replicates perfectly, so replication is not a backup.",
            "section": "mental-model",
            "concept": "replication.what-it-does",
            "mistake": "replication.confused-with-backup",
        },
        {
            "key": "async-loss",
            "kind": "choice",
            "prompt": "With asynchronous replication, the primary crashes right after acknowledging a write. What can happen to that write?",
            "options": [
                "Nothing, it was acknowledged",
                "It can be lost if no replica received it before the crash",
                "It is replayed automatically after failover",
                "It becomes a write conflict",
            ],
            "answer": 1,
            "explanation": "Asynchronous means the primary acknowledges before shipping the change. If it dies first, the promoted replica never saw the write. Quantify that window per data type; for money, use semi-synchronous or synchronous.",
            "section": "how-it-works",
            "concept": "replication.sync-vs-async",
        },
        {
            "key": "read-your-writes",
            "kind": "spot_mistake",
            "prompt": "A user updates their profile, reloads the page, and sees the old value because the page read from a replica. What is this, and what is a standard fix?",
            "options": [
                "A hash collision; retry the read",
                "A read-your-writes anomaly; serve that user's own recent writes from the primary, or pin their session to the primary for a short window",
                "Split brain; fence the old primary",
                "Cascading failure; add another replica",
            ],
            "answer": 1,
            "explanation": "Replication lag means the replica has not seen the write yet. Read-your-writes is one of the three lag anomalies with a standard fix; the others are monotonic reads and consistent prefix.",
            "section": "common-failure-modes",
            "concept": "replication.lag-anomalies",
            "mistake": "replication.no-read-your-writes",
        },
        {
            "key": "split-brain",
            "kind": "choice",
            "prompt": "During failover a network partition leaves two nodes both believing they are the primary. What prevents this?",
            "options": [
                "A larger replication log",
                "Quorum, leases or fencing, so only one node can accept writes",
                "Synchronous replication",
                "Reading from replicas",
            ],
            "answer": 1,
            "explanation": "Failover design is incomplete without a split-brain guard. A quorum decides who is primary, a lease expires so an isolated primary stops accepting writes, and fencing cuts the old primary off from storage.",
            "section": "common-failure-modes",
            "concept": "replication.split-brain",
            "mistake": "replication.split-brain-ignored",
        },
        {
            "key": "mode-for-money",
            "kind": "choice",
            "prompt": "For a payments ledger, which replication mode is the defensible default?",
            "options": ["Asynchronous", "Semi-synchronous or synchronous", "Multi-leader", "Leaderless with a write quorum of one"],
            "answer": 1,
            "explanation": "Money must not lose acknowledged writes on failover, so wait for at least one replica. Asynchronous is fine for a social feed, and saying why is the depth signal.",
            "section": "how-it-works",
            "concept": "replication.sync-vs-async",
        },
        {
            "key": "which-reads-primary",
            "kind": "choice",
            "prompt": "An e-commerce site has one primary and three asynchronous replicas with about 200 ms of lag. Which of these reads should stay on the primary?",
            "options": [
                "A product page",
                "A category listing",
                "The shopping cart after the user adds an item",
                "A nightly analytics report",
            ],
            "answer": 2,
            "explanation": "Default reads to replicas and make the exceptions explicit. The price was the same 200 ms ago, but a user adding an item and not seeing it is an immediate, obvious bug. Analytics belongs on a dedicated replica so it cannot slow production reads.",
            "section": "design-decisions",
            "concept": "replication.read-routing",
            "mistake": "replication.replicas-instantly-consistent",
        },
        {
            "key": "fast-failover-cost",
            "kind": "choice",
            "prompt": "To recover quickly, a team sets the failover health-check timeout very short. What trade-off does the lesson warn about?",
            "options": [
                "Reads become slower on every replica",
                "A transient network blip can trigger a promotion, which is its own incident",
                "Replication lag grows because the primary is busier",
                "Multi-leader write conflicts start to appear",
            ],
            "answer": 1,
            "explanation": "Fast failover versus false failover: aggressive detection recovers quickly and risks promoting during a blip. Detection needs a timeout long enough to avoid reacting to noise.",
            "section": "trade-offs",
            "concept": "replication.failover-detection",
        },
        {
            "key": "replicas-for-writes",
            "kind": "spot_mistake",
            "prompt": "A design says: 'Writes are becoming the bottleneck, so we will add three more read replicas.' What is wrong?",
            "options": [
                "Replicas do not scale writes; every write still goes through the primary, and each replica adds replication load to it",
                "Three is too few; five is the minimum",
                "The new replicas must be synchronous to help",
                "Nothing; more replicas absorb more of every kind of load",
            ],
            "answer": 0,
            "explanation": "Replication scales reads only. Write scaling is vertical first, then sharding, then multi-leader with conflict resolution. Expecting replicas to help write throughput is a listed mistake.",
            "section": "common-mistakes",
            "concept": "replication.what-it-does",
            "mistake": "replication.replicas-scale-writes",
        },
    ],
}
