"""Knowledge checks: fundamentals, HTTP/TLS, CDN, distributed systems, observability, batch and stream, news feed, Dropbox, metrics platform."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "system-design-fundamentals": [
        {
            "key": "what-is-architecture",
            "kind": "choice",
            "prompt": "The lesson defines architecture as the set of decisions that are expensive to change later. Which of these is an architecture decision by that definition?",
            "options": [
                "Which HTTP client library the service uses",
                "Which database the system is built on",
                "The name of a helper function",
                "The indentation style of the codebase",
            ],
            "answer": 1,
            "explanation": "Swapping a database means migrating data and rewriting access patterns, so it is expensive to change later. A library, a function name or a code style can be changed in an afternoon.",
            "section": "mental-model",
            "concept": "system-design-fundamentals.architecture-definition",
            "mistake": "system-design-fundamentals.architecture-as-component-selection",
        },
        {
            "key": "start-simple",
            "kind": "choice",
            "prompt": "An internal tool takes 40 writes per second. A candidate's first diagram already has a queue, a cache and a second region. By the lesson's method, what should the first design have been?",
            "options": [
                "One service and one database, adding components only when a stated number forces them",
                "The same diagram, since it is safer to over-build",
                "A sharded database, because writes always grow",
                "A CDN and a load balancer, since every system needs both",
            ],
            "answer": 0,
            "explanation": "Begin with the smallest system that meets the requirements, say so, and let the numbers push you. At 40 writes per second one service and one database is genuinely fine; each added arrow must be justified by a number.",
            "section": "how-it-works",
            "concept": "system-design-fundamentals.start-simple",
            "mistake": "system-design-fundamentals.unjustified-components",
        },
        {
            "key": "component-justification",
            "kind": "choice",
            "prompt": "Reads far exceed what one primary can serve, and a little lag is acceptable. Which component does the lesson's table say this justifies?",
            "options": ["Read replica", "Shards", "Queue", "Search index"],
            "answer": 0,
            "explanation": "Replicas take reads that exceed one primary, at the cost of lag. Shards are for data or write volume beyond one machine, a queue is for slow or bursty work, and a search index is for query patterns the primary store cannot serve.",
            "section": "how-it-works",
            "concept": "system-design-fundamentals.component-reasons",
        },
        {
            "key": "reliability-vs-availability",
            "kind": "choice",
            "prompt": "A service answers every request within 50 ms, but 2% of the responses contain wrong totals. Which property is it failing?",
            "options": ["Availability", "Reliability", "Durability", "Throughput"],
            "answer": 1,
            "explanation": "Availability is whether it responds; reliability is whether it responds correctly; durability is whether committed data survives. Responding fast with wrong answers is a reliability failure, and mixing these terms up is a listed mistake.",
            "section": "common-mistakes",
            "concept": "system-design-fundamentals.vocabulary",
            "mistake": "system-design-fundamentals.availability-reliability-confused",
        },
        {
            "key": "async-cost",
            "kind": "choice",
            "prompt": "You move image processing off the request path onto a queue. According to the lesson's trade-off table, what do you now pay for the throughput and spike absorption you gained?",
            "options": [
                "Eventual results, duplicate handling and more to operate",
                "Slower reads because of extra joins",
                "Staleness and invalidation complexity",
                "Loss of fault isolation",
            ],
            "answer": 0,
            "explanation": "Async buys throughput, spike absorption and isolation; it costs eventual results, duplicate handling and operational burden. Staleness is the cache trade-off and joins belong to normalisation.",
            "section": "trade-offs",
            "concept": "system-design-fundamentals.six-trade-offs",
        },
        {
            "key": "correlated-replicas",
            "kind": "spot_mistake",
            "prompt": "A design doc says: 'We run three replicas, so a single failure cannot take us down.' All three sit in one availability zone and were deployed from the same build. What is wrong?",
            "options": [
                "Nothing, three replicas is the standard number",
                "They share a zone and a deploy, so one event can take all three down: correlated failure",
                "Three replicas cannot scale reads",
                "Replicas only protect durability, not availability",
            ],
            "answer": 1,
            "explanation": "Three replicas means nothing if they share a rack, zone or deploy. A zone outage or a bad build hits all of them at once, which is the correlated failure mode the lesson warns about.",
            "section": "common-failure-modes",
            "concept": "system-design-fundamentals.correlated-failure",
            "mistake": "system-design-fundamentals.replicas-in-one-failure-domain",
        },
        {
            "key": "cascade",
            "kind": "short_answer",
            "prompt": "A slow dependency triggers retries, the retries add load, and the dependency gets slower still. What kind of failure is this, and why does the lesson say systems usually fall over this way?",
            "options": [],
            "answer": None,
            "model_answer": "A cascading failure driven by a feedback loop. Systems usually fall over from feedback loops like retries amplifying load, not from a single dead machine, because each step makes the next one worse.",
            "explanation": "The loop is the failure: slowness causes retries, retries cause load, load causes slowness. Recognising the loop is what separates a fix from a bigger machine.",
            "section": "common-failure-modes",
            "concept": "system-design-fundamentals.cascading-failure",
        },
        {
            "key": "average-latency",
            "kind": "choice",
            "prompt": "A candidate reports 'average latency is 80 ms' for a service. Why does the lesson count this as a mistake?",
            "options": [
                "The mean hides the tail; latency should be quoted as a percentile such as p95 or p99",
                "80 ms is too slow for any API",
                "Latency should be reported as throughput instead",
                "Averages are only valid for write requests",
            ],
            "answer": 0,
            "explanation": "Latency is the time for one operation and must always be quoted as a percentile. A mean of 80 ms can hide a p99 of several seconds, which is what users actually notice.",
            "section": "common-mistakes",
            "concept": "system-design-fundamentals.vocabulary",
            "mistake": "system-design-fundamentals.mean-latency",
        },
    ],
    "sd-http-tls": [
        {
            "key": "round-trip-floor",
            "kind": "choice",
            "prompt": "Round trip to the origin is 150 ms. A cold HTTPS request over TLS 1.2 needs a TCP handshake and a TLS handshake before the request is sent. What is the latency floor before your server does any work?",
            "options": ["450 ms", "150 ms", "300 ms", "600 ms"],
            "answer": 0,
            "explanation": "TCP costs one round trip and TLS 1.2 costs two, so three round trips at 150 ms is 450 ms before the request itself even leaves. The request and response add a fourth round trip on top.",
            "section": "mental-model",
            "concept": "sd-http-tls.round-trips",
            "mistake": "sd-http-tls.tls-is-free",
        },
        {
            "key": "edge-termination-arithmetic",
            "kind": "short_answer",
            "prompt": "Users in Sydney call an API in Virginia at a 200 ms round trip. In your own words, explain why an edge POP in Sydney that terminates TLS makes the request nearly four times faster even though the backend is unchanged.",
            "options": [],
            "answer": None,
            "model_answer": "The TCP and TLS handshake round trips now happen against the nearby edge at about 5 ms each instead of 200 ms. The edge keeps a warm keep-alive connection to Virginia, so only the actual request crosses the Pacific. Roughly 800 ms becomes about 210 ms.",
            "explanation": "The handshakes are pure round trips with no backend work, so moving them next to the user removes almost all of them. The one long hop that remains is the real request.",
            "section": "mental-model",
            "concept": "sd-http-tls.edge-termination",
        },
        {
            "key": "http2-stalls",
            "kind": "choice",
            "prompt": "Mobile users on a lossy network see sporadic multi-second stalls even though their requests are multiplexed over HTTP/2. What explains it?",
            "options": [
                "HTTP/2 still runs on TCP, so one lost segment stalls every multiplexed stream",
                "HTTP/2 allows only one request per connection at a time",
                "HPACK header compression fails on lossy links",
                "TLS 1.3 re-handshakes after each lost packet",
            ],
            "answer": 0,
            "explanation": "HTTP/2 removed application-level head-of-line blocking but not transport-level. QUIC in HTTP/3 lets a lost packet stall only its own stream, which is why it helps lossy mobile networks most.",
            "section": "how-it-works",
            "concept": "sd-http-tls.head-of-line-blocking",
            "mistake": "sd-http-tls.http2-eliminated-hol",
        },
        {
            "key": "safe-retry",
            "kind": "choice",
            "prompt": "A request times out and the client wants to retry automatically. Which of these is safe to retry without an idempotency key?",
            "options": [
                "PUT /accounts/42/address with the full new address",
                "POST /payments creating a new charge",
                "PATCH /orders/9 adding one item",
                "None of them, retries are never safe",
            ],
            "answer": 0,
            "explanation": "PUT is idempotent by definition, so repeating it leaves the same state. POST is not idempotent and needs an idempotency key, and PATCH is not necessarily idempotent.",
            "section": "how-it-works",
            "concept": "sd-http-tls.idempotent-methods",
            "mistake": "sd-http-tls.retry-post-without-key",
        },
        {
            "key": "regulated-edge-termination",
            "kind": "choice",
            "prompt": "Your product handles regulated health data. The team wants to terminate TLS at a CDN edge for latency. What does the lesson say this costs, and what is the usual answer?",
            "options": [
                "The edge provider sees plaintext; regulated workloads may need passthrough or re-encryption with mTLS internally",
                "Certificates must be renewed twice as often",
                "Keep-alive stops working past the edge",
                "Nothing, edge termination is always free",
            ],
            "answer": 0,
            "explanation": "Everything behind the termination point is plaintext unless you re-encrypt. Edge termination is faster and enables caching and routing, but a regulated threat model may require passthrough or mTLS to the origin.",
            "section": "trade-offs",
            "concept": "sd-http-tls.termination-point",
        },
        {
            "key": "timeout-from-mean",
            "kind": "choice",
            "prompt": "You set a service-to-service timeout equal to the downstream's mean latency of 40 ms. What does the lesson predict?",
            "options": [
                "Many slow but healthy requests fail spuriously; tune the timeout from the p99 instead",
                "The connection pool exhausts because 40 ms is too long",
                "Nothing changes, the mean is the right basis",
                "Retries become idempotent",
            ],
            "answer": 0,
            "explanation": "Short timeouts protect the pool but cause false failures on slow-but-healthy requests. The lesson says to tune from the p99, not the mean.",
            "section": "trade-offs",
            "concept": "sd-http-tls.timeouts",
        },
        {
            "key": "pool-exhaustion",
            "kind": "spot_mistake",
            "prompt": "An endpoint that never calls the recommendation service starts failing when that service becomes slow. The engineer says the two are unrelated. What is actually happening?",
            "options": [
                "The slow service holds connections, the shared pool empties, and unrelated requests cannot get one",
                "The recommendation service's certificate expired",
                "HTTP/3 fallback is disabled",
                "DNS caching is returning the wrong address",
            ],
            "answer": 0,
            "explanation": "Connection pool exhaustion is one of the most common production incidents: one slow dependency pins connections, the pool empties, and endpoints that do not even use it start failing.",
            "section": "common-failure-modes",
            "concept": "sd-http-tls.pool-exhaustion",
            "mistake": "sd-http-tls.pool-failures-look-unrelated",
        },
        {
            "key": "no-read-timeout",
            "kind": "choice",
            "prompt": "A client library ships with its default, effectively infinite, timeouts. A dependency hangs. What does the lesson say happens?",
            "options": [
                "Each hung call pins a thread forever, and enough of them take the whole process down",
                "The request is retried automatically after 30 seconds",
                "The connection falls back to HTTP/1.1",
                "Nothing, the TCP handshake times out instead",
            ],
            "answer": 0,
            "explanation": "A missing read timeout means one hung dependency can occupy a thread until the process dies. Set separate connect, read and total timeouts.",
            "section": "common-mistakes",
            "concept": "sd-http-tls.timeouts",
            "mistake": "sd-http-tls.default-infinite-timeouts",
        },
    ],
    "sd-cdn": [
        {
            "key": "two-reasons",
            "kind": "choice",
            "prompt": "You put a CDN in front of a video product. The lesson says the interviewer wants two reasons. Which pair?",
            "options": [
                "Lower latency from proximity, and origin offload so your fleet does not serve the egress",
                "Stronger consistency and cheaper databases",
                "Faster writes and simpler invalidation",
                "Lower latency and end-to-end encryption",
            ],
            "answer": 0,
            "explanation": "A CDN buys both latency (a nearby edge instead of a distant origin) and capacity (offload, ideally above 95% for static content). Say both; the offload ratio is the number that matters.",
            "section": "mental-model",
            "concept": "sd-cdn.latency-and-offload",
        },
        {
            "key": "vary-user-agent",
            "kind": "choice",
            "prompt": "A team sets Vary: User-Agent on product images so different devices get different sizes. What happens to the edge hit rate?",
            "options": [
                "It collapses, because each object splits into hundreds of cached copies",
                "It improves, because each device gets a tailored copy",
                "Nothing, Vary only affects browsers",
                "It halves, one copy for mobile and one for desktop",
            ],
            "answer": 0,
            "explanation": "Vary on a high-cardinality header fragments the cache into hundreds of variants. Vary: Accept-Encoding is fine; anything high-cardinality ruins hit rates.",
            "section": "how-it-works",
            "concept": "sd-cdn.vary",
            "mistake": "sd-cdn.high-cardinality-vary",
        },
        {
            "key": "stale-if-error",
            "kind": "short_answer",
            "prompt": "Your origin goes down for ten minutes. Explain what users see if the CDN is configured with stale-if-error, and what they see without it.",
            "options": [],
            "answer": None,
            "model_answer": "With stale-if-error the edge keeps serving its cached copy, so cached pages keep working and only uncached paths fail. Without it, misses and revalidations fail and users see errors. The directive turns the CDN into an availability mechanism, not only a latency one.",
            "explanation": "This is a cheap and under-used availability win, and it is the standard answer to 'your origin is down, what do users see?'",
            "section": "how-it-works",
            "concept": "sd-cdn.stale-if-error",
        },
        {
            "key": "personalised-strip",
            "kind": "choice",
            "prompt": "A page is identical for everyone except a 'recommended for you' strip. Which approach keeps the page cacheable at the edge?",
            "options": [
                "Cache the shell at the edge and have the client fetch the personalised strip after page load",
                "Key the shared cache by user id so every user gets their own copy",
                "Mark the whole page private, no-store",
                "Vary the page on the session cookie",
            ],
            "answer": 0,
            "explanation": "Compose personalisation client-side or at the edge so the cacheable majority stays cached. Never key a shared cache on a user id: that is not a cache, it is a distributed storage bill.",
            "section": "how-it-works",
            "concept": "sd-cdn.personalisation",
            "mistake": "sd-cdn.cache-keyed-by-user",
        },
        {
            "key": "push-for-launch",
            "kind": "choice",
            "prompt": "A game studio releases a 40 GB patch at a fixed time to millions of players. Push or pull, and why?",
            "options": [
                "Push: pre-position the files so a million simultaneous first-misses do not hit the origin",
                "Pull: the first player in each region fetches it, which is fine",
                "Pull with a TTL of zero so everyone gets the freshest bytes",
                "Neither, patches should be served from the origin directly",
            ],
            "answer": 0,
            "explanation": "Pull is the default because it is simple and self-managing, but a predictable large launch is exactly the case for push. Otherwise the first second of the launch is a self-inflicted stampede on the origin.",
            "section": "design-decisions",
            "concept": "sd-cdn.push-vs-pull",
        },
        {
            "key": "tag-purge",
            "kind": "choice",
            "prompt": "Product pages are cached at the edge for 24 hours to maximise offload. Prices change several times a day. What does the lesson say resolves this without giving up offload?",
            "options": [
                "Tag responses with the product id and purge by tag when a price changes",
                "Drop the TTL to zero",
                "Vary the page on a price header",
                "Serve product pages from the origin only",
            ],
            "answer": 0,
            "explanation": "Freshness versus offload is the core CDN trade-off, and tag-based purging mostly resolves it at the cost of bookkeeping. Versioned URLs are better still when the URL can change; a TTL of zero quietly turns the CDN into an expensive proxy.",
            "section": "trade-offs",
            "concept": "sd-cdn.invalidation",
        },
        {
            "key": "cached-private-response",
            "kind": "spot_mistake",
            "prompt": "A team caches every GET at the edge for 60 seconds, including /account, which returns the logged-in user's details with a Set-Cookie header. What is wrong?",
            "options": [
                "One user's authenticated response can be served to another user; it must be private, no-store",
                "Nothing, 60 seconds is short enough to be safe",
                "The TTL should use s-maxage instead of max-age",
                "Only Vary: Accept-Encoding is missing",
            ],
            "answer": 0,
            "explanation": "Caching an authenticated response or a Set-Cookie at the edge is a serious, recurring incident: the next visitor gets someone else's account. Personal responses are marked private, no-store and routed to the origin.",
            "section": "common-failure-modes",
            "concept": "sd-cdn.caching-private",
            "mistake": "sd-cdn.cache-authenticated-responses",
        },
        {
            "key": "purge-not-instant",
            "kind": "choice",
            "prompt": "An editor fixes a factual error and the plan is to purge the article URL so the fix is live everywhere within one second. Why is that plan unrealistic per the lesson?",
            "options": [
                "Purge propagates across a global network in seconds to minutes, and the misses afterwards hit the origin",
                "Purge by URL only works for images",
                "The browser always keeps its copy for a year",
                "Edge PoPs cannot be purged, only the shield can",
            ],
            "answer": 0,
            "explanation": "Assuming purge is instant and global is a listed mistake. Expect seconds of propagation and a miss spike afterwards, and prefer versioned URLs wherever the URL can change.",
            "section": "common-mistakes",
            "concept": "sd-cdn.invalidation",
            "mistake": "sd-cdn.purge-is-instant",
        },
    ],
    "distributed-systems": [
        {
            "key": "hardcoded-addresses",
            "kind": "choice",
            "prompt": "A service hardcodes the IP addresses of its downstream nodes. Which fallacy is it assuming, and what does the lesson say to design instead?",
            "options": [
                "Topology does not change; use service discovery",
                "Latency is zero; add batching",
                "The network is secure; add TLS",
                "There is one administrator; version the contracts",
            ],
            "answer": 0,
            "explanation": "Each fallacy is a design obligation. Assuming a fixed topology is true on a laptop and false in production, where nodes move, so addresses come from service discovery.",
            "section": "mental-model",
            "concept": "distributed-systems.fallacies",
        },
        {
            "key": "timeout-ambiguity",
            "kind": "choice",
            "prompt": "You send a write and get no response before the timeout. Which of these possibilities can you rule out?",
            "options": [
                "None: the request may never have arrived, may have run with the response lost, or may still be running",
                "That the request never arrived",
                "That the request executed",
                "That the request is still running",
            ],
            "answer": 0,
            "explanation": "This is the two-generals problem in practice. A timeout cannot distinguish the three cases, which is why 'did my write succeed?' is unanswerable and why writes need idempotency keys.",
            "section": "how-it-works",
            "concept": "distributed-systems.timeout-ambiguity",
            "mistake": "distributed-systems.timeout-means-failure",
        },
        {
            "key": "wall-clock-lww",
            "kind": "choice",
            "prompt": "Two machines write the same key. Machine A's clock is 3 seconds ahead. With last-write-wins by wall-clock timestamp, what happens?",
            "options": [
                "The write that actually happened later can be silently discarded",
                "Both writes are kept as a conflict",
                "The write from machine A always loses",
                "Nothing, NTP keeps clocks within microseconds",
            ],
            "answer": 0,
            "explanation": "Clock skew is typically milliseconds and occasionally seconds. Ordering by wall clock across machines discards the wrong write; use logical clocks or a single ordering point instead.",
            "section": "how-it-works",
            "concept": "distributed-systems.time",
            "mistake": "distributed-systems.order-by-now",
        },
        {
            "key": "retry-amplification",
            "kind": "choice",
            "prompt": "Three layers of a call chain each retry a failed call three times. How many backend calls can one user request become, and what does the lesson recommend?",
            "options": [
                "27; retry at one layer only",
                "9; retry at every layer but add jitter",
                "3; retries do not multiply",
                "81; add a fourth retrying layer",
            ],
            "answer": 0,
            "explanation": "Three times three times three is 27. Retries multiply across layers at the moment the system can least take it, so retry at one layer, ideally the outermost one that can make a sensible decision.",
            "section": "how-it-works",
            "concept": "distributed-systems.retries",
            "mistake": "distributed-systems.retry-every-layer",
        },
        {
            "key": "short-timeout-cascade",
            "kind": "choice",
            "prompt": "A failure detector's timeout is set very short to free resources quickly. What does the lesson warn happens under load?",
            "options": [
                "Healthy but slow nodes are declared dead, work is reassigned, load rises, and more nodes look slow",
                "Real failures go unnoticed and requests hang",
                "Idempotency keys stop working",
                "Clock skew increases",
            ],
            "answer": 0,
            "explanation": "Aggressive timeouts free resources and kill healthy-but-slow requests. Reassigning their work adds load, which makes more nodes slow: a cascading failure built out of impatience.",
            "section": "trade-offs",
            "concept": "distributed-systems.failure-detection",
        },
        {
            "key": "grey-failure",
            "kind": "spot_mistake",
            "prompt": "A node passes its liveness check every second yet returns errors for 30% of requests at ten times normal latency. The load balancer keeps sending it traffic. What is wrong with the setup?",
            "options": [
                "The check only tests liveness; a grey failure needs checks that do real work and ejection on error rate and latency",
                "The timeout is too short",
                "The node should be restarted on every failed request",
                "Health checks should run less often",
            ],
            "answer": 0,
            "explanation": "Grey failures pass health checks while serving garbage and cause long incidents. Mitigations are health checks that exercise real work, outlier detection on error rate and latency, and client-side hedging or ejection.",
            "section": "common-failure-modes",
            "concept": "distributed-systems.grey-failure",
            "mistake": "distributed-systems.design-for-clean-crashes-only",
        },
        {
            "key": "abandoned-work",
            "kind": "choice",
            "prompt": "Service A gives up on B after 10 seconds. B waits up to 30 seconds on C. C slows to 25 seconds per call. What goes wrong?",
            "options": [
                "B keeps working on requests A has already abandoned, wasting capacity when nobody is listening",
                "A's requests always succeed because B is still waiting",
                "Nothing, longer timeouts downstream are safer",
                "C retries on A's behalf",
            ],
            "answer": 0,
            "explanation": "Each caller's timeout must be meaningfully shorter than its caller's remaining budget, and a deadline should be propagated down the chain, so nobody works on a request that has already been abandoned.",
            "section": "common-failure-modes",
            "concept": "distributed-systems.timeout-budgets",
            "mistake": "distributed-systems.mismatched-timeouts",
        },
        {
            "key": "payment-timeout",
            "kind": "short_answer",
            "prompt": "A call to a payment provider times out. Explain why 'just retry it' is a mistake and describe the design the lesson recommends.",
            "options": [],
            "answer": None,
            "model_answer": "The first call may have succeeded with the response lost, so a blind retry can charge the customer twice. Generate an idempotency key before the first attempt and send it on every retry so the provider returns the original result. If keys are unsupported, query the charge's status before retrying; failing that, mark the payment UNKNOWN and resolve it in reconciliation.",
            "explanation": "A timeout does not mean the operation did not happen. Idempotency makes the ambiguity harmless, and reconciliation catches whatever the happy path cannot.",
            "section": "common-mistakes",
            "concept": "distributed-systems.idempotency",
            "mistake": "distributed-systems.timeout-means-failure",
        },
    ],
    "observability": [
        {
            "key": "which-signal-localises",
            "kind": "choice",
            "prompt": "Checkout p99 is 2 seconds while every service reports p99 under 200 ms. Which signal does the lesson's workflow use to find where the time went?",
            "options": [
                "Traces, which show the sequential hops of one request",
                "Metrics, aggregated per service",
                "Logs, grepped by service name",
                "CPU dashboards for every host",
            ],
            "answer": 0,
            "explanation": "Metrics detect, traces localise, logs diagnose. Fifteen sequential 130 ms calls add up to two seconds, and that is visible in a trace and almost never in per-service metrics.",
            "section": "mental-model",
            "concept": "observability.three-signals",
        },
        {
            "key": "user-id-label",
            "kind": "choice",
            "prompt": "A metric http_requests_total carries the labels endpoint, status class, region and user_id. Which label breaks the metrics backend, and where should that context go?",
            "options": [
                "user_id; it creates one time series per user, so it belongs in traces and logs",
                "region; regions change too often",
                "status class; it should be the raw status code",
                "endpoint; paths are too long",
            ],
            "answer": 0,
            "explanation": "Cardinality is the cost driver. Labels must be low-cardinality (endpoint, status class, region, version); high-cardinality dimensions like user id belong in traces and logs.",
            "section": "how-it-works",
            "concept": "observability.cardinality",
            "mistake": "observability.high-cardinality-labels",
        },
        {
            "key": "saturation-signal",
            "kind": "choice",
            "prompt": "Inventory shows normal CPU and a clean error rate, yet its callers wait 3 seconds per request. Which measurement does the lesson say reveals the problem?",
            "options": [
                "Saturation, such as connection pool usage at 100%",
                "Utilisation, such as CPU percentage",
                "Error rate per endpoint",
                "Total log volume",
            ],
            "answer": 0,
            "explanation": "Utilisation says how busy something is; saturation says how much work is waiting, and it is the leading indicator of failure. A full connection pool with idle CPU is exactly the case the USE framework catches.",
            "section": "how-it-works",
            "concept": "observability.use-saturation",
        },
        {
            "key": "averaged-percentiles",
            "kind": "spot_mistake",
            "prompt": "A team computes p99 on each of 20 instances and averages the 20 values for the dashboard. What is wrong?",
            "options": [
                "Averaging pre-computed percentiles is meaningless; record histograms and compute percentiles from the merged data",
                "Nothing, this is the standard approach",
                "They should average p50 instead",
                "They should take the maximum of the means",
            ],
            "answer": 0,
            "explanation": "Record latency as a histogram so percentiles aggregate correctly across instances. Averaging percentiles is a mistake real systems make, and it hides the tail.",
            "section": "how-it-works",
            "concept": "observability.histograms",
            "mistake": "observability.averaging-percentiles",
        },
        {
            "key": "tail-sampling",
            "kind": "choice",
            "prompt": "You can afford to keep 1% of traces. Which sampling strategy does the lesson prefer, and why?",
            "options": [
                "Tail-based: decide after the request completes so every slow or failed request is kept",
                "Head-based, because it is cheapest",
                "A random 1% chosen at the client, with no exceptions",
                "Only requests from internal users",
            ],
            "answer": 0,
            "explanation": "Head-based sampling is cheap but throws away interesting requests at random. Tail-based sampling keeps the slow and failed ones, and the lesson says to trace 100% of errors.",
            "section": "design-decisions",
            "concept": "observability.sampling",
        },
        {
            "key": "cost-levers",
            "kind": "choice",
            "prompt": "Observability is 12% of infrastructure spend and must come down without losing the ability to debug. Which levers does the lesson name?",
            "options": [
                "Cut log volume (sample successes, keep errors), reduce cardinality, and downsample old metrics",
                "Disable tracing and delete dashboards",
                "Log more at DEBUG level and keep metrics forever",
                "Replace histograms with averages",
            ],
            "answer": 0,
            "explanation": "Logs usually dominate cost, and cardinality and log volume are the two levers. Sample successes, never errors; downsample old metrics; keep detail where it is useful.",
            "section": "trade-offs",
            "concept": "observability.cost",
        },
        {
            "key": "pipeline-down",
            "kind": "short_answer",
            "prompt": "Your metrics pipeline lags badly during a major incident, exactly when you need it. How do you still know whether the product is working, and how should the pipeline degrade?",
            "options": [],
            "answer": None,
            "model_answer": "Keep a minimal independent path to the most critical signals, for example a synthetic transaction checked from outside the system. Build ingestion so it degrades by dropping detail rather than dropping everything.",
            "explanation": "The observability stack is a system with its own failure modes, and it tends to fall over under the incident it is needed for. Independence and graceful degradation are the two habits.",
            "section": "common-failure-modes",
            "concept": "observability.pipeline-health",
        },
        {
            "key": "alert-on-cpu",
            "kind": "choice",
            "prompt": "An on-call rotation pages when CPU exceeds 80%. It fires every night during batch jobs and nobody acts. What does the lesson say to alert on instead?",
            "options": [
                "User-visible symptoms such as error-budget burn rate and latency SLOs, each with a runbook",
                "CPU above 90% instead of 80%",
                "Memory as well as CPU",
                "Every log line at ERROR level",
            ],
            "answer": 0,
            "explanation": "High CPU is a cause, not an incident; users getting errors is. Alerts nobody acts on train people to ignore the real ones, so every alert should be a symptom with a runbook.",
            "section": "common-mistakes",
            "concept": "observability.alerting",
            "mistake": "observability.alert-on-causes",
        },
    ],
    "sd-batch-stream-processing": [
        {
            "key": "report-on-oltp",
            "kind": "choice",
            "prompt": "Finance wants a daily revenue report. An engineer proposes running it as a big SQL scan against the production app database every night. What does the lesson's mental model say?",
            "options": [
                "Analytics scans must not run on the OLTP database; move the data through a pipeline to a warehouse",
                "Fine, nightly traffic is low",
                "Use a stream engine instead of SQL",
                "Run it against Kafka directly",
            ],
            "answer": 0,
            "explanation": "OLTP serves one row at a time and must never be slowed by a report; analytics scans millions of rows. The pipeline exists to move data from the first world to the second.",
            "section": "mental-model",
            "concept": "sd-batch-stream-processing.oltp-vs-analytics",
        },
        {
            "key": "offline-click",
            "kind": "choice",
            "prompt": "A click happens at 09:59 on a phone in flight mode and reaches the pipeline at 11:30. Counting by processing time puts it where, and why is that wrong?",
            "options": [
                "In the 11:00 bucket, so the 09:00 count is wrong even though the click happened then",
                "In the 09:00 bucket, because processing time is correct",
                "It is dropped, because processing time ignores offline events",
                "In both buckets, so it is double counted",
            ],
            "answer": 0,
            "explanation": "Event time is when the thing happened; processing time is when the pipeline saw it. Counting by processing time is easy and wrong: a slow network moves revenue into the wrong hour.",
            "section": "how-it-works",
            "concept": "sd-batch-stream-processing.event-time",
            "mistake": "sd-batch-stream-processing.count-by-processing-time",
        },
        {
            "key": "watermark-arithmetic",
            "kind": "choice",
            "prompt": "Allowed lateness is 2 seconds and the newest event time seen is 08. Where is the watermark, and what has happened to the window that ends at 05?",
            "options": [
                "Watermark at 06; the window ending at 05 has closed and emitted its result",
                "Watermark at 08; the window is still open",
                "Watermark at 10; nothing closes until 12",
                "Watermark at 05; the window closes right now",
            ],
            "answer": 0,
            "explanation": "The watermark trails the newest event time by the allowed lateness: 08 minus 2 is 06. Once it passes the end of a window, that window closes; anything for it arriving later is late.",
            "section": "how-it-works",
            "concept": "sd-batch-stream-processing.watermarks",
        },
        {
            "key": "replay-correctness",
            "kind": "choice",
            "prompt": "A stream worker crashes mid-window. On restart it loads a checkpoint and replays the log, so some events are processed twice. What keeps the result correct?",
            "options": [
                "An idempotent sink that upserts by window and key, or a transaction that writes results and offsets together",
                "The log deletes events once they are read",
                "The watermark skips replayed events",
                "A checkpoint after every event, so nothing is replayed",
            ],
            "answer": 0,
            "explanation": "Replay means duplicates are inevitable; the sink makes them harmless. Writing (09:00, apple, 41) twice leaves 41. Say 'effectively once' to be precise.",
            "section": "how-it-works",
            "concept": "sd-batch-stream-processing.exactly-once",
            "mistake": "sd-batch-stream-processing.exactly-once-without-sink",
        },
        {
            "key": "backfill",
            "kind": "short_answer",
            "prompt": "A bug corrupted last month's stream results. Describe how you recompute them without touching the live pipeline.",
            "options": [],
            "answer": None,
            "model_answer": "Start a second consumer group at an old offset and replay the retained log through the same code into a shadow table, then swap when it catches up. Retention must be long enough to reach back that far. In batch, rerun the days.",
            "explanation": "Every stream job must be replayable and every batch job safe to rerun. The shadow table and swap are what protect the live pipeline.",
            "section": "how-it-works",
            "concept": "sd-batch-stream-processing.backfill",
        },
        {
            "key": "choose-batch",
            "kind": "choice",
            "prompt": "A dashboard is looked at by one analyst each morning. Which mode does the lesson recommend, and why?",
            "options": [
                "Batch; streaming is more work and freshness is not a requirement here",
                "Stream; it is always more correct",
                "Micro-batch every second",
                "Lambda, running both paths",
            ],
            "answer": 0,
            "explanation": "Pick by how fresh the answer must be: daily report, batch; minutes, micro-batch; seconds, stream. Choosing streaming for a report read once a day is a listed mistake.",
            "section": "design-decisions",
            "concept": "sd-batch-stream-processing.batch-vs-stream",
            "mistake": "sd-batch-stream-processing.stream-for-daily-report",
        },
        {
            "key": "lateness-dial",
            "kind": "choice",
            "prompt": "You raise allowed lateness from 30 seconds to 10 minutes. What do you gain and what do you pay?",
            "options": [
                "Fewer real events dropped; every window's result is delayed by up to 10 minutes",
                "Faster results; more events dropped",
                "Exactly-once for free; more disk",
                "Smaller state; slower replay",
            ],
            "answer": 0,
            "explanation": "Allowed lateness is a dial. More catches more late events and delays every result; less gives faster results and drops more. Set it from measured arrival delay, usually the 99th percentile.",
            "section": "trade-offs",
            "concept": "sd-batch-stream-processing.lateness",
        },
        {
            "key": "append-rerun",
            "kind": "spot_mistake",
            "prompt": "A nightly job reads day D's events and appends the totals to the results table. It crashed halfway last night, so the on-call reran it. What is wrong?",
            "options": [
                "Appending means the rerun double counts the day; the job must overwrite only day D's output",
                "Nothing, reruns are always safe",
                "The job should have read day D-1 as well",
                "Reruns must wait for the next scheduled time",
            ],
            "answer": 0,
            "explanation": "Every batch job must be safe to run twice: read only day D, overwrite only day D's output. That is what lets you crash, rerun, and fix a whole month later.",
            "section": "common-mistakes",
            "concept": "sd-batch-stream-processing.idempotent-batch",
            "mistake": "sd-batch-stream-processing.append-instead-of-overwrite",
        },
    ],
    "sd-news-feed": [
        {
            "key": "write-amplification",
            "kind": "choice",
            "prompt": "800 posts per second and an average of 200 followers. Which number does the lesson say drives the entire design?",
            "options": [
                "Roughly 170,000 feed writes per second, the write amplification",
                "2,500 posts per second at peak",
                "45,000 feed reads per second at peak",
                "13 TB of post storage per year",
            ],
            "answer": 0,
            "explanation": "Posts per second times average followers gives about 170,000 feed insertions per second, far more than the 2,500 post writes. Whether you pay that cost on write or on read is the central decision.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-news-feed.write-amplification",
            "mistake": "sd-news-feed.amplification-not-computed",
        },
        {
            "key": "ids-not-content",
            "kind": "choice",
            "prompt": "A post seen by 5 million readers is edited. In a design that stores only post ids in each feed list, what happens?",
            "options": [
                "The post store is updated once; every feed hydrates the new body from cache",
                "5 million feed entries are rewritten",
                "The edit is rejected because feeds are immutable",
                "The post is removed from feeds and fanned out again",
            ],
            "answer": 0,
            "explanation": "Feeds hold ids and hydrate bodies by batch from cache. That keeps feeds small, avoids duplicating content 200 times, and means an edit or delete is corrected in one place.",
            "section": "step-4-data-model",
            "concept": "sd-news-feed.ids-in-feed",
            "mistake": "sd-news-feed.content-in-feed",
        },
        {
            "key": "hybrid-fanout",
            "kind": "choice",
            "prompt": "In the hybrid design, which users are fanned out on write, and what happens for the rest?",
            "options": [
                "Users below roughly 10,000 followers fan out on write; celebrity posts are stored once and merged at read",
                "Celebrities fan out on write; normal users are merged at read",
                "Everyone fans out on write, with a bigger queue",
                "Nobody; every feed is pulled from followed accounts on request",
            ],
            "answer": 0,
            "explanation": "Fan-out on write is cheap for normal users and covers almost all posts. A celebrity's post is written once and merged at read time from a heavily cached entry that serves millions of readers. The threshold is tunable; the reasoning is the crossover of write cost and read cost.",
            "section": "step-5-first-architecture-and-the-central-decision",
            "concept": "sd-news-feed.hybrid",
            "mistake": "sd-news-feed.one-strategy-for-all",
        },
        {
            "key": "delete-from-feeds",
            "kind": "short_answer",
            "prompt": "A post is deleted. Explain how it disappears from 5 million precomputed feeds, and why the lesson prefers that approach.",
            "options": [],
            "answer": None,
            "model_answer": "It is not removed from the lists. At read time, hydration checks that each post still exists and is visible, so the deleted post simply does not render. Hydration already happens on every read, so the filter is nearly free, and it is far cheaper than rewriting millions of lists. Unfollows and blocks are filtered the same way and age out of the capped list.",
            "explanation": "Read-time filtering is the standard answer. Write-time correction across millions of lists costs more than the deletes are worth.",
            "section": "how-it-works",
            "concept": "sd-news-feed.read-time-filtering",
        },
        {
            "key": "feed-store-lost",
            "kind": "choice",
            "prompt": "Redis loses every feed list. What does the lesson say about recovery and backups?",
            "options": [
                "Feeds are derived data: fall back to pull with a concurrency limit and rebuild lazily; no backup is needed",
                "Restore the lists from the nightly Redis backup",
                "Users lose their feeds permanently",
                "Replay every post through fan-out at full speed immediately",
            ],
            "answer": 0,
            "explanation": "Because feeds can be rebuilt from posts and follows, they need no backup, only a documented and tested rebuild path with a known rate. The concurrency limit keeps the post store alive while it happens.",
            "section": "evolution-under-pressure",
            "concept": "sd-news-feed.derived-data",
        },
        {
            "key": "queue-depth-vs-age",
            "kind": "spot_mistake",
            "prompt": "Fan-out workers are monitored by queue depth, which sits flat at one million. Users complain their posts take an hour to appear. What is wrong with the monitoring?",
            "options": [
                "Depth hides lag; alert on the age of the oldest unprocessed post",
                "Queue depth should be zero at all times",
                "The workers need cursor pagination",
                "The queue should be replaced by synchronous writes",
            ],
            "answer": 0,
            "explanation": "A steady depth can mean a steady one-hour delay. Fan-out lag is invisible when monitoring watches queue length rather than oldest-message age.",
            "section": "failure-modes",
            "concept": "sd-news-feed.fanout-lag",
            "mistake": "sd-news-feed.monitor-queue-depth",
        },
        {
            "key": "hybrid-cost",
            "kind": "choice",
            "prompt": "The hybrid takes fast reads from push and cheap writes from pull. What does the lesson say it costs you?",
            "options": [
                "Two code paths that must produce consistent results",
                "Write amplification for every celebrity post",
                "Feeds that can never be stale",
                "A mandatory backup of the feed store",
            ],
            "answer": 0,
            "explanation": "Push gives fast reads and expensive writes; pull the reverse. The hybrid takes the good half of each and pays with two paths, precomputed and merged, that must agree.",
            "section": "trade-offs",
            "concept": "sd-news-feed.push-vs-pull",
        },
        {
            "key": "offset-pagination",
            "kind": "choice",
            "prompt": "The feed API uses ?offset=40&limit=20. The user scrolls while new posts arrive. What happens, and what does the lesson use instead?",
            "options": [
                "Duplicates and gaps as the feed shifts; use an opaque cursor on (timestamp, post_id)",
                "Nothing, offsets are stable within a session",
                "The request fails; use limit only",
                "Older posts vanish; increase the limit",
            ],
            "answer": 0,
            "explanation": "A feed shifts constantly under the reader, so offsets point at different items on each page. Cursor pagination on (timestamp, post_id) is the standard fix and offset pagination is a listed mistake.",
            "section": "common-mistakes",
            "concept": "sd-news-feed.pagination",
            "mistake": "sd-news-feed.offset-pagination",
        },
    ],
    "sd-dropbox": [
        {
            "key": "metadata-hot-path",
            "kind": "choice",
            "prompt": "1 billion file changes a day, average file 1 MB. Which part of the system does the lesson say is the hot path that must scale?",
            "options": [
                "The metadata service, because metadata operations vastly outnumber byte transfers",
                "Object storage, because bytes dominate",
                "The notification channel",
                "The chunk garbage collector",
            ],
            "answer": 0,
            "explanation": "About 12,000 metadata operations per second on average, several times that at peak, while bytes go straight to object storage. Reordering that expectation is itself the answer to 'where is the bottleneck?'",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-dropbox.metadata-dominates",
            "mistake": "sd-dropbox.bytes-are-the-bottleneck",
        },
        {
            "key": "one-byte-change",
            "kind": "choice",
            "prompt": "A 2 GB file changes by one byte. What crosses the network on upload, and what makes that possible?",
            "options": [
                "About one 4 MB chunk; the client hashes chunks locally and asks which are missing before sending any bytes",
                "The whole 2 GB, since object storage has no partial writes",
                "Only a metadata row, since deduplication already has the file",
                "Half the file, since the changed half is re-sent",
            ],
            "answer": 0,
            "explanation": "POST /chunks/check returns which hashes the server already has; the client uploads only the missing chunks to pre-signed URLs, then commits the version. This single round trip is the heart of the product.",
            "section": "step-3-api-design",
            "concept": "sd-dropbox.hash-before-upload",
            "mistake": "sd-dropbox.whole-file-upload",
        },
        {
            "key": "offline-week",
            "kind": "choice",
            "prompt": "A laptop was offline for a week. How does it find what changed while it was away?",
            "options": [
                "It reads the per-user change log from its saved cursor, a cheap sequential read",
                "It compares hashes of every file with the server",
                "The server re-sends the whole tree",
                "It waits for a notification that carries the changed content",
            ],
            "answer": 0,
            "explanation": "The append-only change log per user plus a device cursor turns 'what changed?' from an expensive diff into a sequential read, which is what makes sync efficient and resumable.",
            "section": "step-4-data-model",
            "concept": "sd-dropbox.change-log",
            "mistake": "sd-dropbox.compare-whole-trees",
        },
        {
            "key": "offline-conflict",
            "kind": "choice",
            "prompt": "Two devices edit report.docx while offline, then both come online. What happens at commit, and what is the recommended resolution?",
            "options": [
                "The second commit fails its parent_version check; create a conflicted copy rather than discard either edit",
                "The later timestamp wins and overwrites the other",
                "Both commits succeed and the file is corrupted",
                "The server merges the two documents automatically",
            ],
            "answer": 0,
            "explanation": "parent_version is an optimistic concurrency check. The standard answer is never lose data: keep both as a conflicted copy and let the human resolve it. Last-write-wins silently discards someone's work.",
            "section": "how-it-works",
            "concept": "sd-dropbox.conflicts",
            "mistake": "sd-dropbox.last-write-wins",
        },
        {
            "key": "chunk-gc",
            "kind": "choice",
            "prompt": "A chunk's reference count hits zero just as another user's upload is about to reference it. What does the lesson say to do?",
            "options": [
                "Mark it; delete only if still unreferenced after a grace period longer than the longest upload; a reference un-marks it",
                "Delete it immediately; the upload will re-send the chunk",
                "Never delete chunks",
                "Lock the chunks table during every upload",
            ],
            "answer": 0,
            "explanation": "Reference counting is racy. Mark-and-sweep with a grace period retains some garbage, but getting it wrong deletes user data, so the conservative approach is correct.",
            "section": "evolution-under-pressure",
            "concept": "sd-dropbox.garbage-collection",
            "mistake": "sd-dropbox.aggressive-gc",
        },
        {
            "key": "unbounded-log",
            "kind": "spot_mistake",
            "prompt": "A design keeps every change-log entry forever so any device, however long offline, can always catch up incrementally. What is wrong?",
            "options": [
                "The log is unbounded; retain a window and fall back to a state-based full resync when a cursor is too old",
                "Nothing, storage is cheap",
                "Devices should never be offline that long",
                "The log should be per device rather than per user",
            ],
            "answer": 0,
            "explanation": "A device offline for months would replay an enormous, mostly superseded log. Compaction plus a full-resync fallback bounds retention; needing both paths is the mature answer.",
            "section": "failure-modes",
            "concept": "sd-dropbox.full-resync",
            "mistake": "sd-dropbox.no-resync-fallback",
        },
        {
            "key": "global-dedup-cost",
            "kind": "choice",
            "prompt": "Global cross-user deduplication saves a lot of storage. What does the lesson say it costs?",
            "options": [
                "An information leak (you can detect whether a file exists) and incompatibility with per-user encryption",
                "Slower uploads for every user",
                "More metadata rows per file",
                "It prevents versioning",
            ],
            "answer": 0,
            "explanation": "Timing an upload reveals whether the system already has a file, and identical plaintext encrypts differently under different keys. Many products therefore deduplicate within a user or workspace.",
            "section": "trade-offs",
            "concept": "sd-dropbox.dedup-scope",
        },
        {
            "key": "naive-answer",
            "kind": "short_answer",
            "prompt": "A candidate says: 'Upload the files to object storage and download them on the other devices.' Explain what this answer misses.",
            "options": [],
            "answer": None,
            "model_answer": "It misses chunking with a hash check before upload (so large files are re-uploaded in full, and fixed-size chunks would break on insertion), conflict handling for offline edits, a cursor-based change log so sync does not compare whole trees, the fact that metadata operations dominate the load, and that most of the complexity lives in the client.",
            "explanation": "The naive answer treats sync as storage. Everything that makes the product work hangs off content-addressed chunks, the change log, and conflict handling.",
            "section": "common-mistakes",
            "concept": "sd-dropbox.naive-design",
            "mistake": "sd-dropbox.just-object-storage",
        },
    ],
    "sd-metrics-platform": [
        {
            "key": "number-to-watch",
            "kind": "choice",
            "prompt": "50,000 hosts each expose 1,000 series scraped every 15 seconds. Which number does the lesson say to watch, and why?",
            "options": [
                "50M active series; series count, not byte volume, drives index size and query cost",
                "3.3M points per second; ingestion rate is the limit",
                "570 GB per day; disk is the limit",
                "43 TB of logs per day; logs are the only limit",
            ],
            "answer": 0,
            "explanation": "Points compress to about 2 bytes each, so volume is manageable. Series count determines the index and query performance, and one bad label can multiply it by a thousand overnight.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-metrics-platform.cardinality",
        },
        {
            "key": "label-multiplication",
            "kind": "choice",
            "prompt": "A metric has 5 services x 10 endpoints x 5 status codes. A team adds a user_id label with a million values. How many series result?",
            "options": ["250 million", "250,000", "1 million", "1,250"],
            "answer": 0,
            "explanation": "Every distinct label combination is its own series, so the damage is multiplicative: 250 series times a million user ids is 250 million, which will take the platform down.",
            "section": "step-3-api-and-data-model",
            "concept": "sd-metrics-platform.cardinality",
            "mistake": "sd-metrics-platform.cardinality-is-additive",
        },
        {
            "key": "why-tsdb",
            "kind": "choice",
            "prompt": "Why does a time-series database beat a general-purpose database for metrics by an order of magnitude, per the lesson?",
            "options": [
                "Immutable time-partitioned blocks, delta-of-delta and XOR compression at 1-2 bytes per point, and a label index",
                "It supports SQL joins across series",
                "It stores every point as a row with a B-tree index",
                "It keeps all data in memory",
            ],
            "answer": 0,
            "explanation": "Consecutive points are similar, so specialised encodings reach 1-2 bytes per point versus tens in a general store. Immutable blocks mean no update path and cheap expiry, and the inverted index makes label selection a set intersection.",
            "section": "step-4-storage-design",
            "concept": "sd-metrics-platform.tsdb",
            "mistake": "sd-metrics-platform.general-db-for-metrics",
        },
        {
            "key": "priority-shedding",
            "kind": "choice",
            "prompt": "The buffer between the ingest gateway and the writers nears its limit during an incident. What does the lesson say to shed first?",
            "options": [
                "Debug logs and detailed metrics from healthy services, keeping error logs from the failing one",
                "The newest data, since older data is already indexed",
                "All logs from every service equally",
                "Error logs, since they are the largest",
            ],
            "answer": 0,
            "explanation": "Backpressure must be explicit and priority-aware. Under pressure you want to lose debug logs from a healthy service, not error logs from the failing one; this is the part candidates miss.",
            "section": "how-it-works",
            "concept": "sd-metrics-platform.priority-shedding",
            "mistake": "sd-metrics-platform.indiscriminate-drop",
        },
        {
            "key": "query-isolation",
            "kind": "choice",
            "prompt": "During a major incident log volume spikes 10x and engineers need fast queries. Which design decision keeps queries usable?",
            "options": [
                "Reserving query capacity separately from ingestion so writes cannot starve reads",
                "Pausing ingestion until the queries finish",
                "Indexing full text so searches run faster",
                "Doubling retention",
            ],
            "answer": 0,
            "explanation": "Buffers absorb the spike and storage lags, but the key decision is isolation: the system degrades to 'recent data available, historical queries slow' rather than becoming unavailable.",
            "section": "evolution-under-pressure",
            "concept": "sd-metrics-platform.query-isolation",
        },
        {
            "key": "shared-failure-domain",
            "kind": "spot_mistake",
            "prompt": "The metrics platform runs on the same cluster and service mesh as production, and its alerts route through the production notification service. What is wrong?",
            "options": [
                "It shares a failure domain with what it monitors, so it is down exactly when it is needed",
                "Nothing, sharing infrastructure saves cost",
                "The mesh adds too much latency to scrapes",
                "Alerts should be evaluated by a single node",
            ],
            "answer": 0,
            "explanation": "The platform must be more available than what it observes: no shared database, mesh or cluster, external monitoring of the watcher, and alert delivery that does not route through the outage.",
            "section": "failure-modes",
            "concept": "sd-metrics-platform.independence",
            "mistake": "sd-metrics-platform.shared-infrastructure",
        },
        {
            "key": "quota-friction",
            "kind": "choice",
            "prompt": "A team's legitimate new metric is blocked by the per-tenant series limit. What does the lesson say the fix is?",
            "options": [
                "Fast, self-service quota changes, not removing the limits",
                "Remove the limit for that team permanently",
                "Remove all limits, since they cause friction",
                "Have the platform team approve each metric by hand",
            ],
            "answer": 0,
            "explanation": "Strict quotas protect everyone and will occasionally block a legitimate use. Limits are the platform's admission control; the answer to friction is a quick quota change, not no limits.",
            "section": "trade-offs",
            "concept": "sd-metrics-platform.quotas",
            "mistake": "sd-metrics-platform.no-limits",
        },
        {
            "key": "unbounded-query",
            "kind": "short_answer",
            "prompt": "An engineer runs a dashboard query over a full year of 15-second data across every service, and the cluster stalls. What should the platform have done?",
            "options": [],
            "answer": None,
            "model_answer": "Bounded the query: limits on series touched, time range and execution time, rejected early with a clear message. Selected a downsampled resolution automatically for a year-long range, since a graph cannot display 15-second points anyway. Cached results for completed windows.",
            "explanation": "A single unbounded query can consume the cluster. Query limits, automatic resolution selection and result caching are what keep query cost bounded.",
            "section": "common-mistakes",
            "concept": "sd-metrics-platform.query-limits",
            "mistake": "sd-metrics-platform.unbounded-queries",
        },
    ],
}
