"""Knowledge checks: non-functional requirements, realtime protocols, data stores, message queues, idempotency, security, unique ids, Instagram, autocomplete, blob storage."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "sd-nonfunctional-requirements": [
        {
            "key": "no-number",
            "kind": "spot_mistake",
            "prompt": "A candidate writes on the board: 'The system must be highly available and low latency.' What is wrong with this as a requirement?",
            "options": [
                "Nothing, that is a normal non-functional requirement",
                "It has no numbers, so it cannot drive a single architectural decision",
                "It should also name the database",
                "Availability and latency cannot both be requirements at once",
            ],
            "answer": 1,
            "explanation": "A non-functional requirement is a wish until it has a number. '99.95% for reads, p99 under 150 ms' is architecture; 'highly available' is not.",
            "section": "mental-model",
            "concept": "sd-nonfunctional-requirements.numbers",
            "mistake": "sd-nonfunctional-requirements.vague-requirement",
        },
        {
            "key": "path-availability",
            "kind": "choice",
            "prompt": "A request must synchronously call four services, each 99.9% available. What is the availability of the request path?",
            "options": [
                "About 99.9%, the weakest link decides",
                "About 99.6%, because availabilities multiply along the path",
                "About 99.99%, because redundancy adds up",
                "About 99.975%, the average of the four",
            ],
            "answer": 1,
            "explanation": "0.999 to the fourth power is about 0.996, over a day of downtime a year. Availability is a property of the path, not of individual boxes, which is why removing a synchronous dependency is often the cheapest win.",
            "section": "how-it-works",
            "concept": "sd-nonfunctional-requirements.dependencies-multiply",
            "mistake": "sd-nonfunctional-requirements.weakest-link",
        },
        {
            "key": "tail-fanout",
            "kind": "choice",
            "prompt": "Each page load makes 20 backend calls to a service with a p99 of 1 second. Roughly what fraction of page loads contain a 1-second call?",
            "options": ["About 1 in 100", "About 1 in 5", "About 1 in 20", "Almost none, p99 is rare"],
            "answer": 1,
            "explanation": "With 20 calls at a 1% chance each, roughly one in five page loads hits the tail. Fan-out turns a rare slow case into the typical experience, which is why the p99 matters and the average does not.",
            "section": "how-it-works",
            "concept": "sd-nonfunctional-requirements.percentiles",
            "mistake": "sd-nonfunctional-requirements.p99-is-rare",
        },
        {
            "key": "error-budget",
            "kind": "short_answer",
            "prompt": "Your SLO is 99.9% over a month. What is the error budget in minutes, and what does the lesson say to do with it?",
            "options": [],
            "answer": None,
            "model_answer": "About 43 minutes of downtime a month (100% minus the SLO). Spend it deliberately on risky deploys, migrations and experiments. Zero errors is not a target; it means you are over-investing in reliability relative to features.",
            "explanation": "The error budget is what turns reliability into an engineering decision rather than an aspiration.",
            "section": "how-it-works",
            "concept": "sd-nonfunctional-requirements.error-budget",
        },
        {
            "key": "per-endpoint",
            "kind": "choice",
            "prompt": "An e-commerce design has a product page read and a place-order endpoint. Which way of setting their availability and consistency targets does the lesson recommend?",
            "options": [
                "One system-wide target: 99.99% and strong consistency for everything",
                "Product page 99.99% with staleness allowed; place order 99.9% with strong, exactly-once effect",
                "Product page strongly consistent; place order eventually consistent",
                "Use the strictest target and apply it only to reads",
            ],
            "answer": 1,
            "explanation": "Gather requirements per endpoint. A product page can be stale for a minute and must almost always load; an order must be correct and can tolerate a slower, slightly less available path.",
            "section": "design-decisions",
            "concept": "sd-nonfunctional-requirements.per-endpoint",
            "mistake": "sd-nonfunctional-requirements.one-target-for-all",
        },
        {
            "key": "global-50ms",
            "kind": "choice",
            "prompt": "The latency target drops to p99 under 50 ms for a global audience, and you serve from one region. What has to change?",
            "options": [
                "Add more servers in that region",
                "Move to edge compute or regional replicas, and decide what consistency you give up",
                "Switch to a faster database engine",
                "Batch requests to raise throughput",
            ],
            "answer": 1,
            "explanation": "Physics puts a floor of roughly 70 to 150 ms round trip between continents, so one region cannot meet 50 ms globally. Regional replicas or edge compute are required, and they force a consistency decision.",
            "section": "trade-offs",
            "concept": "sd-nonfunctional-requirements.latency-topology",
        },
        {
            "key": "retry-amplification",
            "kind": "choice",
            "prompt": "A dependency degrades and every client retries three times. What does the lesson say happens next?",
            "options": [
                "The retries succeed and the outage is masked",
                "Effective load roughly triples and the dependency fails completely",
                "Latency improves because retries spread the load",
                "The load balancer removes the dependency from the pool",
            ],
            "answer": 1,
            "explanation": "Retries multiply load exactly when the dependency can least take it. A degraded service under triple load dies properly; this is the retry-amplified outage.",
            "section": "common-failure-modes",
            "concept": "sd-nonfunctional-requirements.retry-amplification",
            "mistake": "sd-nonfunctional-requirements.retries-are-free",
        },
        {
            "key": "average-latency",
            "kind": "choice",
            "prompt": "The interviewer says: 'Average latency is 40 ms. Is that good?' What is the best response?",
            "options": [
                "Yes, anything under 100 ms is good",
                "Ask for p95, p99 and the fan-out factor, because the mean hides the tail",
                "No, aim for 10 ms",
                "Convert it to throughput first",
            ],
            "answer": 1,
            "explanation": "Average latency is close to meaningless. Users experience the tail, and fan-out makes the tail common, so the percentiles and the number of calls per page are what you need.",
            "section": "common-mistakes",
            "concept": "sd-nonfunctional-requirements.percentiles",
            "mistake": "sd-nonfunctional-requirements.quoting-means",
        },
    ],
    "sd-realtime-protocols": [
        {
            "key": "weakest-mechanism",
            "kind": "choice",
            "prompt": "Notifications arrive about once a minute and only flow from server to client. Which mechanism should you pick?",
            "options": ["WebSocket", "Server-sent events", "Short polling every 100 ms", "Long polling with a 1-second timeout"],
            "answer": 1,
            "explanation": "Pick the weakest mechanism that meets the requirement. One-directional, low-rate updates are exactly what SSE is for; a WebSocket would add a stateful tier for no benefit.",
            "section": "mental-model",
            "concept": "sd-realtime-protocols.choosing",
            "mistake": "sd-realtime-protocols.websocket-by-default",
        },
        {
            "key": "polling-qps",
            "kind": "choice",
            "prompt": "One million clients short-poll every 5 seconds. How many requests per second does the server receive?",
            "options": ["5,000", "200,000", "1,000,000", "20,000"],
            "answer": 1,
            "explanation": "1,000,000 divided by 5 is 200,000 requests per second, most of them returning nothing. That arithmetic is the cost of polling at scale, and also why a 30-second poll against a cached endpoint can be nearly free.",
            "section": "how-it-works",
            "concept": "sd-realtime-protocols.polling-cost",
        },
        {
            "key": "gateway-fleet",
            "kind": "choice",
            "prompt": "You need 10 million concurrent WebSocket connections and a well-tuned node holds about 250,000. Roughly how many gateway nodes is that?",
            "options": ["One, a server can hold millions", "About 40", "About 4", "About 400"],
            "answer": 1,
            "explanation": "Tens of kilobytes plus a file descriptor per connection cap a node at roughly 100k to 500k sockets. A million users is a fleet, not a server, and 10 million at 250k each is about 40 nodes.",
            "section": "how-it-works",
            "concept": "sd-realtime-protocols.connection-cost",
            "mistake": "sd-realtime-protocols.ignoring-per-connection-cost",
        },
        {
            "key": "push-to-user",
            "kind": "short_answer",
            "prompt": "A service needs to push a message to one specific user across a fleet of gateway servers. Describe how it reaches the right socket, and where the message is stored.",
            "options": [],
            "answer": None,
            "model_answer": "Persist the message first. A registry in Redis maps user_id to gateway_id; the service publishes to a pub/sub channel, the gateway holding that user's socket is subscribed and writes to it. If the registry entry is stale or the client is offline, the client catches up by cursor over HTTP.",
            "explanation": "Registry plus pub/sub keeps the gateway stateless apart from the sockets, and persisting first means losing a socket costs latency rather than data.",
            "section": "how-it-works",
            "concept": "sd-realtime-protocols.standard-architecture",
        },
        {
            "key": "catch-up",
            "kind": "choice",
            "prompt": "A mobile client drops its WebSocket for two minutes and reconnects. How should it get the messages it missed?",
            "options": [
                "The gateway replays what it buffered for that socket",
                "A cursor-based HTTP fetch of everything after its last acknowledged message",
                "The server resends the last N messages on every reconnect",
                "Subscriptions in gateway memory make sure nothing is missed",
            ],
            "answer": 1,
            "explanation": "Always catch up by cursor over HTTP, never by replaying the socket. Messages are persisted before they are pushed, so the live channel is only a delivery optimisation.",
            "section": "design-decisions",
            "concept": "sd-realtime-protocols.cursor-catch-up",
            "mistake": "sd-realtime-protocols.socket-as-source-of-truth",
        },
        {
            "key": "hint-vs-payload",
            "kind": "choice",
            "prompt": "A document app has complex per-user permissions. Should the server push the full changed content over the socket, or push a hint that something changed?",
            "options": [
                "Push the full payload, it saves a round trip",
                "Push a hint and let the client fetch; authorisation and ordering happen on the cacheable fetch",
                "Poll instead, sockets cannot carry documents",
                "Open a second socket for permission checks",
            ],
            "answer": 1,
            "explanation": "Payload is faster; the hint is safer. For anything with complex permissions the hint pattern keeps authorisation and ordering out of the push path and lets the fetch be cached.",
            "section": "trade-offs",
            "concept": "sd-realtime-protocols.hint-pattern",
        },
        {
            "key": "reconnect-herd",
            "kind": "spot_mistake",
            "prompt": "A design redeploys all gateway nodes at once, and the client reconnects immediately whenever its socket drops. What is wrong?",
            "options": [
                "Nothing, fast reconnects minimise downtime",
                "Hundreds of thousands of clients reconnect in the same second; you need backoff with jitter and staggered restarts",
                "WebSockets reconnect on their own, so client code is unnecessary",
                "Gateways must never be deployed while clients are connected",
            ],
            "answer": 1,
            "explanation": "Every gateway deploy is a mass reconnection event. Exponential backoff with jitter on the client and staggered, slowly drained gateway restarts are mandatory to avoid the thundering herd.",
            "section": "common-failure-modes",
            "concept": "sd-realtime-protocols.reconnect-storm",
            "mistake": "sd-realtime-protocols.no-jitter",
        },
        {
            "key": "sports-broadcast",
            "kind": "choice",
            "prompt": "A sports app has 5 million viewers, a score update every 30 seconds, and no client-to-server messages. Every viewer sees the same data. What is the cheapest design?",
            "options": [
                "A WebSocket gateway fleet of about 20 nodes",
                "One SSE stream per viewer",
                "A cached endpoint with a 5-second TTL served from the CDN",
                "Long polling with a 30-second timeout",
            ],
            "answer": 2,
            "explanation": "Identical-payload broadcast is a CDN problem, not a socket problem. A cached endpoint serves 5 million viewers from the edge for almost nothing; reaching for WebSockets here inherits statefulness for no benefit.",
            "section": "common-mistakes",
            "concept": "sd-realtime-protocols.choosing",
            "mistake": "sd-realtime-protocols.websocket-by-default",
        },
    ],
    "databases": [
        {
            "key": "queries-first",
            "kind": "choice",
            "prompt": "A candidate opens with: 'We will use Cassandra for everything.' What should have come first?",
            "options": [
                "The write and read patterns, size, atomicity and staleness for each main entity",
                "A comparison of Cassandra and MongoDB",
                "The number of shards",
                "The replication factor",
            ],
            "answer": 0,
            "explanation": "Access patterns, then constraints, then store, then schema. If you can answer the five questions for the main entities, the store usually picks itself and you can defend it.",
            "section": "mental-model",
            "concept": "databases.access-patterns-first",
            "mistake": "databases.logo-first",
        },
        {
            "key": "lsm-vs-btree",
            "kind": "choice",
            "prompt": "A workload is append-only at 40,000 writes per second, read by key and time range, and never joined. Which storage engine fits, and why?",
            "options": [
                "B-tree, because reads are only a few page fetches",
                "LSM tree, because writes are sequential and fast; compaction is the price",
                "Either, the storage engine does not matter at this scale",
                "A columnar warehouse, because the data is time-ordered",
            ],
            "answer": 1,
            "explanation": "Write-heavy workloads lean LSM: writes go to memory and flush as sorted immutable files. B-trees favour read-heavy and range-query work but pay random I/O on writes. Compaction and less predictable tail latency are the LSM cost.",
            "section": "how-it-works",
            "concept": "databases.storage-engines",
        },
        {
            "key": "leave-postgres",
            "kind": "choice",
            "prompt": "Which of these is a specific, nameable reason to leave a relational primary, according to the lesson?",
            "options": [
                "The team prefers working with JSON",
                "NoSQL is faster",
                "Write volume exceeds one primary even after tuning, and the data partitions cleanly",
                "The main table has passed a million rows",
            ],
            "answer": 2,
            "explanation": "A well-indexed Postgres handles tens of thousands of reads and thousands of writes per second, with JSON columns if needed. Leave it for a signal you can name: write volume beyond one primary, pure key access at huge scale, full-text ranking, blobs, or billion-row aggregations.",
            "section": "how-it-works",
            "concept": "databases.relational-default",
            "mistake": "databases.nosql-means-faster",
        },
        {
            "key": "dual-write",
            "kind": "spot_mistake",
            "prompt": "The application writes a product to Postgres, then writes the same product to Elasticsearch. Both writes succeed almost every time. What is wrong?",
            "options": [
                "Nothing, that is how the two stay in sync",
                "Dual writes fail partially and diverge silently; feed the index by CDC or a transactional outbox instead",
                "Elasticsearch should be the source of truth",
                "The writes should happen in the opposite order",
            ],
            "answer": 1,
            "explanation": "When the database write succeeds and the index write fails, nothing reconciles them. Derived stores must be fed from the one source of truth via change data capture or an outbox, so they are eventually consistent but never permanently wrong.",
            "section": "design-decisions",
            "concept": "databases.derived-stores",
            "mistake": "databases.dual-writes",
        },
        {
            "key": "connection-exhaustion",
            "kind": "choice",
            "prompt": "200 application nodes each keep a pool of 50 connections to one relational database. What happens, and what is the fix?",
            "options": [
                "10,000 connections; a relational database handles that comfortably",
                "The database is exhausted; put a connection pooler such as PgBouncer in front of it",
                "Reads slow slightly but nothing fails",
                "Only 200 connections are ever used, one per node",
            ],
            "answer": 1,
            "explanation": "Relational databases handle a few hundred connections well, not thousands. A pooler multiplexes the fleet onto a small number of real connections; mentioning it reads as production experience.",
            "section": "common-failure-modes",
            "concept": "databases.connection-limits",
            "mistake": "databases.ignoring-pooling",
        },
        {
            "key": "consolidate",
            "kind": "choice",
            "prompt": "A small team considers keeping append-only chat messages in the same Postgres as user accounts instead of adding Cassandra. What is the trade?",
            "options": [
                "Fewer moving parts and a poorer fit, versus an ideal fit and much more to operate and keep in sync",
                "Postgres cannot store chat messages at all",
                "Cassandra is always cheaper to run",
                "No trade, one store is always right",
            ],
            "answer": 0,
            "explanation": "One store means less to operate, monitor, back up and synchronise, at the cost of fit. Several stores fit each pattern ideally and multiply the operational surface. Consolidation is often right for a small team.",
            "section": "trade-offs",
            "concept": "databases.polyglot-persistence",
        },
        {
            "key": "analytics-on-primary",
            "kind": "choice",
            "prompt": "A morning reporting query scans the whole transactions table on the production primary. What is the problem and the fix?",
            "options": [
                "No problem, reads are cheap",
                "It competes with production traffic; feed a columnar warehouse asynchronously and query that",
                "Add an index and keep running it on the primary",
                "Run it on a replica of a different database engine",
            ],
            "answer": 1,
            "explanation": "Analytics on the primary is one of the listed mistakes. Aggregations over billions of rows belong in a columnar store loaded asynchronously from the source of truth.",
            "section": "common-mistakes",
            "concept": "databases.analytics-separation",
            "mistake": "databases.analytics-on-primary",
        },
        {
            "key": "driver-locations",
            "kind": "choice",
            "prompt": "100,000 drivers each write their location every 4 seconds, and a location is worthless after a minute. Where does this data belong?",
            "options": [
                "The Postgres trips table",
                "Redis with a geospatial index or an in-memory grid; losing it costs seconds of staleness",
                "Object storage, one object per driver",
                "The columnar warehouse",
            ],
            "answer": 1,
            "explanation": "That is 25,000 writes per second of short-lived data. It does not belong in Postgres at all; an in-memory store fits the access pattern, and losing it costs staleness, not correctness.",
            "section": "example",
            "concept": "databases.access-patterns-first",
        },
    ],
    "message-queues": [
        {
            "key": "growing-backlog",
            "kind": "choice",
            "prompt": "The backlog on a queue has grown steadily for three days. What does that tell you?",
            "options": [
                "The queue is absorbing load as intended",
                "Consumers are undersized; the queue hid the problem rather than solving it",
                "Producers should retry more often",
                "Ordering has broken down",
            ],
            "answer": 1,
            "explanation": "A queue converts a latency problem into a backlog problem. If the backlog only grows, arrival exceeds processing and the failure has merely been deferred.",
            "section": "mental-model",
            "concept": "message-queues.backlog",
            "mistake": "message-queues.infinite-capacity",
        },
        {
            "key": "exactly-once-boundary",
            "kind": "choice",
            "prompt": "Your consumer writes to an external database and calls a third-party API. What delivery guarantee can you honestly promise end to end?",
            "options": [
                "Exactly-once, using Kafka transactions",
                "At-least-once delivery with an idempotent consumer",
                "At-most-once, by acknowledging before processing",
                "Exactly-once, if retries are disabled",
            ],
            "answer": 1,
            "explanation": "Exactly-once exists inside some systems, but the guarantee ends the moment the consumer touches an external store or API. The professional answer is at-least-once plus idempotent processing.",
            "section": "how-it-works",
            "concept": "message-queues.delivery-semantics",
            "mistake": "message-queues.claiming-exactly-once",
        },
        {
            "key": "ordering-key",
            "kind": "choice",
            "prompt": "Events for one order must be processed in sequence, but you need many consumers for throughput. What do you do?",
            "options": [
                "Use global ordering with a single consumer",
                "Partition by order_id, so one order is in order and different orders run in parallel",
                "Timestamp each event and sort at the consumer",
                "Disable retries so nothing arrives out of order",
            ],
            "answer": 1,
            "explanation": "Ordering is per partition or key. Global ordering means one consumer and no parallelism; partitioning by the entity being mutated is the practical compromise.",
            "section": "how-it-works",
            "concept": "message-queues.ordering",
            "mistake": "message-queues.global-ordering",
        },
        {
            "key": "async-cost",
            "kind": "choice",
            "prompt": "Thumbnail generation moves from the request path to a queue, so the API now responds in 50 ms. What does the client lose, and what must you add?",
            "options": [
                "Nothing; the queue is a pure win",
                "Synchronous confirmation; add a status endpoint so the client can learn the outcome",
                "Ordering; add timestamps to every message",
                "Durability; add replication to the queue",
            ],
            "answer": 1,
            "explanation": "The request gets faster and the client now sees eventual completion, so it needs another way to learn the result. Naming that cost, plus at-least-once delivery, is what makes 'add a queue' a justified decision.",
            "section": "trade-offs",
            "concept": "message-queues.async-cost",
        },
        {
            "key": "visibility-timeout",
            "kind": "choice",
            "prompt": "The visibility timeout is 30 seconds and p99 processing time under load is 45 seconds. What happens?",
            "options": [
                "Messages are processed more slowly but exactly once",
                "Messages reappear while still being processed, causing duplicates precisely when load is highest",
                "The consumer crashes",
                "Messages go straight to the dead letter queue",
            ],
            "answer": 1,
            "explanation": "When processing outlives the lease, the message becomes visible again and a second consumer picks it up. Set the timeout above p99 processing time or extend the lease while working.",
            "section": "common-failure-modes",
            "concept": "message-queues.visibility-timeout",
            "mistake": "message-queues.short-lease",
        },
        {
            "key": "outbox",
            "kind": "spot_mistake",
            "prompt": "A service commits the order to the database, then publishes OrderCreated to the queue. What is wrong?",
            "options": [
                "Nothing, that is the standard order of operations",
                "If the publish fails, the order exists and no downstream system hears about it; use a transactional outbox",
                "It should publish first and commit second",
                "The queue should write the order row itself",
            ],
            "answer": 1,
            "explanation": "Write the event into an outbox table in the same transaction as the business change, and let a relay publish from it. Naming the transactional outbox is a strong signal.",
            "section": "design-decisions",
            "concept": "message-queues.outbox",
            "mistake": "message-queues.dual-write-no-outbox",
        },
        {
            "key": "crash-mid-message",
            "kind": "short_answer",
            "prompt": "A consumer crashes halfway through handling a 'send confirmation email' message. What happens to the message, and how do you make sure the email is not sent twice?",
            "options": [],
            "answer": None,
            "model_answer": "The lease expires and the message is redelivered. The consumer records the message id in a processed-messages table with a unique constraint, in the same transaction as marking the email sent, so a redelivery violates the constraint and is skipped.",
            "explanation": "Redelivery is guaranteed; the dedup record written transactionally with the effect is what makes it harmless.",
            "section": "design-decisions",
            "concept": "message-queues.idempotent-consumer",
        },
        {
            "key": "sync-vs-async",
            "kind": "choice",
            "prompt": "Which of these should stay on the synchronous request path rather than going to a queue?",
            "options": [
                "Sending the confirmation email",
                "Payment authorisation at checkout",
                "Updating the search index",
                "Emitting analytics events",
            ],
            "answer": 1,
            "explanation": "Keep work synchronous when the user must know the outcome now: payment authorisation, login, inventory reservation. Using a queue for work the user is waiting on is a listed mistake.",
            "section": "common-mistakes",
            "concept": "message-queues.when-async",
            "mistake": "message-queues.queue-for-sync-work",
        },
    ],
    "sd-idempotency": [
        {
            "key": "naturally-idempotent",
            "kind": "choice",
            "prompt": "Which of these operations is naturally idempotent, so a retry needs no bookkeeping?",
            "options": [
                "increment attempts",
                "SET status = 'shipped'",
                "balance = balance - 50",
                "append a row with no unique key",
            ],
            "answer": 1,
            "explanation": "An absolute update has the same effect whether run once or twice. Relative updates and unkeyed appends accumulate, so they need a dedup record or a redesign such as a keyed ledger entry.",
            "section": "mental-model",
            "concept": "sd-idempotency.natural-idempotency",
        },
        {
            "key": "same-transaction",
            "kind": "short_answer",
            "prompt": "Why must the dedup record and the effect be written in the same transaction?",
            "options": [],
            "answer": None,
            "model_answer": "Otherwise you can perform the effect, crash before recording the key, and the retry performs the effect again. One transaction means the effect and its record either both exist or neither does.",
            "explanation": "This is the key insight people miss; separating the two reopens the duplicate window the key was meant to close.",
            "section": "mental-model",
            "concept": "sd-idempotency.dedup-transaction",
        },
        {
            "key": "concurrent-duplicates",
            "kind": "choice",
            "prompt": "Two copies of the same request arrive 5 ms apart on different servers. What makes this safe?",
            "options": [
                "Check the keys table, then insert if the key is absent",
                "A unique constraint on the key: one insert wins, the other fails and takes the duplicate path",
                "A distributed lock service around every request",
                "Routing all requests for one client to one server",
            ],
            "answer": 1,
            "explanation": "A check-then-insert without a constraint has a race and will eventually double-execute. The unique constraint is what serialises simultaneous duplicates.",
            "section": "how-it-works",
            "concept": "sd-idempotency.unique-constraint",
            "mistake": "sd-idempotency.check-then-insert",
        },
        {
            "key": "body-mismatch",
            "kind": "choice",
            "prompt": "A client reuses an idempotency key from a 5,000 charge but now sends amount 9,000. What should happen?",
            "options": [
                "Return the stored 5,000 charge",
                "Create a 9,000 charge",
                "Reject with 422, because the stored request hash differs",
                "Charge the difference",
            ],
            "answer": 2,
            "explanation": "Store the request hash and reject a reused key with a different body. Silently returning the old result would hide a real client bug.",
            "section": "how-it-works",
            "concept": "sd-idempotency.request-hash",
        },
        {
            "key": "two-systems",
            "kind": "choice",
            "prompt": "The dedup record lives in your database but the effect happens in a separate payment processor. What does the lesson say you need?",
            "options": [
                "One transaction spanning both systems",
                "An outbox plus an idempotent consumer, or a saga",
                "A longer key retention window",
                "A server-generated key for the processor call",
            ],
            "answer": 1,
            "explanation": "One transaction is no longer possible across two systems. This is exactly where distributed transaction patterns return: outbox with idempotent consumers, or a saga.",
            "section": "design-decisions",
            "concept": "sd-idempotency.cross-system",
        },
        {
            "key": "key-expiry",
            "kind": "choice",
            "prompt": "Keys expire after one hour, but the client's retry policy keeps retrying for up to six hours. What breaks?",
            "options": [
                "Nothing, retries carry the same key",
                "A retry after expiry is no longer protected and can create a duplicate charge",
                "The stored response becomes wrong",
                "Concurrent duplicates are no longer detected",
            ],
            "answer": 1,
            "explanation": "Retention must cover client retry windows and operator replays. 24 hours to 7 days is typical; storage is trivial next to a duplicate charge, and the window must be documented.",
            "section": "trade-offs",
            "concept": "sd-idempotency.retention",
            "mistake": "sd-idempotency.keys-expire-too-fast",
        },
        {
            "key": "server-key",
            "kind": "choice",
            "prompt": "The server generates a fresh idempotency key for every request it receives. What does this protect against?",
            "options": [
                "Duplicate requests from client retries",
                "Nothing; a retry carries a different key, so it is treated as a new request",
                "Only concurrent duplicates",
                "Body mismatches",
            ],
            "answer": 1,
            "explanation": "The client must generate the key because the retry has to carry the same key as the original attempt. A server-generated id changes on every attempt and is useless.",
            "section": "common-failure-modes",
            "concept": "sd-idempotency.client-key",
            "mistake": "sd-idempotency.server-generated-key",
        },
        {
            "key": "email-outside-txn",
            "kind": "spot_mistake",
            "prompt": "A consumer upserts the order row idempotently, commits, and then sends a confirmation email. What is wrong?",
            "options": [
                "Nothing, the upsert makes the whole handler idempotent",
                "The email is outside the transaction, so a redelivery sends it twice",
                "Upserts are not idempotent",
                "The email must be sent before the upsert",
            ],
            "answer": 1,
            "explanation": "An idempotent database write with an unprotected external side effect is a listed failure. The email needs its own dedup, for example recording it as sent in the same transaction as the processed message id.",
            "section": "common-mistakes",
            "concept": "sd-idempotency.side-effects",
            "mistake": "sd-idempotency.unprotected-side-effect",
        },
    ],
    "security": [
        {
            "key": "assume-breach",
            "kind": "choice",
            "prompt": "The lesson says to assume a breach will happen somewhere. What should the design aim for?",
            "options": [
                "Making a breach impossible",
                "Containing the breach and detecting it",
                "Keeping the breach out of the logs",
                "Encrypting everything so a breach has no effect",
            ],
            "answer": 1,
            "explanation": "The four questions end with blast radius: when something is compromised, how much is exposed and how fast can you revoke it. Containment structure is the security design.",
            "section": "mental-model",
            "concept": "security.blast-radius",
        },
        {
            "key": "idor",
            "kind": "choice",
            "prompt": "GET /documents/{id} returns the document to any logged-in user who knows the id. What is the vulnerability and where is the fix?",
            "options": [
                "Injection; use parameterised queries",
                "Insecure direct object reference; add an ownership check in the service, which alone knows the owner",
                "Enumeration; make the ids random",
                "SSRF; allowlist the destinations",
            ],
            "answer": 1,
            "explanation": "The gateway can only decide whether this client may call this route. Only the service knows who owns the resource, so every resource-level read and write needs an ownership check there.",
            "section": "how-it-works",
            "concept": "security.two-layer-authorisation",
            "mistake": "security.role-check-only",
        },
        {
            "key": "tenant-isolation",
            "kind": "choice",
            "prompt": "Which option enforces tenant isolation without depending on every query remembering a filter?",
            "options": [
                "A tenant_id column checked in application code",
                "Row-level security in the database",
                "A tenant header set by the client",
                "Logging every cross-tenant read",
            ],
            "answer": 1,
            "explanation": "A tenant_id column with application enforcement is the cheapest option and one missing WHERE clause is a cross-tenant leak. Row-level security enforces below the application layer.",
            "section": "how-it-works",
            "concept": "security.multi-tenancy",
            "mistake": "security.filter-in-app-code",
        },
        {
            "key": "tokenisation",
            "kind": "short_answer",
            "prompt": "Explain how tokenisation keeps card data out of most of the architecture, and what that does to the blast radius.",
            "options": [],
            "answer": None,
            "model_answer": "Replace the card number with a meaningless token and keep the real value in one small, tightly controlled service. Nothing else in the system ever sees a card number, so a compromise anywhere else exposes only tokens, and the audit scope shrinks to that one service.",
            "explanation": "Tokenisation is an architectural pattern, not just a control: a security requirement producing a boundary.",
            "section": "how-it-works",
            "concept": "security.tokenisation",
        },
        {
            "key": "identity-header",
            "kind": "spot_mistake",
            "prompt": "The gateway validates the token and adds an X-User-Id header that services trust. Clients can also send X-User-Id themselves. What is wrong?",
            "options": [
                "Nothing, services should trust the gateway",
                "The gateway must strip client-supplied identity headers, or any client can impersonate anyone",
                "Services must never trust any header",
                "Identity should be in a cookie instead",
            ],
            "answer": 1,
            "explanation": "Downstream services trust the header because traffic came through the gateway. That only holds if the gateway strips any such header supplied by the client before attaching its own.",
            "section": "design-decisions",
            "concept": "security.identity-propagation",
            "mistake": "security.trusting-client-headers",
        },
        {
            "key": "token-lifetime",
            "kind": "choice",
            "prompt": "A design uses 24-hour stateless JWTs so no server state is needed. A token is stolen. What compromise does the lesson recommend?",
            "options": [
                "Store JWTs in local storage so they can be cleared",
                "Short-lived access tokens of 5 to 15 minutes plus a server-side, revocable refresh token",
                "Longer tokens plus a blacklist checked on every request",
                "Replace tokens with long-lived API keys",
            ],
            "answer": 1,
            "explanation": "A signed JWT cannot be revoked before expiry, so its lifetime bounds the damage. Short access tokens with a revocable refresh token resolve the stateless-versus-revocable tension.",
            "section": "trade-offs",
            "concept": "security.token-lifetime",
            "mistake": "security.long-lived-stateless-token",
        },
        {
            "key": "ssrf",
            "kind": "choice",
            "prompt": "A link-preview feature fetches any URL a user pastes. What is the risk, and what prevents it?",
            "options": [
                "Injection; escape the URL",
                "SSRF, reaching internal endpoints; allowlist destinations and block internal address ranges",
                "Credential stuffing; rate limit the endpoint",
                "Enumeration; return uniform errors",
            ],
            "answer": 1,
            "explanation": "A service fetching a user-supplied URL can be tricked into calling internal endpoints. SSRF comes up often in designs with webhooks or link previews, and the fix is destination allowlisting.",
            "section": "common-failure-modes",
            "concept": "security.ssrf",
        },
        {
            "key": "at-rest",
            "kind": "choice",
            "prompt": "A design says: 'The database is encrypted at rest, so the data is protected.' What does at-rest encryption actually protect against?",
            "options": [
                "A compromised application",
                "A stolen disk, not a compromised application; field-level encryption protects against more",
                "SQL injection",
                "Cross-tenant leaks",
            ],
            "answer": 1,
            "explanation": "Disk and database encryption is table stakes and only defeats a stolen disk. An application that can read the data still reads it, which is why the genuinely sensitive columns get field-level encryption.",
            "section": "common-mistakes",
            "concept": "security.encryption-scope",
            "mistake": "security.at-rest-is-enough",
        },
    ],
    "sd-unique-ids": [
        {
            "key": "random-ids",
            "kind": "choice",
            "prompt": "Random-and-big ids such as UUID v4 are the easiest way to be unique without a central counter. What do they do badly?",
            "options": [
                "They collide too often",
                "They sort badly: they say nothing about time and scatter inserts across the index",
                "They need a central counter after all",
                "They need a clock you can trust",
            ],
            "answer": 1,
            "explanation": "Random ids are easy but sort badly; time-based ids sort well but need a trusted clock. Each new UUID v4 row lands in a random place in the B-tree, so inserts slow down and the cache stays cold.",
            "section": "mental-model",
            "concept": "sd-unique-ids.random-vs-time",
        },
        {
            "key": "sequence-overflow",
            "kind": "choice",
            "prompt": "A Snowflake generator receives 5,000 id requests within one millisecond. What happens?",
            "options": [
                "All 5,000 get ids",
                "4,096 get ids; the rest wait for the next millisecond",
                "The machine id is incremented to make room",
                "Some ids collide",
            ],
            "answer": 1,
            "explanation": "The 12-bit sequence holds 4,096 values per millisecond per machine. When it reaches 4,095 the generator waits for the next millisecond, which is about four million ids per second per node.",
            "section": "how-it-works",
            "concept": "sd-unique-ids.snowflake-bits",
        },
        {
            "key": "clock-backwards",
            "kind": "short_answer",
            "prompt": "A server's clock jumps back 200 ms after an NTP correction. What should its Snowflake generator do, and how do you keep such jumps small?",
            "options": [],
            "answer": None,
            "model_answer": "Refuse to generate, returning errors or waiting until the clock catches up, because it could otherwise hand out an id it already gave. Set NTP to slew rather than step, and alert on any large jump. A short pause is better than a duplicate id.",
            "explanation": "The load balancer routes around the refusing node for 200 ms and no duplicate id is ever issued, which is the property that matters.",
            "section": "how-it-works",
            "concept": "sd-unique-ids.clock-safety",
        },
        {
            "key": "hash-short-id",
            "kind": "choice",
            "prompt": "A URL shortener takes the first seven characters of a hash of the long URL as the short id. What is the cost compared with base62 of a counter?",
            "options": [
                "The ids become guessable",
                "Seven hash characters collide eventually, so every write needs a database check and a salted re-hash on collision",
                "It needs a trusted clock",
                "The ids are 128 bits",
            ],
            "answer": 1,
            "explanation": "A counter is already unique, so base62 of it never collides. A truncated hash will, so you pay an extra read on every write. Most designs use the counter and shuffle bits if guessing is a problem.",
            "section": "how-it-works",
            "concept": "sd-unique-ids.short-ids",
            "mistake": "sd-unique-ids.unhandled-hash-collision",
        },
        {
            "key": "epoch",
            "kind": "spot_mistake",
            "prompt": "A design says: 'We will use Snowflake ids with the 41-bit timestamp counted in milliseconds since 1970.' What is wrong?",
            "options": [
                "Nothing, 41 bits is plenty",
                "Milliseconds since 1970 already use 41 bits, so it runs out; count from a custom epoch to get the full 69 years",
                "Snowflake needs 48 timestamp bits",
                "The machine id must come before the timestamp",
            ],
            "answer": 1,
            "explanation": "Forgetting the custom epoch is a listed mistake. Counting from your own launch date is what gives you the whole 69-year range.",
            "section": "common-mistakes",
            "concept": "sd-unique-ids.custom-epoch",
            "mistake": "sd-unique-ids.no-custom-epoch",
        },
        {
            "key": "billion-row-key",
            "kind": "choice",
            "prompt": "A table will hold billions of rows, is paged with 'newer than id X', and every index should stay as small as possible. Which id fits best?",
            "options": [
                "UUID v4",
                "Snowflake: 64 bits and sorted by time",
                "UUID v7: sorted by time but 128 bits",
                "A hash of the row content",
            ],
            "answer": 1,
            "explanation": "Time order rules out UUID v4 and a content hash. UUID v7 sorts but costs twice the space in every index. Snowflake gives both time order and 64 bits.",
            "section": "choosing-by-need",
            "concept": "sd-unique-ids.choosing",
        },
        {
            "key": "invoice-numbers",
            "kind": "choice",
            "prompt": "Public invoice numbers must not reveal how many orders you have or when they were made. Which id type fits?",
            "options": ["Auto-increment", "Snowflake", "Random UUID v4", "Range allocation"],
            "answer": 2,
            "explanation": "Counters reveal everything, Snowflake reveals time and rough volume, and range allocation is a counter in batches. Random ids are unguessable, which is the requirement here.",
            "section": "choosing-by-need",
            "concept": "sd-unique-ids.choosing",
            "mistake": "sd-unique-ids.guessable-ids",
        },
        {
            "key": "range-crash",
            "kind": "choice",
            "prompt": "With range allocation, a server crashes with 700 ids left in its batch of 1,000. What happens to those ids?",
            "options": [
                "Another server picks up the remaining 700",
                "They are lost, and gaps do not matter",
                "The next batch collides with them",
                "All ids from that server become invalid",
            ],
            "answer": 1,
            "explanation": "Range allocation trades one round trip per batch for ids that are only roughly increasing and a wasted remainder on crash. Uniqueness is unaffected because the batch was never reissued.",
            "section": "trade-offs",
            "concept": "sd-unique-ids.range-allocation",
        },
    ],
    "sd-instagram": [
        {
            "key": "egress-number",
            "kind": "choice",
            "prompt": "500M daily users generate 100 billion image requests a day at about 200 KB each. What is the daily egress, and what does it decide?",
            "options": [
                "20 TB a day; a server workload with a cache",
                "20 PB a day; a CDN is not an optimisation but the only viable architecture",
                "200 TB a day; add more origin servers",
                "2 PB a day; a bigger object store",
            ],
            "answer": 1,
            "explanation": "100 billion times 200 KB is 20 petabytes a day. That is not an origin workload; at a 98% CDN offload origin egress falls to 400 TB, the difference between impossible and expensive.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-instagram.egress",
            "mistake": "sd-instagram.never-computing-egress",
        },
        {
            "key": "upload-path",
            "kind": "choice",
            "prompt": "How does a 3 MB photo get from the phone into storage?",
            "options": [
                "The client POSTs it to the API, which streams it to object storage",
                "The client gets a short-lived pre-signed URL and PUTs the bytes straight to object storage; the API only writes metadata",
                "The client sends it base64-encoded inside the create-post JSON",
                "The client uploads it to the CDN, which forwards it to the API",
            ],
            "answer": 1,
            "explanation": "At 3,000 uploads a second of 3 MB each, 9 GB/s of ingest must never pass through the application tier. POST /uploads returns a pre-signed, size-limited URL; the client PUTs directly; POST /posts then creates the post.",
            "section": "step-3-api-design",
            "concept": "sd-instagram.presigned-upload",
            "mistake": "sd-instagram.uploads-through-api",
        },
        {
            "key": "counters-separate",
            "kind": "choice",
            "prompt": "Why does the data model keep like and comment counts in a separate counters table instead of columns on the post row?",
            "options": [
                "Joins are faster that way",
                "A viral post would otherwise create a hot row",
                "Counters need strong consistency and the post row does not",
                "The post row is immutable",
            ],
            "answer": 1,
            "explanation": "A viral post takes millions of likes; updating the post row for each one turns it into a hot row. Keeping counters separate isolates that write load.",
            "section": "step-4-data-model",
            "concept": "sd-instagram.data-model",
        },
        {
            "key": "reconciliation",
            "kind": "short_answer",
            "prompt": "How do the metadata store and object storage stay consistent when they can diverge in both directions?",
            "options": [],
            "answer": None,
            "model_answer": "The post row is the source of truth. A sweeper deletes objects with no row or whose pending row is older than 24 hours; another sweeper flags rows whose bytes are missing. Deletes are soft-deletes first, with a background job removing renditions and purging the CDN, so nothing races in-flight readers.",
            "explanation": "Reconciliation sweeps in both directions plus soft delete are mandatory; two stores will not always agree on their own.",
            "section": "how-it-works",
            "concept": "sd-instagram.reconciliation",
        },
        {
            "key": "on-demand-renditions",
            "kind": "spot_mistake",
            "prompt": "The design pre-generates all seven renditions for every upload so that any read is served instantly. What is wrong?",
            "options": [
                "Nothing, predictable latency is worth it",
                "Most photos are never viewed at full size; generate two or three eagerly and the rest on first request",
                "Renditions should be generated on the client",
                "Seven renditions is too few",
            ],
            "answer": 1,
            "explanation": "Pre-generating everything multiplies storage for the long tail nobody views. Producing the rest on demand trades a slow first request for most of the derivative storage; the right answer differs by rendition.",
            "section": "trade-offs",
            "concept": "sd-instagram.storage-economics",
            "mistake": "sd-instagram.pregenerate-everything",
        },
        {
            "key": "transcode-backlog",
            "kind": "choice",
            "prompt": "Transcoding workers are two hours behind during a peak event. What should you do first?",
            "options": [
                "Pause uploads until the backlog clears",
                "Generate the feed rendition first so the photo is usable in seconds, and autoscale workers on queue age",
                "Move rendition generation into the client",
                "Drop all renditions except the original",
            ],
            "answer": 1,
            "explanation": "Prioritise the rendition that makes the photo usable, defer the rest, autoscale on queue age and use spot capacity for the non-urgent work. The archive-quality rendition can wait a day.",
            "section": "evolution-under-pressure",
            "concept": "sd-instagram.pipeline-backlog",
        },
        {
            "key": "exif",
            "kind": "choice",
            "prompt": "The processing worker serves renditions without stripping EXIF metadata. Why does the lesson call this an incident rather than a bug?",
            "options": [
                "The files are slightly larger",
                "EXIF can contain the location where the photo was taken, so this is a privacy incident",
                "The CDN cannot cache images with EXIF",
                "The checksum will not match the declared one",
            ],
            "answer": 1,
            "explanation": "Location data in photos is a genuine privacy issue. Stripping EXIF in the worker is a small detail that reads as real-world experience.",
            "section": "failure-modes",
            "concept": "sd-instagram.exif",
            "mistake": "sd-instagram.exif-left-in",
        },
        {
            "key": "delete-everything",
            "kind": "choice",
            "prompt": "A user deletes a post. Which answer is complete?",
            "options": [
                "Delete the row; the storage lifecycle policy handles the bytes",
                "Soft-delete the row now, then remove originals and renditions, purge the CDN, and let backups expire on schedule",
                "Hard-delete the row and all bytes synchronously in one request",
                "Purge the CDN only, since the bytes are cheap to keep",
            ],
            "answer": 1,
            "explanation": "Deletion must reach derivatives, caches, CDNs and backups. Soft delete first avoids racing in-flight readers; a background job does the rest, and the deletion policy has to cover backup retention.",
            "section": "common-mistakes",
            "concept": "sd-instagram.deletion",
            "mistake": "sd-instagram.incomplete-deletion",
        },
    ],
    "sd-autocomplete": [
        {
            "key": "scale-implies",
            "kind": "choice",
            "prompt": "250,000 suggestion requests a second with a p99 budget of 50 ms, and the index is a few gigabytes. What do these numbers imply?",
            "options": [
                "Shard the index widely and query a database per request",
                "An in-memory lookup, the index replicated in full to every node, and ranking precomputed offline",
                "Use the search index with a cache in front",
                "Query per keystroke with a 100 ms budget instead",
            ],
            "answer": 1,
            "explanation": "The budget rules out any network hop to a database, the index size means no sharding is needed, and scoring cannot happen at request time. Stating those three conclusions is most of the design.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-autocomplete.offline-online-split",
        },
        {
            "key": "late-response",
            "kind": "choice",
            "prompt": "The user types 'ca' then 'cat'. The response for 'ca' arrives after the response for 'cat'. What must the client do with it?",
            "options": [
                "Show it, since it arrived most recently",
                "Discard it; in-flight requests are cancelled so a late earlier-prefix response never overwrites current suggestions",
                "Merge both lists",
                "Re-request 'cat'",
            ],
            "answer": 1,
            "explanation": "Cancelling in-flight requests when a newer keystroke arrives is a real bug fix in naive implementations. Debounce, cancellation, local caching and silent failure cut backend load more than any server optimisation.",
            "section": "step-3-api-design",
            "concept": "sd-autocomplete.client-behaviour",
            "mistake": "sd-autocomplete.no-cancellation",
        },
        {
            "key": "trie-topk",
            "kind": "choice",
            "prompt": "In the serving trie, how are the top 10 suggestions for the prefix 'ca' obtained?",
            "options": [
                "Traverse the subtree under 'ca' and sort the completions by score",
                "Read the precomputed top-k list stored at the 'ca' node",
                "Query the aggregate table for rows starting with 'ca'",
                "Merge the children's lists at request time",
            ],
            "answer": 1,
            "explanation": "Each node stores its precomputed top-k. A lookup is a walk of len(prefix) nodes followed by reading a small list, with no aggregation, sorting or scoring at request time.",
            "section": "step-4-data-model",
            "concept": "sd-autocomplete.precomputed-topk",
            "mistake": "sd-autocomplete.traversing-subtree",
        },
        {
            "key": "frequency-threshold",
            "kind": "choice",
            "prompt": "Beyond ranking quality, why does the offline pipeline drop queries below a frequency threshold?",
            "options": [
                "It only saves memory",
                "A rare query may identify an individual, so the threshold protects privacy and also drops spam",
                "It makes the trie walk faster",
                "The trie cannot store rare strings",
            ],
            "answer": 1,
            "explanation": "Filtering is more important than ranking. The threshold removes queries that could expose personal information, alongside PII strings, offensive content and bot-generated queries.",
            "section": "how-it-works",
            "concept": "sd-autocomplete.filtering",
            "mistake": "sd-autocomplete.no-filtering",
        },
        {
            "key": "breaking-news",
            "kind": "choice",
            "prompt": "A news event makes a brand new query the top search worldwide within minutes, but the base index rebuilds hourly. How do you keep suggestions fresh?",
            "options": [
                "Rebuild the full index every minute",
                "Add a small real-time overlay from the last few minutes, merged at lookup; it holds only thousands of entries",
                "Query the search index for trending terms on each request",
                "Raise the edge cache TTL",
            ],
            "answer": 1,
            "explanation": "The two-tier index gives freshness without constant rebuilds: the large hourly base plus a tiny overlay that costs almost nothing to merge.",
            "section": "evolution-under-pressure",
            "concept": "sd-autocomplete.two-tier-index",
        },
        {
            "key": "silent-degradation",
            "kind": "short_answer",
            "prompt": "The suggest service goes down entirely. What should users see, and why is that acceptable?",
            "options": [],
            "answer": None,
            "model_answer": "No suggestions, and search keeps working. Nobody can tell whether suggestions are missing or imperfect, so the correct design is silent degradation rather than retries and error states. Treating the service as critical and over-engineering its availability is a mistake.",
            "explanation": "This is one of the few systems where complete failure is acceptable, and saying so explicitly is a good signal.",
            "section": "common-mistakes",
            "concept": "sd-autocomplete.silent-degradation",
            "mistake": "sd-autocomplete.over-engineering-availability",
        },
        {
            "key": "personalise-cost",
            "kind": "choice",
            "prompt": "How does the lesson personalise suggestions, and what does personalisation cost?",
            "options": [
                "A trie per user; it costs memory",
                "Re-rank the global top 20 with the user's history and location; it costs edge cacheability",
                "Query the search index with the user id; it costs latency",
                "Client-side only; it costs nothing",
            ],
            "answer": 1,
            "explanation": "Retrieval stays global and cheap, and personalisation is a cheap re-rank over a tiny candidate set. Personalised responses cannot be shared at the edge, which is a significant loss.",
            "section": "trade-offs",
            "concept": "sd-autocomplete.personalisation",
            "mistake": "sd-autocomplete.per-user-index",
        },
        {
            "key": "index-per-keystroke",
            "kind": "spot_mistake",
            "prompt": "A design proposes: on each keystroke, query the search index for terms matching the prefix, rank them, and return the top 10. What is wrong?",
            "options": [
                "Nothing, it gives the freshest results",
                "A distributed query, scoring pass and sort per keystroke at 250,000 a second cannot meet 50 ms and costs too much",
                "It should return the top 5 instead",
                "It only needs a bigger cache in front",
            ],
            "answer": 1,
            "explanation": "Move work from read time to write time when reads outnumber writes by orders of magnitude. Autocomplete is the extreme case; the live path must be a memory lookup.",
            "section": "failure-modes",
            "concept": "sd-autocomplete.offline-online-split",
            "mistake": "sd-autocomplete.index-per-keystroke",
        },
    ],
    "sd-blob-storage": [
        {
            "key": "erasure-disk",
            "kind": "choice",
            "prompt": "You store 100 PB. How much disk do three full copies need, and how much does 6-plus-3 erasure coding need?",
            "options": ["300 PB versus 150 PB", "300 PB versus 100 PB", "200 PB versus 150 PB", "300 PB versus 300 PB"],
            "answer": 0,
            "explanation": "Three copies triple the disk. Six data pieces plus three parity pieces is 1.5 times, and still survives three losses. That saving is worth millions.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-blob-storage.erasure-coding",
        },
        {
            "key": "delete-marker",
            "kind": "choice",
            "prompt": "DELETE on a key in a versioned bucket returns 204. What actually happened to the data?",
            "options": [
                "The bytes were freed on the data nodes",
                "A delete marker was added; the bytes stay until a delayed garbage collector frees them",
                "Every version of the object was removed",
                "The object was moved to archive storage",
            ],
            "answer": 1,
            "explanation": "Deletes only mark. GC later finds chunks no version references and waits a few hours first, so an in-flight read or a mistaken delete cannot hit freed space.",
            "section": "step-3-api",
            "concept": "sd-blob-storage.deletes-and-gc",
            "mistake": "sd-blob-storage.delete-frees-bytes",
        },
        {
            "key": "bytes-through-metadata",
            "kind": "choice",
            "prompt": "A design streams object bytes through the metadata service so it can update the record as they arrive. Why is that wrong?",
            "options": [
                "Metadata records would be too large",
                "Tens of gigabytes a second would pass through the small hot store; bytes stream between front doors and data nodes only",
                "Checksums cannot be computed there",
                "The metadata service cannot be sharded",
            ],
            "answer": 1,
            "explanation": "Metadata maps a key to a chunk list; data nodes store chunks; the two never mix. Routing 30 GB/s of reads through the metadata store turns it into the bottleneck.",
            "section": "step-4-data-model",
            "concept": "sd-blob-storage.metadata-data-split",
            "mistake": "sd-blob-storage.bytes-through-metadata",
        },
        {
            "key": "metadata-first",
            "kind": "spot_mistake",
            "prompt": "The front door writes the object record to the metadata DB first, then streams the bytes to the data nodes. What is wrong?",
            "options": [
                "Nothing, the key becomes visible sooner",
                "A crash after the metadata write leaves a key pointing at bytes that never arrived; bytes first leaves only an orphan",
                "The bytes should go through the metadata service instead",
                "The order does not matter once checksums are used",
            ],
            "answer": 1,
            "explanation": "Write bytes first and metadata last. Then the worst case is a stray chunk that a cleanup job removes, never a key that points at nothing.",
            "section": "failure-modes",
            "concept": "sd-blob-storage.metadata-last",
            "mistake": "sd-blob-storage.metadata-before-bytes",
        },
        {
            "key": "multipart",
            "kind": "short_answer",
            "prompt": "A client uploads a 5 TB file over a bad connection and dies halfway. How do the API and the metadata make this work?",
            "options": [],
            "answer": None,
            "model_answer": "Begin creates an upload row. Each part is uploaded like a small object, with its own ETag and chunk list, in parallel and retried alone. Finished parts stay for a week, so the client uploads only the missing parts and calls complete, which is one atomic metadata transaction that joins the chunk lists in order. If it never returns, GC frees the parts.",
            "explanation": "Multipart is parts written like small objects plus one atomic complete; the object appears all at once.",
            "section": "how-it-works",
            "concept": "sd-blob-storage.multipart",
        },
        {
            "key": "zone-loss",
            "kind": "choice",
            "prompt": "A whole zone goes dark. What still works?",
            "options": [
                "Nothing until the zone returns",
                "Reads and writes continue: other zones hold copies, erasure-coded chunks keep six pieces, metadata keeps a Raft majority",
                "Reads only, because metadata leaders cannot be elected",
                "Writes only, because reads need all three copies",
            ],
            "answer": 1,
            "explanation": "Copies are in three zones so every object keeps two; erasure coding places at most three pieces per zone so six survive; metadata shards keep a majority outside any one zone and re-elect leaders.",
            "section": "evolution-under-pressure",
            "concept": "sd-blob-storage.zone-failure",
        },
        {
            "key": "three-copies-then-ec",
            "kind": "choice",
            "prompt": "Why do most real object stores keep three copies while data is new and erasure-code it once it is old?",
            "options": [
                "Erasure coding cannot be written directly",
                "Three copies read simply and fast for hot data; erasure coding halves disk for cold data at the cost of heavier reads",
                "Regulations require three copies for 30 days",
                "The scrubber only works on full copies",
            ],
            "answer": 1,
            "explanation": "A missing erasure-coded piece needs six reads plus arithmetic, which hurts hot small objects. Paying that only for cold data gets the disk saving without the read penalty where it matters.",
            "section": "trade-offs",
            "concept": "sd-blob-storage.erasure-coding",
        },
        {
            "key": "eleven-nines",
            "kind": "choice",
            "prompt": "A design claims eleven nines of durability from three copies in three zones and nothing else. What is missing?",
            "options": [
                "Nothing, three zones are enough",
                "Checksums on every read, a scrubber that rebuilds silent corruption, and fast throttled repair",
                "A fourth copy in a fourth zone",
                "RAID on every data node",
            ],
            "answer": 1,
            "explanation": "At petabyte scale disks silently flip bits. Eleven nines comes from the loop of checksums, a scrubber that reads every chunk every few weeks, and repair that finishes long before a second failure, not from copies alone.",
            "section": "common-mistakes",
            "concept": "sd-blob-storage.durability",
            "mistake": "sd-blob-storage.copies-alone",
        },
    ],
}
