"""Knowledge checks: requirements gathering, load balancing, object storage, event-driven architecture,
resilience patterns, multi-region, geospatial indexing, Netflix, job scheduler, leaderboard."""

from __future__ import annotations

CHECKS: dict[str, list[dict]] = {
    "requirements-gathering": [
        {
            "key": "skipped-confirm",
            "kind": "choice",
            "prompt": "A candidate lists scope, three functional requirements and numbered non-functional ones, then starts drawing. Which of the four moves did they skip, and why does it matter?",
            "options": [
                "Estimation: without numbers nothing justifies the architecture",
                "Confirm: saying it back and getting a yes, the step interviewers notice when it is missing",
                "Out-of-scope: they never named what they are not building",
                "Nothing was skipped; drawing is the right next step",
            ],
            "answer": 1,
            "explanation": "The four moves are scope, functional, non-functional, confirm. Confirm is the one candidates skip and interviewers notice: you say the contract back in two sentences and get a yes before it becomes the grading criteria.",
            "section": "mental-model",
            "concept": "requirements-gathering.four-moves",
            "mistake": "requirements-gathering.no-confirm",
        },
        {
            "key": "which-justifies-cdn",
            "kind": "choice",
            "prompt": "In minute thirty you add a CDN. Which written requirement do you point at to justify it?",
            "options": [
                "A user can upload a video",
                "A viewer can watch a video",
                "p99 start of playback under 2 s worldwide",
                "A viewer sees a view count",
            ],
            "answer": 2,
            "explanation": "Non-functional requirements with numbers are what produce boxes on the diagram. The three functional lines shape the API and data model; the p99 worldwide latency line is the one that forces a CDN.",
            "section": "how-it-works",
            "concept": "requirements-gathering.functional-vs-nonfunctional",
            "mistake": "requirements-gathering.only-functional",
        },
        {
            "key": "fifteen-questions",
            "kind": "spot_mistake",
            "prompt": "A candidate opens with fifteen questions in a row: users, region, ratio, real-time, auth, payments, moderation, analytics, retention, and so on, each waiting for an answer. What is wrong?",
            "options": [
                "Nothing; thorough discovery is what interviewers grade",
                "It burns about four minutes and reads as an audit; bundle defaults into one proposal and ask for confirmation",
                "The order is wrong; scale must always be asked first",
                "They should draw a first diagram and ask questions afterwards",
            ],
            "answer": 1,
            "explanation": "Propose rather than interrogate: one sentence with four assumptions lets the interviewer correct any of them in five seconds. Fifteen serial questions feel like an audit and eat the deep-dive time.",
            "section": "how-it-works",
            "concept": "requirements-gathering.propose-not-interrogate",
            "mistake": "requirements-gathering.interrogation",
        },
        {
            "key": "you-decide",
            "kind": "choice",
            "prompt": "You ask about scale and the interviewer says 'you decide'. What is the strongest response?",
            "options": [
                "Pick a small scale so the design stays simple and finishes on time",
                "Say 10M DAU and give the reason: that is where a single database stops being sufficient",
                "Ask two more questions to narrow it down before choosing",
                "Skip scale for now and return to it during the deep dive",
            ],
            "answer": 1,
            "explanation": "Decide out loud, with a reason. Choosing a scale where the interesting problems start lets the rest of the interview show your best work, and it is an expected move.",
            "section": "design-decisions",
            "concept": "requirements-gathering.decide-out-loud",
            "mistake": "requirements-gathering.small-scale-to-be-safe",
        },
        {
            "key": "assume-or-ask",
            "kind": "choice",
            "prompt": "Which of these can you state in passing and move on, instead of asking about?",
            "options": [
                "The read to write ratio",
                "Whether the system is global or single region",
                "The cloud vendor",
                "Whether view counts may be stale or must be strongly consistent",
            ],
            "answer": 2,
            "explanation": "Assume anything that does not change the architecture (vendor, auth mechanism, exact schema types). Ask about anything that changes the shape of the system: scale, ratio, consistency, geography, real-time versus batch.",
            "section": "design-decisions",
            "concept": "requirements-gathering.assume-vs-ask",
        },
        {
            "key": "deliberate-cut",
            "kind": "choice",
            "prompt": "You decide to leave search out so you can go deep on the feed. How should you handle that cut?",
            "options": [
                "Say nothing; the interviewer will ask if they care about search",
                "Name it as a deliberate cut and offer to return to it if there is time",
                "Include it anyway, because narrow scope looks like avoiding the hard part",
                "Ask the interviewer to remove search from the prompt",
            ],
            "answer": 1,
            "explanation": "Narrow scope lets you finish and go deep, but too narrow looks like avoidance. Naming the cut out loud turns it into a choice the interviewer can accept or reverse.",
            "section": "trade-offs",
            "concept": "requirements-gathering.narrow-vs-broad",
            "mistake": "requirements-gathering.silent-cut",
        },
        {
            "key": "filler-requirement",
            "kind": "choice",
            "prompt": "A candidate writes 'the system should be secure and maintainable' in the requirements list. What is the problem?",
            "options": [
                "It is a functional requirement written in the wrong list",
                "It forces no decision, so it is filler that justifies nothing later",
                "Security is out of scope in design interviews",
                "It should have been asked as a question instead",
            ],
            "answer": 1,
            "explanation": "A requirement that does not force a decision produces no architecture. Requirements exist so that later components point back to a line the interviewer agreed to.",
            "section": "common-failure-modes",
            "concept": "requirements-gathering.requirements-that-justify",
            "mistake": "requirements-gathering.filler-requirements",
        },
        {
            "key": "why-write-down",
            "kind": "short_answer",
            "prompt": "Why should you write both requirement lists somewhere visible and leave them there for the whole interview? Give one concrete use.",
            "options": [],
            "answer": None,
            "model_answer": "So you can point at them when defending a decision later instead of asserting opinions. For example, adding a CDN points at 'p99 playback under 2 s worldwide', and 'why is this eventually consistent?' points at 'view counts may lag 60 s', a constraint the interviewer already agreed to.",
            "explanation": "Requirements you never refer to again are a common mistake. Written requirements become the justifications you harvest later.",
            "section": "common-mistakes",
            "concept": "requirements-gathering.write-it-down",
            "mistake": "requirements-gathering.requirements-never-used",
        },
    ],
    "load-balancing": [
        {
            "key": "l4-or-l7",
            "kind": "choice",
            "prompt": "Requests under /video must reach one service and /api another, and you want TLS terminated in one place. Which layer of load balancer do you need, and why?",
            "options": [
                "L4, because it is faster and handles millions of connections",
                "L7, because routing on path and terminating TLS require parsing the request",
                "Either, since both layers see the URL",
                "DNS, because path routing happens at name resolution",
            ],
            "answer": 1,
            "explanation": "L4 sees only IP, port and TCP. Anything where routing depends on content, plus TLS termination and header rewriting, needs L7. Most real systems run L4 at the edge for volume and L7 behind it for policy.",
            "section": "mental-model",
            "concept": "load-balancing.l4-vs-l7",
        },
        {
            "key": "default-algorithm",
            "kind": "choice",
            "prompt": "Your stateless HTTP service has requests ranging from 5 ms to 3 s. Which algorithm is the sensible default, and what goes wrong with round robin here?",
            "options": [
                "Round robin; nothing goes wrong when the servers are identical",
                "Least connections; round robin keeps feeding a node stuck on slow requests because it is simply next",
                "Consistent hashing; it keeps each client on the same node",
                "Weighted round robin; the weights absorb the slow requests",
            ],
            "answer": 1,
            "explanation": "Round robin fails when request cost varies: one node picks up three slow requests and still receives new ones. Least connections tracks actual load and is the best general default.",
            "section": "how-it-works",
            "concept": "load-balancing.algorithm-choice",
            "mistake": "load-balancing.round-robin-variable-cost",
        },
        {
            "key": "readiness-vs-liveness",
            "kind": "choice",
            "prompt": "A node's connection pool is exhausted and its cache is cold, but the process itself is fine. Which health check should it fail, and what should follow?",
            "options": [
                "Liveness, so the orchestrator restarts it",
                "Readiness, so the balancer stops sending it requests without killing it",
                "Both, to be safe",
                "Neither; the balancer will notice through error rates",
            ],
            "answer": 1,
            "explanation": "Failing liveness means restart me. Failing readiness means stop sending me requests but do not kill me. An exhausted pool or cold cache is a readiness problem; restarting it would only make things worse.",
            "section": "how-it-works",
            "concept": "load-balancing.readiness-vs-liveness",
            "mistake": "load-balancing.restart-on-readiness",
        },
        {
            "key": "draining-sequence",
            "kind": "short_answer",
            "prompt": "Every deploy produces a burst of 502s because the old process is simply killed. Describe the removal sequence that makes deploys invisible to users.",
            "options": [],
            "answer": None,
            "model_answer": "Connection draining: 1) the node fails readiness, 2) the load balancer stops sending it new requests, 3) in-flight requests complete up to a drain timeout, 4) only then does the process exit.",
            "explanation": "Without draining, every deploy, scale-in and spot reclamation drops requests. It is one of the most common and most preventable sources of error budget consumption.",
            "section": "how-it-works",
            "concept": "load-balancing.draining",
            "mistake": "load-balancing.no-draining",
        },
        {
            "key": "proxy-retries",
            "kind": "spot_mistake",
            "prompt": "A gateway is configured to retry any request that times out, up to three times, regardless of method or error code. What is wrong?",
            "options": [
                "Nothing; retries recover transient failures",
                "It retries non-idempotent requests and, with no budget, doubles load exactly when the fleet is struggling",
                "Three is too few; five attempts is the standard",
                "Retries belong in the client, never in a proxy",
            ],
            "answer": 1,
            "explanation": "Safe proxy retries: idempotent requests only, only on connection failures and 503, with a retry budget such as 10% of requests so retries cannot amplify an outage. Retrying timeouts on any method can duplicate work.",
            "section": "design-decisions",
            "concept": "load-balancing.retry-budget",
            "mistake": "load-balancing.retry-amplification",
        },
        {
            "key": "aggressive-checks",
            "kind": "choice",
            "prompt": "You set health checks to every 1 second with ejection after a single failure. What trade-off have you made?",
            "options": [
                "Faster detection, at the risk of flapping: a blip ejects healthy nodes, which can cascade if enough capacity leaves",
                "Lower monitoring cost, because fewer checks are needed overall",
                "None; faster detection is strictly better",
                "Slower deploys, because draining now waits for more checks",
            ],
            "answer": 0,
            "explanation": "Fast detection versus flapping. A typical shape is a 2 to 5 second interval, 2 to 3 consecutive failures to eject, and more successes to reinstate, so a transient blip does not remove half the fleet.",
            "section": "trade-offs",
            "concept": "load-balancing.health-check-aggressiveness",
            "mistake": "load-balancing.flapping",
        },
        {
            "key": "fast-failing-node",
            "kind": "choice",
            "prompt": "One of 30 nodes has a full disk; it returns 500 in 3 ms while healthy nodes take 50 ms. Under least connections, what happens to its share of traffic before ejection?",
            "options": [
                "It drops, because errors count as active failures",
                "It rises, because fast failures free connections quickly so it always looks least loaded",
                "It stays the same, since least connections ignores latency",
                "It is ejected on the first error by passive checks",
            ],
            "answer": 1,
            "explanation": "The fastest node is the broken one. Least connections and least response time both send it more traffic. The fix is outlier detection on error rate plus a readiness check that inspects disk and dependencies.",
            "section": "common-failure-modes",
            "concept": "load-balancing.fast-failure-attracts-traffic",
            "mistake": "load-balancing.errors-look-like-capacity",
        },
        {
            "key": "deep-health-check",
            "kind": "choice",
            "prompt": "Every node's health check runs a query against the shared database. The database has a 10 second blip. What happens?",
            "options": [
                "Only nodes with open transactions are ejected",
                "The whole fleet fails its checks at once and the balancer takes everything out of rotation",
                "Nothing; health check results are cached by the balancer",
                "The database is marked unhealthy and the nodes keep serving",
            ],
            "answer": 1,
            "explanation": "A health check that depends on the shared database creates correlated ejection. Exercise critical dependencies shallowly so one database blip does not become a total outage.",
            "section": "common-mistakes",
            "concept": "load-balancing.health-check-depth",
            "mistake": "load-balancing.correlated-ejection",
        },
    ],
    "sd-object-storage": [
        {
            "key": "not-a-filesystem",
            "kind": "choice",
            "prompt": "A team plans to append lines to a 2 GB log object and to list the 'directory' logs/2026/ that holds 40 million objects. What does the object storage model say?",
            "options": [
                "Both work; objects are files and prefixes are directories",
                "Objects are immutable so you replace, not append; prefixes are conventions, so that listing is slow and paginated",
                "Appending works but listing needs versioning enabled",
                "Listing is fast because keys are indexed; appending needs multipart",
            ],
            "answer": 1,
            "explanation": "Object storage is a key-to-bytes map with a flat namespace: no partial updates, no real directories, no queries. Listing a prefix with millions of objects as if it were a directory is a known failure mode.",
            "section": "mental-model",
            "concept": "sd-object-storage.not-a-filesystem",
            "mistake": "sd-object-storage.treats-as-filesystem",
        },
        {
            "key": "upload-flow",
            "kind": "choice",
            "prompt": "A user uploads a 5 GB file. Where do the bytes go, and what does your API do?",
            "options": [
                "Bytes stream through the API, which writes them to storage and then the metadata row",
                "The API authorises, writes a pending metadata row and returns a pre-signed URL; the client PUTs bytes to storage",
                "The API stores the bytes as a blob column and later moves them to storage",
                "The client uploads to the CDN, which forwards the bytes to the API",
            ],
            "answer": 1,
            "explanation": "Bytes never pass through the application tier. The API handles only JSON: authorise, create a pending row, issue a short-lived pre-signed URL scoped to one key, then mark the row ready on the storage event.",
            "section": "how-it-works",
            "concept": "sd-object-storage.presigned-upload",
            "mistake": "sd-object-storage.bytes-through-api",
        },
        {
            "key": "why-multipart",
            "kind": "choice",
            "prompt": "Why use multipart upload for a 50 GB file on a flaky mobile connection?",
            "options": [
                "Each part is uploaded and retried independently, and parts can go in parallel",
                "It compresses the file before upload so less data is sent",
                "It lets the API validate each part inline before storage accepts it",
                "It removes the need for a pre-signed URL",
            ],
            "answer": 0,
            "explanation": "The file is split into parts of roughly 5 to 100 MB, each uploaded and retried on its own, then completed with a manifest. That is what lets a huge upload survive a dropped connection and resume.",
            "section": "how-it-works",
            "concept": "sd-object-storage.multipart",
        },
        {
            "key": "private-downloads",
            "kind": "spot_mistake",
            "prompt": "To serve private files, a design has the API check permissions on each download and then stream the object through the API to the client. What is wrong?",
            "options": [
                "Nothing; that is the only way to enforce permissions",
                "It reintroduces the bandwidth problem; check once and return a short-lived signed CDN URL instead",
                "Permissions should be enforced by the CDN, not the API",
                "The bucket should simply be made public for simplicity",
            ],
            "answer": 1,
            "explanation": "Proxying downloads puts the bytes back through your servers. Do the authorisation check once, then issue a signed URL with a short expiry, served through a CDN.",
            "section": "design-decisions",
            "concept": "sd-object-storage.signed-download-urls",
            "mistake": "sd-object-storage.proxy-downloads",
        },
        {
            "key": "archive-thumbnails",
            "kind": "choice",
            "prompt": "A lifecycle rule moves every object to the archive tier after 30 days. Product thumbnails are read constantly for years. What happens?",
            "options": [
                "Costs fall, because archive is the cheapest tier",
                "Thumbnail reads become slow (minutes to hours) and retrieval fees cost more than the rule saves",
                "Nothing; archive reads are immediate on modern providers",
                "The thumbnails are deleted after 30 days",
            ],
            "answer": 1,
            "explanation": "Archive tiers are dramatically cheaper to store and slow and expensive to read. A lifecycle rule that archives frequently-read data costs more than it saves; tier by access pattern.",
            "section": "trade-offs",
            "concept": "sd-object-storage.storage-classes",
            "mistake": "sd-object-storage.archive-hot-data",
        },
        {
            "key": "orphaned-object",
            "kind": "choice",
            "prompt": "An upload to storage succeeded but the metadata write failed. What is the state, and what fixes it?",
            "options": [
                "An orphaned object nobody knows exists; a reconciliation sweep over both sides",
                "Orphaned metadata; delete the row",
                "Nothing is wrong, the object will appear in listings anyway",
                "Storage rolls the upload back automatically",
            ],
            "answer": 0,
            "explanation": "The database is the source of truth for what exists. Orphans occur in both directions, so a sweeper reconciles metadata against objects and objects against metadata.",
            "section": "common-failure-modes",
            "concept": "sd-object-storage.reconciliation",
            "mistake": "sd-object-storage.no-reconciliation",
        },
        {
            "key": "presigned-scope",
            "kind": "choice",
            "prompt": "A pre-signed upload URL is valid for 7 days, allows any key under the user's prefix and has no size limit. What is the risk?",
            "options": [
                "None; the user owns that prefix anyway",
                "It is a security incident waiting to happen; scope it to one key, one method, a maximum size and minutes of expiry",
                "Uploads will fail because providers reject long-lived URLs",
                "Storage cost rises because of the long expiry",
            ],
            "answer": 1,
            "explanation": "Over-permissive pre-signed URLs and public buckets are still among the most common real-world data exposures. Keep URLs short, narrow and size-bounded.",
            "section": "common-failure-modes",
            "concept": "sd-object-storage.presigned-scope",
            "mistake": "sd-object-storage.broad-presigned-url",
        },
        {
            "key": "halve-the-bill",
            "kind": "short_answer",
            "prompt": "A media product's storage bill grows every month with no policy in place. Name three levers from the lesson that would cut it.",
            "options": [],
            "answer": None,
            "model_answer": "Lifecycle tiering (standard, then infrequent access, then archive, then delete); expire old versions and derived renditions that can be regenerated on demand; deduplicate with content-addressed keys; use better compression and formats; find the few prefixes that hold most of the bytes.",
            "explanation": "No lifecycle policy means unbounded growth. Lifecycle rules and storage classes are the main cost lever and are worth naming unprompted.",
            "section": "common-mistakes",
            "concept": "sd-object-storage.cost-levers",
            "mistake": "sd-object-storage.no-lifecycle",
        },
    ],
    "event-driven-architecture": [
        {
            "key": "command-in-disguise",
            "kind": "spot_mistake",
            "prompt": "A checkout service publishes a message named SendWelcomeEmail to a topic and calls it event-driven. What is wrong?",
            "options": [
                "Nothing; any consumer can subscribe to it",
                "It names the reaction, not the fact; it is a command in an event's clothing that re-couples publisher and consumer",
                "Events must carry the full order state, and this one does not",
                "Email must always be a synchronous call",
            ],
            "answer": 1,
            "explanation": "Events are past-tense facts (OrderPlaced); commands are directed requests (SendEmail). Publishing a command as an event means the publisher again knows what the consumer should do.",
            "section": "mental-model",
            "concept": "event-driven-architecture.events-vs-commands",
            "mistake": "event-driven-architecture.command-as-event",
        },
        {
            "key": "dual-write",
            "kind": "choice",
            "prompt": "The order service commits the order to its database, then in a second step publishes OrderPlaced to the broker. What can go wrong, and what fixes it?",
            "options": [
                "Duplicate events; fix with consumer deduplication",
                "The commit succeeds but the publish fails, leaving downstream permanently wrong; fix with a transactional outbox or CDC",
                "The event is published before the commit; fix by publishing after the commit",
                "Nothing; brokers are durable",
            ],
            "answer": 1,
            "explanation": "This is a dual write and it fails partially. The outbox inserts the event in the same transaction as the state change and a relay publishes it; CDC reads the replication log. Either way the event exists if and only if the change committed.",
            "section": "how-it-works",
            "concept": "event-driven-architecture.outbox",
            "mistake": "event-driven-architecture.dual-write",
        },
        {
            "key": "notification-amplifier",
            "kind": "choice",
            "prompt": "Six consumers each call the order service for details every time they receive an OrderPlaced event containing only an order_id. Which event style fixes the load, and what does it cost?",
            "options": [
                "Delta events; they are the most compact",
                "Event-carried state, so consumers do not call back; the cost is larger, possibly stale payloads and schema coupling",
                "Notification events with a cache in front of the order service",
                "Batching the notifications hourly",
            ],
            "answer": 1,
            "explanation": "Notification events turn every consumer into a callback, a load amplifier. Event-carried state is the usual default; include a version and timestamp so late or duplicate events can be discarded.",
            "section": "how-it-works",
            "concept": "event-driven-architecture.event-content-style",
            "mistake": "event-driven-architecture.notification-callback-storm",
        },
        {
            "key": "choreography-or-orchestration",
            "kind": "choice",
            "prompt": "Order fulfilment has six steps, compensation on failure, deadlines, and support staff who ask 'where is order 123?'. Choreography or orchestration?",
            "options": [
                "Choreography, for maximum decoupling",
                "Orchestration: a coordinator makes the flow visible and drives compensation, at the cost of a central component",
                "Neither; make the six calls synchronous",
                "Choreography with a shared log table for support",
            ],
            "answer": 1,
            "explanation": "Choreography suits simple fan-out where nobody needs the overall outcome. A multi-step business process with compensation and state anyone might ask about is an orchestration problem.",
            "section": "how-it-works",
            "concept": "event-driven-architecture.choreography-vs-orchestration",
        },
        {
            "key": "event-or-call",
            "kind": "short_answer",
            "prompt": "State the rule for deciding whether an interaction should be an event or a synchronous call. Then apply it to payment capture at checkout and to updating the search index.",
            "options": [],
            "answer": None,
            "model_answer": "Use an event when the publisher does not need the outcome to respond; keep a synchronous call when the caller must know the result now. Payment capture at checkout stays synchronous because checkout must know it succeeded. Updating the search index becomes an event because checkout does not need to wait for it.",
            "explanation": "Authorisation, payment capture and inventory reservation need the result now. Notifications, indexing, analytics and downstream workflows do not.",
            "section": "design-decisions",
            "concept": "event-driven-architecture.event-or-sync",
            "mistake": "event-driven-architecture.everything-is-an-event",
        },
        {
            "key": "visible-gap",
            "kind": "choice",
            "prompt": "After the move to events, a user sees 'order confirmed' while the warehouse has not yet received the order. How should you treat this?",
            "options": [
                "As a bug; make the warehouse consumer synchronous",
                "As an explicit product decision: say what the user sees in the gap and keep the UI honest about it",
                "As impossible if the broker is fast enough",
                "As something retries will remove",
            ],
            "answer": 1,
            "explanation": "Eventual consistency is now user-visible: 'placed' and 'reflected everywhere' are different moments. State the gap and what the user sees in it rather than pretending it is not there.",
            "section": "trade-offs",
            "concept": "event-driven-architecture.user-visible-eventual-consistency",
            "mistake": "event-driven-architecture.gap-is-a-bug",
        },
        {
            "key": "event-cycle",
            "kind": "choice",
            "prompt": "Consumer A emits an event that triggers B, and B emits an event that triggers A. A bad deploy goes out. What happens?",
            "options": [
                "The broker detects the cycle and drops the events",
                "An infinite loop generating millions of events, an event storm",
                "Nothing, as long as both consumers are idempotent",
                "Ordering breaks but volume is unaffected",
            ],
            "answer": 1,
            "explanation": "Event storms and cycles are a listed failure mode: one bad deploy becomes an infinite loop. Idempotency does not help because each event is new, not a duplicate.",
            "section": "common-failure-modes",
            "concept": "event-driven-architecture.event-storms",
        },
        {
            "key": "ordering",
            "kind": "choice",
            "prompt": "A parallel consumer processes OrderCancelled before OrderPlaced for the same order. Which two things prevent this?",
            "options": [
                "A partition key per order so its events stay in one partition, plus a version field so stale events are ignored",
                "A global sequence number issued by the broker",
                "Retrying the cancel until the placed event arrives",
                "Making the consumer single-threaded across all orders",
            ],
            "answer": 0,
            "explanation": "Assuming ordered delivery without a partition key is a common mistake. Partition by entity key and have consumers check a version so redelivery or parallelism cannot apply a stale update over a newer one.",
            "section": "common-mistakes",
            "concept": "event-driven-architecture.ordering",
            "mistake": "event-driven-architecture.assumed-ordering",
        },
    ],
    "sd-resilience-patterns": [
        {
            "key": "no-timeout-optional",
            "kind": "choice",
            "prompt": "The recommendations widget calls a service with no timeout and no fallback. The widget is optional to the page. What can this dependency do to your service?",
            "options": [
                "Nothing worse than a missing widget",
                "Take the whole service down: hung calls hold threads until the pool is exhausted",
                "Only slow the widget itself",
                "Raise error rates without affecting latency",
            ],
            "answer": 1,
            "explanation": "A dependency with no timeout and no fallback can take you down, however optional it is. Every call needs the four decisions: timeout, retry policy, circuit breaker, fallback.",
            "section": "mental-model",
            "concept": "sd-resilience-patterns.four-decisions",
            "mistake": "sd-resilience-patterns.optional-means-harmless",
        },
        {
            "key": "timeout-budgets",
            "kind": "spot_mistake",
            "prompt": "The frontend waits 10 s for the API, the API waits 15 s for its downstream, and the downstream waits 20 s for the database. What is wrong?",
            "options": [
                "Nothing; longer inner timeouts are safer",
                "Each layer's timeout must fit inside its caller's budget; here inner layers work for callers that already gave up",
                "The frontend timeout is too short for the chain",
                "All three timeouts should be equal",
            ],
            "answer": 1,
            "explanation": "Timeouts must shrink as you go down: if the frontend waits 10 s, the API should wait about 3 s and the downstream about 1 s. Deadline propagation passes the remaining budget so nobody spends capacity on abandoned work.",
            "section": "how-it-works",
            "concept": "sd-resilience-patterns.timeout-budgets",
            "mistake": "sd-resilience-patterns.inner-timeout-longer",
        },
        {
            "key": "retry-jitter-budget",
            "kind": "choice",
            "prompt": "1,000 clients hit the same transient failure at the same instant and all retry after exactly 100 ms, then 200 ms, then 400 ms. What is missing?",
            "options": [
                "A longer base delay",
                "Jitter, so the retries do not land together, plus a retry budget that caps retries at a share of total requests",
                "More attempts before giving up",
                "Retries at every layer, not just one",
            ],
            "answer": 1,
            "explanation": "Backoff alone keeps clients synchronised. Full jitter spreads them out, a budget (for example 10% of requests) bounds the damage in a widespread failure, and retries should live at one layer only.",
            "section": "how-it-works",
            "concept": "sd-resilience-patterns.retry-storms",
            "mistake": "sd-resilience-patterns.backoff-without-jitter",
        },
        {
            "key": "breaker-tuning",
            "kind": "choice",
            "prompt": "A circuit breaker opens after 2 failed calls, counted raw. A low-traffic endpoint gets 3 requests per minute. What goes wrong?",
            "options": [
                "Nothing; low traffic means few errors",
                "Two unlucky errors open the circuit; trip on error rate over a rolling window with a minimum request volume instead",
                "The breaker never opens because the volume is too low",
                "The half-open state is skipped",
            ],
            "answer": 1,
            "explanation": "Trip on rate, not count, with a minimum volume, and consider tripping on latency too, because slow is the dangerous case. Thresholds that are too sensitive trip on normal variance.",
            "section": "how-it-works",
            "concept": "sd-resilience-patterns.circuit-breaker",
            "mistake": "sd-resilience-patterns.breaker-on-raw-count",
        },
        {
            "key": "shared-pool",
            "kind": "choice",
            "prompt": "When the recommendation service slows down, endpoints that never call it start failing too. What mechanism is missing?",
            "options": [
                "A circuit breaker on those unrelated endpoints",
                "Bulkheads: a separate pool and concurrency limit per dependency, so one slow dependency cannot consume every thread",
                "A CDN in front of the page",
                "Longer timeouts on the unrelated endpoints",
            ],
            "answer": 1,
            "explanation": "A shared thread pool lets one slow dependency starve all endpoints. Bulkheads isolate resources like ship compartments: a flooded compartment does not sink the vessel.",
            "section": "common-failure-modes",
            "concept": "sd-resilience-patterns.bulkheads",
            "mistake": "sd-resilience-patterns.shared-thread-pool",
        },
        {
            "key": "fail-open-closed",
            "kind": "choice",
            "prompt": "The authorisation service is unreachable, and separately the recommendation service is unreachable. Fail open or closed for each?",
            "options": [
                "Open for both, to keep the product usable",
                "Closed for both, to be safe",
                "Authorisation closed, since failing open is a security hole; recommendations open with a fallback, to keep the feature",
                "Authorisation open, recommendations closed",
            ],
            "answer": 2,
            "explanation": "Decide per dependency and say so. Optional dependencies get short timeouts, no retries, an aggressive breaker and a fallback; critical ones get a clear failure story.",
            "section": "design-decisions",
            "concept": "sd-resilience-patterns.fail-open-vs-closed",
            "mistake": "sd-resilience-patterns.all-dependencies-equal",
        },
        {
            "key": "silent-fallback",
            "kind": "choice",
            "prompt": "Fallbacks keep the product usable when a dependency is down. What is their downside, and what must accompany every fallback?",
            "options": [
                "They add latency; pair them with a cache",
                "They can mask a real problem; alert whenever a fallback is in use",
                "They double infrastructure cost; pair them with a budget",
                "They break idempotency; pair them with keys",
            ],
            "answer": 1,
            "explanation": "A silent fallback means the system degrades and nobody notices for a week. Fallback usage rate is one of the signals to monitor.",
            "section": "trade-offs",
            "concept": "sd-resilience-patterns.fallback-alerting",
            "mistake": "sd-resilience-patterns.silent-fallbacks",
        },
        {
            "key": "slow-not-down",
            "kind": "short_answer",
            "prompt": "Describe the mechanism by which a dependency that is slow, not down, takes out the service that calls it. Then name two patterns that break that mechanism.",
            "options": [],
            "answer": None,
            "model_answer": "Threads block waiting on the slow dependency, connection and thread pools fill, queues grow, health checks time out, and the failure spreads upstream through resource exhaustion rather than error codes. Patterns that break it: timeouts (with deadline propagation), bulkheads that isolate pools per dependency, and circuit breakers that fail fast instead of accumulating blocked threads.",
            "explanation": "Talking only about a dependency being down and never about it being slow is a common mistake. Slowness is what kills systems.",
            "section": "common-mistakes",
            "concept": "sd-resilience-patterns.slow-is-worse-than-down",
            "mistake": "sd-resilience-patterns.only-considers-down",
        },
    ],
    "sd-multi-region": [
        {
            "key": "where-most-stop",
            "kind": "choice",
            "prompt": "A product wants fast reads for users on three continents and a consistency model the team can still reason about. Which topology does the lesson say most products stop at?",
            "options": [
                "Single region, multi-AZ",
                "Active-passive with a warm standby",
                "Active-active with a single write region: reads local everywhere, writes routed to one region",
                "Active-active multi-write with conflict resolution",
            ],
            "answer": 2,
            "explanation": "Read replication across regions is a normal engineering project. Accepting writes in two regions is a different discipline because it means conflicts, so most products route writes centrally and keep reads local.",
            "section": "mental-model",
            "concept": "sd-multi-region.topologies",
            "mistake": "sd-multi-region.multi-write-by-default",
        },
        {
            "key": "multi-az-first",
            "kind": "choice",
            "prompt": "A team proposes two regions because 'we need high availability'. There is no latency or data residency requirement. What should you say first?",
            "options": [
                "Go active-active multi-write for instant failover",
                "Three zones in one region replicate synchronously and survive a datacentre loss for far less; ask what region two is for",
                "Use DNS failover between the two regions",
                "Multi-region is always required for high availability",
            ],
            "answer": 1,
            "explanation": "Most availability requirements are met by multi-AZ with almost none of the consistency problems. Multi-region is for latency, region loss or residency, and the reason decides the design.",
            "section": "how-it-works",
            "concept": "sd-multi-region.multi-az-first",
            "mistake": "sd-multi-region.region-when-az-suffices",
        },
        {
            "key": "rpo-from-lag",
            "kind": "short_answer",
            "prompt": "Asynchronous replication to the standby region lags by about 8 seconds. The primary region is lost without warning. What is your RPO, and what would a zero RPO cost?",
            "options": [],
            "answer": None,
            "model_answer": "RPO is about 8 seconds of writes, because with asynchronous replication the data you lose on an unplanned failover is exactly the replication lag. Zero RPO needs synchronous cross-region replication, which adds a full 60 to 200 ms round trip to every write.",
            "explanation": "RPO is how much data you may lose, RTO is how long until service returns. The physics of cross-region round trips is what makes zero RPO expensive.",
            "section": "how-it-works",
            "concept": "sd-multi-region.rpo-equals-lag",
            "mistake": "sd-multi-region.async-means-no-loss",
        },
        {
            "key": "avoid-conflicts",
            "kind": "choice",
            "prompt": "Two regions must both accept writes. Which data strategy avoids write conflicts entirely, and what is its limitation?",
            "options": [
                "Last-write-wins on every table; no limitation",
                "Geo-partitioning: each record has a home region and is written only there; access from elsewhere is a slower read",
                "A globally consistent database; no limitation beyond licence cost",
                "CRDTs on every table; they only work for counters",
            ],
            "answer": 1,
            "explanation": "European users write in Europe, American users in America, so no record is written in two places and there are no conflicts by construction. It is the best default for most consumer products and often a legal requirement.",
            "section": "how-it-works",
            "concept": "sd-multi-region.geo-partitioning",
        },
        {
            "key": "travelling-user",
            "kind": "choice",
            "prompt": "In a geo-partitioned design, a European user travels to Asia for a month. What should happen to their data and requests?",
            "options": [
                "Silently migrate their data to the Asia region for speed",
                "Their data stays in Europe; their reads are slower from Asia and they are not silently migrated",
                "Cache their whole profile in Asia and accept writes there",
                "Block access until they return to Europe",
            ],
            "answer": 1,
            "explanation": "Naming the moving user shows you have thought past the diagram. Silent migration would create two homes for one record and reintroduce the conflict problem.",
            "section": "design-decisions",
            "concept": "sd-multi-region.user-who-moves",
            "mistake": "sd-multi-region.silent-migration",
        },
        {
            "key": "surprise-line-item",
            "kind": "choice",
            "prompt": "The first multi-region bill arrives. Which line item does the lesson say surprises people, and roughly what does the overall bill look like?",
            "options": [
                "Compute in the second region; total is about 1.2x",
                "Cross-region data transfer; total is roughly double the infrastructure plus transfer",
                "Storage duplication; total is about 1.5x",
                "The global load balancer; total is about 3x",
            ],
            "answer": 1,
            "explanation": "Roughly double the infrastructure plus inter-region transfer, which can exceed compute costs. Naming transfer specifically shows you have seen a real bill.",
            "section": "trade-offs",
            "concept": "sd-multi-region.cost",
        },
        {
            "key": "untested-multi-write",
            "kind": "spot_mistake",
            "prompt": "Design: two regions both accept writes for the same records, replicate asynchronously both ways, have no conflict handling because 'writes rarely collide', and failover has never been rehearsed. What is the biggest problem?",
            "options": [
                "Nothing; collisions are rare enough to ignore",
                "Split brain with no reconciliation, plus an untested failover; geo-partition or name a conflict rule, and run drills",
                "Asynchronous replication is the flaw; make it synchronous",
                "Two regions is too few; three are needed for a quorum",
            ],
            "answer": 1,
            "explanation": "Both regions accepting writes with no reconciliation is split brain, and an untested failover does not work. Also plan failback: the recovered region holds writes the promoted one never saw.",
            "section": "common-failure-modes",
            "concept": "sd-multi-region.split-brain",
            "mistake": "sd-multi-region.no-conflict-story",
        },
        {
            "key": "forgotten-regional",
            "kind": "choice",
            "prompt": "The database is replicated to region B, but the cache and the nightly invoice cron job exist only in region A. Region A fails and you promote B. What happens?",
            "options": [
                "Everything works, because the database is replicated",
                "Invoices stop and B's cold cache hammers the database; every stateful or scheduled component needs a regional story",
                "The cron job replicates along with the database",
                "The cache warms itself from region A's snapshots",
            ],
            "answer": 1,
            "explanation": "Forgetting that caches, queues and scheduled jobs are regional is a common mistake. A forgotten component that exists in one region is usually why an untested failover fails.",
            "section": "common-mistakes",
            "concept": "sd-multi-region.everything-regional",
            "mistake": "sd-multi-region.forgotten-regional-component",
        },
    ],
    "sd-geospatial-index": [
        {
            "key": "two-stages",
            "kind": "choice",
            "prompt": "A candidate says 'I index by geohash, so the query returns exactly the drivers within 2 km'. What is missing?",
            "options": [
                "Nothing; geohash cells are sized to the radius",
                "The index only finds the rough area; an exact distance check on the candidates is always the second stage",
                "A second index on longitude",
                "Sorting the geohash strings before the scan",
            ],
            "answer": 1,
            "explanation": "Two stages, always: the cell index gives a rough superset in one lookup, then you compute exact distance on the few hundred candidates and drop those outside the circle.",
            "section": "mental-model",
            "concept": "sd-geospatial-index.two-stages",
            "mistake": "sd-geospatial-index.no-exact-distance-step",
        },
        {
            "key": "lat-lng-band",
            "kind": "choice",
            "prompt": "Why does a compound index on (latitude, longitude) not answer 'within 2 km' efficiently?",
            "options": [
                "Floating point columns cannot be indexed",
                "It is sorted by latitude first, so it yields a band across the world that is still scanned row by row for longitude",
                "It works, but only for radii under 1 km",
                "Compound indexes cannot do range queries",
            ],
            "answer": 1,
            "explanation": "Nearby is two ranges at once. A one-column ordering gives a horizontal band holding millions of points. The fix is to encode both numbers into one key that keeps nearby points together.",
            "section": "how-it-works",
            "concept": "sd-geospatial-index.why-plain-index-fails",
            "mistake": "sd-geospatial-index.lat-lng-index",
        },
        {
            "key": "shared-prefix",
            "kind": "choice",
            "prompt": "Two points share the first 5 characters of their geohash. What do you know, and what does that let the database do?",
            "options": [
                "They are within 5 metres; the database can skip the distance check",
                "They are in the same 5-character cell; a prefix scan with a B-tree index finds everything in that cell",
                "They have the same latitude; the database can use the latitude index",
                "They are in adjacent cells; the database must scan both",
            ],
            "answer": 1,
            "explanation": "A shared prefix means a shared bigger cell, so 'everything in this cell' is WHERE geohash LIKE 'prefix%'. The converse is not true: points 20 m apart across a border can differ in the last or even first character.",
            "section": "how-it-works",
            "concept": "sd-geospatial-index.geohash-prefix",
        },
        {
            "key": "nine-cells",
            "kind": "choice",
            "prompt": "A driver 30 m from the rider sits just across a cell border. Why is he still found, and what precision do you choose for a 2 km radius?",
            "options": [
                "Because geohash cells overlap; precision does not matter",
                "Because you search the query cell plus its 8 neighbours; pick cells about 1 to 2 km wide so 9 cells cover the circle",
                "Because you search the parent cell one character shorter",
                "Because the exact-distance step scans all drivers in the city",
            ],
            "answer": 1,
            "explanation": "Cells have hard borders. Nine prefix scans are still cheap. Matching the cell size to the radius keeps the 9 cells covering the circle without pulling in a whole region.",
            "section": "how-it-works",
            "concept": "sd-geospatial-index.neighbour-cells",
            "mistake": "sd-geospatial-index.single-cell-search",
        },
        {
            "key": "moving-drivers",
            "kind": "choice",
            "prompt": "One million drivers ping every 4 seconds, around 250,000 writes per second. How do you keep the index correct without melting a disk index?",
            "options": [
                "Write every ping to the geohash column with a B-tree index",
                "Keep current positions in memory, update the cell only when it changes, and batch history to a log",
                "Drop pings until the rate is manageable",
                "Shard the disk index by driver id",
            ],
            "answer": 1,
            "explanation": "Most pings do not change the cell. The live store holds only current positions and can be lost, because the next round of pings rebuilds it. History goes to a log for trips and billing.",
            "section": "how-it-works",
            "concept": "sd-geospatial-index.moving-objects",
            "mistake": "sd-geospatial-index.pings-to-disk",
        },
        {
            "key": "nearby-query-walkthrough",
            "kind": "short_answer",
            "prompt": "Walk through the 'drivers within 2 km of the rider' query end to end, naming which step is rough and which is exact.",
            "options": [],
            "answer": None,
            "model_answer": "Encode the rider's position to a geohash at the chosen precision; compute the 8 neighbour cells; fetch every driver in those 9 cells from the live in-memory index (the rough candidate set); compute exact distance to each candidate and drop those beyond 2 km (the exact step); rank the rest by distance, ETA, rating or car type; return the top N.",
            "explanation": "Fetching the 9 cells is cheap and rough. The distance check is exact. Candidates inside a searched cell but outside the circle are normal and expected.",
            "section": "how-it-works",
            "concept": "sd-geospatial-index.query-flow",
        },
        {
            "key": "uneven-density",
            "kind": "choice",
            "prompt": "A 1 km cell in Manhattan holds thousands of restaurants; the same cell in the desert holds none. Which structure adapts, and what does it cost?",
            "options": [
                "Geohash at a finer precision everywhere; a bigger index",
                "A quadtree: it splits only boxes that are too full, but it is an in-memory tree that must be rebalanced as points move",
                "Redis GEO; it is in memory",
                "PostGIS; it supports polygons",
            ],
            "answer": 1,
            "explanation": "A geohash grid uses one cell size everywhere. A quadtree gives dense areas many small boxes and empty land one big box, so a search reads about the same number of points anywhere.",
            "section": "trade-offs",
            "concept": "sd-geospatial-index.geohash-vs-quadtree",
        },
        {
            "key": "equal-area-shards",
            "kind": "spot_mistake",
            "prompt": "A design shards the live driver index into equal-area regions and says load balances itself. What is wrong?",
            "options": [
                "Nothing; equal areas give equal load",
                "Density is uneven: Manhattan at 6 pm outnumbers all of Montana, so one shard melts; split hot regions into small shards",
                "Nearby queries would have to cross every shard",
                "Regions must be sharded by driver id, not geography",
            ],
            "answer": 1,
            "explanation": "Sharding by equal areas and being surprised by a hot city is a listed mistake. Splitting hot regions is the quadtree idea one level up; a query still touches one shard, or two near a border.",
            "section": "common-mistakes",
            "concept": "sd-geospatial-index.hot-city-shards",
            "mistake": "sd-geospatial-index.equal-area-sharding",
        },
    ],
    "sd-netflix": [
        {
            "key": "fixed-catalogue",
            "kind": "choice",
            "prompt": "The interviewer confirms the catalogue is tens of thousands of professionally produced titles released on a schedule. What does that let you do that a user-upload platform cannot?",
            "options": [
                "Skip adaptive bitrate streaming",
                "Pre-encode every title exhaustively and pre-position content at the edge before anyone requests it",
                "Rely on a single CDN provider",
                "Avoid DRM and licensing entirely",
            ],
            "answer": 1,
            "explanation": "This single fact changes the architecture. UGC cannot pre-encode per title or pre-position, because popularity is unknown at upload time and caches fill reactively.",
            "section": "step-1-clarify-the-requirements",
            "concept": "sd-netflix.fixed-catalogue",
            "mistake": "sd-netflix.youtube-answer",
        },
        {
            "key": "peak-egress",
            "kind": "choice",
            "prompt": "100M daily viewers, about 10% of them watching at peak, average bitrate 4 Mbps. What is peak egress?",
            "options": ["4 Tbps", "40 Tbps", "400 Gbps", "400 Tbps"],
            "answer": 1,
            "explanation": "10M concurrent streams times 4 Mbps is 40 Tbps. It is the same egress problem as YouTube, but with a known catalogue the content can be at the edge before it is requested.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-netflix.peak-bandwidth",
        },
        {
            "key": "playback-position-store",
            "kind": "choice",
            "prompt": "Playback position is 330,000 tiny writes per second keyed by (profile, title) with no transactional need. Which store, and why not the catalogue database?",
            "options": [
                "The relational catalogue database, since titles already live there",
                "A key-value store with last-write-wins and a write-behind cache; a relational primary would saturate on this write rate",
                "Object storage, one object per profile",
                "The CDN edge, since that is where playback happens",
            ],
            "answer": 1,
            "explanation": "Tiny value, high write rate, no transactions: the wrong shape for a relational primary. Write-behind is acceptable here because losing 30 seconds of position on a cache failure is fine.",
            "section": "step-4-data-model",
            "concept": "sd-netflix.playback-position",
            "mistake": "sd-netflix.position-in-relational-db",
        },
        {
            "key": "compute-vs-bandwidth",
            "kind": "choice",
            "prompt": "Why does the lesson call 'encoding compute is cheap relative to bandwidth' the central economic insight of this design?",
            "options": [
                "Because encoding runs on spare CDN capacity",
                "A title is encoded once and watched hundreds of millions of times, so per-title optimisation pays back in bandwidth",
                "Because storage of renditions is free",
                "Because viewers pay for their own bandwidth",
            ],
            "answer": 1,
            "explanation": "Per-title and per-shot encoding ladders save a large fraction of bandwidth at identical quality. The one-off encoding cost is amortised over every view, which is why spending heavily on it is right.",
            "section": "how-it-works",
            "concept": "sd-netflix.per-title-encoding",
            "mistake": "sd-netflix.fixed-encoding-ladder",
        },
        {
            "key": "stream-limit",
            "kind": "short_answer",
            "prompt": "How do you enforce a concurrent stream limit when apps crash and sessions never send 'ended'? Name the honest trade-off in your mechanism.",
            "options": [],
            "answer": None,
            "model_answer": "Each session holds a lease renewed by heartbeats and expiring after a few minutes of silence; the count is the number of unexpired leases. The trade-off: a user who force-quits occupies a slot for a few minutes. A shorter lease frees the slot sooner but risks ending sessions for viewers on flaky connections.",
            "explanation": "A start-minus-end counter drifts because sessions do not end cleanly. The lease length is a user-visible product decision hiding inside a technical mechanism.",
            "section": "evolution-under-pressure",
            "concept": "sd-netflix.session-leases",
            "mistake": "sd-netflix.counter-without-expiry",
        },
        {
            "key": "entitlement-per-segment",
            "kind": "spot_mistake",
            "prompt": "A design checks subscription, stream limit and regional licensing on every segment request so that revoked accounts stop instantly. What is wrong?",
            "options": [
                "Nothing; it is the most secure option",
                "At 10M streams that is millions of checks per second; check once at playback start and sign a short-lived manifest URL",
                "Entitlement should be enforced by the CDN provider",
                "Region should only be checked while browsing, never at playback",
            ],
            "answer": 1,
            "explanation": "Checking entitlement per segment creates an impossible request rate. Once per session, bound to a short-lived signed manifest, is correct and bounded. Playback start still re-checks region because a VPN can make browsing and playing disagree.",
            "section": "failure-modes",
            "concept": "sd-netflix.entitlement-once",
            "mistake": "sd-netflix.entitlement-per-segment",
        },
        {
            "key": "buffer-trade-off",
            "kind": "choice",
            "prompt": "The client buffers tens of seconds ahead to protect the rebuffer ratio. What is the cost of that choice?",
            "options": [
                "Wasted bandwidth when viewers abandon a title quickly",
                "Higher entitlement load, since each buffered segment is re-checked",
                "Slower playback start, because the whole buffer must fill first",
                "Larger storage at the edge",
            ],
            "answer": 0,
            "explanation": "Large buffers prevent rebuffering, the metric that matters most, and waste data when viewers leave. Startup begins at a conservative bitrate so the buffer does not delay the first frame.",
            "section": "trade-offs",
            "concept": "sd-netflix.buffering",
        },
        {
            "key": "single-cdn",
            "kind": "choice",
            "prompt": "One CDN provider has a regional outage. In the recommended design, what do viewers experience?",
            "options": [
                "An outage until DNS fails over to another provider",
                "At worst a brief quality dip: the manifest lists several CDNs, clients switch mid-stream, new sessions are steered away",
                "Playback stops until the manifest is refreshed",
                "Only offline downloads keep working",
            ],
            "answer": 1,
            "explanation": "Assuming a single CDN converts a provider incident into an outage. Multi-CDN steering with client-side switching is the payoff for the added complexity.",
            "section": "common-mistakes",
            "concept": "sd-netflix.multi-cdn",
            "mistake": "sd-netflix.single-cdn",
        },
    ],
    "sd-job-scheduler": [
        {
            "key": "exactly-once-response",
            "kind": "short_answer",
            "prompt": "The interviewer asks for exactly-once job execution. Give the response you would deliver: why it is impossible, and what you offer instead.",
            "options": [],
            "answer": None,
            "model_answer": "Exactly-once is not achievable because a worker can complete the work and die before acknowledging, or be paused past its lease and then finish. What I can guarantee is at-least-once delivery with a stable run_id, with idempotency keyed on that id as part of the job contract. For jobs that cannot be made idempotent, an at-most-once mode that does not retry, with the explicit risk that a run may be skipped.",
            "explanation": "Offering both modes and being honest about what each gives up is the complete answer, and it usually settles the level of the conversation.",
            "section": "step-1-clarify-the-requirements",
            "concept": "sd-job-scheduler.exactly-once-impossible",
            "mistake": "sd-job-scheduler.claims-exactly-once",
        },
        {
            "key": "concurrent-jobs",
            "kind": "choice",
            "prompt": "100,000 jobs fire per minute and the average job takes 5 seconds. Roughly how many jobs run concurrently, and what does that number size?",
            "options": [
                "About 1,700; the number of scheduler instances",
                "About 8,500; the worker fleet",
                "About 100,000; the dispatch queue depth",
                "About 500,000; the runs table",
            ],
            "answer": 1,
            "explanation": "100,000 per minute is about 1,700 executions per second; times 5 seconds is about 8,500 running at once. Workers are the scaling dimension and must be stateless and replaceable.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-job-scheduler.scale-arithmetic",
        },
        {
            "key": "unique-constraint",
            "kind": "choice",
            "prompt": "Two scheduler instances both decide job 42 is due at 09:00:00. What stops a duplicate run without a distributed lock?",
            "options": [
                "Leader election so only one scheduler runs",
                "A UNIQUE constraint on (job_id, scheduled_for, attempt): both insert, exactly one succeeds",
                "A Redis SETNX lock with a TTL around the insert",
                "Hash-partitioning the jobs so two schedulers never see the same job",
            ],
            "answer": 1,
            "explanation": "The database constraint provides the mutual exclusion, so schedulers can race harmlessly. Partitioning reduces wasted work but correctness never depends on it.",
            "section": "step-4-data-model",
            "concept": "sd-job-scheduler.unique-constraint",
            "mistake": "sd-job-scheduler.lock-for-correctness",
        },
        {
            "key": "missed-run-policy",
            "kind": "choice",
            "prompt": "The scheduler was down from 09:00 to 11:00. An hourly job processes a time window and must never leave a gap. Which missed-run policy fits it?",
            "options": [
                "Skip: run only the current occurrence",
                "Run once: a single catch-up run",
                "Backfill: run every missed occurrence",
                "Wait for an operator to decide",
            ],
            "answer": 2,
            "explanation": "Skip suits a cache refresh, run once suits most reporting, backfill suits windowed processing. The right answer is that the policy is configurable per job, which separates a scheduler from a cron loop.",
            "section": "how-it-works",
            "concept": "sd-job-scheduler.missed-runs",
            "mistake": "sd-job-scheduler.no-missed-run-policy",
        },
        {
            "key": "gc-pause-double-run",
            "kind": "choice",
            "prompt": "A worker is paused by garbage collection for 90 seconds, its lease expires, the reaper retries, then the worker wakes and completes too. Which mitigation is the only genuinely complete fix?",
            "options": [
                "The worker checks it still holds the lease before any side effect",
                "Doubling the lease duration",
                "Passing run_id as an idempotency key so the target itself deduplicates, which needs the target's cooperation",
                "Leader election among workers",
            ],
            "answer": 2,
            "explanation": "Checking the lease narrows the window but cannot close it. Only deduplication at the thing being called is complete, and saying that it requires cooperation from the target is a true and useful point.",
            "section": "evolution-under-pressure",
            "concept": "sd-job-scheduler.duplicate-execution",
            "mistake": "sd-job-scheduler.lease-check-is-enough",
        },
        {
            "key": "synchronised-retries",
            "kind": "spot_mistake",
            "prompt": "Design: every failed run retries on a fixed 60 second interval. A target service is down for ten minutes, 50,000 runs fail, then the target comes back. What happens, and what should change?",
            "options": [
                "It recovers smoothly, since retries are spread over the ten minutes",
                "All 50,000 runs retry in sync and knock the target over again; use backoff with jitter and a per-target circuit breaker",
                "The runs go straight to the dead-letter state",
                "The reaper spreads the retries automatically",
            ],
            "answer": 1,
            "explanation": "Fixed intervals produce synchronised storms. Backoff with jitter spreads retries; a breaker per target holds runs instead of burning attempts; the dead-letter alert should be on the rate, not each failure.",
            "section": "failure-modes",
            "concept": "sd-job-scheduler.retry-storm",
            "mistake": "sd-job-scheduler.fixed-retry-interval",
        },
        {
            "key": "short-lease",
            "kind": "choice",
            "prompt": "Leases are set to 30 seconds, but under load some jobs take 5 minutes. What do you get?",
            "options": [
                "Faster crash recovery with no downside",
                "Systematic duplicate execution: the reaper retries jobs that are still running",
                "Jobs silently skipped after the lease ends",
                "Workers refusing to accept long jobs",
            ],
            "answer": 1,
            "explanation": "Short leases recover quickly and cause duplicates for slow jobs; long leases are safe and delay recovery. Long jobs should heartbeat to extend the lease, with a hard timeout for hung jobs.",
            "section": "trade-offs",
            "concept": "sd-job-scheduler.lease-duration",
            "mistake": "sd-job-scheduler.lease-shorter-than-job",
        },
        {
            "key": "dependency-as-timing",
            "kind": "choice",
            "prompt": "Job B must run after job A finishes. A candidate schedules B ten minutes after A. What is wrong?",
            "options": [
                "Nothing, provided A always takes under ten minutes",
                "Dependencies are a workflow problem, not a timing one; the scheduler starts a workflow that tracks steps and failures",
                "B should be scheduled five minutes after A to be safe",
                "A and B should be merged into one job",
            ],
            "answer": 1,
            "explanation": "A DAG of jobs is a workflow engine. Encoding dependencies as delays breaks the first time A is slow or fails, and naming that is worth doing.",
            "section": "common-mistakes",
            "concept": "sd-job-scheduler.dependencies",
            "mistake": "sd-job-scheduler.dependency-as-delay",
        },
    ],
    "sd-leaderboard": [
        {
            "key": "ties",
            "kind": "choice",
            "prompt": "Two players both have 4,820 points. What rule do you agree in requirements, and what happens on the board if you ignore it?",
            "options": [
                "Random order; nothing visible happens",
                "Earlier score wins; if ignored, Redis orders by member name and the two players swap places on every refresh",
                "Higher player id wins; if ignored, one player is dropped",
                "Both share a rank and the next rank is skipped",
            ],
            "answer": 1,
            "explanation": "Fold time into the score: score times 2^20 plus (max_time minus time_of_score), so the main score dominates and the earlier score ranks higher among equals. Strip the time bits for display.",
            "section": "step-1-clarify-the-requirements",
            "concept": "sd-leaderboard.ties",
            "mistake": "sd-leaderboard.ties-by-member-name",
        },
        {
            "key": "write-rate",
            "kind": "choice",
            "prompt": "5M active players on a busy day, about 10 matches each. Roughly what peak write rate does the lesson derive, and what does it imply for the ranked structure?",
            "options": [
                "About 500 per second; a SQL index handles it",
                "About 5,000 per second; beyond a SQL rank query, so the sorted structure must live in memory",
                "About 50,000 per second; shard across ten nodes from day one",
                "About 5 per second; anything works",
            ],
            "answer": 1,
            "explanation": "50 million score updates a day is about 5,000 per second at peak. With 25M entries at 100 bytes the set is 2.5 GB, which fits one Redis node with little room, so plan to split.",
            "section": "step-2-estimate-the-scale",
            "concept": "sd-leaderboard.scale-arithmetic",
        },
        {
            "key": "rebuild-path",
            "kind": "short_answer",
            "prompt": "Redis loses the whole sorted set. Walk through how the board comes back and why no score is lost.",
            "options": [],
            "answer": None,
            "model_answer": "A replica takes over first. If both are lost, the score update stream is the source of truth: every score was appended to the durable log before ZADD. A consumer keeps the scores database built from the log, and a rebuild job replays the current period into a fresh sorted set in a few minutes. The set is only the fast view.",
            "explanation": "The stream is the truth, the sorted set is the fast view. Say the rebuild time; a rebuild job nobody has tested is a listed failure mode.",
            "section": "step-4-data-model",
            "concept": "sd-leaderboard.log-is-truth",
            "mistake": "sd-leaderboard.redis-is-truth",
        },
        {
            "key": "rank-is-position",
            "kind": "choice",
            "prompt": "Why does 'my rank' take about 25 steps in a sorted set of 25M players but a scan in SQL?",
            "options": [
                "Redis is in memory and SQL is on disk",
                "A skip list finds a position in O(log n) hops, while SQL answers rank by counting every row with a higher score",
                "SQL has no index on the score column",
                "Sorted sets store every rank precomputed",
            ],
            "answer": 1,
            "explanation": "Rank is a position, not a count. ZREVRANK walks about log n levels of the skip list; SELECT COUNT(*) WHERE score > mine walks millions of rows for a player near the bottom, on every read.",
            "section": "how-it-works",
            "concept": "sd-leaderboard.sorted-set",
            "mistake": "sd-leaderboard.sql-rank",
        },
        {
            "key": "period-keys",
            "kind": "choice",
            "prompt": "One sorted set holds all scores for all time, and the monthly reset deletes it. What is the trade-off versus one key per period?",
            "options": [
                "The single key uses less memory and is otherwise equivalent",
                "The reset is a long delete then an empty board, and last month's winners are gone; a key per period keeps history",
                "One key per period doubles write cost",
                "Per-period keys cannot be sharded",
            ],
            "answer": 1,
            "explanation": "Key by game and period, lb:racing:2026-09. A reset is not a delete, it is a new key. Old keys stay for the winners page, then expire; the database keeps them forever.",
            "section": "trade-offs",
            "concept": "sd-leaderboard.time-windows",
            "mistake": "sd-leaderboard.one-key-forever",
        },
        {
            "key": "shard-choice",
            "kind": "choice",
            "prompt": "Writes go up ten times to 50,000 per second, past one Redis node. Which sharding do you pick, and what does a top-10 read then cost?",
            "options": [
                "Score range; top 10 comes from the highest shard only",
                "Player hash: writes spread evenly across nodes; top 10 becomes a merge of each shard's top 10",
                "Player hash; top 10 comes from one shard",
                "Score range; my rank needs a merge across all shards",
            ],
            "answer": 1,
            "explanation": "Score range is cheap on reads but players move shards when their score crosses a boundary; player hash spreads writes and needs a small merge on reads. Pick score range when reads dominate and player hash when writes dominate.",
            "section": "evolution-under-pressure",
            "concept": "sd-leaderboard.sharding",
        },
        {
            "key": "zadd-before-log",
            "kind": "spot_mistake",
            "prompt": "Write path: ZADD into Redis, return the new rank to the player, then append the score to the log asynchronously. AOF persistence is on. What is wrong?",
            "options": [
                "Nothing; AOF makes the set durable",
                "A crash between ZADD and the append loses scores players already saw; append to the log first, then ZADD",
                "The rank should be returned before the ZADD",
                "AOF should be replaced with periodic snapshots",
            ],
            "answer": 1,
            "explanation": "Writing to Redis first and calling it durable is a listed mistake. The log is appended before ZADD so that a lost set can always be rebuilt without losing a score the server said was saved.",
            "section": "failure-modes",
            "concept": "sd-leaderboard.write-order",
            "mistake": "sd-leaderboard.zadd-first",
        },
        {
            "key": "friends-top-10",
            "kind": "choice",
            "prompt": "Show the top 10 among a player's roughly 100 friends. What is the right approach?",
            "options": [
                "One sorted set per friend list, updated on every score",
                "Read the 100 friends' scores with one ZMSCORE call, sort them in memory, take the top 10",
                "Precompute every friends board nightly",
                "A SQL join between friends and scores on every request",
            ],
            "answer": 1,
            "explanation": "The list is small, so the simple answer is right: a few milliseconds. Building a sorted set per friend list multiplies every write by the number of friends.",
            "section": "common-mistakes",
            "concept": "sd-leaderboard.friends-board",
            "mistake": "sd-leaderboard.set-per-friend-list",
        },
    ],
}
